### ISSUE TITLE
Support NSProgressReporting protocol

### ISSUE THREAD

**Issue by fulldecent** [Alamofire/Alamofire#1017]
Please support NSProgressReporting protocol

**Comment by jshier** [comment]
Could you be more specific? Alamofire provides both a `.progress` property on `Request` as well as the `.progress()` closures which can provide the progress details usually provided by `NSProgress`.

**Comment by fulldecent** [comment]
You can access a manager with:

    let manager = Alamofire.Manager.sharedInstance

If manager was [NSProgressReporting protocol](https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSProgressReporting_Protocol/index.html) compliant then you could use it with:

    self.progressTracker = manager

Any network activity would be a child element of `manager.progress` and would communicate information externally.

**Comment by cnoon** [comment]
Hi @fulldecent, thank you for your suggestion. This is not a change we will be making though for a couple reasons. 

First off, that protocol is only for objects reporting a single progress object. A manager is going to be reporting progress on all network activity. If each request creates a child progress object, you won't be able to track the progress on a per request basis anymore. Everything just gets MUCH more complicated.

Additionally, the progress APIs from `NSURLSession` don't work this way either. Progress is measured per request and reported back in that same manner. Collating the progress is not something Alamofire knows how to do since it doesn't know the relationship between requests.

Cheers. 🍻

**Comment by fulldecent** [comment]
Got it, thank you for the explanation.
