### ISSUE TITLE
Sending long params in http body

### ISSUE THREAD

**Issue by anilst** [Alamofire/Alamofire#1018]
I should send the webservice long parameters:
gameId: 123123

But getting the error with 400:
error = "Bad Request";
    exception = "org.springframework.http.converter.HttpMessageNotReadableException";
    message = "Could not read JSON: Can not deserialize instance of long out of START_OBJECT token\n at [Source: java.io.PushbackInputStream@376b10a1; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of long out of START_OBJECT token\n at [Source: java.io.PushbackInputStream@376b10a1; line: 1, column: 1]"

How to solve this problem? Thx

code is below:
let URL = IConstant.BASE_URL + self.prefix_removeGame
        let parameters : [ String : AnyObject] = [ "gameId": removeGameRequest.gameId ]
        Alamofire.request(.POST, URL, parameters: parameters, headers: LoginManager.getBasicAuth(), encoding: .JSON)
            .validate().responseJSON { (response) -> Void in
                
                LoadingView.hideLoadingView(self.view)
                
                switch response.result {
                case .Success:
                    self.mCouponResponse?.betHolders?.removeAtIndex(index)
                    self.activeCouponTV.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Fade)
                    
                    self.fillView()
                    break
                    
                case .Failure:
                    if (response.response?.statusCode == 401) {
                        self.showErrorAlert("Need to login again")
                    } else {
                        self.showErrorAlert(Utils.getErrorMessage(response.data))
                    }
                    
                    break
                }
                
                debugPrint(response.response?.statusCode)
        }

**Comment by jshier** [comment]
Without more detail about what you've tried and the specifications of you backend service, it's hard to say where the issue is here. To get a broader audience for you question, use StackOverflow and tag Alamofire while providing as much context and detail you can about your backend service.

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
