### ISSUE TITLE
Attempt to establish header for Content-Type

### ISSUE THREAD

**Issue by AlexandrPonomarev** [Alamofire/Alamofire#1024]
Hi, in attempt to establish custom header in a **POST** request of **Content-Type: application/vnd.api+json**, goes all the same **Content-Type: application/json** also comes back an error (**Taking a look at your response status code (415) leads me to believe that you're not setting the Content-Type correctly in your request headers.**). Prompt please as correctly it to make that the inquiry would pass normally (**XCode 7.2, iOS 9.2**)

I'm try:
1) 
let headers = ["Content-Type": ""application/vnd.api+json""]
let request = alamofireManager.request(.POST, URLString,
parameters: postParameters,
encoding: .JSON,
headers: headers)

2) 
alamofireManager.session.configuration.HTTPAdditionalHeaders = ["Content-Type": "application/vnd.api+json"]

3) 
request.setValue("application/vnd.api+json", forHTTPHeaderField: "Content-Type»)

4) alamofireManager.session.configuration.HTTPAdditionalHeaders?.updateValue("application/vnd.api+json", forKey: «Content-Type")

**Comment by jshier** [comment]
Your `Content-Type` header is being overwritten by the one generated by the `.JSON` encoding type. To set the header while still using the result of `.JSON` encoding, use the `.Custom` encoding, like this:
```swift
request(.POST, URLString, parameters: parameters, encoding: .Custom({ (inRequest, parameters) -> (NSMutableURLRequest, NSError?) in
            let JSONEncodedRequest = ParameterEncoding.JSON.encode(inRequest, parameters: parameters).0
            JSONEncodedRequest.setValue("application/vnd.api+json", forHTTPHeaderField: "Content-Type")
            
            return (JSONEncodedRequest, nil)
        }), headers: nil)
```
This should accomplish what you want. And if you have more than one or two requests in your app, I would recommend following the `URLRequestConvertible` router pattern [mentioned in our documentation](https://github.com/Alamofire/Alamofire#crud--authorization) so that you don't need to keep replicating this logic.

**Comment by cnoon** [comment]
Thanks @jshier!
