### ISSUE TITLE
Documentation suggestion: explain how it works, not just how you'd use it

### ISSUE THREAD

**Issue by skington** [Alamofire/Alamofire#1040]
I'm new to Swift, although I've been using Perl for decades, and when I looked for a way of doing HTTP(S)? requests and getting back JSON, Alamofire looked like a decent answer. And I've got some code that talks to a remote server and gets back responses, and it appears to behave well. Now I want to test it.

As per the guidelines, I [asked on StackOverflow](http://stackoverflow.com/questions/35144676/how-do-i-mock-an-alamofire-response-only) about my specific problem. I thought I'd raise a meta-issue here, though, while I remember what it was like to be a developer new to Swift.

Let's compare the [Alamofire documentation](https://github.com/Alamofire/Alamofire/blob/master/README.md) compared to the [sort-of Perl equivalent](https://metacpan.org/pod/LWP). Note that the Perl code explicitly talks about the sorts of objects that are involved, and [tells you how to build your own](https://metacpan.org/pod/HTTP::Response) if you dig deep enough.

(And yeah, it's old enough that it thinks that it's worthwhile talking about gopher as a protocol. Ahem...)

There's an idiom in Perl land that's proved to be useful: have two sets of documentation. (1) Explain to newcomers how you use The Thing; and separately (2) explain to advanced users How The Thing Works. Reasonable examples would be [Moose](https://metacpan.org/pod/Moose) or [DBIx::Class](https://metacpan.org/pod/DBIx::Class).

Maybe this would be something worth stealing?

**Comment by kylef** [comment]
Alamofire is a wrapper around the Cocoa URL Loading System, as mentioned in the [advanced usage](https://github.com/Alamofire/Alamofire#advanced-usage).

I think what you are looking for is already available there:

> ## Advanced Usage

> > Alamofire is built on `NSURLSession` and the Foundation URL Loading System. To make the most of this framework, it is recommended that you be familiar with the concepts and capabilities of the underlying networking stack.

> **Recommended Reading**

> - [URL Loading System Programming Guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html)
> - [NSURLSession Class Reference](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSession_class/Introduction/Introduction.html#//apple_ref/occ/cl/NSURLSession)
> - [NSURLCache Class Reference](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLCache_Class/Reference/Reference.html#//apple_ref/occ/cl/NSURLCache)
> - [NSURLAuthenticationChallenge Class Reference](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLAuthenticationChallenge_Class/Reference/Reference.html)

**Comment by skington** [comment]
No, that's not what I'm looking for at all.

What I'm looking for is some sort of documentation about the Request and Response objects themselves, so e.g. I can create a Request object from scratch, supply it with JSON and test that my code works with a variety of responses, without having to mock all of the networking.

**Comment by ogezue** [comment]
I had the same problem. I solved it by coping the example app into my project. Then I renamed all Fake* to Chat*. Now I pulled my data inside the datasource-file and threw everything out what is not necessary. In my eyes the example is to complicated and a bit overengineered.

**Comment by cnoon** [comment]
Hi @skington, what you are asking us to document is not even possible. You cannot make your own requests. The `Manager` instance is responsible for creating `Request` objects and vending them back for inspection. The reason for this design is the fact that Alamofire wraps the URL Loading System as @kylef mentioned earlier.

I would recommend reading the docs that @kylef posted, then read through the Alamofire README a second time. All the information to make all different requests is in there. You cannot dive straight into Alamofire without understanding the URL Loading System and how it works. Alamofire is a convenience layer on top of the Apple APIs making networking easier and more convenient, but it is not a replacement. The APIs work very closely together which is why it's important to learn both.

I'm going to close this issue out for now. If you have some more specific requests that you would like to see us add, I'd be happen to re-open if they seem like a useful addition for the community.
