### ISSUE TITLE
Crash on constructing mutable url request

### ISSUE THREAD

**Issue by foffer** [Alamofire/Alamofire#1042]
The following crashes with a `Thread 1 exc_bad_instruction - fatal error: unexpectedly found nil while unwrapping an Optional value`
```
let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)
    mutableURLRequest.HTTPMethod = method.rawValue
```
[Reference to code](https://github.com/Alamofire/Alamofire/blob/master/Source/Alamofire.swift#L92)

The following works as `expected:`
```
let encodedUrl = URLString.URLString.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())!
let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: encodedUrl)!)
mutableURLRequest.HTTPMethod = method.rawValue
```
Using latest version of Alamofire and Swift 2

**Comment by cnoon** [comment]
This is the expected behavior @foffer. You need to make sure your `URLString` conforms to RFCs 1738 and 1808. Otherwise you will not be able to construct a valid `NSURL` as you have seen. This is documented clearly in the [URLStringConvertible](https://github.com/Alamofire/Alamofire/blob/master/Source/Alamofire.swift#L31-L42) docstrings.

```swift
public protocol URLStringConvertible {
    /**
        A URL that conforms to RFC 2396.
        Methods accepting a `URLStringConvertible` type parameter parse it according to RFCs 1738 and 1808.
        See https://tools.ietf.org/html/rfc2396
        See https://tools.ietf.org/html/rfc1738
        See https://tools.ietf.org/html/rfc1808
    */
    var URLString: String { get }
}
```

I'm not completely sure what you're use case is, but if you can, you should leverage the `ParameterEncoding` enumeration encoding which can handle all this for you to ensure your URL is properly encoded.

Cheers. 🍻

**Comment by foffer** [comment]
Thanks for clarifying this @cnoon
