### ISSUE TITLE
JSON ParameterEncoding

### ISSUE THREAD

**Issue by popwarfour** [Alamofire/Alamofire#1049]
I'm passing in at a empty dictionary _[String, String]_ like so,

`let tempURLRequest = ParameterEncoding.JSON.encode(NSURLRequest(URL: URL), parameters: myDictionary).0` 

The request that gets generated is valid except the **body is empty** and there is no **content-type** which makes our spring/jhipster server throw exceptions _"Required request body is missing"_. I'm certainly no expert on the JSON RFC but I'm pretty confident that the generally accepted definition says that at a minimum you need, _{}_ or _[]_. It looks like this is getting caught in _ParameterEncoding.swift, public enum ParameterEncoding, line 85_ which skips apply parameters and setting a content type in the headers.

_NSJSONSerialization_, which you use internally, would correctly parse this into_ {\n\n}_.

So my questions are, 
1. Since I'm basically sending an empty POST request with no body or content-type should my API not be explicitly treating all requests to that endpoint as JSON content type and actually check whats in the header. AKA does best practice dictate that the API should be resilient towards the content-type in the request?
2. Is there a known / accepted work around to sending up an empty dictionary with a JSON content type.
3. Is this a flat out bug?

Although I feel like my first question is definitely part of the answer, using the encode method and explicitly telling it to use JSON should still produce a application/JSON content-type at a bare minimum.

Lastly big thanks for the excellent frameworks!

**Comment by cnoon** [comment]
These are all very valid points @popwarfour. This particular behavior has a lot of history, but your description and reasoning here is spot on. We're discussing this right now and will get back to you shortly. Thank you for the detailed write up!

**Comment by popwarfour** [comment]
Thanks for the quick reply @cnoon, I'm very much looking forward to hearing about your discussion

**Comment by cnoon** [comment]
Okay @popwarfour, thanks for your patience. We had a good discussion on Slack about this topic and have decided to revert the changes in 75c269ae. Instead, we are now properly handling the case of an empty query string in URL encoding. This has been fixed in 8b618c76 if you want to check it out. These changes will be available in the 3.2.0 which we are working on right now.

Thanks again for your excellent description here. We've been fighting this issue ever since that change was made. You managed to get to the root issue which made it much easier to work out the proper solution.

Cheers. 🍻
