### ISSUE TITLE
Jason Serialized

### ISSUE THREAD

**Issue by citrusbits** [Alamofire/Alamofire#1062]
Error Domain=com.alamofire.error Code=-6006 "JSON could not be serialized. Input data was nil or zero length." UserInfo={NSLocalizedFailureReason=JSON could not be serialized.

And below is my call method
```javascript
func weatherAPICalls (let selectedCityName : String) {
        
        apiManager.currentWeatherByCityNameAsJson(selectedCityName) { (json) -> Void in
            print(json)
             self.headerWeather = Weather(json: json)
        }
 
        apiManager.forecastWeatherByCityNameAsJson(selectedCityName) { (json) -> Void in
          print( json["list"])
        self.hourlyWeatherForecast = json["list"].arrayValue.map {WeatherForeCast(hourlyForecast:$0)}
              
        apiManager.dailyForecastWeatherByCityNameAsJson(selectedCityName) { (json) -> Void in
          print(json["list"])
               
         self.dailyWeatherForecast = json["list"].arrayValue.map {WeatherDailyForeCast(dailyForecast:$0)}
                }
            }
    }
```

**Comment by cnoon** [comment]
Hi @citrusbits,

First of all, none of the code you posted is calling any Alamofire APIs, so that doesn't help us. If you check out these [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/ResponseSerializationTests.swift#L318-L356), you'll see this error is sent when using a JSON response serializer with `nil` or empty data.

In the future, please open a question on Stack Overflow. We use the GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
