### ISSUE TITLE
JSON dictionary on networking error

### ISSUE THREAD

**Issue by dalu93** [Alamofire/Alamofire#1070]
It could be useful to receive, in the same way when the communication is correct, the JSON parsed into a `Dictionary` also for some network requests terminated with different codes like 300<= CODE <= 499

Now I'm parsing manually the `response.data` using `NSJSONSerialization`, but it could be useful if the library does it for us.

Thanks

**Comment by cnoon** [comment]
Hi @dalu93!

You can already do this with custom response serializers or manually parsing the response data yourself. Since responses can vary so widely for various error status codes, we cannot generalize the handling in Alamofire much more than we already have. If you have specific cases you need to handle, you'll need to use more advanced techniques to handle the errors gracefully. Please check out the [Custom Response Serializers](https://github.com/Alamofire/Alamofire#creating-a-custom-response-serializer) section of the README for more info.

Cheers. 🍻
