### ISSUE TITLE
How to use AlamofireNetworkActivityIndicator

### ISSUE THREAD

**Issue by EkambaramE** [Alamofire/Alamofire#1082]
Some one tell me how to use AlamofireNetworkActivityIndicator 

I followed the following steps in link https://github.com/Alamofire/AlamofireNetworkActivityIndicator

but not working

**Comment by cnoon** [comment]
1) You need to use Alamofire to make your requests.
2) You need to make sure your requests are taking at least 1 second to complete, otherwise the indicator won't actually display due to the activation timer.
3) Set the activation timer and completion timer delays to zero to see them display on any request.

Hope that helps. In the future, please open issues against the actual AlamofireNetworkActivityIndicator project.

Cheers. 🍻
