### ISSUE TITLE
Manager.init with NSURLSession: guard too strong?

### ISSUE THREAD

**Issue by binkdotli** [Alamofire/Alamofire#1106]
In [Manager.init:delegate:serverTrustPolicyManager:](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L141), why is it enforced that "The delegate of the URL session. Must equal the URL session's delegate.", i.e. why is the following line required?

    guard delegate === session.delegate else { return nil }

My use case: I obtain an initialized NSURLSession from a security library (out of my control), which provides it own internal proxy object for NSURLSession.delegate, which checks and forwards NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDataDelegate and NSURLSessionDownloadDelegate calls.

To clarify, my initialization code looks something like this:

    let delegate = Manager.SessionDelegate()
    let session: NSURLSession = SecurityLib.initialize(sessionDelegate: delegate,
        taskDelegate: delegate, dataDelegate: delegate, downloadDelegate: delegate)
    let manager = Manager(session: session, delegate: delegate)

The last line currently fails because session.delegate is a proxy object internal to SecurityLib (which forwards all delegate methods to our delegate). If I remove the guard line from Manager.swift things seem to work.

**Comment by wizzardchao** [comment]
Because Alamofire use its SessionDelegate subclass to the real delegate work. It can provide block api of NSURLSessionDelegate(and its subclasses), and also provide a way to fallback to TaskDelegate, which is to each NSURLSessionTask and can provide a more specialized impementation.

If you insist using your delegate, you will lose a lot convenience of the library. I think you can try to make your delegate be a proxy of SessionDelegate by applying all callbacks to the blocks of SessionDelegate.

Hope this can help you.

**Comment by cnoon** [comment]
The line is enforced for safety. It's to make sure you aren't trying to provide a `SessionDelegate` that isn't actually the delegate of the `NSURLSession` you're passing in. Otherwise, Alamofire won't really do much of anything for you.

Thanks for the answer @wizzardchao. You're spot on. In this particular use case @binkdotli, it's probably not worth trying to force your `SecurityLib` session and delegate into Alamofire. However, you could certainly still use parts of Alamofire to help build `NSURLRequest` objects such as `ParameterEncoding` and `MultipartFormData`.

Best of luck! 🍻

**Comment by binkdotli** [comment]
OK, thanks for taking the time to answer this.
