### ISSUE TITLE
Version 3.3.0 breaks SemVer

### ISSUE THREAD

**Issue by jschmid** [Alamofire/Alamofire#1136]
My `Cartfile` contains:

    github "Alamofire/Alamofire" ~> 3.2

We are still using Xcode 7.2 / Swift 2.1. Today I made a `carthage bootstrap` and it downloaded Alamofire 3.3, which of course breaks the compilation.

IMHO this new version should have been a 4.x.

Any thoughts?

Edit: I could fix it with `github "Alamofire/Alamofire" == 3.2.1` of course. But I bet I'm not the only one that will run into this problem.

**Comment by phroggyy** [comment]
I completely agree. I am still able to move to 2.2, so no major issue for me, but it should *at the very least* be in the upgrade notes, as it breaks compilation at 21 places for me in Swift 2.1/Xcode 7.2.1.

**Comment by cnoon** [comment]
@jschmid - this should not be a MAJOR version upgrade according to semver. @phroggyy - you are absolutely right, this info should have been included in the release notes. That has been corrected in fad7390a. Hopefully that helps clarify the reasoning for going with 3.3.0 instead of 4.0.0.

Cheers. 🍻

**Comment by jschmid** [comment]
Thanks for the update. I understand your position 👍
