### ISSUE TITLE
Allow synchronous calls

### ISSUE THREAD

**Issue by balazsgerlei** [Alamofire/Alamofire#1147]
Hi!

While asynchronous calls are indeed a great feature of Alamofire, it is only sufficient if one would like to delegate the job of doing asynchronous calls to it or would like to directly start network calls from ViewControllers.

In a multi-layered architecture however where all business logic is done asynchronously from the point where a user-triggered event leaves the UI, it only complicate things. For example I would like to use RxSwift to handle all my business logic in a separate thread and retreive business entites using the Repository pattern, where the cloud storage (that basically means API calls) is a Repository itself which is called when the requested data is not found locally (in the database, which is another Repository). The fact that Alamofire only allows asynchronous calls makes it impossible to implement this without much pain.

**Would you please consider addign a way to make request synchronously with Alamofire?**

I do think it would be useful in many complex applications. You could of course emphasize in the docs that the recommended way is to call Alamofire asynchronously, and one should only call it synchronously if he or she implement asynchronity manually.

**Comment by cnoon** [comment]
Hi @balazsgerlei,

Thank you for your detailed feature request. I understand that async operations can make things more complicated, but we also don't want to hold up queues (or threads) while the async operation takes place. Since Apple removed the ability to execute synchronous API calls in the `NSURLSession` APIs, you can see that they are forcibly moving in the direction of making network calls asynchronous. We aren't interested in moving backwards to replicate the `NSURLConnection` APIs.

With that said, we have made some improvements to make the concept of thread-safety and synchronous calls easier. In 4c7bf391, we added the `queue` parameter to all the response serializers making it really easy to make a request, and specify the queue to call when it is complete. This is essentially a synchronous API if you handle the response on the same queue that you made the request on. The nice thing is that it allows the queue to process other things with the request is being made.

While I understand synchronous APIs may make things easier, they could also make things much worse. We will not be adding synchronous APIs to Alamofire, but we will continue to try to make the async APIs easier and easier to use.

Cheers. 🍻

**Comment by balazsgerlei** [comment]
Hi @cnoon!

Thank you for your response. I fully understand your reasoning and this queue parameter seems to be a good solution in my usecase, I'll try it out!

**Comment by maxandron** [comment]
Something that might be useful then, is an example showing how to use the queue parameter to make synchronous calls.

The problem with this design in my opinion is that it makes you design your whole call chain to be callback-based.
I believe it is much better to handle this at the bottom level.

Also, since this might be a common request, maybe it is preferable to expose such api instead of having users implement it from scratch every time - maybe even put it in a different module so people won't confuse the two

P.S. Would love to get an example of how to make this synchronous :)

**Comment by Alexander-Ignition** [comment]
Synchronous JSON request.
But I would not recommend this to use because you cannot cancel the request.

```swift
extension Alamofire.Manager {
    
    func syncRequest(URLRequest: URLRequestConvertible) -> Response<AnyObject, NSError> {
        
        var outResponse: Response<AnyObject, NSError>!
        let semaphore: dispatch_semaphore_t! = dispatch_semaphore_create(0)
        
        self.request(URLRequest).responseJSON { (response: Response<AnyObject, NSError>) -> Void in
            
            outResponse = response
            dispatch_semaphore_signal(semaphore)
        }
        dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
        
        return outResponse
    }
}
```

**Comment by maxandron** [comment]
Thank you @Alexander-Ignition !!

**Comment by xygahs0801** [comment]
how to use this extension???please give me a demo.

**Comment by ppamorim** [comment]
It would be a amazing feature. I really need this.

**Comment by reitzig** [comment]
@Alexander-Ignition Aside from some syntax upgrades (`DispatchSemaphore` is a thing now), this does not always work for me. If the Alamofire [request uses the main thread, we get a deadlock](http://stackoverflow.com/q/42644111/539599). While there is a workaround for XCTest, what to do about Swift scripts?

I second this request. An easy way to make Alamofire work synchronously is needed. Not for production use in apps, but for testing and scripting.

**Comment by Alexander-Ignition** [comment]
@reitzig for testing it is better to use XCTestExpectation

for scripts you can try this, but this example does not support `RequestRetrier`
```swift
extension SessionManager {
    
    func syncRequest(_ urlRequest: URLRequestConvertible) -> DataResponse<Any> {
        
        let request: DataRequest = self.request(urlRequest)
        var outResponse: DataResponse<Any>!
        
        request.responseJSON { (dataResponse: DataResponse<Any>) in
            outResponse = dataResponse
        }
        
        let task = request.dataDelegate.dataTask
        let timeout = Date(timeIntervalSinceNow: request.request?.timeoutInterval ?? 10)
        while task.state == .running && !RunLoop.current.run(mode: .defaultRunLoopMode, before: timeout) {
        }
        
        return outResponse
    }
}
```

**Comment by kdawgwilk** [comment]
What about the context of SPM CLI tools?  Writing simple scripts in Swift could benefit greatly from synchronous requests

**Comment by QoT** [comment]
I vote for adding sync requests to Alamofire because in `UIApplication.shared.beginBackgroundTask()` - `UIApplication.shared.endBackgroundTask()` coding paradigm it seems like we cannot use async HTTP requests.

Adding custom code that handles parameters, headers and JSON response seems like a duplicate job since we already have all code that works when app is in a foreground.

All we need is if we are using background iOS execution to set `sync = true` while `sync = false` would be default.

**Comment by jshier** [comment]
Background tasks work fine with asynchronous calls, you just end the task in the completion handler while making sure you have a proper expiration handler. Really you should use a `.background(identifier:)` `URLSessionConfiguration` for things you want to really run in the background. However, Alamofire doesn't support those well, and background sessions are a pretty different beast, so I would recommend using something else if you want true background behavior.

In any event, Alamofire will never support a synchronous API.
