### ISSUE TITLE
Failure when adding encoding: .JSON to call without parameters

### ISSUE THREAD

**Issue by nicnhus22** [Alamofire/Alamofire#1156]
Here in this example:

```swift
let URL = MY_URL
let parameters = [:]
let headers    = SharedItemResources.addAuthenticationTokenToHeader()
        
Alamofire.request(.GET, URL, parameters: parameters, encoding: .JSON, headers: headers).validate().responseJSON { response in
    switch response.result {
            case .Success:
		// Success
            case .Failure:
		// Failure
    }
}
```

I am adding `encoding: .JSON` whereas I am not passing any parameters. It used to work in the previous version (3.1.4) but I just did a `pod install` and now (version 3.3.0) it sends a `FAILURE` without any information. Here's the response object in XCode:

<img width="498" alt="screen shot 2016-03-31 at 13 50 28" src="https://cloud.githubusercontent.com/assets/3611896/14174880/a122e120-f747-11e5-975b-6c102c7f82c6.png">

I tried everything I could but it seems like it is an internal error,

Cheers

**Comment by cnoon** [comment]
You'll need to debug the `error` being returned. Since you are not receiving a URL response, that means you're not actually able to hit the server and your request is not being formed properly. You should try using the following to debug further:

```swift
let request = Alamofire.request(.GET, URL, ...).responseJSON { response in
    print(response)
}

debugPrint(request)
```

In the future, you should open a question on Stack Overflow. If you do end up finding an actual issue in Alamofire, please comment back with more info and I'll be happy to investigate.

Cheers. 🍻
