### ISSUE TITLE
Not *really* authenticating with passed credentials.

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1158]
I changed the .authenticate(user:password:) parameters in my source code from valid to completely invalid credentials and reran the app.  The app continues to get data from the webserver with those invalid credentials.

I then did a debugPrint() of the request and ran the curl command shown from Terminal, and the connection properly failed with a 401 saying authorization was required. 

How do I ensure that *only* the user/pwd that is sent through the authenticate method is used when making connections?

**Comment by grosch** [comment]
Sorry, this is Alamofire 3.2.1, and I'm using the Alamofire.request(.GET, "", parameters:) method, which then chains to a .authenticate

**Comment by cnoon** [comment]
Everything is working as expected. The original request made by Alamofire (NSURLSession) does not include the credential info. That's why you're seeing the 401 behavior with the cURL command. What happens instead is that the original request is made, then the server issues an auth challenge back to the client. When this happens, Alamofire will provide the credential back to the server, and then the request is successfully made. After the connection has been authenticated, the server trusts subsequent requests. If not, it will issue another challenge and Alamofire will provide it.

Cheers. 🍻
