### ISSUE TITLE
Chunked background upload session on OSX - it is possible? How? 

### ISSUE THREAD

**Issue by timothyarmes** [Alamofire/Alamofire#1168]
Hi,

I apologise for asking of help here, but I've spends days trying to get my head around this and I've getting nowhere.

I'd like to user Alamofire to create a background session upload that sends a file in chunks to a server. Each chuck in be in multipart format.

I can't find any details information on how Amalofire handles background sessions. In my particular case this is what I need to handle:

I wish to upload a video file from either my main OSX application, or from an OSX sharing extension.
The server endpoint requires that I send the files in chucks of a given size.
I need to use backgrounds sessions for this, so I'll need session delegates
I don't understand how to use Alomafire with background sessions and session delegates and I can't find any documentation on the subject. 
I'm also not sure if Alamofire helps with the delegate callbacks - does it recreate the tasks? The related code i've seen appear to only refer to iOS9, not OSX.

Thanks,

Tim

**Comment by cnoon** [comment]
Hi @timothyarmes,

Given your needs here, I'd recommend using your own NSURLSession and NSURLSessionDelegate, then using Alamofire to help create the `MultipartFormData` objects to upload. This will end up being much easier in the long run because Alamofire currently does not support these complicated background session use cases very well. This is something we'd like to attempt to address in Alamofire 4.

Best of luck! 🍻

**Comment by pvinis** [comment]
any examples for this?
