### ISSUE TITLE
Almofire got some issue while executing the "carthage update --platform iOS" with version 3.3.1

### ISSUE THREAD

**Issue by rohitLptpl** [Alamofire/Alamofire#1179]
Getting issue with Almofire version "3.3.1" but its working fine with version "2.0"
 Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** BUILD FAILED **

**Comment by cnoon** [comment]
The `Unity4XC` plugin will not cause the build to fail. In order to build Alamofire 3.3.1, you need to use Xcode 7.3, xcodebuild 7.3, and Carthage 0.16. After you have everything updated, I'd suggest wiping DerivedData and the Xcode cache. Then reboot Xcode. After you have all this completed, Alamofire should build properly.
