### ISSUE TITLE
debugPrint of request does not show the actual coalesced headers and can be confusing 

### ISSUE THREAD

**Issue by jerarts** [Alamofire/Alamofire#1184]
If a header is overridden in a request a debugPrint will show both versions and it isn't clear whether the overwriting actually works.

e.g. if I set "Accept-language" to "en-us" in my NSURLRequest and then do a startDataRequest and do a debugPrint on the Request I get back I see:
...
	-H "Accept-Language: en-us" \
	-H "Accept-Language: en-US;q=1.0, ar-US;q=0.9, ja-US;q=0.8, pt-US;q=0.7" \
...

**Comment by cnoon** [comment]
Looks like we have a bit of a bad assumption in the `CustomDebugStringConvertible` logic. Right now we're extracting all the `NSURLRequest` headers, then the `NSURLSessionConfiguration` headers. Instead, we should collect them in the opposite order and have any duplicates in the `NSURLRequest` replace the previous value since that's the actual behavior when the request is sent.

Would anyone in the community like to help out to fix this issue?

**Comment by cnoon** [comment]
Would anyone in the community like to help out to fix this issue? Should be easy to collect the headers then append them to the `components`. We'll also want to write some unit tests to verify this behavior.

**Comment by chrisrichards** [comment]
See pull request #1186

**Comment by cnoon** [comment]
Issue has been resolved in d2b85f43 thanks to @chrisrichards. I'm going to go ahead and close this out.
