### ISSUE TITLE
Why TaskDelegate subclasses are internal?

### ISSUE THREAD

**Issue by RenGate** [Alamofire/Alamofire#1189]
Hello everybody. I was wondering what where the reasons to make such classes as UploadTaskDelegate, DataTaskDelegate and DownloadTaskDelegate internal? They have a bunch of closure-typed properties that, if exposed, would allow to easily add different handlers for NSURLSessionTaskDelegate methods for each individual Request.

**Comment by cnoon** [comment]
These were never intended to be used publicly. They are only implemented to allow internal customization of Alamofire handling. You already have the ability to override everything at the session level through the `Manager.SessionDelegate`. If you can come up with some examples of what you can't currently do because of this design, then we'll certainly consider the proposal. But at this time we have no intention of opening up those APIs.

Cheers. 🍻
