### ISSUE TITLE
It is possible to show progress when I post JSON with application/json content-type?

### ISSUE THREAD

**Issue by DesmondPang** [Alamofire/Alamofire#1194]
I tried to post a large json (contain base64 image string) by using

 Alamofire.request(.POST, "https://httpbin.org/post", parameters: parameters, encoding: .JSON,).progress {  (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite)  in }.

 I understand that I can use upload or formdata to achieve that. I wonder to know if we can use the request function to do that instead of upload().

**Comment by cnoon** [comment]
You certainly can use the `request` method to do this, but I would encourage you to use `upload` instead. The reason is that the `request` method progress tracking only reports downloading progress of the response data. It will not report upload progress. 

The `upload` APIs will report the upload progress to the server and do not report download progress of the server's response data. Because of this, I'm sure you'd prefer the `upload` APIs in this situation.

Cheers. 🍻
