### ISSUE TITLE
  Alamofire  Domain=NSCocoaErrorDomain Code=3840

### ISSUE THREAD

**Issue by crash-wu** [Alamofire/Alamofire#1199]
Hi Dear @mattt : 
     when  I used Alamofire 3.3.1  by Xcode 7.3,I get some questions . Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

I try to use some idea  ，but I'm fail.

My code  is below:
Alamofire.request(.POST, url, parameters: dic, encoding: .JSON, headers: nil).responseJSON(options: .MutableLeaves) { (response) in

}

Thanks for your helping

**Comment by cnoon** [comment]
Hi @crash-wu,

Your error message is encouraging you to use `options: .AllowFragments` instead of `options: .MutableLeaves`. That will allow whatever valid JSON object that isn't currently a collection to be parsed successfully.

In the future, I'd encourage you to instead open a question on Stack Overflow. We use our GitHub project with bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by crash-wu** [comment]
Thanks for your helps.
