### ISSUE TITLE
OAuth 2.0 Authentication

### ISSUE THREAD

**Issue by buzzllc** [Alamofire/Alamofire#1201]
I am trying to pass my OAuth 2.0 Token to my web service and it does not appear that Alamofire is even appending the Authentication header to my request.

let header = ["Authentication", "some-oauth-token"]

Alamofire.request(.GET, url, headers: header, encoding .JSON).responseJSON
{
  response in (code)
}
This always results in a response from my server that the Authentication Header is missing. Should I not be doing it this way? I see there is Authentication methods on the request but I do not see one specifically for passing a token over just other auth methods. Is this frowned upon and I should change the way I am doing my REST Auth stuff?

**Comment by cnoon** [comment]
Hi @buzzllc,

I can't be certain with the info you provided, but most likely you need to do the following instead:

```swift
let headers = ["Authorization": "Bearer \(someAuthToken)"]
```

If that doesn't fix your issue, then I'd encourage you to ask a question on Stack Overflow since that's a better place for this type of question. We use our GitHub project primarily for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
