### ISSUE TITLE
Swift 1.2.0 compatibility issue

### ISSUE THREAD

**Issue by khanshakeeb** [Alamofire/Alamofire#1207]
Hi guys,

I am newbie in Swift 1.2.0 and I wanted to use Alamorfire library for my project. Kindly let me know how I can use older and compatible version of Alamofire with Swift1.2.0. Currently I am getting 3.+ version of Alamofire which is not compatible with Swift 1.2.0

Thanks

**Comment by cnoon** [comment]
Hi @khanshakeeb,

You will need to use Alamofire 2.0.2 if you're still building against Swift 1.2. I'd encourage you to update to the latest version of Swift ASAP because 1) Swift 2.2 is awesome and 2) we have made many great improvements to Alamofire over the past 6-7 months that you will be missing out on.

Cheers. 🍻
