### ISSUE TITLE
debugPrint output doesn't work with tcsh

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1210]
When I run a Request object through debugPrint, the -d output is like so:

```-d "{\"key\" : \"value\"}"```

That's OK in a bash shell, but in tcsh that doesn't work because it thinks the quotes are bad.  If you replace the outside quotes with an apostrophe, and then don't escape the inner quotes (or even escaping is technically OK) then it should work fine in either shell.

**Comment by cnoon** [comment]
Given the amount of variability between `bash` and `tcsh` quote escaping (amazing how painful this is), there's no one solution that solves this problem correctly. I just spent 2 hours trying to work out a solution to no avail.

While your suggestions do stop throwing errors in `tcsh`, the JSON is not able to be parsed correctly server-side. Coupled with the fact that `bash` is the default shell on OS X, we're going to leave the implementation as is. If you MUST use a `tcsh` shell when debugging, you'll need to modify the cURL output directly before using in your shell.

With that said, I realized there was actually an issue with `bash` output as well where the JSON contained single or double quotes. I've pushed up f443cd8a to `master` to resolve the issue.

Sorry this can't work for both shells. We're certainly open to supporting both, but I don't see how it's possible. If you're willing to spend a bunch of time here trying to figure out a better alternative, by all means.

Cheers. 🍻

**Comment by grosch** [comment]
What do you mean it's not parsed correctly?  I simply changed Request.swift so that instead of wrapping the entire -d parameters with quotes it wraps them with apostrophe instead.  That's worked against all my API calls so far.

I also personally got rid of the \ escaping across each line as that's painful to work with when doing copy/paste and editing, but that's just me :) 

What would be great would be some config options so we could say things like don't split the parameters across lines, use apostrophe instead of quote, etc...  Defaults would all stay like they are now, but for those of us that have been in UNIX for so long that we use tcsh instead of (shudder) bash (lol) it would work well.

**Comment by cnoon** [comment]
Apologies @grosch, I realize now that in my reply I didn't provide nearly enough detail. In your simple example, it certainly works. The problem is when keys or values in the JSON contain single or double quotes. I cannot find any possible combination of escaping that works between both shells because of the differences in the way they escape strings.

If you would really like to see this feature support both shells, then I'd encourage you to find a way to make this [test](https://github.com/Alamofire/Alamofire/blob/master/Tests/RequestTests.swift#L565-L596) work in BOTH bash and tcsh. We could also consider having two different methods for building the `cURL` command. Then possibly a way to set your shell preference on a Request.Shell enumeration or something along those lines.
