### ISSUE TITLE
Signing Out User and Signing In Another User

### ISSUE THREAD

**Issue by raginggoat** [Alamofire/Alamofire#1217]
Users are sign in using basic auth. If the sign in is successful, I store the returned JSON for the signed in user in a dictionary in a User class.
```
import Foundation
import UIKit

class User {
    var userJSON: [String:AnyObject]?
}

let sharedUser = User()
```

My issue is that when the app is launched signing in works fine, but if you log out and then try to log in as another user without closing and relaunching the app, the JSON for the first user that was just signed out is stored in the userJSON dictionary instead of the info for the new user who is trying to log in.

Here is the code for signing in:

```
Alamofire.request(.GET, "https://gyminyapp.azurewebsites.net/api/User").authenticate(user: emailTextField.text!, password: passwordTextField.text!)
            .responseJSON {
                son in
                self.responseJSON = json.result.value as? [String: AnyObject]
                print("JSON: \(self.responseJSON)")
                if self.responseJSON!["message"] != nil {
                    let errorMessage = self.responseJSON!["message"] as! String
                    alert = UIAlertController(title: "Error", message: errorMessage, preferredStyle: .Alert)
                    alert?.addAction(okButton)
                    alert!.view.tintColor = BarItems.greenTintColor
                    self.presentViewController(alert!, animated: true, completion: nil)
                } else {
                    if self.responseJSON != nil {
                        sharedUser.userJSON = self.responseJSON
                        print(sharedUser.userJSON)
                    }  
                    self.performSegueWithIdentifier("tabSegue", sender: nil)
                }
            }
```

When the user signs out, they are returned to the sign in screen and the dictionary in the User class is set to nil

```
sharedUser.userJSON = nil
 // Return user to sign in screen
 self.dismissViewControllerAnimated(true, completion: nil)
```

**Comment by cnoon** [comment]
Hi @raginggoat,

These types of questions are best suited for Stack Overflow instead of GitHub. We use our GitHub project for bug reports and feature requests. If you tag `alamofire` on your question, I'm sure the community will be able to help you out.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
