### ISSUE TITLE
File download clarifications

### ISSUE THREAD

**Issue by scobbe** [Alamofire/Alamofire#1234]
Two quick questions/clarifications (forgive me if this post belongs on StackOverflow, rather than GitHub Issues -- I can move it, if necessary): 

1. Is there a reason that the `download` method does not support returning the file contents straight to memory as an `NSData` object, rather than only as a file? Is the best way to achieve this functionality simply to use the `request` method?

2. In the event of a download error, to avoid having a superfluous file written (whose contents are the server error message), I check for an error HTTP response code in the `destination` closure, and if so, I supply Alamofire with a "/dev/null" destination. Is there a better way of doing this?

**Comment by cnoon** [comment]
Hi @scobbe,

### Question 1

The reason that `download` works with `NSURL`s instead of `NSData` objects is that `download` is generally used for larger files. If you had to load the large file's data into memory every time to use it, you would certainly run your app out-of-memory. This is why the `download` APIs exist. To allow you to download large amounts of data and stream them to a file rather than have to collect them in memory. This is really the only difference between `request` and `download`. The `request` API does it all in-memory where the `download` API will stream the data to disk.

### Question 2

This is a great question, and I don't actually have an answer. I've never tried to do it before. It's downloading to the `tmp` directory which is cleaned up by Apple automatically from time-to-time. Therefore, I've never worried about the abandoned files since they'd generally be very small. However, if this works for you, then I'd say roll with it!

Cheers. 🍻

**Comment by scobbe** [comment]
Thanks @cnoon, really appreciate you taking the time to clarify. Super helpful! Have a good one.
