### ISSUE TITLE
How to set timeout Time with Alamofire

### ISSUE THREAD

**Issue by diegothucao** [Alamofire/Alamofire#1237]
Dear friends,
Could you help me how to set timeout with Alamofire?

Thanks in advance

**Comment by cnoon** [comment]
You can set it on the [NSURLRequest](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLRequest_Class/#//apple_ref/occ/instp/NSURLRequest/timeoutInterval) or on the [NSURLSessionConfiguration](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionConfiguration_class/#//apple_ref/occ/instp/NSURLSessionConfiguration/timeoutIntervalForRequest) when it is created.

In the future, you should open this type of question on Stack Overflow instead of on our GitHub project. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
