### ISSUE TITLE
Same Session cookie for different url's / domain

### ISSUE THREAD

**Issue by Sunitadaffodil** [Alamofire/Alamofire#1251]
Hi, 
I want to use same session cookie with different urls
Like , I am getting session cookie from url "http://example.com/login"
After getting session cookie from above step, I could set cookie using 

Alamofire.Manager.sharedInstance.session.configuration.HTTPCookieStorage?.setCookies(cookies, forURL: URL, mainDocumentURL: nil)

Also, I think this needs to be done only one time because Alamofire Manager is a Singleton class.

Now, I want to use this session cookie with URL "http://example.qa/mobile/alerts" (please note this time domain changes from .com to .qa),but I think Alamofire Manager is sending the default session cookie, not the one which I set previously.

In this case, it seems that session cookie is dependent on domain name. Is there any workaround
to make this work?

**Comment by cnoon** [comment]
The singleton `Manager` instance uses the shared cookie store and automatically sends cookies with each response. However, in your case since you're switching domains, you most likely need to send the cookie through a `Cookie` header.

In the future, questions like these should be opened on Stack Overflow. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
