### ISSUE TITLE
Missing argument for parameter #2 in call

### ISSUE THREAD

**Issue by rlam3** [Alamofire/Alamofire#1260]
How to add url parameters to alamofire so i can limit my search results?

I want to be able to do something similar to:

abc.com/api/v1/search/?term=abc?limit=3

```swift
let parameters = ["term":"abc", "limit":3]
Alamofire.request(.GET,'abc.com/api/v1/search',parameters:parameters)
.responseJSON {
    ...
}
```

I keep getting Missing argument for parameter #2 in call. Is a workaround for this? Thanks!

**Comment by cnoon** [comment]
Your URL is invalid. It should probably be something like `"https://abc.com/api/v1/search"`. In the future, you should open a question on Stack Overflow instead of GitHub for this type of question. We use our GitHub project for bug reports and Feature Requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
