### ISSUE TITLE
lack of array indexes, possible cause of server parse error

### ISSUE THREAD

**Issue by timersha** [Alamofire/Alamofire#1265]
Some requests always failed, and after debugging requests with backend developer, we found lack of indexes of objects in array parameter. I'm not sure is it error or not.
ParametersEncoding.swift, line: 192-194, after adding 'index' requests succeeded:
 for (index,value) in array.enumerate() {
                components += queryComponents("\(key)[\(index)]", value)
            }

**Comment by cnoon** [comment]
If the default collection formatting does not meet your needs, you should instead use the `.Custom` parameter encoding type to create your own. We've opened up the APIs in `ParameterEncoding` to make it as easy as possible to roll your own solution.

Cheers. 🍻

**Comment by SASDOE** [comment]
I might add that there is an easier solution (workaround is probably the more appropriate wording): rather than having an array, use a `NSMutableDictionnary` and set your indices as the key. Since you can nest dictionnaries this shouldn't be an issue and avoids the need to write a custom `ParameterEncoding`.
