### ISSUE TITLE
When using the link "VPN network.Alamofire monitoring network, the network status to: NotReachable.But the current network is available.

### ISSUE THREAD

**Issue by duanyicanyuan** [Alamofire/Alamofire#1270]
When using the link "VPN network.Alamofire monitoring network, the network status to: NotReachable.But the current network is available.

```
    var manger: NetworkReachabilityManager?


    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        manger = NetworkReachabilityManager(host: "https://www.apple.com")
        manger?.listener = { status in
            switch status {
            case .NotReachable:
                print("NotReachable")
                
            case .Unknown:
                print("NotReachable")
                
            default:
                break
            }
        }
        self.manger?.startListening()
        
        return true
    }
```
How can I solve this problem?

**Comment by cnoon** [comment]
Hmmm...not sure on this one @duanyicanyuan. We'll have to investigate. Does anyone in the community have experience using the Reachability APIs on a VPN?

**Comment by Abhishekg219** [comment]
I am having the same issue. Listener is not working when the network goes off. The callback function is not getting called once the network went off.

**Comment by cnoon** [comment]
Hi everyone,

My apologies for not addressing this issue sooner. Thank you for your patience. We've been swamped with Alamofire 4. 

I've managed to get to the bottom of the problem here. The core issue is that you're including the `https://` as part of the host when it should actually be `www.apple.com` as documented in our [README](https://github.com/Alamofire/Alamofire#network-reachability).

I've also spent some time putting together a sample app to test the behavior on a VPN. I've tested it on various VPNs all over the world and it behaves perfectly on iOS 10 as long as you set the `host` correctly. I haven't tested on iOS 9 since I don't have an iOS 9 device at the moment. If someone could test this on iOS 9, I'd appreciate it.

- [Connectivity.zip](https://github.com/Alamofire/Alamofire/files/491459/Connectivity.zip)

Hopefully this helps resolve future issues.

Cheers. 🍻
