### ISSUE TITLE
URLRequestConfigurable

### ISSUE THREAD

**Issue by gmarm** [Alamofire/Alamofire#1282]
I created a small protocol named `URLRequestConfigurable` which works in similar fashion to `URLRequestConvertible` but in my opinion makes Routers more readable.

You can find it (and the reasoning behind it) [here](https://github.com/gmarm/AlamofireURLRequestConfigurable). It's easy to integrate via CocoaPods and comes with a small example project.

I wanted to ask you, is this protocol something you would consider merging? Thanks!

**Comment by cnoon** [comment]
Hi @gmarm,

I like the example you put together. It certainly makes the simple cases easier to read and more consistent. I'm a bit on the fence as to whether this belongs in Alamofire itself, but in general, I certainly like the approach!

With that said, I would probably think about changing a couple of things if we were to bring it in. First off, I would create a `URLRequestConfiguration` struct to contain all the values instead of using a `typealias`. That would actually allow you to use default parameters in a bunch of your `Router` cases which would make it even more condensed! 😉

I'd also encourage you to think about the same concept for download and upload tasks as well. Could the `URLRequestConfiguration` struct handle all the various types of tasks with optional parameters? Possibly.

What's your take @jshier, @AnthonyMDev, @kcharwood?

**Comment by jshier** [comment]
It doesn't seem like much of a win to me. 

While it might be easier to work with in some scenarios, it leads to a huge amount of redundancy in others. What if the vast majority of my endpoints use the same HTTP method? It would be duplicated in every case rather than being the result of a single switch default. So it seems like it makes some of the complex cases easier to express, it also makes the simple cases require more boilerplate. The suggestion of a `URLRequestConfiguration` struct would help with that since it can have default values, but really that would only help if those default values happened to coincide with what was actually required.

Readability is also a hugely subjective trait. I find the typical `enum` router to be perfectly readable, as it's rare that I need to know every property of an endpoint at a glance. Rather, I'm usually looking to make sure a particular property of an endpoint is set correctly. And once those values are set, I never look at it again, so it's not code that I read every day.

However, I do think this is a place where Alamofire could be enhanced. Rather than something immediate, though, my thought was to wait until WWDC and see everything Apple is going to do with Swift 3 (most is already revealed, but their presentations can provide good ideas too) and then start working on Alamofire 4 to take advantage of the new features as soon as possible at the core of the framework. Seeing how protocols have advanced could give us a better idea of what we could do in the framework to make it easier for users to create routers, among other things. 

So while I think some users will find this a useful enhancement on top of `URLRequestConvertible`, I don't think it's something to be included in the framework right now.

**Comment by gmarm** [comment]
Thanks for your feedback! 

@cnoon, it definitely makes sense to turn the `typealias` into a `struct`, and @jshier you make some very valid points indeed.

I think I will then keep iterating on this in a separate repo, and lets see what will be announced at WWDC.

Cheers!

**Comment by gmarm** [comment]
I've updated `URLRequestConfigurable` for Swift 3.0, also taking into consideration the feedback posted above.

You can find it [here](https://github.com/gmarm/AlamofireURLRequestConfigurable).

If it's something you would consider merging let me know, otherwise I'm gonna keep it as a separate repo. :)
