### ISSUE TITLE
No network (app crash)

### ISSUE THREAD

**Issue by chashmeetsingh** [Alamofire/Alamofire#1283]
Data from my API takes 5s to be retrieve in those 5 s if I disconnect internet app crashes

**Comment by cnoon** [comment]
Hi @chashmeetsingh,

I'd suggest you continue to debug on your end what the actual issue is. If you end up finding a specific issue in Alamofire itself, please provide more info and I'll be happy to re-open and help investigate further. If you need additional help debugging your issue, then I'd suggest you open a question on Stack Overflow.

Cheers. 🍻
