### ISSUE TITLE
Question: Does each .responseJSON handler deserialize the raw data into JSON?

### ISSUE THREAD

**Issue by mrubin** [Alamofire/Alamofire#1294]
If I have multiple `.responseJSON()` handlers installed on a given request, does each one deserialize the JSON from the underlying data? (Just want to confirm)

Is there any mechanism by which I could pass the deserialized JSON `AnyObject` along to further `responseJSON` handlers?

For example, let's say that at a lower level (of my code), I want to ensure that I received a valid JSON response from the server - if not, I want to print a message or handle this in a common/centralized way. So I install a `.responseJSON` handler (or a `response(request, response, data, error)` handler and attempt to do the deserialization myself). Then higher up, the code responsible for making the request has its own `.responseJSON` handler. In the case of a successful result.. I've already deserialized the JSON.. but now I'm doing it again (?).

I could make a custom response serializer... but it looks like that's always given the `NSData` again. For the default case of the response handlers running on the main queue (so, serially).. it would be nice to have a mechanism to pass data from one to the other.

Thank you.

**Comment by cnoon** [comment]
Hi @mrubin,

Great questions. Let me try to clarify for you.

> If I have multiple .responseJSON() handlers installed on a given request, does each one deserialize the JSON from the underlying data?

Each one will deserialize the JSON from the `NSData`.

> Is there any mechanism by which I could pass the deserialized JSON AnyObject along to further responseJSON handlers?

There is nothing built directly into Alamofire at the moment to support this. You would need to build a custom response serializer. @jshier has built a good example of how this could look [here](https://gist.github.com/jshier/f08f08e05d994b5bdc7d). This is also the best way to handle any custom threading model you need to use. The underlying `response` method takes an optional `queue` parameter to allow you to continue running your custom response serializer on whatever `dispatch_queue_t` you want.

Instead of trying to think of how to pass objects between chained request methods, I would encourage you to think of how to split your response serializer into multiple steps like @jshier does in his example.
