### ISSUE TITLE
Alamofire behavior when app go to background

### ISSUE THREAD

**Issue by vsching** [Alamofire/Alamofire#1299]
Hi,
I am doing an image upload using Alamofire.upload().response.

However, sometimes user press the home button(not lock button) and the app go into background when it is uploading. 
I noticed that Alamofire response closure does not run when it happens. Causing my app to think that upload has failed, even thou it has succeed.

Is it the default behavior of nsurlconnection? How do I avoid this issue?

Thanks

**Comment by cnoon** [comment]
Hi @vsching,

You'll want to read up on how the [URL Loading System](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html#//apple_ref/doc/uid/10000165-BCICJDHA) works from Apple. You're question requires quite a bit of background knowledge on how the default URL session configuration works vs. a background URL session configuration. I'd encourage you to open a question on Stack Overflow rather than our GitHub project. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
