### ISSUE TITLE
Not working with mjpeg format (video stream from ip camera)

### ISSUE THREAD

**Issue by kovallux** [Alamofire/Alamofire#1300]
Hi, I discovered that Alamofire does not work with multi part jpeg streams from ip cameras, though NSURLSession with **dataTaskWithRequest** method works fine.
When I try this:

```
Alamofire.request(.GET, "http://wmccpinetop.axiscam.net/mjpg/video.mjpg")
            .responseData { response in
                switch response.result {
                case .Success:
                    success(response.data)
                case .Failure:
                    failure(response.result.error)
                }
        }
```

It does not even get any response.

Try this url http://wmccpinetop.axiscam.net/mjpg/video.mjpg (not working), other image streaming formats seem to work fine. Can you check?

**Comment by cnoon** [comment]
Hi @kovallux,

Alamofire is going to handle the request the same way that `NSURLSession` does because Alamofire is built ontop of `NSURLSession`. When you say `dataTaskWithRequest` works, what do you mean by that? Could you provide a code sample? That data task will stay open until you actually cancel the request.

Here's an example of how you could use the `stream` api to stream the data directly to a closure that you control to process the image data as it is downloaded from the server.

```swift
func testMJPGDataFormat() {
    let expectation = expectationWithDescription("Video image should succeed")
    var gatheredEnoughImageData = false
    let imageData: NSMutableData = NSMutableData()

    let request = Alamofire.request(.GET, "http://wmccpinetop.axiscam.net/mjpg/video.mjpg")
    request.validate(statusCode: 200..<400)
    request.stream { data in
        guard !gatheredEnoughImageData else { return }

        imageData.appendData(data)

        print("New data: \(data.length), total image data: \(imageData.length)")

        if imageData.length > 300_000 {
            gatheredEnoughImageData = true
            request.cancel()
            expectation.fulfill()
        }
    }

    waitForExpectationsWithTimeout(timeout, handler: nil)

    print("Final Image Data Length: \(imageData.length)")
}
```

Hopefully this helps give you some ideas on how this could work. I'm going to close this issue out for now. If you end up providing some more info that leads us to believe there's an issue with Alamofire, we'll happily re-open this issue and continue to investigate further.

Cheers. 🍻
