### ISSUE TITLE
Upload tasks from NSData are not supported in background sessions

### ISSUE THREAD

**Issue by girishghoda** [Alamofire/Alamofire#1304]
hi
how to resolve this error
i want to upload data in background

if i use multipart from data then its increase data length which is not match to original so my image not perfactly upload to server

but if i use data then its upload perfactly

but when i try upload with manager then its fire not supported background session error

Thank you

**Comment by cnoon** [comment]
Hi @girishghoda,

These types of questions are best suited for Stack Overflow. We use our GitHub project for bug reports and feature requests. I'd also encourage you to provide more info when creating the Stack Overflow question, otherwise it is really difficult for people to help you out.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
