### ISSUE TITLE
Background manager configuration

### ISSUE THREAD

**Issue by shalinipriyaannadurai** [Alamofire/Alamofire#1336]
Hi Team,

I am trying to make network call when my app is background. So I am using background manager configuration API in the iOS Sample App.

But I get the following error. I am wondering how to proceed.
Any help is appreciated.

FAILURE: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://httpbin.org/post, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://httpbin.org/post}

**Comment by jshier** [comment]
Issues of this sort are nearly always due to failing to keep a reference to your `Manager` alive. Usually you'll want a singleton value that lives outside of any view controller or other structure in the app. For more information, questions like this are a good idea for StackOverflow, where you can get implementation help. If you find a bug with Alamofire, feel free to open another issue with a code sample and we'll take a look.
