### ISSUE TITLE
Download Response Data nil every time

### ISSUE THREAD

**Issue by girishghoda** [Alamofire/Alamofire#1344]
download.response { request, response, data, error in }

after download response data always return nil

actually i want to get download data & append in existing file & save

Thank you.

**Comment by cnoon** [comment]
Hi @girishghoda,

You need to use the `error` to check whether or not the download was successful when using the `download` APIs. Here's an [example](https://github.com/Alamofire/Alamofire#downloading-a-file-wprogress) in our README.

The `data` parameter will only be non-nil when the download fails and resume data was generated. The reason for this because of the way download tasks work with an `NSURLSession`. If you are downloading small amounts of information and need to access the data directly in-memory, then you should probably look at using the `request` APIs instead.

Cheers. 🍻

**Comment by girishghoda** [comment]
hi @cnoon 
so how to access downloaded data ?
i want daownload data bcz i download large file in chunk manner i request server to give me 1 mb byte & i append las saved file .

Thank you

**Comment by cnoon** [comment]
You need to read the data from the `NSURL` you provided in the `destination` closure.

**Comment by girishghoda** [comment]
Thank you @cnoon
