### ISSUE TITLE
Hello, I had used pod to install Alamofire,but Xcode does not prompt，I do not know why,can you tell me?

### ISSUE THREAD

**Issue by bianxiang** [Alamofire/Alamofire#1348]
![image](https://cloud.githubusercontent.com/assets/16380379/16864458/635cf7c2-4a8f-11e6-95a2-97a0c0d704b1.png)

**Comment by cnoon** [comment]
There could be all sorts of issues as to why autocomplete wouldn't work correctly such as indexing is not complete, Xcode cache is corrupt, not installed correctly, machine needs to be rebooted, Alamofire hasn't been compiled in the project, etc.

With that said, it looks like autocomplete is working. Look at the 5th item down...`AlamofireVersionNumber`. That symbol comes from Alamofire. Instead, try some of the methods in our [README](https://github.com/Alamofire/Alamofire#usage).

Best of luck! 🍻

**Comment by SahebRoy92** [comment]
Same issue is recurring for me. 
I didnt get the solution to this anywhere else, that is why I have to open this issue once again.

Here is my pod details 

platform :ios, '10.0'

```
use_frameworks!
target 'PhotoTagger' do
    pod 'Alamofire'
end
```

Also the only thing being auto completed is `AlamofireVersionNumber` and i cannot access anything when I am trying to use the auto complete feature. Now if i write Alamofire by hand then I can access some methods, but then again something is going wrong and code is not compiling, which i think boils down to the issue that the class isnt being fetched by auto complete.

I have tried - 

In Project settings > Build settings
1. Always search user path To YES 
2. Header search path to only include "$(inherited)" as non-recursive


All other pods are working fine, except Alamofire.
Also after writing class name by hand or copy pasting, some of the methods that are being auto completed does not have the same signature of the actual method of the Alamofire class 

Please please please !! help me sort this out, so that someone out there when facing this can help themselves too. There isnt any solution to this as of now.
