### ISSUE TITLE
Please support server signed x509 certificates

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1351]
[VeeWee's blog post](http://veewee.github.io/blog/authenticating-with-x509-client-certificates/) shows what I'm trying to do. 

Basically OAuth is a PITA to setup and this seems much easier and more secure.  I can just generate a certificate on the server that lasts for 20 years, create a client one that lasts just as long, and then bundle that client one inside my application.  Now I know that even if somebody figures out a person's user/pwd they still can't connect to the web API because they're not providing the properly signed certificate.

**Comment by grosch** [comment]
Any thoughts on when this might be able to happen?  I've been trying to make it work myself but I'm pretty clueless as to what I'm doing here.

**Comment by grosch** [comment]
I ended up getting this working with the following code.  Not sure if it's *right* or not, but it seems to work, and hopefully saves you some time on implementation.  See specifically the note on passing nil for the certificates.  

```Swift
        manager.delegate.sessionDidReceiveChallenge = {
            session, challenge in

            guard challenge.previousFailureCount == 0 else {
                challenge.sender?.cancelAuthenticationChallenge(challenge)
                return (.CancelAuthenticationChallenge, nil)
            }

            let url = NSBundle.mainBundle().URLForResource("Certificates", withExtension: "p12")!
            let data = NSData(contentsOfURL: url)!

            var importResult: CFArray? = nil
            SecPKCS12Import(data, [kSecImportExportPassphrase as String : "qwer1234ASDF"], &importResult)

            let result = (importResult! as NSArray as! [[String : AnyObject]]).first!

            let identity = result[kSecImportItemIdentity as String] as! SecIdentity

            // See oso.com.pl/?p=207&lang=en for why certificates is nil
            let credential = NSURLCredential(identity: identity, certificates: nil, persistence: .ForSession)

            return (.UseCredential, credential)
        }
```

**Comment by jshier** [comment]
@grosch We'll discuss what it would take to do this.

**Comment by grosch** [comment]
Hi, @jshier.  I'm sure you guys are swamped with the new GM release, but was just wondering if there was any progress on this one?

**Comment by cnoon** [comment]
No progress at all @grosch. We have however implemented a new `RequestAdapter` and `RequestRetrier` system to support auth flows like OAuth2. You can check it out in our Alamofire 4 [migration guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#new-features). But this will certainly not ship in Alamofire 4, if at all. We haven't had time to discuss it yet in detail.

**Comment by cnoon** [comment]
Hi @grosch,

I just looked through your implementation and I think it makes sense. As long as you're able to get the handshake to succeed, you should be good there. 👍🏼

Now as to whether or not we'll be adding direct support for x.509 certs in Alamofire, I'd say at this time we most likely won't add direct support for them. You're the only person that has requested support and it doesn't seem super common in the mobile world. If we end up having more people request support for client certs, we'll certainly reconsider. But for now, we'll leave client side cert authentication up to each client to implement in a manner similar to what you've posted above.

With that said, I've added a card to our Trello backlog to investigate this again in a future release. But if there isn't that much of an appetite from the community for this feature, I doubt we'll end up supporting it since it's a difficult feature to test.

Cheers. 🍻
