### ISSUE TITLE
Use parameter names in closures

### ISSUE THREAD

**Issue by BenchR267** [Alamofire/Alamofire#1355]
In callback closures like the following:

```Swift
self.manager.request(.GET, url, parameters: parameters, encoding: .URLEncodedInURL)
            .response { request, response, data, error in
            
        }
```

Alamofire does not use parameter names for the parameters of the closure. Xcode offers a very good autocompletion if those are specified and they don't have to be typed each type the method is called.
I propose adding those names and would like to help adding them if you are ok with the change, maybe you have some good reasons to not add them. Would love to discuss about it!

**Comment by jshier** [comment]
I agree, this has long been an annoyance for me as well. I'll look into getting it done. I think it's something that can be done without making any breaking changes, since it's just a convenience for developers. However, I don't know how this will be impacted by [Swift Evolution proposal 111](https://github.com/apple/swift-evolution/blob/master/proposals/0111-remove-arg-label-type-significance.md) for Swift 3.

**Comment by cnoon** [comment]
Due to the changes in Swift 3, this isn't something you can actually do. However, we've modified all the `response` APIs in Alamofire 4 to only take a `response` object rather than the four listed above. That should make things easier.

Cheers. 🍻

**Comment by BenchR267** [comment]
@cnoon awesome, thanks for the update!
