### ISSUE TITLE
Parse JSON Error

### ISSUE THREAD

**Issue by thaoth58** [Alamofire/Alamofire#1359]
I used .responseJSON 
```
        ApiManagement.manager.request(router.getHashCourse).responseJSON {
            response in
            debugPrint(response)
        }
```
but it return:
FAILURE: Error Domain=NSCocoaErrorDomain Code=3840 "Unable to convert data to string around character 8342." UserInfo={NSDebugDescription=Unable to convert data to string around character 8342.}

But when i use .responseString then I convert the responseString to JSON, it success.

```
        ApiManagement.manager.request(router.getHashCourse).responseString { response in
            if let data = response.result.value?.dataUsingEncoding(NSUTF8StringEncoding) {
                do {
                    let json = try NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments) as? [String:AnyObject]
                    print(json)
                } catch {
                    print(error)
                }
            }
        }
```

Anyone can help me to use .responseJSON, thank so much

**Comment by cnoon** [comment]
Hi @thaoth58,

It appears that `NSJSONSerialization` is failing to parse your response into JSON. That's why I would debug on your end. In the future, I'd encourage you to ask these types of questions on Stack Overflow. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by thaoth58** [comment]
Thank for your response 👍 

But i wonder can we have a function to set the Encoding of the data ? :D

**Comment by cnoon** [comment]
There's no need to set an encoding value because you don't need to convert to a `String` before using `NSJSONSerialization`. The `NSURLSession` already hands you back a complete `NSData` object from the server which can then be handed directly to `NSJSONSerialization`. There's no need to transform the `NSData` into a `String` before `NSJSONSerialization` gets it.

**Comment by thaoth58** [comment]
Maybe i know the issue :D 

My JSON response a string that contains Unicode Character: "\u0110\u0103ng kí thành công vui lòng vào mail \u0111\u1ec3 xác nh\u1eadn."  so that it can't be decoded 

So can you help me with this :( Thank so much

**Comment by thaoth58** [comment]
Oh, sorry, I know. My server uses charset=ISO-8859-1 :((
