### ISSUE TITLE
request sets "Content-Type" = "text/html automatically

### ISSUE THREAD

**Issue by duraiganesh0** [Alamofire/Alamofire#1373]
i used alamofire for the other requests where is sets the content type as follows 
**{ status code: 200, headers {
    Connection = "keep-alive";
    "Content-Length" = 179;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 27 Jul 2016 11:16:25 GMT";
    Etag = "W/\"b3-vhys+vZ9h+PEYCvzLEflJw\"";
    "X-Powered-By" = Express;
} }**

but for this specific request it sets the content type as text/html

**{ status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 1773;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Wed, 27 Jul 2016 11:16:36 GMT";
    Etag = "W/\"6ed-VP4lf3zxrU/ssT2vFK37nw\"";
    "X-Powered-By" = Express;
} }**

what could be the problem?

**Comment by cnoon** [comment]
Hi @duraiganesh0,

The problem is more likely that you're getting back a `500`. You're most likely getting back a default error message from the server that just happens to be HTML. You'll want to print out the `data` returned by the server as a string to see if that can help you figure out what you're doing wrong.

In the future, I'd recommend you open questions like this on Stack Overflow. We use GitHub for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by duraiganesh0** [comment]
thanks @cnoon

**Comment by mcreatisoul** [comment]
Thank you.
I have also faced same type of problem in my web page [https://www.assureshift.in/packers-and-movers-navi-mumbai](https://www.assureshift.in/packers-and-movers-navi-mumbai)
