### ISSUE TITLE
Alamofire multipart usage

### ISSUE THREAD

**Issue by mojidabckuu** [Alamofire/Alamofire#1376]
I started to use Alamofire and faced with a lot of issues during request building.
Alamofire is super async it is nice but at the same time it is stateless. For example, I am building multipart request and it immediately goes to encode my data and parameters using another queue. Only after successful encoding I can obtain real Request reference. So it requires from me create extra `var request: Request?` somewhere and wait when encoding will finish. So literally we have 2 completion blocks one is for encoding and one is for response. Why it is like this? Why it is not merged to the same completion that I expect into response?

**Comment by jshier** [comment]
@mojidabckuu A good question. It comes down to the fact that a multipart request can be very large and the encoding of this data can take more time than should be spent on the calling queue, so it's offloaded to a background queue. At the same time, Alamofire's `Request` type has no notion of an asynchronous `encoding` state, so there's now way for it to represent it's state before it's request is properly encoded. These two facts lead to the current implementation.

 In order to remedy this, Alamofire would either have to make all request encoding asynchronous, in which case `Request` would have to gain the notion of an encoding state and change it's behavior, or it would have to break different types of `Request` into their own subclasses, in which case only the type returned by the multipart encoding methods would know anything about an asynchronous state. 

We're considering changes along these lines for future updates. However, due to the breaking nature of such a change and all of the other changes that are already planned for Alamofire 4, it's unlikely to happen soon. However, if it's something you'd like to see, we'd consider a PR along these lines after Alamofire 4 is released.
