### ISSUE TITLE
Pause Request not contine other Requests wating in Queue.

### ISSUE THREAD

**Issue by ahmad-atef** [Alamofire/Alamofire#1388]
- I'm configuring the Alamofire Manager with HTTPMaximumConnectionsPerHost equals to 4.

- And I'm start Downloading 5 items, then 4 items start downloading and the the 5th item is waiting in queue.

- When I Pause one of the first 4th item, I'm expecting the 5th item to start downloading. This is not happening and this is my issue 💃 👯 
<img width="423" alt="screen shot 2016-08-08 at 3 49 05 pm" src="https://cloud.githubusercontent.com/assets/1938047/17481922/03cfd7a0-5d88-11e6-8c6d-be73ae3c2f0e.png">
<img width="423" alt="screen shot 2016-08-08 at 3 49 12 pm" src="https://cloud.githubusercontent.com/assets/1938047/17481945/2c8329fe-5d88-11e6-9a58-b1185f9a6567.png">

**Comment by jshier** [comment]
I suppose it all comes down to whether calling `suspend()` on task already in progress disconnects from the server. If it keeps the connection open, it makes sense that other tasks wouldn't start, as the connections are still at maximum. I'll do some investigation, but this is likely an underlying `NSURLSession` issue that Alamofire may not be able to do much about. If you're downloading large files, one option is to use `download` instead of `request` to start the process, when then makes it much easier to resume with partial data already on disk. That way you can just [`cancel(byProducingResumeData:)`](https://developer.apple.com/reference/foundation/nsurlsessiondownloadtask/1411634-cancel) and then resume later, rather than `suspend()`ing the task.

**Comment by cnoon** [comment]
There's no code here to go off. You've speculated a bunch here @jshier on the what-ifs where we have no idea how @ahmad-atef is actually "cancelling" the request. We also don't know if these are download or data requests. Everything you've stated is spot on.

I'm going to close this issue out @ahmad-atef. If you end up getting us some more info, we could investigate further if needed.

Cheers. 🍻
