### ISSUE TITLE
Validation for image/jpeg content type

### ISSUE THREAD

**Issue by kaelite** [Alamofire/Alamofire#1410]
Hello!
I have some problems with validating an answer from a server.
I need to know if it is an image, or an error in json format by content-type header.
Here is my code:
```
_ = APIClient.sharedInstance.defaultManager.download(
            APIClient.Router.BackgroundForLoginScreen(self.backgroundImageCreationTimestamp ?? "0"),
            destination: {
                (_,_) in
                return NSURL(fileURLWithPath: self.newBackgroundImageFilePath!)
            }
            )
             .validate(statusCode: 200..<300)
             .validate(contentType: ["image/jpeg"])
            .progress {
                [weak self] bytesRead, totalBytesRead, totalBytesExpectedToRead in
                
            }.response{
..
}

```
With `validate(statusCode: 200..<300)` all is ok.
But content type validation is not working. I have investigate into why it is returning success when I getting html/text answer from server instead image/jpeg. 
I found that reason is the 
` guard let validData = self.delegate.data where validData.length > 0 else { return .Success }` 
in validate(statusCode: ) in Validation.swift.
When I comment this line all is looks like working good. Also I have checked that validData is not used anymore in validate(contentType:). 

Is it anything that I have missed out?

**Comment by cnoon** [comment]
If you're trying to validate that you received a `image/jpeg` content type and you actually received `html/text` content, wouldn't you expect the validation to fail?

It seems to me that you enabled content type validation for `image/jpeg`, but then realized it was failing so you wanted to suppress the error rather than figure out why the validation was actually failing.

You cannot comment out that line of logic. It is there for a very good reason. It's saying that if you didn't get any data back, then you shouldn't produce a content type validation error because the content type doesn't apply to the non-existent data.

I'm going to close this issue out as support for now. If you continue to have issues, then I'd suggest you take this question to Stack Overflow.

Cheers. 🍻
