### ISSUE TITLE
Wrapping upload requests

### ISSUE THREAD

**Issue by mojidabckuu** [Alamofire/Alamofire#1428]
I had a question [here](https://github.com/Alamofire/Alamofire/issues/1376) 
So let's take a simple example
I have a controller that stores a reference for my request
```swift
class ViewController: UIViewController {
    var mrRobot: MRRobot = MRRobot()
    var request: Request!
    
    @IBAction func ElliotsTime(sender: AnyObject) {
        self.requres = self.mrRobot.hackSociety().response...
    }
}
```
and I want to wrap the generation/creation of my request. Just to reduce the code inside controller.

```swift
func hackSociety() -> Alamofire.Request {
    var request: Alamofire.Request! = nil
    Alamofire.upload(CRUDRouter(self, options: options).method(.POST), multipartFormData: { (multipartFormData) in
        multipartFormData.appendBodyPart(fileURL: self.pentagonSecrets, name: "kitty")
    }) { (encodingResult) in
        switch encodingResult {
        case .Success(let upload, _, _):
            request = upload // My request here only
        case .Failure(let encodingError):
            print(encodingError)
        }
    }
    return request
}


```
So it becomes a problem. If I want instantly return a reference on that request I am not able to do this. As solution I can add completion block to that method to handle encoding error. But it is not tasty. In that case it becomes 100 completion blocks when you have 100 multipart requests.

Did I miss something? How I can handle that situation in correct way to have clear chaining without extra completions? I also checked other branches but they have the same logic. Is it only by forking?

**Comment by cnoon** [comment]
If you MUST have the `Request` returned from `hackSociety` (bonus points for Mr. Robot refs), then you could create the `MultipartFormData` on your own, encode it, then pass that off to the `upload(data:)` API instead. This would allow you return the `request` immediately rather than having it be an async operation.

Now let me stress here that unless you're dealing with super small payloads, you don't want to be doing this on the main thread. The multipart form data upload APIs are designed to be async because generally they need to be.

Cheers. 🍻
