### ISSUE TITLE
Problem building test project - framework not found Alamofire for architecture

### ISSUE THREAD

**Issue by mattnedrich** [Alamofire/Alamofire#1429]
I repeatedly receive this error message when trying to build my test project. It seems somewhat intermittent, though when I receive it I don't know how to fix it. Sometimes it goes away when I re-install cocoapods. Not sure if it's an issue with Alamofire or Cocoapods, but I thought I would start here.

It's of interest to note that my actual project builds just fine, this is only an issue with my test project.

`ld: framework not found Alamofire for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by DweebsUnited** [comment]
I'm having the same issue on El Capitan 10.11, with Xcode version 7.3.1. Build and run works just fine, but I can't test without getting this error every time.

My project uses Carthage to manage all the frameworks though, and I have tried reinstalling it, as well as rebuilding all the dependencies, neither of which made a difference.

**Comment by DweebsUnited** [comment]
@mattnedrich 

I finally managed to resolve this for my case. My setup is a little different from you, but the symptoms were exactly the same. Could not build test target, but the project built just fine.

I use carthage, and the issue ended up being Xcode trying to link an OS X framework in an iOS project.

The solution was to change the Build Setting: "Framework Search Paths" to point at the iOS build folder, instead of it being blank.

While it might not work exactly for you, verifying that setting could be illuminating.

**Comment by cnoon** [comment]
Hi @mattnedrich,

This is not an issue with Alamofire. We have many people using Alamofire with CocoaPods without issue. I'd recommend opening a question on [Stack Overflow](https://stackoverflow.com) for questions like this. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by askaale** [comment]
I do also have this issue. Installing Alamofire through CocoaPods.
