### ISSUE TITLE
Upload, extra argument in call

### ISSUE THREAD

**Issue by ingouackaz** [Alamofire/Alamofire#148]
I'm trying to make a post upload request with parameters but it does not work ... .

Swift compiler error display  ''Extra argument in call''

Here is my code    

```
   '' var data : NSData =   UIImagePNGRepresentation(UIImage(named: "file.png"))

    Alamofire.upload(.POST, self._selectedPatient.filesUrl, parameters:["key":"value"],data)
        .responseJSON { (request, response, JSON, error) in

            println(JSON)
    } ''
```

How can we make a post request with multiple parameters ?

**Comment by albincr** [comment]
How can i upload a image along with parameter?? Eg i want to upload an album with images with its name and description?

**Comment by cnoon** [comment]
Hi @albincr, it depends on your service. Most likely you'll want to upload the data as [MultipartFormData](https://github.com/Alamofire/Alamofire#uploading-multipartformdata). You may also need to pass the parameters in the [query string](https://github.com/Alamofire/Alamofire#manual-parameter-encoding-of-an-nsurlrequest) and supply the image data for the [upload](https://github.com/Alamofire/Alamofire#uploading-a-file).

**Comment by albincr** [comment]
![screen shot 2015-07-20 at 3 16 19 pm](https://cloud.githubusercontent.com/assets/12035987/8773512/6a3694b8-2ef2-11e5-9d7a-463cf0e506be.png)


Im getting error at .POST ,

**Comment by cnoon** [comment]
You probably have some conflict. You could try `Alamofire.Method.POST`. Otherwise please take your questions to Stack Overflow.

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
