### ISSUE TITLE
Requiring OS X 10.11 for the Swift3 branch seems very premature

### ISSUE THREAD

**Issue by steveatinfincia** [Alamofire/Alamofire#1490]
I was reading over the similar [issue for iOS 8/9](https://github.com/Alamofire/Alamofire/issues/1367), and I understand the reasoning in general (iOS major versions are adopted *rapidly*, even just the current version gets you almost everyone within a month or two), but things are quite a bit different on OS X.

Stats for OS X adoption are a bit harder to find than iOS, but it looks like 10.11 adoption was [hovering around 40%](http://www.computerworld.com/article/3029090/mac-os-x/os-x-el-capitan-adoption-lags-behind-predecessors.html) even 4 months after it was released. Mac users just don't update as quickly, [even when their hardware is supported by newer versions](https://duo.com/blog/duolytics-os-x-upgrade-adoption).

Current median adoption stats I can come up with, according to [GoSquared](https://www.gosquared.com/global/mac/el-capitan/#month):

* 10.9: **~10%**
* 10.10: **~32%**
* 10.11: **~55%**
* 10.12: **~3%**

To get a number similar to the 92%+ iOS stat you would currently have to go 2 versions back to OS X 10.10, which gives you ~90%. That will likely still be the case for several months, and as Apple will also still be supporting 10.10 with security patches for another year (they support $current - 2), that seems like a better choice of cutoff.

Thanks :)

P.S. does anyone know of a good chart showing which machines are left behind by specific versions of OS X? The data is available but I haven't found an existing site for it yet, I might have to make one.

**Comment by grosch** [comment]
I'd be so very happy if this still supported 10.10

**Comment by cnoon** [comment]
Hi @steveatinfincia,

Thanks for putting together this issue. It's well thought out and makes a very good case against our current deployment target choices. Let me do my best walk you through being on the other side of this ask.

## Background

Alamofire currently supports 4 platforms each across two MAJOR versions of each of them. It also supports three different versions of Swift, not to mention we maintain three different libraries. All of this put together is a huge effort to maintain and keep bug free. We've managed to do a pretty good job on this front, but it's not scalable if we move to supporting 3 MAJOR versions at the same time.

It's very important for us to keep our MAJOR versions supported bundled together across platforms. What I mean by that is that if we decided to support macOS 10.10, then we should really support iOS 8 since they are more or less the same version of the underlying frameworks. Since tvOS and watchOS (debatable) weren't around then, they don't fall into this camp. This helps keep the supported versions more cohesive and also helps us keep in mind the limitations and bugs in these different versions of the underlying frameworks.

There have been some pretty nasty hacks we've had to put in place to workaround various bugs on some of the older frameworks. We've also had to put in place a bunch of workarounds to get around various differences between the platforms across MAJOR versions. All of this creates a VERY large amount of maintenance headache, especially when it comes to testing. We want to make sure we're providing a top notch library with everything covered (as much as possible) in unit or integration tests. And not only do we want to make sure we have full coverage across our feature set across all platforms and versions, we also want to make sure they all pass and continue to pass!

## Testing

Thankfully we're able to leverage Travis CI for testing which has been a huge help, even if it is a little unstable at times. The biggest gap we have here though is actually when trying to test the macOS builds. We don't have the ability to run the test suite on older versions right now. [Travis-CI](https://docs.travis-ci.com/user/osx-ci-environment/) has amazing support for older versions of Xcode, but not on varying OSX versions. This means that we'd be able to get things compiling, but wouldn't be able to run the test suite against macOS 10.10 which is a super high risk proposition. Especially when that's the oldest platform and the one that we've forgotten the most about.

## Decision

Given all these things, we've decided that it's the best overall decision for the community for us to drop both iOS 8 and macOS 10.10 support in Alamofire 4. Please don't think we made this decision lightly. It actually took us several days to come to a consensus. Now what we also don't want to do is leave users in the dark. This is why we released Alamofire 3.5.0 supporting both Swift 2.2 and 2.3 (not a small task) supporting iOS and tvOS 8-10, macOS 10.10-10.12 and watchOS 2-3. We also managed to get the Travis-CI yaml file working across both Xcode 7 and 8 so we have the coverage in the test suite that we're looking for. This allows anyone out there that needs to support macOS 10.10 or iOS 8 to at least have the option to do so while migrating over to Swift 3.

## Options

Now in the worst case scenario that someone is building a new macOS app in Swift 3 and needs to support macOS 10.10, then they'll need to do so in a fork. I just did it to see what would be required and it would just need availability checks around all the `StreamRequest` support. There are probably some other oddities in the test suite that would need to be addressed as well. But this is really worst case scenario if the Alamofire 3.5.0 release just cannot work for you.

I really hope that helps explain our point of view on this matter. Again, it wasn't an easy decision, but we stand by it being the correct one for the community as a whole.

Cheers. 🍻
