### ISSUE TITLE
Swift 3 errors

### ISSUE THREAD

**Issue by rjong** [Alamofire/Alamofire#1498]
Hi there,

I've upgraded my project to Swift 3 and updated Alamofire to version 3.5.
But now I have 190 issues getting from Xcode. Do I forget something while converting?

![Screenshot](http://i.imgbox.com/T838Fax8.png)

Thanks!

**Comment by cnoon** [comment]
Alamofire 3.5.0 only supports Swift 2.3. You need to use HEAD of master for Swift 3. We haven't released Alamofire 4 yet with Swift 3 support.

**Comment by WERUreo** [comment]
@cnoon Can you update the README to reflect that?  Currently, it is saying that Swift 3.0+ is a requirement, but if it's not been officially released, that is misleading.

**Comment by cnoon** [comment]
We're actively updating the documentation now @WERUreo. Please understand that Alamofire 4.0.0 is not released. If you are looking at unreleased branches, you cannot expect all the documentation and everything to be perfectly up-to-date.

**Comment by WERUreo** [comment]
I understand that Alamofire 4.0.0 hasn't been released.  What I'm saying is that the common user's first stop when they search for Alamofire is your Github page, which, by default, points to your master branch.  The README file there has conflicting information which is obviously confusing users, since they are writing issues here.

As for "unreleased branches", people are looking at master, not swift3.  Honestly, I wasn't asking for you to release v4.0.0.  I just thought that seeing Swift 3.0 as a requirement, and then a few lines down see that we should be installing v3.5 is presenting conflicting information and that maybe the requirements listed in the README that everyone is looking at (whether the master branch is unreleased or not) should match the version that same README is directing users to install.
