### ISSUE TITLE
xcode 8 swift convert tool to Alamofire.framework

### ISSUE THREAD

**Issue by mltk96** [Alamofire/Alamofire#1519]
if i want to use my project with swift 2.3 together with Alamofire SDK (that is installed through Cocoapods), what should i do when i open Xcode and it asks me to convert Alamofire.framework to swift 2.3?

**Comment by jshier** [comment]
You should make sure you're using CocoaPods `1.1.0.rc.2`, as that version of CocoaPods will generate the `Pods` project with the correct settings so Xcode won't say you need an upgrade. Plus, make sure you use Alamofire 3.5, as that's the only version compatible with Swift 2.3.

**Comment by mltk96** [comment]
still asks me to upgrade it.

**Comment by mltk96** [comment]
@jshier any advice?

**Comment by mltk96** [comment]
actually after installing AF 4.0, it also asks to convert AF's swift framework to swift 3.0

what am i doing wrong here?

**Comment by thomasbaldwin** [comment]
@mltk96 I'm getting the same issue. Not trying to upgrade my whole project to Swift 3 right now cause that's gonna be some work, and I'm using Alamofire 3.5 with cocoapods and have cocoapods 1.1.0.rc.2 installed, however, it still keeps asking me to convert it...

Sometimes when I build it will ask me to just fix the mistakes instead of convert it. Here are the issues it has:

<img width="453" alt="screen shot 2016-09-14 at 6 48 43 pm" src="https://cloud.githubusercontent.com/assets/5099084/18532718/f0a93694-7aab-11e6-85d0-3ac2c36283e5.png">
