### ISSUE TITLE
SequenceType compiler error

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [Alamofire/Alamofire#1539]
Hi after expending 4 hours I think that this is a problem with Alamofire, I'm trying to add generic response in a collection but I'm getting compiler error. Here is the error

```Undefined symbols for architecture arm64: "ExpSwift.SearchResults.generate () -> Swift.IndexingGenerator<[A]>", referenced from: ExpSwift_Example.ViewController.(viewDidLoad () -> ()).(closure #1).(closure #3) in ViewController.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Here are my classes
```swift
    public final class SearchResults<T> {
    
    var results: [T] = []
    let total: Int64
    
    required public init?(results: [T], total: Int64) {
        self.results = results
        self.total = total
    }
    
    public func getResults() -> [T] {
        return self.results
    }
    
    public func getTotal() -> Int64 {
        return self.total
    }
    
    }

    extension SearchResults : SequenceType {
    public func generate() -> IndexingGenerator<Array<T>> {
        return results.generate()
    }
    }
```
Here is my call with alamofire

```swift
ExpSwift.findLocations(["limit":10, "skip":0, "sort":"name"]).then { (locations: SearchResults<Location>) -> Void in
            for location:Location in locations{
                debugPrint(location.get("name"))
            }

            }.error { error in
                debugPrint(error)
        }
    }
```

I did test the same code on a single class and it works, so my only guess is something related to Alamofire or cocoapods I'm using alamofire version 3.1.5

**Comment by jshier** [comment]
Nothing you've posted points to an Alamofire issue. (You should update to Alamofire 3.5, there have been many bug fixes since 3.1). 

These types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by cesar-oyarzun-m** [comment]
I did post the problem in stackoverflow, I will try updating to Alamofire 3.5 but I post the problem here because I get the error only when I use the class with alamofire, if I use the class alone I don't have that compiler error.

**Comment by jshier** [comment]
I'll just say, I have seen errors like this when I was using CocoaPods to try and embed frameworks inside a framework target which I then used in my main app. CocoaPods can't properly do that right now, so while the autocomplete and stuff may work, the overall build would fail because the symbols weren't properly exported through the various layers of frameworks to my call site in the app. Other than that I think StackOverflow will give you a better chance of finding a fix.

**Comment by cesar-oyarzun-m** [comment]
thanks I will, I think you're right is something maybe with cocoapods
