### ISSUE TITLE
Alamofire POST with JSON encoded parameters - [57] socket is not connected

### ISSUE THREAD

**Issue by felixhedlund** [Alamofire/Alamofire#1545]
I just updated to swift 3 - and finally Alamofire is giving me more info on a problem I've had since I started my current project.

GET requests work fine. But when I try to POST with JSON encoded parameters it seems like the app is using a socket that was already closed.

I've tried everything to get this solved but could it be an underlying issue in iOS?

The only solutions that have worked for me have been to:
1. - encode the parameters in the URL. Not a solution that will work for my project.
2. - just resend the POST until it works. This is the ugly solution I'm using at the moment.

These are the errors I get:
> nw_socket_get_input_frames recvmsg(fd 24, 1024 bytes): [54] Connection reset by peer
> __tcp_connection_write_eof_block_invoke Write close callback received error: [57] Socket is not connected

My GET requests and POSTs without any parameters work just fine - any idea to why this is?

**Comment by jshier** [comment]
Unfortunately this isn't an Alamofire issue, as Alamofire doesn't interact with raw sockets at all. All of Alamofire's networking is done through the `URLSession` APIs, so if there's an issue there I'd suggest opening a bug with Apple.

Otherwise, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
