### ISSUE TITLE
Migration Swift 3.0 Xcode 8.0

### ISSUE THREAD

**Issue by JulienLacr0ix** [Alamofire/Alamofire#1547]
Hello,

Today I migrate to Xcode 8.0 and Swift 3.0 with your new release Alamofire 4.0

I have this podfile :

`# Uncomment this line to define a global platform for your project`
`platform :ios, '9.0'`

`project 'Morning.xcodeproj'`

`target 'Morning' do`
  `# Comment this line if you're not using Swift and don't want to use dynamic frameworks`
  `use_frameworks!`

  `# Pods Fabric`
  `pod 'Fabric', '~> 1.6.7'`
  `pod 'Crashlytics', '~> 3.7.2'`

 `# Pods for Morning`
 `pod 'Alamofire', '~> 4.0'`
  `pod 'SwiftyJSON', git: 'https://github.com/acegreen/SwiftyJSON.git', branch: 'swift3'`
  `pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'`
  `# pod 'Loggerithm', '~> 1.3'`
  
  `target 'MorningTests' do`
   ` inherit! :search_paths`
   ` # Pods for testing`
  `end`

 ` target 'MorningUITests' do`
   ` inherit! :search_paths`
   ` # Pods for testing`
  `end`

`end`

`post_install do |installer|`
	`installer.pods_project.targets.each do |target|`
    	`target.build_configurations.each do |config|`
      		`config.build_settings['SWIFT_VERSION'] = '3.0'`
      	`end`
    `end`
`end`

And when I launch Xcode I have some issue: 188.

<img width="325" alt="screen shot 2016-09-15 at 17 02 04" src="https://cloud.githubusercontent.com/assets/4347183/18555398/076c4026-7b68-11e6-9efc-46a36c955805.png">

Do you have any idea about my problem ?

Thank you for your reply !

@cnoon

**Comment by matheusvvb** [comment]
Same problem here. After update the Alamofire version to 4.0.0

![captura de tela 2016-09-15 as 13 16 07](https://cloud.githubusercontent.com/assets/12235426/18557757/a14e979c-7b46-11e6-837b-d35befd50ea2.png)

**Comment by codymoorhouse** [comment]
It looks like you guys didn't update Alamofire correct to the new version. You have to update your cocoapods first to a version that uses 1.1.0.+.

sudo gem install cocoapods --pre
pod update

**Comment by JulienLacr0ix** [comment]
Thanks for your reply.

 I have already tryed this way. So in my case, I have the last version version of cocoapods. This solution does not fix my issue.

Do you have another idea ?

**Comment by codymoorhouse** [comment]
In your Podfile.lock file which version does it show for you for Alamofire?

**Comment by JulienLacr0ix** [comment]
In my Podfile.lock :
`COCOAPODS: 1.1.0.rc.2`

**Comment by codymoorhouse** [comment]
Can you post your Podfile.lock? Or if you know the version of Alamofire you can post that.

**Comment by JulienLacr0ix** [comment]
Yes of course :
PODS:
  - Alamofire (4.0.0)
  - Crashlytics (3.7.3):
    - Fabric (~> 1.6.3)
  - Fabric (1.6.8)
  - PKHUD (3.2.1)
  - SwiftyJSON (2.3.2)

DEPENDENCIES:
  - Alamofire (~> 4.0)
  - Crashlytics (~> 3.7.2)
  - Fabric (~> 1.6.7)
  - PKHUD (from `https://github.com/toyship/PKHUD.git`)
  - SwiftyJSON (from `https://github.com/acegreen/SwiftyJSON.git`, branch `swift3`)

EXTERNAL SOURCES:
  PKHUD:
    :git: https://github.com/toyship/PKHUD.git
  SwiftyJSON:
    :branch: swift3
    :git: https://github.com/acegreen/SwiftyJSON.git

CHECKOUT OPTIONS:
  PKHUD:
    :commit: 28fb970b41d63134e962f9da766b96670c0f55f0
    :git: https://github.com/toyship/PKHUD.git
  SwiftyJSON:
    :commit: 8971384559780e631b041ac91b16734a396d4c14
    :git: https://github.com/acegreen/SwiftyJSON.git

SPEC CHECKSUMS:
  Alamofire: fef59f00388f267e52d9b432aa5d93dc97190f14
  Crashlytics: 76f6beaff70acf226139582c09c78461597c2b98
  Fabric: 5755268d0171435ab167e3d0878a28a777deaf10
  PKHUD: 001c11518f125a273ddf026bcc64918423744ea2
  SwiftyJSON: 04ccea08915aa0109039157c7974cf0298da292a

PODFILE CHECKSUM: 95ffb93589959087c06fecd62b7c58e4b5eff3a4

COCOAPODS: 1.1.0.rc.2

**Comment by codymoorhouse** [comment]
Hmm okay thanks, so your alamofire is up-to-date. I wonder if its something with the cache. 

Try running:
pod cache clean --all
pod update

If that doesn't work, try cleaning the project before running
Let me know how that goes.

Next I would look into looking at your build settings and making sure the versions align there as well with 9.0.

**Comment by JulienLacr0ix** [comment]
Okay, thanks for your reply. I didn't think about `pod cache clean -all` it was a good idea but does not work ...

I clean my ios project with product->clean and with product->(shift)clean build folder
and it does not work again. I have 188 issue again.

My project support iOS 9.0 and pod project too.
My Podfile have this line : `platform :ios, '9.0'`

So I think it's ok about iOS version.

About my build settings what do you want to see ?

Thx !

**Comment by jshier** [comment]
When you update your project to Swift 3, you need to run the conversion tool on your project first (not the CocoaPods, just your project). This is in the Edit menu -> Convert -> "To Current Swift Syntax...". This will update your project to require the Swift version you select (2.3 or 3), in addition to attempting to transition your apps code to that version of Swift as well. Once that's done and your project file has been modified to contain the `SWIFT_VERSION` setting, running `pod update` will use that setting to generate a new `Pods` project integration that uses that setting to set the Swift version for all of your pods. That should fix issues with the `SWIFT_VERSION` setting being required and such. 

However, since this is entirely an Xcode and CocoaPods integration issue I'm closing this issue out. If you have further issues, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by JulienLacr0ix** [comment]
@jshier 

Hi!

Yes I agree with you about best practice to migrate a project on Swift 3.0. And the problem is I made this exact process.

And I have 188 issue for Alamofire. I don't have problem with other library.

So I open an issue on your github because I looking for your help. 
Can you reopen my issue to keep looking for a solution ?

Thx!

**Comment by jshier** [comment]
There is not solution beyond what I've described. A project that has properly upgraded to Swift 3, CocoaPods 1.1.0, and Alamofire 4 should build just fine, barring any updates that must be made in the app's code to support the Alamofire 4 changes. Your issues are not with Alamofire, they're with something in your integration process that's preventing Xcode from seeing and building your app and it's dependencies as Swift 3 code. That is far beyond the purview of Alamofire.

**Comment by JulienLacr0ix** [comment]
Ok my bad.

I made `pod install` after convert my code in Swift 3.0.

If I convert my personal code and I launch `pod update` after modify my podfile my project build properly ! Maybe an error on cocoapods ? Or `pod install` is not a best practice ? I don't know but my problem is solve !!

Thank you for your reply @jshier & @codymoorhouse and have a good day ;-)
