### ISSUE TITLE
Using Xcode8.0,  Alamofire 3.5 issue with Swift 2.3

### ISSUE THREAD

**Issue by duanyicanyuan** [Alamofire/Alamofire#1555]
Undefined symbols for architecture x86_64:
  "Alamofire.Request.responseJSON (queue : __ObjC.OS_dispatch_queue?, options : __C.NSJSONReadingOptions, completionHandler : (Alamofire.Response<Swift.AnyObject, __ObjC.NSError>) -> ()) -> Self", referenced from:

How to solve the above problem?

**Comment by iliubave** [comment]
Update to Alamofire 4.0? Or is there a specific reason you don't want to?

**Comment by vslavik** [comment]
> Update to Alamofire 4.0? Or is there a specific reason you don't want to?

Not speaking for @duanyicanyuan, but its Swift >= 3.0 requirement is a pretty big one if you have larger codebase...

**Comment by duanyicanyuan** [comment]
@iliubave I need to support iOS8, but Alamofire 4.0 does not support

**Comment by Amefuri** [comment]
I have the same problem.
and cannot use Alamofire 4.0 since it required iOS 9.0

**Comment by Herb-Sun** [comment]
I need to support iOS 8+, I also want to use Alamofire 4.0 ~~~~(>_<)~~~~

**Comment by LinkedHK** [comment]
Stick with AFNetworking and Objective C was the best decision I have ever made. no hassle with updates

**Comment by jshier** [comment]
@duanyicanyuan Be sure to clear your derived data after doing an update, it seems like maybe you have some build products in there that haven't been rebuilt.

Otherwise, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
