### ISSUE TITLE
Error: Cannot call value of non-function type 'HTTPURLResponse'

### ISSUE THREAD

**Issue by elena-dare** [Alamofire/Alamofire#1560]
Error: Cannot call value of non-function type 'HTTPURLResponse'.
Problem is in the row "imageRequest.request.response" after updating to Swift 3.0

`	func getNetworkImage(_ urlString: String, completion: @escaping ((UIImage) -> Void)) -> (ImageRequest) {
		let queue = decoder.queue.underlyingQueue
		let request = Alamofire.request(urlString)
		let imageRequest = ImageRequest(request: request)
		
		
		imageRequest.request.response(
			queue: queue,
			responseSerializer: Request.imageResponseSerializer(),
			completionHandler: { response in
				guard let image = response.result.value else {
					return
				}
				let decodeOperation = self.decodeImage(image) { image in
					completion(image)
					self.cacheImage(image, urlString: urlString)
				}
				imageRequest.decodeOperation = decodeOperation
			}
		)
		
		return imageRequest
	}`

**Comment by jshier** [comment]
This type of compiler error is usually caused by something in your call to `response` no lining up with the compiler's type expectations. I would make sure everything in your codes has the type you think it does.

Otherwise, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by vchirino** [comment]
@elena-dare did you find the solution for this issue?

I want to do this:

**request.response {(req, resp, _, _) in
}.resume()**

the **request** is a Request (Alamofire) and i'm getting the same error:

_**Cannot call value of non-function type 'HTTPURLResponse'.**_
