### ISSUE TITLE
Proposition: Utilize existing Result project instead of own class

### ISSUE THREAD

**Issue by pawel-sekara** [Alamofire/Alamofire#1566]
There is a Result project which ReactiveCocoa uses:
https://github.com/antitypical/Result

Existing Result class conflicts with RAC one making it hard to use both libraries at the same time.

**Comment by cnoon** [comment]
We will not be adding dependencies to Alamofire @pawel-sekara. Please see #1167 for more information.

Cheers. 🍻

**Comment by ultimate-deej** [comment]
I'd like to point out the problem. I have read the other issues but IMO nobody has put it clearly yet. So, it's my turn to try.
Here's the problem as I see it, expressed by a table (yes, I see it like that). Let's take `Result` and, for instance, `SessionManager`:

 Type | Name Matches Type's Purpose | Name Matches the Purpose of the Library | Role in the Library
------|------|------|------
SessionManager | yes | yes | major
Result | no | no | utility

Considering its role, `Result` has no 'right' to be a top level symbol and have a name like that _(which is really broad)_ at the same time. It's just an auxiliary for the library and has a very specific purpose, _much more specific than its name_.

As for me, `RequestResult` could work out just fine. It matches the doc comment to the least, and reflects its true intent while not polluting (no offense meant) the top level namespace.

The last thought, regarding being a top level symbol. Technically, types are namespaced by modules, I know. But one doesn't usually write module name every time he refers to a type. From the everyday programming's point of view, they are at the top level.
Due to that fact, I think that explicit disambiguation by prefixing a module name should be the last resort for resolving name clashes and should be avoided whenever possible.
