### ISSUE TITLE
 Error in alamofire - 4.0 ( 3.0 swift )

### ISSUE THREAD

**Issue by dev12-SC** [Alamofire/Alamofire#1570]
I'm a mistake to use the alamofire in xcode 8.0 with 3.0 swift .
I tried many ways to work , updated in the pod lib alamofire to 4.0 the last came out with swift supports 3.0 and I'm in trouble .
Problem is in the picture below , if someone can help me with this problem thanks
![erro alamofire](https://cloud.githubusercontent.com/assets/15039214/18648186/e1aa0618-7e8f-11e6-9c34-731476ba1722.jpg)

**Comment by sungkim23** [comment]
I believe this is solved by updating the Cocoapods correctly, referring back to the Documentation, it states.

CocoaPods 1.1.0+ is required to build Alamofire 4.0.0+.

The current gem install cocoapods doesn't install 1.1.0+, you need to do gem install cocoapods --pre to install the beta version which is in 1.1.0+

**Comment by zjTek** [comment]
Can ALF4.0 been used on platform ios8?

**Comment by sjmueller** [comment]
This is a bigger problem than updating cocoapods, since I'm using carthage (which is resolving to 4.0.0) and I'm receiving the same exact error.

**Comment by jamshaidsadiq** [comment]
I'm receiving the same exact erro

**Comment by sjmueller** [comment]
Ok folks, so turns out that this is a super misleading error from the compiler that causes you to focus on the wrong area when troubleshooting. The source of the problem lies when the closure parameters are either incorrect or being misused (which will be common for old code since there's many signature changes from 3.0 -> 4.0). For instance, take the following code:

```
        Alamofire.upload(fileData, to: uploadUrl, method: .put)
            .uploadProgress { progress in
                // print("Upload Progress: \(progress.fractionCompleted)")
                // callback([Int(totalBytesExpectedToWrite/totalBytesWritten) as AnyObject])
            }
            .response { response in
                print(response.statusCode)
        }
```
This will give the infamous error:

![image](https://cloud.githubusercontent.com/assets/29085/18661825/7d56bd9a-7ecc-11e6-9599-f97f79b2f474.png)

The problem here is that the response *parameter* does not actually have a statusCode. Instead, the location of that property is at `response.response?.statusCode`, so the correct code that compiles is:

```
        Alamofire.upload(fileData, to: uploadUrl, method: .put)
            .uploadProgress { progress in
                // print("Upload Progress: \(progress.fractionCompleted)")
                // callback([Int(totalBytesExpectedToWrite/totalBytesWritten) as AnyObject])
            }
            .response { response in
                print(response.response?.statusCode)
        }
```

I'm sure this will manifest quite differently in various use cases across the 4.0 api in swift 3, but hopefully this gives a better clue than the compiler where to look.

**Comment by jamshaidsadiq** [comment]
i commented my code but still getting error

**Comment by stefanlam88** [comment]
Any solution with tis? I m facing it too

**Comment by toLLL** [comment]
Same error there, any news ?

**Comment by dosboxd** [comment]
I am getting this error too

**Comment by cnoon** [comment]
You must use `AlamofireImage 3.0.0` and `Alamofire 4.0.0` if you want to use AlamofireImage on Swift 3. I just created a small sample project demonstrating both working together.

- [AFTester.zip](https://github.com/Alamofire/Alamofire/files/491315/AFTester.zip)

If you are having trouble with the response error documented by @sjmueller...please see his comments to resolve your compilation issue.

Cheers. 🍻
