### ISSUE TITLE
Locking / Unlocking Screen Causes First Request Failure

### ISSUE THREAD

**Issue by Jayvd** [Alamofire/Alamofire#1594]
There is a noticably weird bug I have found in Alamofire.

This problem only occur when the screen is locked when the app is on the foreground

Steps to Reproduce

1. While App in the Foreground
2. Lock Phone
3. Unlock Phone
4. Trigger a request with Alamofire. <- This first request will always fail `Error Domain=NSURLErrorDomain Code=-1005 “The network connection was > lost.`
5. Every single request after this will get a proper response. Unless if the phone is locked again while it is in the foreground.

Can anyone using Alamofire find a fix to this?

N.B.: This problem found on Alamofire 4.0. I have also tested this on Alamofire 2.0 and it also has the same problem.

**Comment by thebluepotato** [comment]
I see you posted #1586. It seems to be the same bug so I'd suggest closing #1586 and changing this one's title to something a bit less vague (like #1586)

**Comment by cnoon** [comment]
Thanks @thebluepotato. @Jayvd, please don't open duplicate issues. It won't help you get your issue resolved any faster.

**Comment by cnoon** [comment]
Hi @Jayvd,

I put together a little sample app that demonstrates that making an Alamofire request immediately when your app is opened after unlocking does in fact succeed. I don't know exactly what is going on with your app, but it doesn't seem to be an issue with Alamofire directly.

- [Relauncher.zip](https://github.com/Alamofire/Alamofire/files/491428/Relauncher.zip)

> You'll need to set the team to debug the app on a device. 

I'm not quite sure what to tell you from here. You'll need to investigate your own app further to figure out why your requests are failing. 

I'm going to close this issue out since there's nothing that appears to be wrong with Alamofire. If you do end up finding something specific to Alamofire that seems problematic, please post your findings back on this ticket and we'll happily investigate further.

Cheers. 🍻

**Comment by NielsKoole** [comment]
So thank you @cnoon for clarifying. I just checked your example to verify the problem. When I execute the request to httpbin on the simulator (iOS10) and device (iOS9) it works fine. But when I connect to my own server it won't work anymore on my device. So with that knowlegde I came by this [https://github.com/facebook/react-native/issues/7943](link). Seems to be an issue with nginx 1.10.1

I've checked my servers nginx version which is 1.10.0 assuming it has the same issue, I'm now trying to update my nginx package. Will keep you posted.

**Comment by tobiasoleary** [comment]
My intuition says it has to do with the Keep-Alive setting. I think there was a bug in iOS 8 where the connection stayed open longer than the Keep Alive told it to (Don't know if it's still an issue). 

Do you cancel all open requests and then close all your connections when the app enters the background?

**Comment by NielsKoole** [comment]
Well the problem for me occurs when I start the app for the first time. So at that moment there are zero requests done, until the request get triggered by UI which results in a failure. So I don't think that has something to do with it.

**Comment by tobiasoleary** [comment]
Take a look at Issue #872. 

https://github.com/Alamofire/Alamofire/issues/872

**Comment by NielsKoole** [comment]
OK. Sounds like the similar thing indeed. The only 'strange' thing is, when my first request is a GET request it works like a charm the first time, it only fails consistently the first time when it's a POST request.

**Comment by NielsKoole** [comment]
Bump. Somebody found a solution or workaround already?

**Comment by rizwan95** [comment]
@NielsKoole  Initialize your Network Manager class again, in applicationWillEnterForeground and it will solve the problem. The reason for this issue is, when you lock your device , the OS locks the sockets and doesn't release them when the phone is unlocked. So please again initialize your network manager class and it will solve your problem. Reference : https://github.com/Alamofire/Alamofire/issues/872
