### ISSUE TITLE
Umbrella header 'Alamofire.h' not found

### ISSUE THREAD

**Issue by zhangfogao** [Alamofire/Alamofire#1609]
what's wrong with blow   imgae.   when I bulid program  
![image](https://cloud.githubusercontent.com/assets/20221361/18807344/f56b92da-8276-11e6-93c6-d4f48ed77425.png)

**Comment by cnoon** [comment]
Hi @zhangfogao,

This type of question is best suited for [Stack Overflow](https://stackoverflow.com). We use our GitHub project for bug reports and feature requests. Most likely you're issue is due to a mismatch in CocoaPods version or how you have your project configured.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by zhangfogao** [comment]
OK！ Thank you！
