### ISSUE TITLE
Æ, ø and å in response not working.

### ISSUE THREAD

**Issue by Dbigshooter** [Alamofire/Alamofire#1618]
Hi there,

I'm trying to get a responseJSON containing JSON with æ, ø and å, however it appears like this, for example:

`U00e6`

My call looks like this: 

```
Alamofire.request(specificURL, method: .get, parameters: param, encoding: URLEncoding.default, headers: nil).responseJSON { (response: DataResponse<Any>) in
            print(response)
        }

```

**Comment by jdleo** [comment]
@Dbigshooter that U00e6 you're getting is utf32 hex. You're gonna want to do some checks, and then get that converted over to the character you want. I wrote a function for you. Unless someone has a better way, this one works. Example:  
```
//say you get "//U00e6" from a GET request called  "response"

Alamofire.request(specificURL, method: .get, parameters: param, encoding: URLEncoding.default, headers: nil).responseJSON { (response: DataResponse<Any>) in
            let convertedHex = convertFromUnicode(myString: response)
            print(convertedHex) //this will print what you want :)
        }

//the function i wrote to convert unicode to string
func convertFromUnicode(myString:String) -> String {
    var myString = myString
    let convertDict:[String:String] = ["\\U00c0":"À", "\\U00c1" :"Á","\\U00c2":"Â","\\U00c3":"Ã","\\U00c4":"Ä","\\U00c5":"Å","\\U00c6":"Æ","\\U00c7":"Ç","\\U00c8":"È","\\U00c9":"É","\\U00ca":"Ê","\\U00cb":"Ë","\\U00cc":"Ì","\\U00cd":"Í","\\U00ce":"Î","\\U00cf":"Ï","\\U00d1":"Ñ","\\U00d2":"Ò","\\U00d3":"Ó","\\U00d4":"Ô","\\U00d5":"Õ","\\U00d6":"Ö","\\U00d8":"Ø","\\U00d9":"Ù","\\U00da":"Ú","\\U00db":"Û","\\U00dc":"Ü","\\U00dd":"Ý","\\U00df":"ß","\\U00e0":"à","\\U00e1":"á","\\U00e2":"â","\\U00e3":"ã","\\U00e4":"ä","\\U00e5":"å","\\U00e6":"æ","\\U00e7":"ç","\\U00e8":"è","\\U00e9":"é","\\U00ea":"ê","\\U00eb":"ë","\\U00ec":"ì","\\U00ed":"í","\\U00ee":"î","\\U00ef":"ï","\\U00f0":"ð","\\U00f1":"ñ","\\U00f2":"ò","\\U00f3":"ó","\\U00f4":"ô","\\U00f5":"õ","\\U00f6":"ö","\\U00f8":"ø","\\U00f9":"ù","\\U00fa":"ú","\\U00fb":"û","\\U00fc":"ü","\\U00fd":"ý","\\U00ff":"ÿ"]
    
    for (key,value) in convertDict {
        myString = myString.replacingOccurrences(of: key, with: value)
        
    }
    return myString
}
```

**Comment by jdleo** [comment]
@Dbigshooter I take that back, with my function, if it's not unicode, it will just literally return the original string. So you can put anything thru that. I just have the respective strings for each unicode value in that dictionary if you couldn't tell. If you're getting just U00e6 instead of //U00e6 like some people do, then just swap all the backslashes out

**Comment by jshier** [comment]
@Dbigshooter Are you sure your JSON is properly encoded? It sounds like it hasn't been properly encoded into UTF-8, which JSON requires. In any event, Alamofire doesn't do anything special with JSON payloads, it just uses `JSONSerialization` to decode the `Any` value out of it. If you find something that might be a bug in Alamofire, feel free to open a new issue with a sample project or at least a code sample that replicates the issue.

Otherwise, these types questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
