### ISSUE TITLE
Parameters getting an optional prefix

### ISSUE THREAD

**Issue by puhgeh** [Alamofire/Alamofire#1622]
Hi,

Why does the parameters being sent over gets an optional prefix? The parameters being passed in the request are not optional so why is it being converted and even being sent with unwrapped value (with optional prefix). Any solution on this?

Thanks!

**Comment by cnoon** [comment]
Hi @puhgeh,

To be honest, I don't really understand your question. I'm not sure what you mean by an optional prefix. However, I "may" have an idea, so I'm going to roll with it.

I "think" you're asking why `Parameters` is optional in the `ParameterEncoding` protocol. The reason this is optional is that we treat `nil` differently than an empty dictionary. A `nil` dictionary just simply returns the `URLRequest` with no actual parameter encoding since there weren't any parameters. An empty dictionary is however encoded by setting the `Content-Type` header and sometimes setting the `httpBody` of the `URLRequest` to empty `Data`.

If this was not your question, please rephrase and I'll try again.

Cheers. 🍻

**Comment by puhgeh** [comment]
Hi @cnoon ,

I've tried sending a request from my mobile app to my web service (by query or body or default encoding, basically tried all types) and the parameter values being sent has the optional prefix. I have here one of the logged request received in my web service:

Info:   content-type:application/x-www-form-urlencoded; charset=utf-8
Info:   accept:*/*
Info:   connection:keep-alive
Info:   content-length:204
Info:   user-agent:TestExercise/0.1.0 (com.vandt.app.Hate2Exercise; build:1; iOS 10.0.0) Alamofire/4.0.1
Info:   accept-language:en;q=1.0
Info:   authorization:Basic MjI3WkhCOjMwOWVhO....
Info:   accept-encoding:gzip;q=1.0, compress;q=0.5
Info:   request: client_id=Optional%28%222A3D%22%29&code=Optional%28%2249fb9ec9d73988a8e313285%22%29&grant_type=Optional%28%22authorization_code%22%29&redirect_uri=Optional%28%22testexercise%3A//%22%29

Notice the Optional word prefix on every parameter value. Same goes even on body type and so on.

**Comment by cnoon** [comment]
Hmmm...I'd guess you're passing in optional String parameters instead of making sure the `client_id` and `grant_type` are actually strings and not optional strings.

**Comment by jshier** [comment]
Actually, the values are probably being passed through string interpolation when being added as parameters, as the `Parameters` type of `[String : Any]` won't accept optional values. @puhgeh Don't run your parameter values through string interpolation just to make them non-optional values, you need to actually unwrap them like @cnoon said.

**Comment by puhgeh** [comment]
i'm passing them as string literals. like ["client_id": "blah_blah_blah", ....].
