### ISSUE TITLE
always fail with long URL

### ISSUE THREAD

**Issue by leizard** [Alamofire/Alamofire#1654]
Hi. I'm using Alamofire for requests to my Magento server. Everything works perfectly until I have to request by one different kind of url which use for searching.
The url is like this:
`
http://mymagento.com/index.php/rest/V1/products/?searchCriteria[filter_groups][1][filters][0][field]=category_id&searchCriteria[filter_groups][1][filters][0][value]=33&searchCriteria[filter_groups][1][filters][0][condition_type]=eq
`

I use it like other normal Alamofire request:
```
       let requestURL = "http://mymagento.com/index.php/rest/V1/products/?searchCriteria[filter_groups][1][filters][0][field]=category_id&searchCriteria[filter_groups][1][filters][0][value]=33&searchCriteria[filter_groups][1][filters][0][condition_type]=eq"
        
        Alamofire.request(requestURL)
            .validate()
            .responseArray { (response: DataResponse<[Product]>) in
                
                let result = response.result
                
                switch result {
                case .success :
                    if let products = result.value {
                        for product in products {
                            debugPrint(product.sku)
                            productList.append(product)
                        }
                        onSuccess(productList)
                        break
                    }
                case .failure :
                    onError(result.error! as NSError)
                }
        }
```
But the response result always fail. I tested the url on The RESTful client side Chrome plugin and it's working well. 
Do I miss something ?
Thank you.

**Comment by cnoon** [comment]
Hi @leizard,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by leizard** [comment]
Oh I should read the doc carefully. thank you for your reply
