### ISSUE TITLE
Validate Error 

### ISSUE THREAD

**Issue by umeshjavastar** [Alamofire/Alamofire#1659]
I am sending a request to server with .Validate() but I am facing a little bit of error
I am using..

` Alamofire.request(getUrl("category"),method: .get, parameters:params, headers: 
    customHeader).validate().responseJSON {`
     `  response in`
             ` switch response.result{`
                ` case .success:`
                   `if let value = response.result.value {`
                    `result = JSON(value)`
                    `//completion(result)`
                    `resolve(result)`
                `  }`
               `case .failure(let error):`
                  `reject(error)`
                `print("\(error)")`
       `  }`
  ` }`
        
`responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400))`

How to resolve this?? Please suggest me..

**Comment by hardikdevios** [comment]
is This error printing in the Logs ?

**Comment by umeshjavastar** [comment]
yes I don't know why this error arise?

**Comment by cnoon** [comment]
Hi @umeshjavastar,

You're validating that the response status code is 200...299 and it's 400. That's why you're getting an unacceptable status code error. Instead of opening an issue for this on our GitHub project, you should instead open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by Amandeep-iOS** [comment]
Update following to 
fileprivate var acceptableStatusCodes: [Int] { return Array(200..<500) }

**Comment by Jeff-KaayLabs** [comment]
This error mostly occurs because of empty JSON

**Comment by Srinivasan27** [comment]
Was the issue on server side? Please update your answer. Many [Stackoverflow](http://www.stackoverflow.com/) redirecting here.

**Comment by usama4792** [comment]
> Was the issue on server side? Please update your answer. Many [Stackoverflow](http://www.stackoverflow.com/) redirecting here.

its not on server side its working perfectly on postman
