### ISSUE TITLE
Uploading Multipart Form Data successes with no internet connection

### ISSUE THREAD

**Issue by quiKsilverItaly** [Alamofire/Alamofire#1660]
Using 4.0.1.

I completely turned of the phone from any internet connection and tried to upload something via Multipart Form Data. This part of the code becomes relevant:

```
switch encodingResult {
        case .success(let upload, _, _):
            upload.responseJSON { response in
                debugPrint(response)
            }
        case .failure(let encodingError):
            print(encodingError)
        }
}
```

I expected the `.failure` case, but for some reason the `.success` case gets returned. Also the inner closure of `upload.responseJSON` never gets called, but still it enters into the `.success` case. 

Why is that? Is that on purpose? With internet connection the method works completely fine and also the inner closure of `upload.responseJSON` gets called.

**Comment by cnoon** [comment]
Hi @quiKsilverItaly,

The success case is called because that's the success of the multipart form data encoding. It also exposes the actual upload request allowing you to chain onto it. Your `responseJSON` closure should be called eventually, but it may take a while depending on how much data you're uploading. You could add `uploadProgress` and `downloadProgress` closures to the `upload` to monitor the progress more closely.

Cheers. 🍻
