### ISSUE TITLE
RequestChain problem in Alamofire 4

### ISSUE THREAD

**Issue by omidkh68** [Alamofire/Alamofire#1661]
request.response(completionHandler: { response in
                if response.error != nil {
                    completionHandler(success: false, errorResult: ErrorResult(request: request, error: error))
                    return
                }
                self.requests.removeFirst()
                self.start(completionHandler)
            })

error : **cannot call value of non-function type 'HTTPURLResponse?'**

![screen shot 1395-07-12 at 17 55 08](https://cloud.githubusercontent.com/assets/4400137/19050804/15cb39de-89bd-11e6-8afc-53427ac5e14e.png)

it was working in Alamofire 3 :(

**Comment by omidkh68** [comment]
it was working in Alamofire 3

**Comment by hardikdevios** [comment]
try to write the method step by step you will see the exact error.

**Comment by cnoon** [comment]
Hi @omidkh68,

My guess is that the issue is actually in your implementation, not in the chained method signature...that looks correct. I'd take @hardikdevios's advice here and just rebuild the method and you'll spot your mistake.

In the future, for questions like this, you should instead open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
