### ISSUE TITLE
Request and DataRequest have duplicate names for function and property: response

### ISSUE THREAD

**Issue by MarcOConnor** [Alamofire/Alamofire#1679]
Hi! this is using Alamofire 4.0.1 on Xcode 8 and with Swift 3.0 (targeting iOS 9)

I want to call the response function of the DataRequest like this:
```
 request.response { response in
                    self.handleCallbackWithResponse(response.response, rawData: response.data, error: response.error, emptySucessBlock: emptySucessBlock,
                        errorBlock: errorBlock, completionHandler: completionHandler)
                }

```

but get this compiler error:
Cannot call value of non-function type 'HTTPURLResponse?'

The variable is declared in Request.swift:

```
    /// The response received from the server, if any.
    open var response: HTTPURLResponse? { return task?.response as? HTTPURLResponse }

```

... and the function is declared in an extension to DataRequest in ResponseSerialization.swift:
e.g.: 
```
    @discardableResult
    public func response(queue: DispatchQueue? = nil, completionHandler: @escaping (DefaultDataResponse) -> Void) -> Self {

```

The error is gone, when I rename the function in the ResponseSerialization.swift code (and in my code, when I call it)

Kind regards, Marc

**Comment by hardikdevios** [comment]
Please check method step by step let me help you please give me your method **prototype** of 

`handleCallbackWithResponse`

I think you are not passing the correct **parameters** while calling this function.

**Comment by cnoon** [comment]
Hi @MarcOConnor,

The issue is with your `handleCallbackWithResponse` API as @hardikdevios alluded to. It most likely needs to take a `DataResponse` instead of a `Response`. Just comment out that line of code and slowly start adding things back in.

For more info, please see #1560, #1597, #1650 and #1661.

In the future, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire` for this type of question. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
