### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by danipralea** [Alamofire/Alamofire#1692]
Hello!
I have an authentication process that I need to implement and it's done via basic-auth. It's working via Paw and Postman and via an old Objective-C app, but now I started a new Swift 3 app with Alamofire 4 and RxSwift and I'm having issues sending it.
My problem is that the `authorizationHeader(user: String, password: String) -> (key: String, value: String)` method is the exact thing I need.
I just don't know how to access it and add it to the request headers (since the URLRequest is static now, instead of the mutable on as in Alamofire 3 had)

Can anyone point me into a right direction?
I have also tried using the `authenticate` method directly, but to no avail:

``` swift
class func Authenticate(router: Router, username: String, password: String) -> Observable<Any> {
        return Observable.create({ observer in
            let request = Alamofire.request(router)
                .authenticate(user: username, password: password, persistence: URLCredential.Persistence.forSession)
                .responseJSON(completionHandler: {
                    response in

                    switch response.result {
                    case .success(let value):
                        if Router.debugNetworking {
                            print("printing json directly from response: \(value)")
                        }
                        observer.on(.next(value))
                        observer.on(.completed)

                    case .failure(let error):
                        print("Error: \(error)")
                        observer.on(.error(NetworkError.ServerConnectionProblems(message: error.localizedDescription)))
                    }

                })
            request.resume()
            return Disposables.create {
                request.cancel()
            }
        })
    }
```

So I either need to attach this exact key-value pair to the request header:

``` swift
open static func authorizationHeader(user: String, password: String) -> (key: String, value: String)? {
        guard let data = "\(user):\(password)".data(using: .utf8) else { return nil }

        let credential = data.base64EncodedString(options: [])

        return (key: "Authorization", value: "Basic \(credential)")
    }
```

or the `authenticate` method working as expected

**Comment by jshier** [comment]
The `.authenticate()` function is proper way to add basic auth credentials, but you can take a look at our [AuthenticationTests](https://github.com/Alamofire/Alamofire/blob/master/Tests/AuthenticationTests.swift) file to see how we test this functionality. First, though, I would check and make sure your requests are being made as you expect and the server is seeing the credentials. 

If you find an issue with Alamofire, feel free to open a new issue, otherwise these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) with tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by danipralea** [comment]
I actually tested and can tell for sure that `.athenticate()` is not working. I had to add custom header for it to work

**Comment by jshier** [comment]
Were you able to see any request logs to see if the `.authenticate()` method was adding the basic auth correctly? I don't think there's anything for Alamofire to do here, as our authentication support goes through the system libraries, but it would be interesting to know what the exact issue was just in case.

**Comment by jshier** [comment]
@danipralea Anything more to add? We'd like to narrow down why this wasn't working, but all of our tests pass. Perhaps your server didn't accept typical basic-auth? I've manually verified Alamofire works correctly, both in our tests and against [HTTPBin's basic-auth endpoint](https://httpbin.org/basic-auth/username/password).

**Comment by danipralea** [comment]
I can confirm my server allows basic-auth. Tested with Postman and Paw as well.

I can do additional tests if you need me to, just tell me which ones, cause I already switched my implementation

**Comment by jshier** [comment]
@danipralea I'm mostly interested in what the request difference was that made your requests not work. That is, what was different between the requests returned by `.authenticate()` and you manual header addition.

**Comment by cnoon** [comment]
Hi @danipralea,

Have a look at this [authentication test](https://github.com/Alamofire/Alamofire/blob/master/Tests/AuthenticationTests.swift#L112-L141). It demonstrates how to use the `authorizationHeader` API when creating a `Request`.

Cheers. 🍻

**Comment by danipralea** [comment]
thanks. I already did it that way 😄
