### ISSUE TITLE
Working in simulator but not on device

### ISSUE THREAD

**Issue by travisday** [Alamofire/Alamofire#1697]
I am having trouble finding where this problem lies. I am using Alamofire to get a JSON array and then I iterate through each item and append it to my swift array which then displays it on a UITable.

```swift
Alamofire.request("http://104.131.134.48:8090/all", method: .get).responseJSON { response in
            if let JSON = response.result.value {
                for title in JSON as! [AnyObject]{
                    self.shows.append(Show(name: title as! String, description: "Is the best", image: #imageLiteral(resourceName: "blowgun")))
                }
                print("JSON: \(JSON)")
                print("Shows: \(self.shows)")
            }
```
It works fine and populates the Table on the simulator but it does not when I test on a real device. My server still says it sent the JSON but I cannot find out why it will not work on the real device.

**Comment by skyline75489** [comment]
Have you seen any error message?

**Comment by jshier** [comment]
@travisday If you find any underlying Alamofire issue here, feel free to open another issue. Otherwise, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
