### ISSUE TITLE
RequestRetrier endless loop?

### ISSUE THREAD

**Issue by marcusleon** [Alamofire/Alamofire#1699]
Is there a risk that when using `RequestRetrier` that you end up in an endless loop? 

... Where the `should(...)` implementation indicates the response be retried and the retry then fails with the same error as the original....  resulting in an endless fail/retry loop.  Do we need to code for this scenario or does the framework cover this?

If you're updating your session/token via REST in `should(...)` then I assume you have to ensure you're not using the same retrier so you don't get in an endless loop?   But wasn't sure about the actual request retry.

**Comment by Daltron** [comment]
I am also curious about this. I think it would be great if there was some kind of built in mechanism that allows you to set the number of retries to perform on a particular request before giving up.

**Comment by jshier** [comment]
@marcusleon @Daltron Support for retry counts was added to `master` recently but has not yet been released officially. Once #1682 has been finalized and merged, we'll do another release. Otherwise yes, you'll need to ensure the retries stop yourself, even after we add the retry count to the framework. I'm closing this for now, but @cnoon, anything to add, give you wrote this feature?
