### ISSUE TITLE
Swift 3.0.1: /Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any

### ISSUE THREAD

**Issue by racer1988** [Alamofire/Alamofire#1745]
Building the framework with Carthage on Swift 3.0.1 produces following warnings:

/Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any

**Comment by Erulezz** [comment]
Fixed in https://github.com/Alamofire/Alamofire/pull/1735 .

**Comment by DanBurkhardt** [comment]
Ok, I may just be a real noob but I have tried compiling via carthage with version 4.0.1 and I still get this warning. My project will not compile as a result. If this is fixed, which version do we need to target when building with Carthage in order to use it? I guess I am asking: what should my cartfile entry look like for this to pull down properly. 

Thanks!

**Comment by racer1988** [comment]
Just put 

    github "Alamofire/Alamofire"

it will take the last version.

and check what version of Swift you are using!
mine is:

    swift --version

    Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
    Target: x86_64-apple-macosx10.9

**Comment by racer1988** [comment]
But @Erulezz  and @DanBurkhardt 

The PR is not merged yet, so the warning is still there, we need to wait for #1735

**Comment by cnoon** [comment]
I'm going to close this issue out since #1735 has been merged. The 4.1.0 release will be released shortly. Thanks for everyone's patience here.

Cheers. 🍻
