### ISSUE TITLE
troubles with making requests after migrating from version 3 to 4

### ISSUE THREAD

**Issue by klado** [Alamofire/Alamofire#1762]
Hi! After migrating and converting my code to swift 3 I have this troubles:
`Alamofire.request(url, method: .get, parameters: data, encoding: .URL, headers: headers).responseJSON...` shows error "Extra argument 'method' in call".

aslo trouble with multipart upload:

`Alamofire.upload(
            multipartFormData: { mfdata in
              // ... code ...
            },
            treshhold: SessionManager.multipartFormDataEncodingMemoryThreshold,
            to: baseURL + url,
            method: .post,
            headers: headers
        )` { encoding result in
          // ... code ...
         }

shows "Ambigious reference to member 'upload(_:to:method:headers:)'"

**Comment by jshier** [comment]
These types of compiler errors are usually caused by type issues, so double check the types of all of your parameters.

However, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
