### ISSUE TITLE
Xcode 8.2 will be the last release to support SWIFT 2.3, are we obliged to migrate to Alamofire 4?

### ISSUE THREAD

**Issue by DrAma999** [Alamofire/Alamofire#1764]
I know that this has already been discussed, but I guess that the decision of Apple to drop SWIFT 2.3 support in xcode releases after 8.2 could open different scenarios.
I've already read the reason around making Alamofire 4 available only from iOS9 and I agree, but after this Apple decision this means that for further apps release we are obliged to migrate to Alamofire 4 and drop iOS8 support.

This is quite a big issue (most of clients still request for iOS8 support), I'd like to know if there are plans to migrate Alamofire 3 to SWIFT 3.

Thank you,
Andrea

**Comment by MrLoveQD** [comment]
+ 1 like for you.
The same to you :-(
Please!

**Comment by cnoon** [comment]
Hi @DrAma999,

First off, there's no way we will be porting Alamofire 3.x to Swift 3. That wouldn't make sense for us to do and would be a huge amount of work. Instead, we've decided that we're going to add support for iOS 8 and macOS 10.10 in Alamofire 4 since Apple is going to deprecate Swift 2.3 sooner than we thought. Please see #1774 for more info.

I'm going to close this issue out. Please redirect all further comments to #1774.

Cheers. 🍻

**Comment by DrAma999** [comment]
@cnoon awesome. Thank you!
