### ISSUE TITLE
Error Object deserialization with ObjectMapper

### ISSUE THREAD

**Issue by multiholle** [Alamofire/Alamofire#1767]
We are updating to Swift 3 and therefore to the latest Alamofire version. Unfortunately the signature of the Result enum changed.

```
-public enum Result<Value, Error: Swift.Error> {
+public enum Result<Value> {
```
https://github.com/Alamofire/Alamofire/commit/7b419b76a48b7c6e6b676ccc5d66e64cb00c93c2#diff-7a1ba79e4a1bfd6430ca2070dcbc3ea0

We were using the generic error type to implement our custom response serializer. Our rest api delivers json objects in case of an error. We would like to map the error response using ObjectMapper.

Is there a way to implement this feature using the current Alamofire API?

```swift
public enum ErrorInfoJson<T: Mappable>: ErrorType {
    case Canceled
    case Network(ErrorInfoMessage)
    case UnexpectedStatusCode(Int, T?)
    case ParseError
}
```

```swift
public func responseObjectErrorInfoJson<T: Mappable, E: Mappable>(completionHandler: Response<T, ErrorInfoJson<E>> -> Void) -> Self {
    return response(queue: nil, responseSerializer: Request.ObjectErrorInfoJsonResponseSerializer(), completionHandler: completionHandler)
}
```

```swift
public static func ObjectErrorInfoJsonResponseSerializer<T: Mappable, E: Mappable>() -> ResponseSerializer<T, ErrorInfoJson<E>> {
    return ResponseSerializer { request, response, data, error in
        guard error == nil else {
            return parseErrorInfoJson(request, response: response, data: data, error: error!)
        }
        
        if let parsedObject: T = parseJson(request, response: response, data: data, error: error) {
            return .Success(parsedObject)
        }
        
        return .Failure(.ParseError)
    }
}
```

```swift
private static func parseErrorInfoJson<T, E: Mappable>(request: NSURLRequest?, response: NSHTTPURLResponse?, data: NSData?, error: NSError) -> Result<T, ErrorInfoJson<E>> {
    if error.code == NSURLErrorCancelled {
        return .Failure(.Canceled)
    }
    
    guard let statusCode = response?.statusCode else {
        return .Failure(.Network(ErrorInfoMessage(error: error)))
    }
    
    // error = nil, da der Response nur im Erfolgsfall deserialisiert wird
    let parsedObject: E? = parseJson(request, response: response, data: data, error: nil)
    return .Failure(.UnexpectedStatusCode(statusCode, parsedObject))
}
```

**Comment by jshier** [comment]
The generic error parameter was removed from the `Result` definition because all underlying errors from the Apple frameworks and Alamofire itself are captured as the `Error` type (a change required by Swift 3). So you can still use your custom error type just fine, you just have to extract it by casting to the appropriate type when you want to interact with it. I'm guessing with the appropriate generics it will still work.

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
