### ISSUE TITLE
having trouble trying to add in support for AVAssetDownloadTask

### ISSUE THREAD

**Issue by skydivedan** [Alamofire/Alamofire#1816]
I'm working on a project that can download AVAssets, using `AVAssetDownloadTask` -- which is part of AVFoundation. Since I'm using Alamofire, I thought it might be good to try and extend Alamofire to support this new kind of URLSessionTask (around since iOS 9). So, I forked the repo, and put my additions over here: https://github.com/skydivedan/Alamofire

I created a unit test for it, `AVAssetDownloadsTest`, and it fails before it creates the AVAssetDownloadTask. For this kind of task to be created, I need to create an `AVAssetDownloadURLSession` (subclass of `URLSession`) and a `AVAssetDownloadDelegate` (subclass of `URLSessionTaskDelegate`), which I do. 

The problem comes up in my `AVAssetDownloadRequest`. In the `task` method (for the TaskConvertible) I check to see if the `URLSession` is an `AVAssetDownloadURLSession`, if not it bails. It looks like it is not, but I can't explain why, since I have code that definitely created it as such.

I'd appreciate any advice on what I'm missing here.

**Comment by jshier** [comment]
Thanks for the work here, this is really interesting. We'll take a look and see how we'd like to integrate this sort of task.

**Comment by cnoon** [comment]
Hi @skydivedan,

Given that the `AVAssetDownloadURLSession` must be initialized with a background configuration, I'd recommend steering clear of Alamofire for this logic right now. The current design of Alamofire makes it quite difficult to work with background sessions in any useful way if your app is being backgrounded and will be woken up when the app has been terminated in the background. There's no way to rewire up the closures you attached previously.

As to your more specific implementation issue, none of your tests will work because background sessions do not work in test suites as of Xcode 8.2.1. We've had to disable all our background session tests in Alamofire because of this bug. This has been the case with all the Xcode 8.x releases which our team pointed out to the Apple engineers at WWDC but it still has not been resolved.

I pulled down your project and ran the test and I see the same issue you're running into. I can't really explain why that `as?` check doesn't work. What I'd try at this point is to create a sample app that runs essentially the same test since the background session stuff doesn't work in test targets. I would guess that you'll have more luck there.

I've added a task to our Trello backlog to investigate this more for AF5. This is something that I think could be useful in Alamofire core, but we need to come up with a better design and strategy for background sessions in general before adding support here.

I'm going to close this issue out for now, but if you would be so kind as to post your findings back here if you make any headway I'd greatly appreciate it. Then we may be able to use some of your findings if we decide to implement this directly into Alamofire in the future.

Cheers. 🍻
