### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by jaymutzafi** [Alamofire/Alamofire#1817]
Hi,

Getting an "Module compiled with Swift 2.3 cannot be imported in Swift 3.0.1" error when importing Alamofire. 

I have 4.2 installed via Carthage and working in xcode 8.1, swift 3, brand new project. 

What am I missing?
Thanks

**Comment by jshier** [comment]
You can't use frameworks using Swift 2.3 and 3.0 in the same project. Make sure your project is set to use Swift 3.

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
