### ISSUE TITLE
`.download` image and `responseData` doesn't work

### ISSUE THREAD

**Issue by ded** [Alamofire/Alamofire#1818]
I copied this verbatim from the main README and it doesn't work (using the following jpeg in the example).

```swift
Alamofire.download("https://static.preapp.co/medias/2016/11/10/3194-a7d7afbf22.jpg")
    .downloadProgress { progress in
        print("Download Progress: \(progress.fractionCompleted)")
    }
    .responseData { response in
        // response.result.value  is ALWAYS nil
        if let data = response.result.value {
            let image = UIImage(data: data)
        }
    }
```

**Comment by ded** [comment]
Didn't provide this information earlier. 
I'm on Swift 3.0, using Xcode 8.1. Alamofire 4.2.0 (cocoapods)

**Comment by Faisal-AlNeela** [comment]
I had the same problem
did you found a solution???

**Comment by cnoon** [comment]
You need to specify the `destination` closure. Otherwise the file isn't moved out of the temp directory and you don't have access to the data outside of your sandbox after the `SessionDelegate` API is called. See our [README](https://github.com/Alamofire/Alamofire#download-file-destination) for more info.

I just pushed up ffaa0718 which updates the README to hopefully make this more clear.

Cheers. 🍻
