### ISSUE TITLE
eTag support

### ISSUE THREAD

**Issue by thierrybucco** [Alamofire/Alamofire#1826]
Hi,

I am unable to find how to enable eTag support on Alamofire.
Do you have any documentation I can read?

Thanks a lot.

**Comment by jshier** [comment]
`eTag` is part of the underlying `URLSession` APIs used by Alamofire and we don't expose any high level APIs to interact with them directly. If you need direct control, I suggest you look into how they're normally exposed to the `URLSession` APIs and how they work in general. Supporting them should really be automatic or as simple as attaching a header like any other. Feel free to open a new issue if you run into issues that may be Alamofire bugs, otherwise general support from something like StackOverflow will probably answer the questions you have.
