### ISSUE TITLE
v4.2.0 Swift 3+ Issue with header setup

### ISSUE THREAD

**Issue by krunalbhavsar** [Alamofire/Alamofire#1859]
#Error 1:
Static member 'defaultHTTPHeaders' cannot be used on instance of type 'SessionManager'
var defaultHeader = Alamofire.SessionManager.default.defaultHTTPHeaders

#Error 2: extra param 'method' in call
Alamofire.request(URLConvertible, method: HTTPMethod, parameters: Parameters?, encoding: ParameterEncoding, headers: HTTPHeaders?)

**Comment by jshier** [comment]
As you can see [in the source](https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L56), `defaultHTTPHeaders` is a `static` method, not an instance one.

Your error is usually due to some type mismatch that the Swift compiler can't give a good diagnostic about.

In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com).

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by krunalbhavsar** [comment]
Update on #Error 1:
This is a statement/line, i copied from main page of Alamofire source, as a part of header customization. But when i build the same statment in my project, it's showing me an error Static member 'defaultHTTPHeaders' cannot be used on instance of type 'SessionManager'.
var defaultHeader = Alamofire.SessionManager.default.defaultHTTPHeaders
Pl. look at these statements, available on source code page.
-----------
Modifying the Session Configuration

var defaultHeaders = Alamofire.SessionManager.default.defaultHTTPHeaders
defaultHeaders["DNT"] = "1 (Do Not Track Enabled)"

let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = defaultHeaders

let sessionManager = Alamofire.SessionManager(configuration: configuration)

---------------------------------------------------


Update on #Error 2:
It's not a Stackoverflow question. It's an Alamofire source bug. When you start writing "Alamofire.request("

it will show/allow you to add these many params, "String URL Convertible", method: <Alamofire.HTTPUrlMethod>, parameters: parameters, encoding:URLEncoding.default, headers: header

But when you compelete this line and build, it shows an error like extra parameter in arguments/call.

**Comment by krunalbhavsar** [comment]
![screen shot 2016-12-19 at 9 48 25 am](https://cloud.githubusercontent.com/assets/16011224/21301103/64e2f8be-c5d0-11e6-9ca8-0dd5ec69e720.png)

**Comment by krunalbhavsar** [comment]
Please look at this snapshot, it may give you an exact idea about what's my query.
