### ISSUE TITLE
Getting data but result is failure

### ISSUE THREAD

**Issue by jeffayan** [Alamofire/Alamofire#1897]
FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))
  ▿ failure : AFError
    ▿ responseSerializationFailed : ResponseSerializationFailureReason

**Comment by ayunav** [comment]
Same here! 😓

**Comment by jshier** [comment]
Error 3840 is `JSONSerialization`'s way of telling you that it didn't receive valid JSON. Most commonly this is caused by the server returning an HTML error page of some kind.

Also, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
