### ISSUE TITLE
Exception by JSON encoding

### ISSUE THREAD

**Issue by appmagnetics** [Alamofire/Alamofire#1900]
Hi, I'm stuck in the following situation: 1) create dictionary data 

                let subparams:[String:Any?]  = [
                    "estimate_service_id": NSNumber(value: timesheet.serviceID),
                    "work_date":timesheet.workDate as AnyObject,
                    "duration":NSNumber(value: Int(timesheet.workDuration)),
                    "description":timesheet.workDescription as AnyObject,
                    "staff_id":FPUserController.sharedInstance.getStaffId() as AnyObject,
                    "docket_id":NSNumber(value: timesheet.jobID),
                    "task_id": nil
                    ]
                let array = [subparams]
                params = [ "timesheets": array]

Resulting in following data (by debugPrint()):

`Optional(["timesheets": [["estimate_service_id": Optional(1932), "task_id": Optional(1578), "staff_id": Optional(842), "description": Optional(), "work_date": Optional(2017-01-09), "docket_id": Optional(81), "duration": Optional(1800)]]])`

And when the data is given to 

`Alamofire.JSONEncoding.default.encode(mutableURLRequest, with: params)`

Then I get the exception at 

ParameterEncoding.swift:  let data = try JSONSerialization.data(withJSONObject: parameters, options: options)

To me the data looks valid. What are possible steps to figure out what is wrong?

References: 

Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON', '~> 3.0’

**Comment by appmagnetics** [comment]
I can confirm that issue does not appear starting from Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1). I think you should close this issue.

**Comment by cnoon** [comment]
Hi @appmagnetics,

Most likely the issue is due to you converting your data types over to Objective-C, then trying to implicitly covert them to `Any`. Instead, get rid of your `NSNumber` and `as AnyObject` casts and things will probably start working.

If that doesn't fix things up, then I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
