### ISSUE TITLE
Background upload in share extension exits prematurely

### ISSUE THREAD

**Issue by nickvelloff** [Alamofire/Alamofire#1915]
Alamofire (4.2.0)

Does `SessionManager` have to stay allocated after initiating a background upload? I hope not, because if so it can't be used in an extension context AFAIK. 

Interestingly, `self.session?.uploadTask(with: req, fromFile: sharedContainerFileUrl)` does work, and upload completed. 

If I never exit the extension, the file uploads to S3 successfully. Obviously not exiting the extension until an image upload completes is an anti-pattern, so I can't really do that. 

If you are certain this is not an issue with Alamofire, I'm happy to move it to stack overflow. 

``` Swift
//  var session: URLSession?
//  var uploadTask: URLSessionUploadTask?
  var manager: SessionManager?

  fileprivate func shareSignalProducer(forImageUrl url: URL, publish: Bool, site: Site, note: String) -> SignalProducer<Void, NSError> {

    let configuration = URLSessionConfiguration.background(withIdentifier: "group.io.thegrid.take.er.easy")
    configuration.sharedContainerIdentifier = "group.io.thegrid"
    self.manager = SessionManager(configuration: configuration)

    return SignalProducer<Void, NSError> { observer, _ in

      guard var sharedContainerFileUrl = self.sharedBaseDirectory else {
        observer.send(error: GridError.sharedContainerAccessError.nsError)
        return
      }
      sharedContainerFileUrl.appendPathComponent(UUID().uuidString)
      sharedContainerFileUrl.appendPathExtension(url.pathExtension)

      guard let data = try? Data(contentsOf: url, options: Data.ReadingOptions.mappedIfSafe) else {
        observer.send(error: GridError.readFromDiskError.nsError)
        return
      }

      guard let _ = try? data.write(to: sharedContainerFileUrl, options: Data.WritingOptions.atomic) else {
        observer.send(error: GridError.writeToDiskError.nsError)
        return
      }

      self.http.getSignedUploadURL(objectName: "image", contentType: url.mimeType())
        .subscribe(onNext: { signedURL in


          self.manager?.upload(sharedContainerFileUrl, to: signedURL.signedUrl, method: .put, headers: ["Content-Type": url.mimeType()])

          /* This does initiate and complete the upload in the backgoround
          self.session = URLSession(configuration: configuration)

          guard let presignedURL = URL(string: signedURL.signedUrl) else { fatalError("SignedUploadURL.signedUrl invalid value") }

          var req = URLRequest(url: presignedURL)
          req.httpMethod = "PUT"
          req.setValue(url.mimeType(), forHTTPHeaderField: "Content-Type")

          self.uploadTask = self.session?.uploadTask(with: req, fromFile: sharedContainerFileUrl)
          self.uploadTask?.resume()
          */

        }, onError: { error in
          observer.send(error: GridError.error(description: error.localizedDescription).nsError)
        }, onCompleted: {
          observer.send(value: ())
          observer.sendCompleted()
        })
        .addDisposableTo(disposeBag)
    }
  }
```

**Comment by nickvelloff** [comment]
Another note:
As a test I added a progress handler,  and did not exit the extension until it was triggered with > 0 percentage complete. Same result, just terminated the upload.

**Comment by 0xc00010ff** [comment]
Seeing the same result in a share extension.

```
let sessionConfig = URLSessionConfiguration.background(withIdentifier: "com.my.app.Background")
sessionConfig.sharedContainerIdentifier = "group.com.my.app"
let manager = Alamofire.SessionManager(configuration: sessionConfig)
manager.startRequestsImmediately = true
_ = manager.request(DataRouter.create(data))
```
(where the `DataRouter` enum implements URLRequestConvertible, and `data` is a simple object that supplies request params. Works consistently in the main app.)

does not fire a request to my server unless I manually breakpoint before dismissing the share extension and wait for the request to complete. 

Commenting this out and replacing it with a simple 
```
let session = URLSession(configuration: sessionConfig)
session.dataTask(with: request).resume()
```
yields the expected result of sending the request once the share extension is dismissed. 


Any ideas?

**Comment by nickvelloff** [comment]
That is exactly the result I had. The moment the extension dismisses, the upload terminates.

**Comment by jshier** [comment]
Thanks for the report, we'll look into this.

**Comment by jshier** [comment]
This may or may not be related to #1851.

**Comment by jshier** [comment]
@nickvelloff @0xc00010ff I was able to create a project which uploaded images from disk from a share extension. Initially, when declaring the `SessionManager` locally, I was getting the uploads cancelled as well. However, moving my `SessionManger` into a singleton so that the reference stays alive allowed my uploads to complete. Now, I don't know how long the share extension process stays alive after posting, but it was offscreen for a few seconds before the upload finished without completely killing the share process. 
```swift
struct BackgroundCommunicator {
    
    static let shared = Communicator()
    
    let manager: SessionManager = {
        let configuration = URLSessionConfiguration.background(withIdentifier: "com.jonshier.AlamofireTest.ShareUpload")
        configuration.sharedContainerIdentifier = "group.com.jonshier.AlamofireTest"
        
        return SessionManager(configuration: configuration)
    }()
    
}
```
But in general, yes, a `SessionManager` needs to live as long as its transfers do, if only because, when it's `deinit`d it cancels its outstanding tasks. This is, perhaps, technically incompatible with background sessions, but it should suffice for any scenario where the containing process lives long enough.

I'll keep this issue open for now to see if this solution works for you.

**Comment by cnoon** [comment]
I agree here with @jshier's assessment. The only thing I'd like to add is that I'm not sure if you're extension will be relaunched in the background once the transfer completes after it has been terminated by the OS. I would assume it would, but I'm not positive. You'd have to test this on a device to know for sure with an upload that was big enough to make sure the extension was actually shut down.

Another approach here would be to have the client application make the request on your extension's behalf if you can't get the background sessions working correctly with the extension. Background sessions certainly work correctly in the app, but may have different behavior in the extensions. Just something else to consider.

I'm going to close this issue out for now since there's nothing actionable here for the AF team. Feel free to continue to comment on this issue and we'll happily re-open if anyone finds anything that needs further investigation.

Cheers. 🍻

**Comment by nickvelloff** [comment]
@cnoon @jshier - Here is the rub... If you create a singleton and the extension does not terminate properly, or the singleton is leaked, there is a good chance you won't be able to laugh that extension again until the system cleans it up. 
Extension contexts/lifecycles are ephemeral, and there is a good chance the use case is to be able to launch the share or otherwise multiple times.

The flow for a share in my application _does_ require the main application to process follow up requests, so in that sense it _could_ all be deferred and managed by the main app. 

All that said, I stuck with `uploadTask` as it does exit the extension cleanly, and perform the upload successfully. I really don't think the issue is likely resolved from a root cause standpoint, but there are workarounds for sure.

Thanks guys for the discussion.

**Comment by jshier** [comment]
@nickvelloff Do you have any documentation you can point us to regarding the lifetimes and environment of extensions? I'm not sure what you're talking about here. Using a singleton (or any long lived instance) just ensures that the `SessionManager` doesn't cancel the requests until much later. It's still `deinit`d when the extension is exited. But yes, Alamofire would need some fundamental behavioral changes for background sessions to support this sort of use properly. Not the least of which is not cancelling background tasks when the `SessionManager` is `deinit`'d. We'll take a look at this more in the future.

**Comment by 0xc00010ff** [comment]
Hey guys I meant to follow up on this- I ended up finding the same results. Making the session manager static ensures it lives until the (upload) tasks are complete. Thanks for your time and assessments @jshier.

@cnoon and @nickvelloff also have good points for taking care of more complex or chained uploads in a `URLSessionTaskDelegate`.
