### ISSUE TITLE
Alamofire memory leaks?

### ISSUE THREAD

**Issue by juicyfru1t** [Alamofire/Alamofire#1934]
I am not sure this is the place and the way to ask a question, but I am out of options. Long story short - memory leaks are caused by `static Request.serializeResponceJSON` inside Alamofire. My problem is fully described in this [stackoverflow thread](http://stackoverflow.com/questions/41594282/alamofire-memory-leaks-instruments). I got a few up votes, so I suggest, it does not happen due to some obvious mistakes, made by me, so I really need some explanation. I've asked this in [SwiftyJSON repo](https://github.com/SwiftyJSON/SwiftyJSON/issues/780), they've suggested, that it is connected with Alamofire. You can find test project there.

**Comment by jshier** [comment]
Most likely this is a false positive or underlying Swift issue, but in the case that it isn't it appears to be triggered in your code, not Alamofire's. Alamofire only shows up in the call stack because the leaking code was called during response serialization. Perhaps letting Swift manage the intermediary array in your `initArrayFrom(data:)` method would help?
```swift
class func initArrayFrom(data: JSON) -> [ReservationSchedule] {
    return data.arrayValue.map(ReservationSchedulre.init(data:))
}
```
As an aside, the leak mentioned in the SwiftyJSON issue is different from the one your reported in your StackOverflow question, and is a false positive.
