### ISSUE TITLE
Documentation is mis guiding.

### ISSUE THREAD

**Issue by jsiddharth** [Alamofire/Alamofire#1979]
I am trying to call my HTTP post request with a JSON data object. I was told that I need to use upload method.

As I try to use the upload method.
Xcode auto complete shows
Alamofire.upload(<#T##data: Data##Data#>, to: <#T##URLConvertible#>)

When I try to

let fullURL = God.getFullURL(apiURL: self.apiUrl)
self.postData = try! JSONSerialization.data(withJSONObject: postData, options: JSONSerialization.WritingOptions.prettyPrinted)

Alamofire.upload(postData, fullURL).responseJSON { response in
self.responseData = response.result.value
}
I get an error

Cannot invoke 'upload' with an argument list of type '(Data, String)'
Check out
http://stackoverflow.com/questions/42113651/swift-3-0-alamofire-4-0-extra-argument-method-in-call/42122684#42122684

DONT CLOSE THE ISSUE WITHOUT RESOLVING AND RECOMMENDING CORRECTIONS. Your documentation is faulty. 

https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md

Look at your migration guide for .POST, you recommned using upload.

**Comment by reitzig** [comment]
I for one don't see the docs saying that you can pass `String` as URL; you need to call `asURL`, if available. The compiler message is quite clear.

Less anger and entitlement would help a long way, too.

**Comment by jshier** [comment]
Also, reading the code of the library itself can go a long way to filling in any misunderstanding or confusion you may have from the documentation. 

Like the compiler (and the documentation) says, using `upload(data, string)` isn't going to work, not least of which is because you need the `to` label for the destination. `upload(data, to: "https://httpbin.org/post")` works just fine.

For typical REST usage, `request` is what you need. Something like `request("https://httpbin.org/post, method: .post, parameters: parameters, encoding: JSONEncoding.default)` will work just fine. 

If you have actual examples of inaccurate documentation, feel free to open a new issue pointing it out specifically.

**Comment by jsiddharth** [comment]
Sorry to sound upset, my earlier question was closed with a very cryptic response. 

https://github.com/Alamofire/Alamofire/issues/1958

**Comment by reitzig** [comment]
@jshier FWIW, "reading the code of the library itself" is exactly what documentation should save us from. While I take your point -- other developers can sometimes be expected to look at the code before posting an issue, just to be more constructive about it -- it's not a good response to a (hypothetical) concern about the documentation.

That said, I find the documentation of Alamofire quite good.
