### ISSUE TITLE
Streaming MultiPartFormData

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#1980]
Looking at Alamofire for doing multi-part requests with potentially large data, I'm confused: why does it only support assembling everything in RAM or in a file?

Taking from `writeEncodedData(to:URL)`, I think something like this should do:

~~~swift
    /// Writes the appended body parts into the given output stream.
    ///
    /// This process is facilitated by reading and writing with input and output streams, respectively. Thus,
    /// this approach is very memory efficient and should be used for large body part data.
    ///
    /// - parameter stream: The stream to write the multipart form data into.
    ///
    /// - throws: An `AFError` if encoding encounters an error.
    public func writeEncodedData(to outputStream: OutputStream) throws {
        if let bodyPartError = bodyPartError {
            throw bodyPartError
        }

        self.bodyParts.first?.hasInitialBoundary = true
        self.bodyParts.last?.hasFinalBoundary = true

        for bodyPart in self.bodyParts {
            try write(bodyPart, to: outputStream)
        }
}
~~~

(Not compiled nor tested, so I post it in this form instead of a pull request for now.)

I would then bridge the `OutputStream` to a buffered `InputStream` and upload that one using one of the regular variants of `Alamofire.upload`.

Is there any fundamental issue with this that I'm overlooking?

**Comment by jshier** [comment]
@cnoon Perhaps you can answer this?

**Comment by cnoon** [comment]
Hi @reitzig,

Great question here as there is tons of complexity around streaming big chunks of data up to a server. 

To start off, how do you envision the `OutputStream.write` method to work if it doesn't write to RAM or to the file system? I don't see how that's possible offhand, but maybe I'm missing something obvious. To be able to convert all the body parts into an output stream, you actually have to write the data into the output stream which is either going to be loaded into memory (RAM in a buffer) or written out to disk.

Now as for directly streaming the data from multiple body parts from various locations (file, in-memory, input stream, etc.) one could create a subclassed `InputStream` that reads data on-the-fly from the `MultipartFormData` object. This is the approach that was used in AFNetworking. This approach is a very hacked together solution that barely works in AFNetworking. When we went to try to build a similar type of approach in Swift, `NSInputStream` couldn't even be subclassed as it through compiler errors. I believe that issue has since been resolved, but the complexity around the low level bridging required is something that we decided to avoid at the time and couldn't even implement if we wanted. After Mattt and I had a very long conversation about it, we both decided it was best to try to use an in-memory solution for small payloads and move to an on-disk solution for larger ones.

Now that I believe you can actually subclass `InputStream`, it should be possible to create a `MultipartFormDataStream` or something like that that subclasses `InputStream` and reads the data on-the-fly for each read. This is something that I haven't had time to investigate myself but would be awesome to have in Alamofire. I think it would probably be as simple as adding a `stream` or `inputStream` property to the `MultipartFormData` object that vended the custom subclassed stream with all the appropriate implementation. If you wanted to take this one I think it would be a really good addition. If not, then at least you have the history of why the feature is currently designed as it is.

Just let me know what you think here @reitzig. I'd be happy to help try and guide you through the implementation more in-depth if necessary, but I don't have time right now to build out the feature myself. I'm going to leave this issue open for a few days for you to get back to us with your thoughts and we'll decide from there.

Cheers. 🍻

**Comment by reitzig** [comment]
@cnoon Thanks for your elaborate response!

I thought that you'd rewire that `OutputStream` to an `InputStream` used for upload. But you are right, that's backwards; a better signature would be `func readEncodedData() throws -> InputStream` (name tbd). This could then be passed to `upload(InputStream)` or used by `upload(multipartFormData:)`.

I agree that it shouldn't be too hard to add this (isn't that what you always say before actually digging in? :'D). I'm tight on time right now, but I may look into it. Given that we may want this in our application, chances are I can develop it on company time even -- will have to check with the bosses, obviously.

**Comment by reitzig** [comment]
Quick draft. This is unnecessarily complicated by the fact that `InputStream` is not a protocol. \*sigh\*

```swift
public func readEncodedData() throws -> InputStream {
        if let bodyPartError = bodyPartError {
            throw bodyPartError
        }

        self.bodyParts.first?.hasInitialBoundary = true
        self.bodyParts.last?.hasFinalBoundary = true

        return MpfdStream(parts: self.bodyParts.map({ $0.bodyStream }))
    }

private class MpfdStream: InputStream {
    private var current: Int
    private var parts: [InputStream]

    init(parts: [InputStream]) {
        super.init(???) // Whatever do we do here?
        precondition(parts.count > 0)
        self.parts = parts
        self.current = 0
    }

    override func read(_ buffer: UnsafeMutablePointer<UInt8>, maxLength len: Int) -> Int {
        guard current >= 0 && current < self.parts.count else {
            return -1 // What is correct here?
        }

        var currentPart = self.parts[current]
        assert(currentPart.hasBytesAvailable) // otherwise we'd have moved the index on!

        let response = super.read(buffer, maxLength: len)

        if !currentPart.hasBytesAvailable {
            self.current += 1
        }

        return response
    }

    override var hasBytesAvailable: Bool {
        return current >= 0
                && current < self.parts.count
                && self.parts[self.current].hasBytesAvailable
    }

    // What else do we have to override?
}
```

Side note: what happens with the boundaries if I call `writeEncodedData` multiple times, but add parts in between? Looks like a potential bug to me. But then, all the streams will be consumed, anyway...

**Comment by cnoon** [comment]
Hi @reitzig,

I'm going to close this issue out for now. If you're still interested in reviving this effort, please feel free to open a PR.

Cheers. 🍻
