### ISSUE TITLE
lag on first request, not lag on following requests

### ISSUE THREAD

**Issue by LupoDiRoma** [Alamofire/Alamofire#1986]
I have posted this on StackOverflow but we can't figure it out. In a nutshell:
- I have a singleton class that implements all network calls using Alamofire and AlamofireImage with caching
- AlamofireImage with caching is working like a charm with call backs to UIImageViews upon data received
- Alamofire POST/GET responseJSON calls have a 20 seconds (estimated) lag before they fire. If I debug, the lag does not occurr. If I press pause during the lag time, the app seems to be sitting on the main thread waiting for?

Here is an example, this log in function calls a proprietary API using HTTP GET. The API responds within 50ms when called using curl and when called by this call if you hit the login button twice. So the issue seems to be the first "cold" call to a specific URL.

```
func login(email:String, password:String, controller:UIViewController)   {
    ... url and parameters are set up here...
let task = Alamofire.request(url, method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: nil).responseString
            { response in
                switch(response.result) {
                case .success(_):
                    if let json = response.result.value {
                        if let r = JSONDeserializer<Response<Session>>.deserializeFrom(json: json) {
                            if r.status == 200 {
                                switch r.content{
                                case let s as Session:
                                    self.session = s
                                    self.updateSession()
                                    NSLog("*** session %@ obtained", s.session_id)
                                default:
                                    NSLog("could not read the session payload!")
                                }
                            }
                            else {
                                // TODO do something about the error code
                                NSLog("session not obtained, error %d %@",r.status, r.error)
                            }
                        }
                    }
                case .failure(_):
                    NSLog("session not obtained, error %@",response.result.error as! String)
                }
                controller.reloadInputViews()
            }
        task.resume()
}
```

Here is my pod file
```
platform :ios, '10.0'

target "TeamMateiOS" do
  use_frameworks!
  pod "Koloda"
  pod 'FXKeychain'
  pod 'JSQMessagesViewController'
  pod 'ImagePicker'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Alamofire-Synchronous'
  pod 'HandyJSON' 
  pod 'SwiftKeychainWrapper'
  pod 'Fabric'
  pod 'Crashlytics'
end
```

**Comment by cnoon** [comment]
Hi @LupoDiRoma,

First off, thanks for filing an issue on Stack Overflow. Next time please post a link if you end up having to open the issue on our GitHub project.

Overall, there's nothing in Alamofire that is causing the delay you're seeing. We have 1000s of apps shipping with Alamofire that do not have this problem that fire many requests at app launch or foreground event. We've also seen this type of issue filed before, and it always ends up being something in the client implementation that is a bit off.

The only thing I can see in your code sample here that seems a bit odd is that you're calling `resume` on your `task` which is technically the `request` vended by the session manager. Did you purposefully set `startRequestsImmediately` to `false` on your session manager? If yes, then the `resume` call is necessary, if not, then you should remove it. I don't think this is part of your problem, but I noticed it and thought I'd point it out for you.

Other than that, I'd suggest you remove portions of your app to simplify the use case as much as possible, or create a separate test app that just calls your login functionality to isolate what the delay could be caused by. I know this is quite a bit of work, but it's sometimes necessary to figure out what the underlying issue actually is.

Best of luck! 🍻

**Comment by LupoDiRoma** [comment]
Thank you, indeed the problem is what I am passing as callback. I am using a reference to the UIViewController that initiated the call so that I can call reloadInputViews() and keep things agnostic. If I don't pass it, everything flies but the controller will never know the data is ready. I am open to suggestion, please and thank you.
