### ISSUE TITLE
Memory leak with an NSLock

### ISSUE THREAD

**Issue by xmollv** [Alamofire/Alamofire#2000]
Hi! I was checking if I had any memory leaks with Instruments and I found that Alamofire is leaking an NSLock. I don't know if it has already been reported, but on the latest release (**4.4.0**) is still present. I have found it using the **4.3.0** and I have updated the pod to check if it was already fixed. The app it's on it's early stages, this happens with just a single GET request.

**The version of Xcode you're using:** 8.2.1
**The version of iOS or macOS you're targeting:** iOS 10.2 (14C89)
**The full output of any stack trace or compiler error:**

![screen shot 2017-03-02 at 13 00 02](https://cloud.githubusercontent.com/assets/8229382/23506639/844a50be-ff49-11e6-917c-fe4867718a3c.png)
![screen shot 2017-03-02 at 13 00 58](https://cloud.githubusercontent.com/assets/8229382/23506644/877b4324-ff49-11e6-83ee-9fab3aeb14dc.png)

**Comment by jshier** [comment]
Yes, this is a known false positive. If the declaration of the `NSLock` is moved to the top of the `SessionManager` file, I've heard that "fixes" the leak. I also believe this false positive is fixed in Xcode 8.3 / Swift 3.1, which will hopefully be released soon. But you can take a look at that in the meantime.

**Comment by cnoon** [comment]
We've already filed a radar for this issue @xmollv and it was closed out as a duplicate.
