### ISSUE TITLE
How To Allow For Self-Signed SSL Certificates

### ISSUE THREAD

**Issue by camcoding** [Alamofire/Alamofire#2013]
I have an RxSwift IOS app (Alamofire 4.2.0, Moya 8.0.1) which must connect to multiple home automation controllers - each having their own self-signed certificate (and no there's no way to enforce that my IOS app users install a trusted SSL cert).  According to the ATS documentation my configuration is correct so it's not an ATS issue.  I filed an issue with Moya and attempted several suggestions (e.g. ServerTrustManager) without any luck.

Here's the error message I get from Moya:

> underlying(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9806, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x61800005b3c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9806, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9806}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by LvJianfeng** [comment]
@camcoding  你好，请问这个问题解决了吗？

**Comment by jshier** [comment]
Looks like you got it fixed in the Moya issue. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
