### ISSUE TITLE
 found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Walker2020** [Alamofire/Alamofire#2028]
// MARK: - Convenience

func URLRequest(
    method: Method,
    _ URLString: URLStringConvertible,
    headers: [String: String]? = nil)
    -> NSMutableURLRequest
{
    let mutableURLRequest: _NSMutableURLRequest_

    if let request = URLString as? NSMutableURLRequest {
        mutableURLRequest = request
    } else if let request = URLString as? NSURLRequest {
        mutableURLRequest = request.URLRequest
    } else {
        **mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)**
    }
__

**Comment by Walker2020** [comment]
"https://test.com/sources/common_7eceaf80.zip\n\n\t\t\t\t"

**Comment by jshier** [comment]
Update to Alamofire 4 and these APIs are much safer. Otherwise ensure your URL is properly encoded before attempting to request it.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
