### ISSUE TITLE
Pagination in Alamofire

### ISSUE THREAD

**Issue by firecast** [Alamofire/Alamofire#2039]
I'm building a wrapper around my API where pagination happens on a request by just changing the `page=<page_number>` on the URL parameters. Ideally the wrapper should paginate somewhat like this 

```
let sessionManager = SessionManager()
sessionManager.adapter = someAdapter

let searchRequest = sessionManager.request(SomeRouter.search(query))
searchRequest.responseCollection(){ // do something here }

// When the user wants the next page results he can just do
searchRequest = searchRequest.next()
searchRequest.responseCollection(){ // do something here }
```

I've tried subclassing DataRequest but the initialiser has internal enum references. Modification of the URLRequest object is also not possible as it is a get only property. This is what I could come up with (somewhat a hackish solution)
```
enum PaginationError: Error {
    case notSupported
}

internal extension URL {
    internal func paramValue(forParam param: String) -> String? {
        guard let urlComponents = URLComponents(url: self, resolvingAgainstBaseURL: false) else { return nil }
        
        return urlComponents.queryItems?.first(where: { $0.name == param })?.value
    }
}

public extension Alamofire.DataRequest {
    public func nextPage(sessionManager: SessionManager) throws -> Alamofire.DataRequest {
        guard let request = self.request,
            let url = request.url,
                let currentPageString = url.paramValue(forParam: "page"),
                    let currentPage = Int(currentPageString) else {
            throw PaginationError.notSupported
        }
        
        let nextPage = currentPage + 1
        let nextPageURL = URL(string: url.absoluteString.replacingOccurrences(of: "page=\(currentPage)", with: "page=\(nextPage)"))!
        
        var newRequest = request
        newRequest.url = nextPageURL
        
        return sessionManager.request(nextPageURL, method: HTTPMethod(rawValue: request.httpMethod!)!)
        
    }
}
```
And calling the next function requires the sessionManager to be passed in which looks a bit ugly.

Is there some other way which is more elegant? I would have been a piece of cake if the Request object had a reference to the URLRequestConvertible and someway to update the URLRequest object in Request.

**Comment by jshier** [comment]
Rather than doing this strictly at the `Request` (or subclasses level), I'd do it at the `URLRequest` level. That, combined with a router (perhaps a `pagedResults` route), should be able to give you the sequence of `URLRequests) needed to get all of the pages. Making them sequentially using the standard Alamofire APIs should be pretty straightforward after that.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
