### ISSUE TITLE
Module doesn't work with Xcode 8.3 and Swift 3.1

### ISSUE THREAD

**Issue by Silvering** [Alamofire/Alamofire#2050]
Alamofire seems to doesn't work with the last version of Xcode.
I get this error message : Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1
Help ;-)

**Comment by benliong** [comment]
This likely duplicates Issue 1753 https://github.com/Alamofire/Alamofire/issues/1753

**Comment by Silvering** [comment]
Removing the DerivedData folder didn't solved my issue... Any idea ? Thanks!

**Comment by jshier** [comment]
@Silvering You'll need to rebuild all of your dependencies and your app with the latest version of Xcode so that all of the built frameworks are using the same version. How to do so depends on how you integrate Alamofire.

In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
