### ISSUE TITLE
Differentiate successful authentication and REST operation timeout error using handlers

### ISSUE THREAD

**Issue by bratislav** [Alamofire/Alamofire#2061]
Hi all,

We are exchanging JSONs between our iOS app and the Exchange web service using an NTLM protocol and one of my client has a very interesting scenario. Here's the problem : 

One of the HTTP POST operations takes just too long to complete and the timeout, which is set on the client to be 45sec, simply exceeds. As a result, the .failure handler triggers and we present "System is not available at the moment" message. This is ok, but is only partly true, because the system IS de-facto available, it's only not available for that specific POST operation, during that timeframe - hence the message. Our message really confuses them! 

The question is how can we differentiate this specific situation from the other calls which will complete successfully during the given period? I.e. how can we detect when the authentication to the NTLM web service succeeds but the afterwards operation fails because of the timeout? What handlers/validation combo can we use and in what way? I guess simply rising the timeout (or completely turning it off) wouldn't be appropriate because we DO need to detect if the system is REALLY unavailable (i.e. all operations).

Please help! If you have any ideas, or even Swift examples, that would be much appreciated.

Thanks,
Bratislav

**Comment by jshier** [comment]
Using the Router pattern from our documentation it's trivially easy to set timeout values on a per-request basis. This should allow you to set a reasonable timeout for a given request while keeping all others at the 45s default. Otherwise you can check the particular error returned to see whether its a timeout or a response error. 

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
