### ISSUE TITLE
GET请求有中文参数时报错：FAILURE: invalidURL("http://api.test.com/v1/posts?tags=獨立樂隊")

### ISSUE THREAD

**Issue by HuangWei201703** [Alamofire/Alamofire#2103]
[Response]: nil
[Data]: 0 bytes
[Result]: FAILURE: invalidURL("http://api.test.com/v1/posts?tags=獨立樂隊")
[Timeline]: Timeline: { "Request Start Time": 516165521.179, "Initial Response Time": 516165521.179, "Request Completed Time": 516165521.179, "Serialization Completed Time": 516165521.179, "Latency": -0.000 secs, "Request Duration": -0.000 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.000 secs }
  - request : nil
  - response : nil
  ▿ data : Optional<Data>
    ▿ some : 0 bytes
      - count : 0
      ▿ pointer : 0x7a62a960
        - pointerValue : 2053286240
      - bytes : 0 elements
  ▿ result : FAILURE: invalidURL("http://api.test.com/v1/posts?tags=獨立樂隊")
    ▿ failure : AFError
      - invalidURL : "http://api.test.com/v1/posts?tags=獨立樂隊"
  ▿ timeline : Timeline: { "Request Start Time": 516165521.179, "Initial Response Time": 516165521.179, "Request Completed Time": 516165521.179, "Serialization Completed Time": 516165521.179, "Latency": -0.000 secs, "Request Duration": -0.000 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.000 secs }
    - requestStartTime : 516165521.17944801
    - initialResponseTime : 516165521.17939502
    - requestCompletedTime : 516165521.17939502
    - serializationCompletedTime : 516165521.17944801
    - latency : -5.2988529205322266e-05
    - requestDuration : -5.2988529205322266e-05
    - serializationDuration : 5.2988529205322266e-05
    - totalDuration : 0.0
  - _metrics : nil

**Comment by HuangWei201703** [comment]
<img width="878" alt="wx20170511-120248 2x" src="https://cloud.githubusercontent.com/assets/26423316/25931911/d1dd59b4-3641-11e7-8da5-df2077f87210.png">

**Comment by Meniny** [comment]
当然会出错，中文需要转义

**Comment by cnoon** [comment]
Hi @HuangWei201703,

Your URL string needs to conform to RFC 2396, otherwise Apple will not instantiate it. If you provided that URL directly, then you need to percent escape the query string values when it includes unicode characters. In the future, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
