### ISSUE TITLE
304 Cache Control not handle

### ISSUE THREAD

**Issue by StevenWatremez** [Alamofire/Alamofire#2109]
Hello, I have an issue about Cache Control with Alamofire.

When I receive a 304 from the server and I have previously cached data from 200, the 304 request is not cached. So when I request again my server, I receive again a 304 instead of cached data. You have an idea about this issue inside Alamofire ?

Everything is ok when I test on chrome or other platforms. I inspected headers for 200 and 304 and it's good to use Cache Control.

Thanks and sorry for my english.

**Comment by StevenWatremez** [comment]
This is my configuration :
```swift
let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 30
configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders
configuration.requestCachePolicy = .useProtocolCachePolicy
configuration.urlCache = URLCache()
self.requestManager = Alamofire.SessionManager(configuration: configuration)
```

**Comment by jshier** [comment]
Your issue is likely the fact that `URLCache` doesn't have a functional empty initializer, so `URLCache()` returns a cache that can't actually store anything. I suggest you initialize it the documented initializer.

In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
