### ISSUE TITLE
Alamofire.request extra arguments error 

### ISSUE THREAD

**Issue by howaisi** [Alamofire/Alamofire#2126]
[
<img width="1009" alt="screen shot 2017-05-29 at 12 38 02 pm" src="https://cloud.githubusercontent.com/assets/26128545/26556943/b896d84e-446b-11e7-9846-433aad6b845a.png">
](url)

**Comment by Matic1993** [comment]
Same problem here. Any ideas how to solve this?

**Comment by cnoon** [comment]
Hi @howaisi,

Most likely the issue is that you've misspelled `parameter`. It should be `parameters` instead. In the future, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
