### ISSUE TITLE
upload 40M mp4 file get Error Domain=NSURLErrorDomain Code=-1005

### ISSUE THREAD

**Issue by smalldu** [Alamofire/Alamofire#2140]
upload small file, it has no problem . When i upload a little bigger file ,  It's progress to 100% and then I get the error. 
```swift
let params:[String:String] = ["token":token]
    Alamofire.upload(multipartFormData: { (mutipartFormData) in
      mutipartFormData.append(data, withName: "file")
      for (key, value) in params {
        if let data = value.data(using: String.Encoding.utf8 )  {
          mutipartFormData.append(data , withName: key)
        }
      }
    }, to: PhotoUploader.server , encodingCompletion: { (encodingResult) in
      switch encodingResult {
      case .success(let upload, _ , _ ):
        // cancel
        if cancelBlock?() ?? false {
          upload.cancel()
        }
        // progress 
        if let progressHandler = progressHandler{
          upload.uploadProgress(closure: progressHandler)
        }
        upload.responseJSON { response in
          switch response.result {
            // Success
          case .success(let value):
           print("success")
           // Failure
          case .failure(let error):
            // error        error code  -1005  
            zp("upload error: \(error.localizedDescription)")
     
          }
        }
      case .failure(let encodingError):
        // error 

        fail(encodingError.localizedDescription)
      }
    })
```

**Comment by tkrajacic** [comment]
That error means that you lost the connection to the host:

[https://developer.apple.com/documentation/cfnetwork/cfnetworkerrors/1416914-cfurlerrornetworkconnectionlost](https://developer.apple.com/documentation/cfnetwork/cfnetworkerrors/1416914-cfurlerrornetworkconnectionlost)

Possibly because of the upload taking too long and the server (PHP?) running into a timeout.

You can try increasing PHPs timeout and maximum upload size on the server side in the php.ini file:

```
upload_max_filesize = 50M

max_execution_time = 60
```

execution time is in seconds.

If you need more help (or aren't using PHP on the server), you might want to try [stackoverflow](https://stackoverflow.com) for more information.

**Comment by smalldu** [comment]
@tkrajacic  thanks for your answer
