### ISSUE TITLE
ParameterEncoding cannot call encode method

### ISSUE THREAD

**Issue by MarcSteven** [Alamofire/Alamofire#2145]
I wanna  call this method ,but it told me it's extra promoter ,but I read the file ,it take two parameters .
ParameterEncoing
fun encode()throws ->NSURLRequest {}
<img width="789" alt="2017-06-09 4 51 38" src="https://user-images.githubusercontent.com/13824297/26968353-5157b406-4d34-11e7-897f-c47bfcd34a1c.png">

**Comment by MarcSteven** [comment]
this is my code as below
num Router<T>:URLRequestConvertible where T:RouterProtocol {
    case post(T,[String:Any])
    case get(T,String)
    case destory(T,String)
    var method:Alamofire.HTTPMethod {
        switch self {
        case .destory:
            return .delete
        case .post:
            return .post
        case .get:
            return .get
        }
    }
    var path:NSURL {
        switch self {
        case .post(let object, _):
            return object.apiType.path
        case .get(let object):
            return object.0.apiType.path
        case .destory(let object):
            return object.0.apiType.path
        }
    }
    var route:String {
        switch self {
        case .post(let object,_):
            return object.post()
        case .get(let object, let identifier):
            return object.get(identifier: identifier)
        case .destory(let object, let identifier):
            return object.destory(identifier: identifier)
        }
    }
   
        var urlRequest: NSMutableURLRequest {
            let task = URLSession.shared.dataTask(with: path as URL) {
                (data, response, error) in
                if error != nil {
                    return
                }
            }
            
            task.resume()
            
            let mutableURLRequest = NSMutableURLRequest(url: path.appendingPathComponent(route)!)
            mutableURLRequest.httpMethod = method.rawValue
            mutableURLRequest.timeoutInterval = TimeInterval(10 * 1000)
                        switch self {
            case .post(_, let parameters):
                return Alamofire.ParameterEncoding.encode(<#T##ParameterEncoding#>)
                //            case .update(_, _, let parameters):
            //                return Alamofire.ParameterEncoding.URL.encode(mutableURLRequest, parameters: parameters).0
            default:
                return mutableURLRequest
            }
        }

        
    }

Why I cannot call this encode method .....

**Comment by cnoon** [comment]
Hi @MarcSteven,

First off, you'll want to try to convert some of your types over to the more Swifty ways of doing things in Swift 3 such as using `URL` and `URLRequest` instead of `NSURL` and `NSMutableURLRequest`.

To fix your immediate problem, you'll need to call one of the actual parameter encoding implementations rather than the protocol itself. You most likely are looking for:

```swift
switch self {
case .post(_, let parameters):
    returnAlamofire.URLEncoding.default.encode(mutableURLRequest, with: parameters)
default:
    return mutableURLRequest
}
```

In the future, I'd recommend you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests. Please also take the time to properly format your code samples so it's easier for us to help you.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
