### ISSUE TITLE
301 Redirect

### ISSUE THREAD

**Issue by ralfwow** [Alamofire/Alamofire#2149]
Hi all,

I'm currently facing an issue with redirect with POST request. Say if i have a request like POST "https://dev.abc.co", in taskWillPerformHTTPRedirection i get https://dev-1.abc.co (correct domain from load balancer), but the redirect request is now in GET instead of POST, and all the POST data is gone. Is there anything I'm missing?

static let manager: SessionManager = {
    
    let configuration = URLSessionConfiguration.default
    configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders
    configuration.requestCachePolicy = .useProtocolCachePolicy
    
    let certs = ServerTrustPolicy.certificates(in: Bundle.main)
    
    let security = ServerTrustPolicy.pinCertificates(certificates: ServerTrustPolicy.certificates(in: Bundle.main),
                                                     validateCertificateChain: true,
                                                     validateHost: true)
  
    let trustPolicies =
      ServerTrustPolicyManager(policies: [
        "*.abc.co":
          .pinCertificates(certificates: ServerTrustPolicy.certificates(in: Bundle.main),
                           validateCertificateChain: true,
                           validateHost: true)
        ])
    
    let manager = SessionManager(configuration: configuration,
                          serverTrustPolicyManager: trustPolicies)
    
    manager.delegate.taskWillPerformHTTPRedirection = { (session, task, response, request) -> URLRequest? in
      print("REDIRECT Request: \(request)")

      return request
    }
    
    return manager
}()

**Comment by jshier** [comment]
After some investigation, it appears that turning `POST` requests into `GET` requests for 301/302 responses is fairly standard behavior and something Apple handles at the core of their networking system. If you can, updating the backend service to return a 307 response should preserve the `POST` request. Otherwise, perhaps the backend can handle the load balancing internally and no expose it to the request? I suggest opening an issue with Apple if you'd like this default behavior. Otherwise you could try and recreate your `POST` request in the redirection delegate method you're already using, but Alamofire provides no support for such a thing.
