### ISSUE TITLE
Custom Validation in validate() 

### ISSUE THREAD

**Issue by anishparajuli555** [Alamofire/Alamofire#2200]
I am using Open Cart API. The api has a very weird mechanism..

The API return header status code 200 even on unauthorized access, instead of 401.And returns the 401 error code in the body as attached in the image. 

<img width="1158" alt="screen shot 2017-07-16 at 7 22 10 pm" src="https://user-images.githubusercontent.com/7752578/28248080-76a39dba-6a5d-11e7-8509-3f27ee643161.png">

This way, my response success block is triggered instead of retrying the request. I have been using the Alamofire Adapter and Retrier for a long and this seems to be working find when the header status code is 401. But the API returns me 401 status code in the body which doesn't trigger the  delegate method while validating the request.
```
    func should(_ manager: SessionManager,
                retry request: Request,
                with error: Error,
                completion: @escaping RequestRetryCompletion) 
```

How should i handle this situation... Is there a way i can call the retrier delegate method manually?

**Comment by anishparajuli555** [comment]
One way how i solved it is 

```
extension DataRequest {
    
    public func validateBodyStatusCode() -> Self {
        
        return validate { request,response,data in
            
            PrinterHelper.jsonPrinter(self.delegate.data!)
            do {
                if  let json = try JSONSerialization.jsonObject(with: data!, options: []) as? [String : Any]{
                    
                    if let statusCode =  json["statusCode"] as? Int, statusCode == 401{
                        
                        let reason:AFError.ResponseValidationFailureReason = .unacceptableStatusCode(code: 401)
                        return .failure(AFError.responseValidationFailed(reason: reason))
                        
                    }else{
                        
                        return .success
                    }
                }else{
                    
                    return .success
                }
                
            } catch let error {
                
                print("Json serialization error \(error)")
                let reason:AFError.ResponseValidationFailureReason = .unacceptableStatusCode(code: response.statusCode)
                return .failure(AFError.responseValidationFailed(reason: reason))
                
            }
        }
    }
}
```

And using the custom Validation as 

```
 let apiRequest = manager!.request(networkAddress, method: EndPoint.method, parameters: parameter, encoding: enCodingFormat, headers:authFlagHeader).validateBodyStatusCode().responseJSON { (response) in
            
            let parsedResult =  ResponseParser<EndPoint.ResponseType>.parseResponse(withResponse: response)
            callback(parsedResult.0,parsedResult.1)
            
        }
```

**Comment by jshier** [comment]
@anishparajuli555 You've hit a rather prickly use case for us. Right now `validate()` is only intended for simple validation scenarios. As you've seen, it doesn't really work that well for validating something in the response data. In fact, that's a highly inefficient use of it, since the response data may then be decoded twice. At the moment I would suggest any validation you need to perform on the response data be done in a custom response serializer and not `validate`. In the future we'll be reevaluating `validate()`s capabilities and how it fits into Alamofire.

**Comment by kiokumicu** [comment]
Have the same issue. API always send 200 status code and in json response body code with real response status.

**Comment by anishparajuli555** [comment]
@kiokumicu  i have added solution above..please have a look

**Comment by kiokumicu** [comment]
@anishparajuli555 yeap, I use it, thx. 
Maybe guys add native support )

**Comment by ios4vn** [comment]
I have same problem. Have anyone know Alamofire 5 solved this case?

**Comment by ios4vn** [comment]
@cnoon thanks guy

**Comment by croossin** [comment]
@jshier / @cnoon - is there any available fix for problems like these in AF5? I’m on beta 6 and was curious your guys recommendations for a situation similar to OP. I am getting 200’s but there is in fact an error in the body that will cause me to refresh some tokens and then retry. What is your recommended solution given we are using AF5. Thanks again.

**Comment by jshier** [comment]
@croossin Once you need to parse response bodies as errors and return the value, it's usually easier and more efficient to do so in the response serialization phase, rather than in validation. Especially now, after beta 5, where the ability to trigger retry from serialization errors were added. So, for parsing, you have a few options:

1. Use `responseDecodable` and, if there was a failure decoding, attempt to parse your error body. (Make sure to pass a custom `DispatchQueue` and call back to `.main` for this.)
2. Use `responseData` and do both the intended type parsing and the failure parsing in the response handler. (Make sure to pass a custom `DispatchQueue` and call back to `.main` for this.)
3. Write your own `ResponseSerializer`-conforming type and do the parsing there. 

Then, just create your own error type and handle the particular case you need in a `RequestRetrier` to trigger the retry.

Personally, I write my own `ResponseSerializer` for all of my projects, especially those that need custom response handling like this.

**Comment by micHar** [comment]
@jshier how do you use custom `ResponseSerializer` with async-await AF api?
