### ISSUE TITLE
Check if all concurrent requests have been completed

### ISSUE THREAD

**Issue by eriktelepovsky** [Alamofire/Alamofire#224]
Hi. I'm trying to launch custom completion handler as soon as all concurrent requests are finished. Something like this (I deleted unimportant code to make it easier to read):

``` swift
class APIManager {
    class var sharedInstance: APIManager {
        struct Static {
            static var instance: APIManager?
            static var token: dispatch_once_t = 0
        }

        dispatch_once(&Static.token) {
            Static.instance = APIManager()
        }

        return Static.instance!
    }

    func downloadAllData(allDataDownloadedCompletionHandler:(Any?)->Void) {
        var downloadRequests:[Request] = [Request]()
        var completionHandlerCounter = 0
        var allData = [AnyObject]()

        let requestCompleted: (Bool, AnyObject?)->Void = { downloaded, data in
            if downloaded && data != nil {
                // append downloaded data to result list
                allData.append(data)
            }

            // check if all requests has been already completed
            completionHandlerCounter = completionHandlerCounter + 1
            if completionHandlerCounter < downloadRequests.count {
                return
            }

            // all requests completed
            println("All data downloaded")
            allDataDownloadedCompletionHandler(allData)
        }

        let types = ["one", "two", "three"]  // there are actually about 10 requests called, but to make it simple I set it to 3
        for type in types {
            downloadRequests.append(self.downloadDataForType(type, completionHandler: requestCompleted))
        }
    }

    func downloadDataForType(type:String, completionHandler:((Bool, AnyObject?)->Void)) -> Request {
        return Alamofire.request(Router.TypeData(type: type)).response({ (request, response, xmlResponse, error) -> Void in
            // request finished
            println("Data for type \(type) downloaded")

            // let's parse response in different queue, because we don't want to hold main UI queue 
            var db_queue = dispatch_queue_create("db_queue", nil)
                dispatch_async(db_queue, {
                if response?.statusCode == 200 {
                    saveToDatabase(xmlResponse)

                    // IT CRASHES HERE !!!
                    return completionHandler(true, xmlResponse)
                }
                return completionHandler(false, nil)
            })
        })
    }
}
```

As you can see, APIManager is a singleton class and I am downloading data (running multiple concurrent asynchronous requests) with call 

``` swift
APIManager.downloadAllData(myCompletionHandler)
```

It works on simulator, but in Release version it use to fall often (**not always**) and in crashlog there is an error with this message:

```
partial apply forwarder for reabstraction thunk helper from @callee_owned (@unowned Swift.Bool, @in protocol<>?) -> (@unowned ()) to @callee_owned (@in (Swift.Bool, protocol<>?)) -> (@out ()) (APIManager.swift:0)
```

You can check full stacktrace here: http://pastebin.com/mJRLUkEe

I don't understand what is going on. Why does it crash? Why does it crash on release version only? And what does this error even mean? 

Any help is very **very** appreciated. Improvements or another idea how to check if all concurrent requests have been completed are welcome as well. Thank you very much.

**Comment by sikoried** [comment]
Sorry to bring this up again, but I'm trying to synchronize groups of requests that have to run in sequence, e.g.
```
[ group1: 
  [ req1: ========>     ]
  [ req2: ====>         ]
  [ ...]
]
// -- sync
[ group2:
  [ req1: =====>        ]
  [ req2: ==>           ]
  [ ... ]
]
// -- sync and exit
```
This procedure is supposed to run without any user interaction, in some background thread (actually, it's a classic offline data sync, with interdependencies between objects), and should signal completion in the very end.
I tried:
- dispatch semaphores (`dispatch_semaphore_*`): this doesn't seem to work, as the executing thread gets stuck in `dispatch_semaphore_wait` while the Alamofire thread seems to not be resumed at all (I'd guess that's interference with Alamofire's internal dispatch groups)
- dispatch groups (`dispatch_group_*`): this doesn't mix with Alamofire's dispatch group (resulted in INVOPs, most likely because of races for the queue)
- extending the Alamofire Manager by a `wait()` function that waits until the queue completes.  I couldn't get this to work either.


Is there any proper way of doing this kind of synchronization?  I would rather not resort to `q`-style promises and deferreds, as it makes things unnecessarily complex.  An help appreciated, thanks!

**Comment by cnoon** [comment]
@sikoried I hate to say it but I think you're really overthinking it. @mattt lays out some great ways to attack this problem which are all much easier than trying to use semaphores and / or groups to try to solve a threading issue that doesn't exist. All the requests return back to the main queue (unless you provide your own dispatch queue), so threading is not an issue you need to deal with.

**Comment by sikoried** [comment]
Ok, I must have missed those, so any help appreciated :-)  Meanwhile, I figured out that I can use `dispatch_group_*` as
```
let group: dispatch_group_t = dispatch_group_create()

dispatch_group_enter(group)
Manager.sharedInstance.request(...).responseSwiftyJSON { (req, response, json, error) in
  // ...
  dispatch_group_leave(group)
}

dispatch_group_notify(group, dispatch_get_main_queue()) {
  NSLog("All calls complete")
}
```
Which works, however, it's again using a callback block which is what I want to avoid.  Using `dispatch_group_wait(group, DISPATCH_TIMEOUT_FOREVER)` instead of `dispatch_group_notify` results in the thread being stuck in wait, presumably because it's executed before the request is processed.  It probably doesn't belong here, but I couldn't find a solution elsewhere, but is there a way to have the thread yield, or have Alamo put the request on a separate background queue (that's independently executed) so that the main thread can actually wait?

**Comment by bensarz** [comment]
@sikoried have you ever found a good solution to this?
I'm running into a similar problem right now.

**Comment by Nick-The-Uncharted** [comment]
This is because responseSwiftyJSON was dispatched to main queue, do this and your problem is solved.
```Swift
        return response(queue: dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0),responseSerializer: User.userResponseSerializer,
            completionHandler: completionHandler)
```

**Comment by benstahl** [comment]
Thanks, @Nick-The-Uncharted, that solved my problem. All along, I thought it was an Alamofire issue when really it was SwiftyJSON. Using SwiftyJSON's response dispatched to the main queue (instead of the default) allowed me to wrap the Alamofire function in a dispatch group with dispatch_wait, and not hang the app.
