### ISSUE TITLE
No response headers when the response fails `ResponseValidationFailureReason.unacceptableStatusCode`

### ISSUE THREAD

**Issue by richardPFisk** [Alamofire/Alamofire#2245]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Coded for client's requests failing.

## What did you expect to happen?

To be able to access the `statusCode` *and* response headers.

## What happened instead?

I can only access the `statusCode`.

## Alamofire Environment

**Alamofire version: 4.5.0**

Would you be willing to accept a well tested pull request which made the simple change adding the response headers to the `ResponseValidationFailureReason.unacceptableStatusCode` enum?

**Comment by jshier** [comment]
We've discussed this feature internally. We created the `AFError` cases very specifically to capture only the content required for the descriptions of the error, not as general values. If you need this information, I suggest capturing the whole `*Response` value and using it to perform your logic. Otherwise a feature like would naturally lead to including every response value with the error, including the `Data` returned and the original `URLRequest`, which is obviously infeasible. If you have some more specific use cases in mind that can't be handled by the `*Response` values, please open a new issue with more specific examples and we'll investigate how they could be handled.
