### ISSUE TITLE
Invalid SSL Certificate

### ISSUE THREAD

**Issue by johnrickman** [Alamofire/Alamofire#225]
How can I allow an invalid certificate? In AFNetworking, there was #define _AFNETWORKING_ALLOW_INVALID_SSL_CERTIFICATES_ 1

**Comment by tobiasoleary** [comment]
You can replace Alamofire's SessionDelegate's `URLSession(session:task:didReceivedChallenge:completionHandler:)`  method with the following to get around it.

```
public func URLSession(session: NSURLSession, task: NSURLSessionTask, didReceiveChallenge challenge: NSURLAuthenticationChallenge, completionHandler: ((NSURLSessionAuthChallengeDisposition, NSURLCredential!) -> Void)) {
    
    
    //TODO: Remove this
    if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
        let trustedDomain "self.signed.domain.com"
        if challenge.protectionSpace.host == trustedDomain {
            let trustedCredential = NSURLCredential(forTrust: challenge.protectionSpace.serverTrust)
            completionHandler(.UseCredential, trustedCredential)
            return
        }
    }
    //TODO: No, Really Remove This
    
    
    if taskDidReceiveChallenge != nil {
        completionHandler(taskDidReceiveChallenge!(session, task, challenge))
    } else if let delegate = self[task] {
        delegate.URLSession(session, task: task, didReceiveChallenge: challenge, completionHandler: completionHandler)
    } else {
        URLSession(session, didReceiveChallenge: challenge, completionHandler: completionHandler)
    }
}
```

I don't know what other effects this code could have on the library, so I suggest you only use it until you get an verified SSL cetificate in place and if you're testing on a localhost server or on a server that doesn't have any private data because it's all fake just don't use https. If the remote server you're testing with does have confidential data you should **not** use this code, you should get a verified SSL certificate.

The developers behind Alamofire have a really good reason for not implementing a simply way to use invalid SSL certificates. It forces us library users to really consider the risks and ramifications of overriding the validation check.

**Comment by tvich1** [comment]
Here is a possible solution on how to accept invalid SSL Certificates in Alamofire. 

Add the following function in your AppDelegate class and call it in didFinishLaunching function:

func acceptInvalidSSLCerts() {
          let manager = Alamofire.Manager.sharedInstance
  print("trying to accept invalid certs")
  
          manager.delegate.sessionDidReceiveChallenge = { session, challenge in
              var disposition: NSURLSessionAuthChallengeDisposition = .PerformDefaultHandling
              var credential: NSURLCredential?
  
              print("received challenge")
  
              if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                  disposition = NSURLSessionAuthChallengeDisposition.UseCredential
                  credential = NSURLCredential(forTrust: challenge.protectionSpace.serverTrust!)
              } else {
                  if challenge.previousFailureCount > 0 {
                      disposition = .CancelAuthenticationChallenge
                  } else {
                      credential = manager.session.configuration.URLCredentialStorage?.defaultCredentialForProtectionSpace(challenge.protectionSpace)
  
                      if credential != nil {
                          disposition = .UseCredential
                      }
                  }
              }
  
              return (disposition, credential)
          }
      }


Reference:-> [Accepting invalid SSL certificates in Alamofire](http://swiftforums.org/forum/alamofire/32-accept-invalid-ssl-certificates-in-alamofire)

**Comment by anamalihassan** [comment]
@tvich1 hey can we enable and disable Invalid SSL Acceptance somehow? I tried your method, it works but it blocks URL OAuth in UIWebView.
