### ISSUE TITLE
ios 11 Support

### ISSUE THREAD

**Issue by Mahan3340** [Alamofire/Alamofire#2301]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

        let parameters: Parameters = ["token": token]

  ```
      Alamofire.request("someURL", method: .get, parameters: parameters)
            .responseJSON
        {
            response in
            let statusCode = response.response?.statusCode
            if(statusCode == nil || statusCode == 0 || response.result.isFailure)
            {
                return
        }
            }
```
## What did you expect to happen?

get response with response code 200 or 201 

## What happened instead?

got 200 with response  = nil , and isFailure = true

## Alamofire Environment

**Alamofire version: 4.4
**Xcode version: 9 
**Swift version: 4 
**Platform(s) running Alamofire: ios 11 iPhone 6s/iPhone 6Plus 
**macOS version running Xcode: 10.12 

## Demo Project
cant provide project cause the request isn't some specific request , just any , I SAY ANY !! request may fail like this or may not , just in ios 11 , its working in postman , android , browser , no matter get,post or what ever , just Check the lib with ios 11 please and it was working just fine , the same request , not a single character is changed the same damn code , but its not working properly in IOS 11 , as u can see I opened issue and right after an hour there was someone else sayin the same problem , but u just close the issue asking for " be more specific " there isn't such thing ! the requests are Random , the webserver is fine the problem is with your Library

**Comment by jshier** [comment]
You need to investigate this further on your own and find out what has changed in your requests that may be causing these issues. Look at the raw request and response data and compare it to previous versions. Check server logs and see if different actions were taken. Because right now, all of our tests pass on all of our supported platforms, including iOS 11, so there's nothing for us to do here. You can't just say "something seems different" and

**Comment by Mahan3340** [comment]
I just don't get it why you don't read the part that the requests are working fine on every other platform and browser or what ever . fine I'm gonna use another Library

**Comment by iant2** [comment]
I'm running into this too, I'm getting a lot of nil pointer crashes (caused by improper handling in my code similar to [https://github.com/Alamofire/Alamofire/issues/1990](this) )

I was checking my server logs and it appears that many of the times my user (same user) experienced a crash, there was no corresponding activity on the server for the request. So it almost seems like the request isn't even going to the server. 

My code is pretty much the same as Mahans above and i know why the actual crash is happening but what I'm trying to figure out is why is the response, response result returned as nil (with no server activity) 

here are some crashes, all 100% on ios 11
http://crashes.to/s/c82fb3d3baf
http://crashes.to/s/7ad76bc169c
http://crashes.to/s/42f8c06e709
http://crashes.to/s/195449a7892
http://crashes.to/s/c82fb3d3baf

**Comment by Mahan3340** [comment]
Actually they dont care , in my case the request is working on Android and postman and browser for get requests but they dont wanna check what's wrong with them and seems they believe its okey from their side

**Comment by jshier** [comment]
@iant2 Can you open a new issue with the code from one of those crashing closures and why it was crashing now? Also, details about your server's caching logic might be helpful. It's possible they changed the caching logic for iOS 11 or introduced a bug.

**Comment by iant2** [comment]
@jshier i will post a new issue. Not sure what you mean about "why it was crashing now?", do the logs I provided not answer this?

Also, there is no backend caching currently, everything pulls directly from the DB

**Comment by jshier** [comment]
@iant2 No, all of the crashes you posted were crashing in your code. If it wasn't crashing before it might be interesting to see why they were now, but nothing in there points to a direct issue with Alamofire. If output from the underlying networking framework has changed that may cause user's code to behave differently, then it would be good to see why. I'm guessing you were just force unwrapping things. Your note about there not being server activity may be interesting, which is why I asked about the caching.
