### ISSUE TITLE
Validate Request not working as expected

### ISSUE THREAD

**Issue by Mazyod** [Alamofire/Alamofire#2307]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I wrote code as follows:
```swift
let dataTask = manager
    .request(task)
    .validate(statusCode: 200..<300)
    .responseJSON(queue: DispatchQueue.global(qos: .utility)) { response in
        ...
    }
```

## What did you expect to happen?

When callback is invoked with HTTP status outside the `validate` range, I should get `response.result` to be a failure.

## What happened instead?

`response.result` was a success.

## Alamofire Environment

**Alamofire version:** 4.5.0 and 4.5.1
**Xcode version:** Xcode 8.3.3
**Swift version:** Swift 3.1
**Platform(s) running Alamofire:** iOS and macOS
**macOS version running Xcode:** 10.12

## Demo Project

https://github.com/Mazyod/Alamofire-validate-bug

**Comment by Mazyod** [comment]
To add more context outside the template, our CI tests were breaking every once in a while, and after investigation, it seems that a test that expects our network layer to return "failure" is returning "success". After further debugging, we found that HTTPRespons code is 400, but result was successful.

So, the repo linked has a reproduce case, very similar to our setup. After running for a sufficient amount of time, it should trigger the assertion.

**Comment by Mazyod** [comment]
Some more debugging information (would really like to cover this bug ASAP):

```
(lldb) p response.debugDescription
(String) $R10 = "[Request]: GET test://the.api
[Response]: <NSHTTPURLResponse: 0x7f93a21dd5e0> 
{ URL: test://the.api } 
{ status code: 400, headers {
    \"Content-Length\" = 13;
    \"Content-Type\" = \"application/json\";
} 
}
[Data]: 13 bytes
[Result]: SUCCESS: {
    foo = bar;
}
[Timeline]: Timeline: { 
\"Request Start Time\": 528660681.752, 
\"Initial Response Time\": 528660681.752, 
\"Request Completed Time\": 528660681.753, 
\"Serialization Completed Time\": 528660681.753, 
\"Latency\": 0.000 secs, 
\"Request Duration\": 0.001 secs,
\"Serialization Duration\": 0.001 secs, 
\"Total Duration\": 0.001 secs }"
```

**Comment by Mazyod** [comment]
Seems like response returns before validation is added to the queue, which shouldn't happen in "real-world" scenarios ... What would be the suggestion here? Is this a limitation? Feature? Bug?

**Comment by jshier** [comment]
I'm guessing this is a race condition between the validation being added to the internal queue and the response handlers being added and run. I'm not sure there's a simple fix here. Are you seeing this in the real world or only when using local stubs?

**Comment by Mazyod** [comment]
Only happens when stubbing, can't imagine it happening in real world scenarios. I switched `startsRequestsImmediately` to false for now.

**Comment by jshier** [comment]
Investigating further, it's certainly possible that validations run independently of response handlers. It also seems possible that the validation can be run before or while `.validate` methods are being called, since that property isn't thread safe. This seems like something that would need to be handled as part of the refactor for #2226, as that would likely involve moving more functionality inside `Request` and ensuring that it can operate asynchronously.

@cnoon any thoughts?

**Comment by nacho4d** [comment]
Hello I am having exactly the same situation here. Everything works fine on real world but on stubs it randomly fails. I hope this bugs gets more attention. Any known work-around to make tests stable would be helpful for me :]

**Comment by Mazyod** [comment]
@nacho4d I am setting `startsRequestsImmediately` to false, and manually starting the request after getting the task from the builder chain.

**Comment by nacho4d** [comment]
Thank you for the suggestion. That is one possible solution I will consider :]
I am using OHHTTTPStubs in my tests. There is an option to set the `responseTime` setting this to 0.1 so far seems to work too

**Comment by jshier** [comment]
@Mazyod @nacho4d It would be interesting if your testing scenarios could be run against my `alamofire5-core-rewrite` branch, if the changes aren't too breaking for you. I've rearchitected the internals of the library to make the order of operations more predictable, but I worry there's still an inherent race between starting a request and adding validators, since the validators aren't part of the request's internal queue. So I'd appreciate it if you could try it out and see!

**Comment by jshier** [comment]
This now be fixed on the `alamofire5` branch and will be part of that release. Closing.
