### ISSUE TITLE
Termination Description: DYLD, Symbol not found: _OBJC_CLASS_$_NSURLSessionStreamTask

### ISSUE THREAD

**Issue by KarmatechMediaworks** [Alamofire/Alamofire#2324]
I am facing a strange issue related to my app build.
This started to happen recently (mid Sept-2017).
I able to upload the app on Test Flight, the app works perfectly on iPhone 6/6s but happens to crash on startup on iPhone 6Plus/6sPlus, but app works perfectly on iPhone 7Plus too.

When I got the crash log from organizer , I tried to figure it out actually what was cause and I happen to note "Termination Description: DYLD, Symbol not found: _OBJC_CLASS_$_NSURLSessionStreamTask" which says the root cause of the crash.

Need help.

-- 
Xcode - 7.3.1
Swift Ver. 2.2
Minimum deployment target : iOS 9.3.

**Comment by jshier** [comment]
Sorry, we no longer support Xcode or Swift versions that old. However, we did see that sort of crash during the Xcode 9 beta cycle, and it seems to be fixed now. Ultimately it's an issue in Apple's frameworks that we can't do anything about. I suggest you file a bug with them, or on their dev forums, but I'm pretty sure you'll get only a minimal response since you're now two major versions of Xcode out of date.
