### ISSUE TITLE
Make "Chained Response Handlers" to maintain order

### ISSUE THREAD

**Issue by ziogaschr** [Alamofire/Alamofire#234]
Is there a way to break chaining if some conditions are met?
For example, if you check below in `responseJWT` I want to check for some conditions and to be able to break chaining, so as the code inside `responseString` will not be executed.

Also from what I found so far, the response handlers are not being executed in the order defined in the code. So the code below first prints `2` and then `1` while I was expecting the opposite.

I think I can understand why this happens. Although, I wanted to ask if you know a way to make it work in the way I am expecting.

``` swift
Alamofire.request(.GET, "http://httpbin.org/get")
         .responseJWT { (_, _, jwtJson, error) in
                 println(1) 
                 println(jwtJson)

                  // can we break the chaining here if some conditions are met?
         }
         .responseString { (_, _, string, error) in
                 println(2)
                 println(string)
         }
```

**Comment by mrubin** [comment]
> There are no guarantees about the ordering of chained responses

This really confused me (versus looking at the code locally and trying to reason about how it works). I've since realized that this comment is outdated. Specifically, [this commit](https://github.com/Alamofire/Alamofire/commit/83774b0f9be426e261a44a040701965d0817c68f#diff-8566d050bc5476c30a47ff3e37f237aa) (which occurred after the above comment) switched to an `NSOperationQueue` with `maxConcurrentOperationCount = 1`, which should guarantee that the chained response handlers are processed in order, one at a time, and consequently enqueue the associated block/closure onto the main dispatch queue (by default) - which is serial - and also process in order and one at a time.

I was trying to figure out whether I needed to explicitly protect against possible concurrent access to a shared resource accessed (only) from response handlers. I've come to the conclusion that since I'm using the main dispatch queue - which is serial - for all response handlers, that should effectively limit access to this shared resource to one response handler at a time.

**Comment by cnoon** [comment]
You assumptions are correct @mrubin. If you don't specify custom `queue`s to run the `response` closures on, it will fallback to the main queue which will result in serial behavior for that request.

**Comment by cartickn** [comment]
So with the updated comment, will the chain break with when it hits the return statement in .responseJWT and not execute .responseString?

```
Alamofire.request(.GET, "http://httpbin.org/get")
         .responseJWT { (_, _, jwtJson, error) in
                 println(1) 
                 println(jwtJson)
                  // can we break the chaining here if some conditions are met?
                 if (1==1){
                     return
                 }
         }
         .responseString { (_, _, string, error) in
                 println(2)
                 println(string)
         }
```

**Comment by mrubin** [comment]
At least on Alamofire 2, I don't believe the chain can break.. the closures (from each response handler) return Void, so there's no way to know to 'break the chain'. Each closure is added to a queue and once it's time to execute them, they're all executed in the order that they were added.

If the response had an error, all the handlers should see that error. Otherwise, I don't think there's a way to directly propagate information from one closure to the next.

**Comment by cnoon** [comment]
So reading back through this thread is pretty interesting. The original response from @mattt clearly indicates that it was running the response serialization closures in parallel. However, when looking back at the codebase in b5d6f581 around the time of that response, I don't think that was possible. The `TaskDelegate` queue has always been a serial queue.

That same behavior was still maintained in aa6ea80b when we switched it from using a `dispatch_queue_t` to an `NSOperationQueue`. Nothing really changed except being able to cancel the operations in a forced shutdown scenario which allows the `Manager` instance to deallocate gracefully.

Now to really answer this question, we need to understand what's going on. Here's the order of operations that govern this behavior:

1. Create request
1. Add responseJWT implementation onto the Request's internal serial queue
1. Add responseString implementation onto the Request's internal serial queue
1. Request finishes, start up the serial queue
1. Executes the responseJWT implementation on the serial queue
1. Calls the responseJWT completion closure on whatever queue was provided (main by default)
1. Executes the responseString implementation on the serial queue
1. Calls the responseString completion closure on the provided queue (main by default)

There's no simple way to break the chaining here. You could couple your response serializers to depend on each other allowing the following ones to `early out` if certain conditions were met, but that seems a bit strange. I think that you'd instead want to build a single response serializer that could handle the multiple scenarios as a single, cohesive operation.

The custom response serializer could also take in multiple closures to chain together inside the response serializer. Either way, if you need to chain these operations together with the concept of breaking the chain, then the default behavior here is not going to work in your favor.
