### ISSUE TITLE
ParameterEncoding's query parameters keys order

### ISSUE THREAD

**Issue by givip** [Alamofire/Alamofire#2342]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have serverside API, that gives different responses depending on url encoded parameters order
For example:

> https://test.com/test?page=1&ajax=true 

gives JSON, and

> https://test.com/test?ajax=true&page=1

gives HTML page 

## What did you expect to happen?

When I configure request, I put inside dictionary with parameters in specified order

## What happened instead?

Alamofire sort them by key

## Alamofire Environment

**Alamofire version: 4.5**
**Xcode version: 9.0.1**
**Swift version: 4**
**Platform(s) running Alamofire: macOS 10.13**
**macOS version running Xcode: 10.13**

**Comment by jshier** [comment]
Unfortunately Swift's dictionaries aren't order preserving, so there's no way to currently accomplish this. Alamofire currently encodes URL parameters in alphabetical order, but there's no way to preserve an arbitrary ordering in the dictionary. So unless the order is want is a sort of some kind, or the arbitrary ordering of the dictionary, there isn't much we can do here. 

So while the top level Alamofire APIs can't accomplish this due to the use of `[String: Any]` for parameters, you can accomplish it by creating a custom parameter type and encoding the requests yourself. We outline one approach in our documentation for [`URLRequestConvertible`](https://github.com/Alamofire/Alamofire#urlrequestconvertible).
