### ISSUE TITLE
Crash on Jailbroken device while initializing the session manager.

### ISSUE THREAD

**Issue by venkatanavn** [Alamofire/Alamofire#2347]
## What did you do?

One of my user is facing a crash when he launches the app. The crash is happening during the initialization of the session manager. I am performing SSL pinning and hence I am initializing the session manager with server trust policies added to it.

**Code usage:**
        let manager = **Alamofire.SessionManager**(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
        )

## What did you expect to happen?

No Crash.

## What happened instead?

Crash occurred.

## Alamofire Environment

**Alamofire version:** 4.5
**Xcode version:** 9.0
**Swift version:** 3.2
**Platform(s) running Alamofire:** iPhone 5s (OS: 10.2.1), **Device is Jailbroken**
**macOS version running Xcode:** 10.12.6
<img width="1157" alt="alamofire-crash-device details" src="https://user-images.githubusercontent.com/18372306/32233128-ac969ddc-be27-11e7-86c8-31cabfc7ee96.png">
<img width="1113" alt="alamofire-crash-stack trace" src="https://user-images.githubusercontent.com/18372306/32233129-aca94b08-be27-11e7-8863-1b0b39927f94.png">

**Comment by jshier** [comment]
I'm not quite sure what's going on in that crash report, but as you can see, the crash doesn't originate in Alamofire, it was chosen by Crashlytics because it was the last line of code that could be clearly symbolicated and wasn't part of a system library. I have no idea what it is, but it seems like `hookkeyboard.dylib` has bound itself into the process. Are you sure this call stack originates from your code and not some custom keyboard which uses Alamofire? 

In any event, unless there's more to go on there not much we can do here. Not only do our tests prove the initializer works fine but so do thousands of apps with likely millions of users. There's a reason most companies don't support jailbroken devices.
