### ISSUE TITLE
swift4.0 error using carthage

### ISSUE THREAD

**Issue by dlxxl06** [Alamofire/Alamofire#2351]
![image](https://user-images.githubusercontent.com/13935772/32433807-dacbf660-c2a1-11e7-9593-9a4b3ca3f588.png)

## Alamofire Environment

**Alamofire version:4.5
**Xcode version:9.0
**Swift version:4.0
**Platform(s) running Alamofire: macOS High Sierra

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by RYDIOO** [comment]
A similar error was referenced [here.](https://github.com/realm/realm-cocoa/issues/5442) but for a different project and I believe the fix was clearing the build folder in Carthage and building using the following command.

> carthage update --platform iOS --no-use-binaries

This should work for you since it will build Alamofire using the compiler you currently have. Still a temporary fix though and if this doesn't work hopefully someone will find a way to get it working for you.

**Comment by ninevcat** [comment]
@RYDIOO it didn't work!! NONONO!😱

**Comment by fromageblanc** [comment]
switch xcodebuild compiler path

for example ,xocde app name is "Xcode9x.app"
`sudo xcode-select --switch /Applications/Xcode9x.app/Contents/Developer`

**Comment by jshier** [comment]
Fundamentally, this error is caused by having build products built with incompatible versions of the Swift compiler. The easiest way to fix it is to rebuild all of your sources. If that's not possible, you'll need to limit your compiler to the version that compatible with your prebuilt binaries.
