### ISSUE TITLE
-999 (NSURLErrorCancelled) instead of anything in NSURLErrorServerCertificate* is given when public key pinned was not matched by remote

### ISSUE THREAD

**Issue by sndive** [Alamofire/Alamofire#2384]
## What did you do?

setup alamofire to use session that pins public key

## What did you expect to happen?

with no .cer files in the main bundle I've expected
NSURLErrorServerCertificate* family of errors returned

## What happened instead?

I've got back NSURLErrorCancelled due to the
wholesale
 disposition = .cancelAuthenticationChallenge
in alamofire taskmanager that's done on trust evaluation failure

## Alamofire Environment

**Alamofire version:**
4.5.1

**Xcode version:**
9.2

**Swift version:**
3.2

**Platform(s) running Alamofire:**
real devices and simulator??? 

**macOS version running Xcode:**
10.13.2

**Comment by sndive** [comment]
AFNetworking claims this fixed back in 2015:
https://github.com/AFNetworking/AFNetworking/issues/3165

**Comment by jshier** [comment]
This is definitely something we want to get fixed for Alamofire 5. However, the question then becomes whether we want to go farther and return a specific `AFError` for this, and how we would do that. I've been experimenting with `URLSession` and its delegate methods, and we can match pinning failures per task if we implement only the task-based challenge delegate method and not the session one. This could allow us to return errors if, say, no certificates were found to pin. Or we could do both. Fail the task with `.rejectProtectionSpace` if pinning fails, return underlying pinning failures from Alamofire if even trying to pin failed.

I have a [PR](https://github.com/Alamofire/Alamofire/pull/2344) up that refactors our pinning support for Alamofire, but I think it's possible to go a bit further and fix this issue as well.

@cnoon Any issue with such a change?

**Comment by jshier** [comment]
For reference, [#3191](https://github.com/AFNetworking/AFNetworking/pull/3191) is the final AFNetworking PR that merged this change.

**Comment by jshier** [comment]
@sndive Looks like that AFNetworking change was reverted in [#3417(https://github.com/AFNetworking/AFNetworking/pull/3417) because it doesn't actually produce a failure in all pinning modes. I'm seeing the same thing locally in a test project. If we want to change something here, I think we're going to have to refactor to include a secondary `AFError` instance and somehow propagate it as the real error instead of the cancellation error. Doable, I think, if we refactor to no use the session challenge method but instead the task one. But that requires rather significant refactoring.

**Comment by sndive** [comment]
one corner case is when certificate or public key pin array is empty -> user error but i dunno
if you want to use a different error than ceritificate/publickey evaluation failure for that.
Maybe cancelled is good enough: after all it's the app issue, not necessarily an alamofire
issue that you want a distinct error for.

**Comment by jshier** [comment]
Yes, there are several error cases we should handle here, including a failure to find certificates of the proper format and domain mapping errors, in addition to a non-cancellation error when pinning fails. But that is all incumbent upon a significant internal refactor which will be part of Alamofire 5.

**Comment by jshier** [comment]
I've successfully created a prototype rewrite of Alamofire's core delegate behavior which allows for individual requests to fail because of pinning errors. I hope to get this integrated into Alamofire 5 soon.

**Comment by goktugaral** [comment]
Hi @jshier , so am I understand correctly? Right now, Alamofire does not return cancellation error when pinning fails. Also if I use correct domain with correct .der certification it is okey, but if I changed my domain it is not even called ServerTrustPolicy cases and returns success response.

**Comment by jshier** [comment]
@goktugaral You're right, we don't return an error if the domain you pinned isn't actually what we need. I think for that, we'd want to enforce a check that says only pinned domains should ever be seen. However, due to Alamofire's `SessionManager` being designed for use with multiple domains, it couldn't be the default. I'll mark this down for an enhancement in Alamofire 5.

**Comment by jshier** [comment]
Tracking these enhancements in #2477.
