### ISSUE TITLE
Bug&Fix: PATCH Parameters In url error

### ISSUE THREAD

**Issue by jiang443** [Alamofire/Alamofire#2385]
i found than parameters can not be added to url with Patch method. 
Then i found this founction in the library.

ParameterEncoding.swift:

 private func encodesParametersInURL(with method: HTTPMethod) -> Bool {
        switch destination {
        case .queryString:
            return true
        case .httpBody:
            return false
        default:
            break
        }

        switch method {
        case .get, .head, .delete, .patch:  //add .patch, then solved
            return true
        default:
            return false
        }
    }
}

**Comment by jshier** [comment]
Like `POST` and `PUT`, `PATCH` is generally considered a resource manipulation method. In `PATCH`'s case, one with partial changes instead of whole new values. In that case, body encoding is still the preferred default. If you need your `PATCH` methods to encode their parameters in the URL, I suggest you create your own `ParameterEncoding`.

**Comment by jiang443** [comment]
thx for your advice
