### ISSUE TITLE
Looping Alamofire requests cause timeout

### ISSUE THREAD

**Issue by martheli** [Alamofire/Alamofire#2403]
## What did you do?

Calling same API hundreds of times.

## What did you expect to happen?

Data to be returned each time

## What happened instead?

Certain number of them complete and then requests just stop and I get timeout error in Xcode console.

## Alamofire Environment

Alamofire version: 4.6.0
Xcode version: 9.2
Swift version: 4
macOS version running Xcode: High Sierra

## Demo Project

I tried to wrap the requests in an Operation queue but I get same error.

```
let queue = OperationQueue()
queue.maxConcurrentOperationCount = 80



for device in devices {   //devices array contains 300-400 devices

queue.addOperation {

          Alamofire.request("https://testurl.com\(device)").responseJSON { response in

                if let json = response.result.value {
                     //do something with json here
                    }
                 }
               }
             }
```

**Comment by MiMo42** [comment]
Try lower the max concurrent operation count
`queue.maxConcurrentOperationCount = 80`
It will negatively affect the overall performance of your operation queue,
which may be the reason why you get timeouts.
Try using NSOperationQueueDefaultMaxConcurrentOperationCount

**Comment by kzhiquan** [comment]
The same issue.

**Comment by jshier** [comment]
I've seen this behavior before. I haven't fully investigated but I believe it's due to the fact that the request has started but is waiting for the underlying `URLSession` to start the associated task, which means the request times out. I suggest you batch your requests to a number perhaps slightly higher than the `URLSession`'s configuration's `httpMaximumConnectionsPerHost`, which defaults to 4 for iOS. It's generally bad practice, and will consume considerable resources, to have hundreds or thousands of outstanding requests in Alamofire.
