### ISSUE TITLE
It shows 405 Server error at first time to get result from API server, and it works fine at second time

### ISSUE THREAD

**Issue by vkcldhkd** [Alamofire/Alamofire#2430]
It shows 405 Server error at first time to get result from API server, and it works fine at second time. I've been trying to solve this issue for a month and couldn't find the solution.

I used Xcode 9.2, Swift 4, and Alamofire 4.6.

Main problem - API server logs suppose to show "POST" on http method. Howerver it shows only "ST" on http method. (This is the main problem.) This caused to get 405 server error.

My Source Codes using Alamofire

Alamofire.request(url, method: .post  , parameters: [“phone”:”123123”],encoding: JSONEncoding.default)
 .validate()
  .responseJSON { (response) in
  if response.result.isSuccess {
    success(response.result.value as! Dictionary)
 } else {
 LogHelper.printLog("response : \(response)")

    fail(response.result.error)
 }
}

What I have tried so far:

I added "application/json" on header => nothing changed.
I changed Alamofire versions and reinstalled it. => nothing changed.
Parameter Key change => 405 error and 500 error
Parameter value change => 405 error at first time, and success at second time request.
Alamofire econding change => nothing changed.
remove ".validate()" on Alamofire request. => nothing changed.
change to responseString from responseJSON => nothing changed.

**Comment by jshier** [comment]
It's highly unlikely this is an Alamofire issue. If the issue is client side at all it likely lives much lower down in the networking stack in `URLSession` or even CFNetwork. You should investigate using tools like HTTP proxies, to see if the request is well formed, or even something like WireShark to allow you to see the raw network traffic. Feel free to open a new issue if you find that Alamofire is responsible somehow.
