### ISSUE TITLE
File downloading issue from Amazon S3 Bucket

### ISSUE THREAD

**Issue by vipspatel22** [Alamofire/Alamofire#2455]
Hello,
I'm not able to download file from Amazon S3 Bucket storage. Please check with sample URL (https://s3.us-east-2.amazonaws.com/snipture/vipul/_59.MP4)
Also find my code 
`
let destination: DownloadRequest.DownloadFileDestination = { _, _ in
    return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
}
do{
    SessionManager.default.download(try getFullAPIUrl(apiPath), headers: ["Content-Type" : "application/octet-stream"], to: destination).downloadProgress { (prog) in
        progress?(prog)
    }.response { (responce) in
        if responce.error == nil, let path = responce.destinationURL?.path {
            block(path, true)
        }else{
            block(nil, false)
            vPrint(items: String(describing: responce.error?.localizedDescription))
        }
    }.resume()
}catch{
    block(nil, false)
}
`

**I'm able to download same file with URLSession.**

**Comment by jshier** [comment]
Unless you can point to a specific issue, or provide a project that demonstrates the issue, there's nothing we can do here. You don't even state what your issue is. If you can find a bug with Alamofire, feel free to file a new issue, follow the issue template, and attach a demo project. 

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by vipspatel22** [comment]
I wants to download file from Amazon s3 bucket storage, using alamofire framework. 
Demo link : (https://s3.us-east-2.amazonaws.com/snipture/vipul/_59.MP4)

You can able to download this file using Alamofire?

**Comment by runzedong** [comment]
> I've solve this issue by my self.

Hi vipspatel22, I hit the almost exact issue, would you like to point a way on how you resolve it?

**Comment by ibi-XuLiu** [comment]
I get the same issue can not download the file from S3 using alamofire. error code -999

**Comment by shreyadc** [comment]
I faced this issue(even in iOS 15, AlamofireImage 4.2.0). I was using af.setImage to download and set images. The images were perfectly downloading from every url, other than the images in aws s3 bucket. The s3 bucket images weren't downloading and displaying properly.
After much debugging, I see that following are the acceptable content types in AFI. 
acceptableContentTypes: ["application/octet-stream", "image/bmp", "image/gif", "image/heic", "image/heif", "image/ico", "image/jp2", "image/jpeg", "image/jpg", "image/png", "image/tiff", "image/webp", "image/x-bmp", "image/x-icon", "image/x-ms-bmp", "image/x-win-bitmap", "image/x-xbitmap"]

But the images in s3 have response content type "binary/octet-stream", so although the images are downloading perfectly and can be further retrieved from response data, they're getting AlamofireImage.AFIError.alamofireError(Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableContentType(..)) and so they are unable to set in the imageview.

AFAIK AFI should include "binary/octet-stream" in the acceptable content-type as well!
