### ISSUE TITLE
Request Failing when connected to a ipv6 network.

### ISSUE THREAD

**Issue by panduranga2016** [Alamofire/Alamofire#2459]
## What did you do?
I am using Alamofire for making networking calls, but while connected to an ipv6 network, the service call is always failing with an error.
The description of the error is 
FAILURE: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x109176510 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://exampleurl.php, NSErrorFailingURLKey=https://exampleurl.php, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}

## What did you expect to happen?
I am expecting a JSON Response.

## Alamofire Environment

**Alamofire version: pod 'Alamofire', '~> 4.5.1'
**Xcode version: Version 9.2 (9C40b
**Swift version: 4.0
**Platform(s) running Alamofire: iOS 9.3 and above, issue is on iOS 11.2.6 
**macOS version running Xcode: 10.12.6 (16G1212)

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Sounds like your DNS service can't find the domain with an IPv6, or your ISP doesn't otherwise support IPv6 connectivity. Nothing we can do about that.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
