### ISSUE TITLE
request / post parameters not making it to host

### ISSUE THREAD

**Issue by justdan0227** [Alamofire/Alamofire#2471]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Dusting off some code from 2 years ago and converting it to Swift4, I'm unable to get my parmaters to the server via a post. Thoughts?

```
        let parameters = [
            "email": email,
            "password": password
        ]
        Alamofire.request( "http://www.example.com/login.php",
                           method: .post,
                           parameters:parameters,
                           encoding: JSONEncoding.default, headers: nil).responseJSON { response in
           
                            if response.data != nil {
                                do {
                                    let json = try JSON(data: response.data!)
                                    print ("Well")
                                } catch {
                                    
                                }
```
                        

## What did you expect to happen?
parameters to get to the host.  My host logs that email and password are not found in the php script of 
```
  if ($_SERVER['REQUEST_METHOD'] == "POST") {
        $email = clean($_POST['email']);
        $password = clean($_POST['password']);
        if (empty($email)) {
            $errors[] = "Email field cannot be empty";
        }

```

## What happened instead?

the returned JSON states that email and password were not a part of the request

## Alamofire Environment

**Alamofire version:**
Latest
**Xcode version:**
9.3 Beta 4
**Swift version:**
4.4
**Platform(s) running Alamofire:**
ios
**macOS version running Xcode:**
10.13.4

## Demo Project
N/A

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
I suggest you debug your request's path through Alamofire and onto the network. You can use an HTTP proxy like [Charles](https://www.charlesproxy.com) for the second part.

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. If you do find a bug in Alamofire, feel free to open a new issue.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by justdan0227** [comment]
So sorry.. thought I was reporting a bug that the .post with parameters was not making it to the host.  I didn't see a post swift4 example with parameters in a request query.
