### ISSUE TITLE
Links do not work with trailing slash!

### ISSUE THREAD

**Issue by abdulla-allaith** [Alamofire/Alamofire#2500]
## What did you do?

Requested a url with a trailing slash e.g. "my.website.com/api/users/"

## What did you expect to happen?

Request should be successful, as the link works in Postman and response is normal.

## What happened instead?

Request returned status code 500 (using `.validate()` so fail function was run)

## Alamofire Environment

**Alamofire version:** 4.6.0
**Xcode version:** 9.0
**Swift version:** 3.0
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.12.6 Sierra

## Demo Project

I do not have a sample project.

**Comment by jshier** [comment]
A 500 error means there was an internal server error, so it seems like the server doesn't like the trailing slash. I've seen this before, mainly with MS servers. Is is possible Postman is stripping the trailing slash automatically? Otherwise you can do it yourself if you want. But given the error is a 500, this isn't an Alamofire issue.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
