### ISSUE TITLE
error   Status Code: 405. Urgent need your help！

### ISSUE THREAD

**Issue by GTMYang** [Alamofire/Alamofire#2501]
I use Moya with Alamofire.
For continuous launched the same request，I've got the following result:
result is .success(Status Code: 405, Data Length: 70)
Message is:
The requested resource does not support http method 'T'.

Urgent need your help！

**Comment by jshier** [comment]
Looks like your request is getting truncated or otherwise not getting to the server correctly. I suggest you inspect your HTTP traffic to see where that might be happening.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by Unome5548** [comment]
I'm hitting the same thing on one of my projects using Alamofire. If I use the vanilla http in swift it doesn't happen. Did this ever get solved?
