### ISSUE TITLE
multipart/form-data UploadRequest body is nil

### ISSUE THREAD

**Issue by gabors** [Alamofire/Alamofire#2536]
## What did you do?

Using AF to POST a multipart/form-data

## What did you expect to happen?

Wanted to inspect the body being sent to the server, but the UploadRequest.body is always nil.
Body is being sent, but I cannot see how it is generated to confirm it is correct.

## What happened instead?

 UploadRequest.body is always nil.

## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.4
**Swift version:** 4.1
**Platform(s) running Alamofire:** macOS, iOS
**macOS version running Xcode:** 10.13.5

**Comment by jshier** [comment]
When making a `MultipartFormData` request, or an `UploadRequest` in general, `URLSession`'s underlying `uploadTask(with:)` API is being used, which means that the task will modify your request when it's issued to include the proper body, which could be a fixed amount of data or streamed from disk or memory. Unfortunately Alamofire has very little visibility into this process, so using an HTTP proxy tool like Charles Proxy can be used to verify what you're sending is correct, if you can't do that from the server side.

**Comment by gabors** [comment]
Thanks for these suggestions. 
I was avoiding using a proxy as it’s a pita to setup with tvOS.

**Comment by jshier** [comment]
I've never done it myself, but instead of setting up a proxy at a system level, you could trying setting it up at a `URLSession` level, though the `URLSessionConfiguration`'s `connectionProxyDictionary`. I found this [documentation for the constants](https://developer.apple.com/documentation/cfnetwork/global_proxy_settings_constants) and [this thread on the Apple Developer forums](https://forums.developer.apple.com/thread/86364).
