### ISSUE TITLE
 Alamofire.NetworkReachabilityManager not  update immediately 

### ISSUE THREAD

**Issue by PrashantKT** [Alamofire/Alamofire#2540]
## What did you do?

  `  static let reachabilityManager_WifiChecker = Alamofire.NetworkReachabilityManager(host: "http://www.google.com")`

I have function which is given below 

     static func isConnectedToWiFi() -> Bool {
        return reachabilityManager_WifiChecker?.isReachableOnEthernetOrWiFi ?? false
    }

I navigate user to setting page to change the wifi  for example  let user to connect particular wifi network 
Now I have listener to app 's didBecomeActive 
in that listener i call `isConnectedToWiFi` but it is giving me false however wifi is connected successfully 

after some seconds when i call the same method now it is return true, so `isConnectedToWiFi` is not return correct value immediately 

## What did you expect to happen?

in app 's didBecomeActive  listener when i call  `isConnectedToWiFi` it should return true if wifi is connected 

## What happened instead?

in app 's didBecomeActive  listener when i call  `isConnectedToWiFi`  it returns false but after some seconds it is return true

## Alamofire Environment

**Alamofire version: 4.4**  
**Xcode version:9.3**
**Swift version:4.1**
**Platform(s) running Alamofire:ios 11**
**macOS version running Xcode:High Sierra**

**Comment by jshier** [comment]
As with `SCNetworkReability` in general, you shouldn't use the URL scheme when giving it a host to track (e.g. `google.com` instead of `http://google.com`). 

More importantly, this is not a recommended use case for Alamofire's `NetworkReachabilityManager` or `SCNetworkReachability` in general, so you may want to reconsider what you're trying to do here. 

Finally, you can track #2275 while we investigate possible subtle bugs in `NetworkReachabilityManager`.
