### ISSUE TITLE
Method Swizzling with Alamofire

### ISSUE THREAD

**Issue by kashiftriffort** [Alamofire/Alamofire#2557]
I need to do method swizzling using Alamofire with respose. I have achieve this using URLSession, however when I try to do with Alamorfire API it didn't work. Please help me in this. Below is my code for method swizzling using URLSession.

 ```
   guard self == URLSession.self else {
      return
    }
        
    let originalSelector = #selector(self.dataTask(with:completionHandler:) as (URLSession) -> (URLRequest, @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask)
    let swizzledSelector = #selector(self.mytestTaskWithRequest(request:completionHandler:))

    let originalMethod = class_getInstanceMethod(self, originalSelector)
    let swizzledMethod = class_getInstanceMethod(self, swizzledSelector)

    method_exchangeImplementations(originalMethod, swizzledMethod)
  }

@objc func mytestTaskWithRequest(request: URLRequest,completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void ) -> URLSessionDataTask {
    
    let started = Date()
    let completionHandler: (Data?, URLResponse?, Error?) -> Void = {(data, response, error) in
      if error == nil {
        DispatchQueue.main.async {
          if let tempResponse = response {
            let endDate = Date()
            let timeInterval = Double(round(1000 * endDate.timeIntervalSince(started)) / 1000)
            self.captureNetworkInfo(senderRequest: request, senderResponse: tempResponse, responseTime: timeInterval)
          }
        }
      }
      completionHandler(data,response,nil)
    }
    return mytestTaskWithRequest(request: request,completionHandler: completionHandler)
  }
```

**Comment by cnoon** [comment]
Hi @kashiftriffort,

You cannot do method swizzling in Alamofire because Alamofire is written in Swift, which doesn't support method swizzling. `URLSession` does support it directly because it is still written in Objective-C and the Objective-C runtime is what supports method swizzling.

WIth that said, method swizzling should be avoided in almost all cases, as there is generally another way to approach the problem. From what it appears in your swizzling method, you are trying to add a feature that already exists in both URLSession and Alamofire. Alamofire has the concept of a `Timeline`, and `URLSession` now supports `URLSessionTaskMetrics`. For more information, check out our [`Statistical Metrcs`](
https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#statistical-metrics) section of the README.

Best of luck! 🍻
