### ISSUE TITLE
Invalid type in JSON write (_SwiftValue)

### ISSUE THREAD

**Issue by MobileDev418** [Alamofire/Alamofire#2584]
I can't pass [JSON] into a parameter.
let logs: [JSON] = [{
"time": "2018-09-06 06:45:00",
"date": "Thursday"
}]
....
let body: Parameters = [
"key": "mobiledev418",
"logs": logs
]

Alamofire.request(url, method: .post, parameters: body, encoding: JSONEncoding.default, headers: headers)
.....

then, response is 400 Bad Request. and Invalid type in JSON write (_SwiftValue)

Please help me.

**Comment by jshier** [comment]
I don't know what the `JSON` type is in this context, so I suggest you look into how you would encode that type into the various types used by `JSONSerialization`, as that's what the `parameters` dictionary gets passed into. Just passing the `logs` value as a `Parameters` value rather than `[JSON]` should work in the mean time.
