### ISSUE TITLE
SSL Certificate Pinning with Alamofire 5

### ISSUE THREAD

**Issue by abhishekthanvi8** [Alamofire/Alamofire#2591]
Hi is there any proper documentation on this issue? I cannot use the SSL pinning way which I was using in Alamofire 4 these keywords are not found when I am doing it as the previous way (ServerTrustPolicy, disableEvaluation, ServerTrustPolicyManager, etc.) How can I use SSL Certificate Pinning with Alamofire 5? Need Urgent Help on it. Thanks

**Comment by cnoon** [comment]
Hi @abhishekthanvi8,

We don't have docs created yet for AF5 since we're still dialing in the APIs. However, you can certainly check out the [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/TLSEvaluationTests.swift#L290-L450) for how to get things up and running in the meantime.

Best of luck! 🍻

**Comment by abhishekthanvi8** [comment]
When I am using Alamofire 5 I am getting errors on these keywords ServerTrustPolicy, ServerTrustPolicyManager. these are unresolved identifiers. How to fix this?
