### ISSUE TITLE
Xcode 10 GM build failure with alamofire5 branch

### ISSUE THREAD

**Issue by cgfarmer4** [Alamofire/Alamofire#2594]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Built project using Xcode 10 GM and Carthage.

## What did you expect to happen?

Project builds and compiles fine.

## What happened instead?

Alamofire builds with Carthage but Xcode fails to build project. Build error is 
`Module 'Alamofire' has no member named 'request'`. I believe there was an abort trap error too.

## Alamofire Environment

**Alamofire version:** 5
**Xcode version:** Version 10.0 (10A254a)
**Swift version:** Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.13.6 (17G65)

This did not start happening until this PR: 

https://github.com/Alamofire/Alamofire/pull/2585

Failed Cartfile:
github "Alamofire/Alamofire" "alamofire5"

If I change my Cartfile back to the previous commit. Builds fine.
github "Alamofire/Alamofire" "d927d24f38f5b4bf3ae10fa8db4df2c5a2ef4ff2"

**Comment by jshier** [comment]
There were breaking changes in the latest version of the `alamofire5` branch (it's still in development, so this will continue to happen until we release it). The global `request` API is now inside an `AF` enum, so you'd rename `Alamofire.request` to `AF.request`.

Also, if you don't tell Carthage to build just the platforms you need, you'll likely run into the issue fixed by [this PR](https://github.com/Carthage/Carthage/pull/2561) where the build fails when trying to build for watchOS. Are you building for iOS only?

**Comment by cgfarmer4** [comment]
Ya I'm using --platform iOS. Thanks for the heads up. I'll hangout on this commit until things go stable. Cheers.
