### ISSUE TITLE
iOS 12, Xcode 10, URLSession data request is cancelled as soon as app is not in foreground with error code 53

### ISSUE THREAD

**Issue by gabors** [Alamofire/Alamofire#2607]
Hi guys, this appears to be an iOS bug, I love and use Alamofire in all my projects, and I'm a bit lost and was hoping you can help as you are likely the people who know most about this stuff.

The issue is that as you have a URLSession data request that runs long enough for the user to swipe to home or to another app, then the data request is cancelled immediately.
The following errors are logged:

`Data request is cancelled.
Task <27A08309-E01C-4F52-A7EE-6356AE4C6A8A>.<1> HTTP load failed (error code: 53 [1:53])
Task <27A08309-E01C-4F52-A7EE-6356AE4C6A8A>.<1> finished with error - code: 53`

Any help or suggestion will be highly appreciated.
The sample code below demonstrates the issue:

`class ViewController: UIViewController
{
    let defaultSession = URLSession(configuration: .default)
    var dataTask: URLSessionDataTask?

    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.run()
    }
    
    func run()
    {
        guard let url = URL(string: "https://httpbin.org/delay/5") else { return }
        print(url.absoluteString)
        
        self.dataTask = defaultSession.dataTask(with: url)
        {
            data, response, error in
            
            defer { self.dataTask = nil }
            
            if let error = error
            {
                print(error.localizedDescription)
            }
            else if let data = data,
                let response = response as? HTTPURLResponse,
                response.statusCode == 200
            {
                print("\(data.count) bytes received")
            }
        }
        dataTask?.resume()
    }
}`

This was never an issue prior to iOS 12 and what it comes down to that you can't expect an API call to complete while you briefly use the multi tasking UI on the device.
Request retry mechanism in Alamofire also doesn't seem to help.

**Comment by jshier** [comment]
This is expected behavior on iOS unless your app is granted additional background execution time by the system. This is usually done by taking a [background task](https://forums.developer.apple.com/thread/85066) but there are some other system assertions you can use as well. If you want to guarantee execution, you need to use background tasks, otherwise you're at the mercy of the system. It's possible Apple tightened or otherwise changed the background execution apps get by default in iOS 12, but this has always been the case.
