### ISSUE TITLE
I got warning : -pie being ignored. it is only used when linking a main executable. how to resolve this warning?

### ISSUE THREAD

**Issue by AgungLaksana** [Alamofire/Alamofire#2624]
here is the screenshot of the warning: https://i.stack.imgur.com/zhwLq.png
even though my app can perform as expected, and alamofire can make request perfectly, but I dont know why I get this warning

## What did you do?
Starting from Xcode 10 and Swift 4.2 I am starting to get the wat

## What did you expect to happen?
this error to disappear

**Alamofire version: 4.7.3
**Xcode version: 10
**Swift version: 4.2
**Platform(s) running Alamofire:**
**macOS version running Xcode: MacOS High Sierra

**Comment by jshier** [comment]
You'll want to regenerate your Alamofire integration and remove the "Generate Position-Dependent Executable" setting. If you're using CocoaPods, removing the previous `xcworkspace` and installing again my update the settings appropriately. Updating to the latest CocoaPods may help too. Otherwise you can manually toggle that setting on the Alamofire framework.

**Comment by AgungLaksana** [comment]
sir, I am new in iOS Development, could you please help me a little bit more, I can't find that  "Generate Position-Dependent Executable" setting, where can I find that setting? Thanks in advance
