### ISSUE TITLE
Custom session in Beta 5

### ISSUE THREAD

**Issue by githubdoramon** [Alamofire/Alamofire#2676]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to create a subclass of Session() so I can add some custom headers

## What did you expect to happen?

When I make a request, I get a response

## What happened instead?

Nothing happens after the request. When I use Session.default I can get a response, but can't customise headers... When I create a new Session(), I never get a response.

## Alamofire Environment

**Alamofire version:** 5.0.0.beta.1
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running Alamofire:** Device emulator
**macOS version running Xcode:** 10.14.2

**Comment by githubdoramon** [comment]
@jshier I gave up on subclassing it (although I was calling super). Now I just have a helper class that instantiates a session (let session = Session()), and add some headers to it.

But the strange thing is... If I just do something like Session().request it never reaches the response, but if I use the regular AF.request, it works (and it just uses the Session.default, which is a Session() right?).

Any ideas what am I doing wrong here?

**Comment by jshier** [comment]
Can you post your code? It's possible that with the new async request creation in AF5 that the session going out of scope (which is why your requests aren't working, you need to keep a reference around until at least the request is complete) stops the process before the task is even created, meaning you don't get an error like you should.

**Comment by githubdoramon** [comment]
You got it right... this was the problem. I was doing something as simple as 

`let request = Session().request("https://notavalideurl.com/").response { response in
      print(response.result)
 }`

When I changed Session() to a variable from appDelegate just to test, it worked.

**Comment by jshier** [comment]
But was your `response` closure getting called at all in that case?

**Comment by githubdoramon** [comment]
No, it wasn't... only when I changed Session to a variable

**Comment by githubdoramon** [comment]
Now... if I do this:

`import Alamofire

class AlamofireCustomSession {
  
  let session = Session()

}`

Then, in another class

`let customSession = AlamofireCustomSession()

customSession.session.request("https://sdadsaddasdsda.com).response { response in 
print(response)
}
`

It stops working... apparently it always needs to be some "global" thing?

**Comment by githubdoramon** [comment]
so... I found out that Session is calling deinit before the closure happens... I am not too good with Swift/iOS, but I imagine that the variable is not being retained or something. I guess the only proper way to do this will be to have a static Session just life AF does right?

**Comment by jshier** [comment]
Yes, like I said, you need to keep a reference to the `Session` around at least until the request completes. Usually this is implemented with a singleton, since you should be using the same `Session` instance for all requests to a single host or set of hosts that share similar configuration. 

I'll create a bug issue for there being no completion though. Previous versions of Alamofire, since the `URLSessionTask` was created immediately, would always complete since the task was cancelled. It seems like we'll need to do a little work in AF5 to pass through a specific error when the session is invalidated before the requests have created a task.

**Comment by jshier** [comment]
This bug will be tracked in #2682.
