### ISSUE TITLE
Get custom parameter when downloading image

### ISSUE THREAD

**Issue by monishpainter** [Alamofire/Alamofire#2684]
I would like to get custom parameter while download image complete which will pass during download image
My code as like below 
`        let para = ["stockIds" : 1 ,"downloadType" : "image"] as [String : Any]`
       
        HttpRequestManager.ManagerBG.download(endpointurl, method: .get, parameters: para, encoding: JSONEncoding.default, to: destination)
            .responseJSON { response in
                debugPrint(response)
                print(response.temporaryURL)
                print(response.destinationURL)
                //need para here
        }
Above method call multiple time so how can i achieve para after complete image download ?

**Comment by jshier** [comment]
I'm not sure what you mean. Where are the parameters you expect, and what format are they in? Image downloads don't usually have any parameters associated with their response bodies.

**Comment by monishpainter** [comment]
I am calling this function multiple time so if i pass custom parameter then if download complete i nee to get that parameter in completion block because i need to handle some action on completion block

**Comment by cnoon** [comment]
Hi @monishpainter,

You question, code sample, and description are very difficult to follow. I'm going to take a guess here in that I think you're trying to access the parameters passed into the function in the `responseJSON` completion closure. If that's the case, then you can simply access the `para` variable you passed into the `download` API because all variables defined in local scope are accessible inside the `responseJSON` closure.

If this isn't what you're actually asking, then I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
