### ISSUE TITLE
How do you implement a RequestAdapter in Alamofire 5?

### ISSUE THREAD

**Issue by hdrm147** [Alamofire/Alamofire#2709]
In the Alamofire 5 Beta, SessionManager has been replaced by Session. I am wondering what the procedure is now for assigning a RequestAdapter, as this was a var in Alamofire 4, but in Alamofire 5 it's now a let constant. Hence the following code:

`var session = Session()
session.adapter = AccessTokenAdapter
throws a compile-time error, "Cannot assign to property: 'adapter' is a 'let' constant"`

Alamofire version: 5.0.0.beta.1
Xcode version: 10
Swift version: 4.0
Platform(s) running Alamofire: iOS

**Comment by jshier** [comment]
In Alamofire 5 `RequestAdapter`s are set on initialization, as they aren't really safe to mutate at the session level. Additionally, in beta 2, adapters will be able to be set on a per-`Request` basis, so even more flexibility will be unlocked once that's released.

**Comment by BrianDoig** [comment]
Does this mean there is no way to set them for the default session now?  That seems to be a let which means you can't update these now.  This means you either need to change your whole app to no longer use the default session manager, or you need to pass the adapter into every network call you make.

**Comment by jshier** [comment]
Yes, it means you can't change them for the default `Session`. Instead, you create your own `Session` singleton which you use to make your requests. If you're using the singleton directly all over your codebase, this should be a simple find and replace fix, but I would suggest architecting your apps so that the `Session` isn't directly exposed to your networking consumers. I typically do this through a network controller of some kind that manages all network related actions.
