### ISSUE TITLE
Randomly getting EXC_BAD_ACCESS 0x20 while getting original request

### ISSUE THREAD

**Issue by tomzr** [Alamofire/Alamofire#2717]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

Hi, i'm randomly getting exc_bad_access error on `Alamofire/Source/Request.swift:108`, mostly while trying to print curl command

```
let request = self.sessionManager!.request(urlRequest)
print(request.debugDescription)
```

```
Request.request.getter Alamofire/Source/Request.swift:108
DataRequest.request.getter Alamofire/Source/Request.swift:372
Request.cURLRepresentation() <compiler-generated>
```
## What did you do?

Created simple get URLRequest with some custom headers

## What did you expect to happen?

print curl command

## What happened instead?

app crashes

## Alamofire Environment

**Alamofire version:** 4.8.1
**Xcode version:** 10.0
**Swift version:** 4
**Platform(s) running Alamofire:** ios 12.1.2

**Comment by cnoon** [comment]
Hi @tomzr,

There's not enough info here to go on. We'll need a sample project or something to be able to dig in further. There are some weird race condition issues buried deep within `CFNetwork` that could be the culprit here, but without a sample project there's no way to tell for sure.

If you need help debugging further, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. If you get a sample project put together, please link it to this issue and we'll happily re-open and investigate further.

Best of luck! 🍻
