### ISSUE TITLE
Ambiguous use of 'Task' error on 4.8.1

### ISSUE THREAD

**Issue by tmauricio** [Alamofire/Alamofire#2777]
Hi!

When i compile my project there are  three erros:
Ambiguous use of 'Task',
Ambiguous use of 'ResponseData' and
Ambiguous use of 'mapArray(JSONObject:)'

I have tried several things that I have read in forums such as deleting the cache with the "pod" command, cleaning the "Pods" folder, cleaning the project from the Xcode but I still have the same problem. help!

## Alamofire Environment

**Alamofire version:4.8.1
**Xcode version:10.2
**Swift version:4.2
**Platform(s) running Alamofire:
**macOS version running Xcode:10.14.4

**Comment by jshier** [comment]
`Task` and `mapArray(JSONObject:)` are not part of Alamofire. If the compiler isn't resolving `ResponseData`, you're likely not getting Alamofire imported correctly. This could be due to a variety of issues, none of which we can really debug here.

Additionally, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com).

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
