### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__SwiftValue)

### ISSUE THREAD

**Issue by Ualikhan07** [Alamofire/Alamofire#2829]
i want filter data when fetching with json,when i send all values app crashes
//1
case retailList(Int,Int)
//2
case .retailList(let cityId, let catId):
 struct Filters {
  var cityId: Int
  var categoryId: Int
  }
            
value["filter"] = Filters(cityId: cityId,categoryId: catId)
//3
case .retailList(let cityId, let catId):
  value["filter"] = [{
  value["cityId"] = cityId
  value["categoryId"] = catId
 }]

let request = javaNetworkProvider.request(.retailList(cityId, catId), callbackQueue:  Queue, progress: nil, completion: { result in
 if let value = result.value {
}

**Comment by jshier** [comment]
This type of issue is typically caused by using types that can't be converted to JSON by `JSONSerialization` in a `Parameters` dictionary. Your `Filters` struct is likely the issue. You'll need to convert its values to a dictionary in order to send them as part of a request. Or, you can update to Alamofire 5, and make the values `Encodable` and we can send them automatically.
