### ISSUE TITLE
Result: failure(Alamofire.AFError.sessionDeinitialized)

### ISSUE THREAD

**Issue by antonioreyna** [Alamofire/Alamofire#2831]
im trying to set the session configuration to AF and it says `Result: failure(Alamofire.AFError.sessionDeinitialized)`

```
let aff = Alamofire.Session(configuration: configuration)
aff.request(...
```

**Comment by jshier** [comment]
If you printed the error's `description` you see this text: 
```swift
"""
Session was invalidated without error, so it was likely deinitialized unexpectedly. \
Be sure to retain a reference to your Session for the duration of your requests.
"""
```
In essence, you need to keep a reference to your `Session` until your requests are complete, otherwise it will be deinitialized and cancel your requests. Usually this is done through a singleton or by injecting the same instance into all users from somewhere that keeps the reference alive.

**Comment by waylon-edmodo** [comment]
Can you make this prompt not to play under release. I also found this problem in my project, but I really can't find out the specific reason. The prompt will pop up occasionally. The user experience is not good.
