### ISSUE TITLE
Array<Any> as parameter

### ISSUE THREAD

**Issue by jasin755** [Alamofire/Alamofire#2835]
How Can I send `Array<Any>` as parameter in request. Alamofire accept only `[String: Any]` but `Array<Any>` is valid too. For example JSONPatch defined in RFC 6902 from the IETF uses array of commands e.g. `[{"op":"replace","path":"/isRead","value":true}]`

**Comment by jshier** [comment]
There is no way to pass `Array<Any>` values through Alamofire's automatic `ParameterEncoding` feature. In Alamofire 5 you can use pass any `Encodable` type as parameters, but since `[Any]` is not `Encodable`, you'd need a better representation to pass (like a JSONPatch representation of some kind). If you can't use an `Encodable` type, you can still manually create your `URLRequest`s and encode your `[Any]` into body data using `JSONSerialization` directly. I would encourage you to explore describing your parameters as `Encodable` types though, they really work best in Swift.
