### ISSUE TITLE
Migrate to native Swift Result enum

### ISSUE THREAD

**Issue by philtre** [Alamofire/Alamofire#2844]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

A native `Result` enum has been added to the Swift Standard Library in Xcode 10.2. 
Also, because `Error` can now conform to itself, we can use it as a concrete type in generics (eg. `Result<String, Error>`).

The native Swift `Result` differs from the Alamofire implementation in two significant ways:
1. It defines a generic constraint on the failure type
2. the `flatMap` and `flatMapError` methods do not throw but rather return a new `Result`

I propose refactoring Alamofire's implementation of `Result` so that it is implemented as a set of extensions on the native Swift implementation.

I'll be submitting a pull request shortly.

**Comment by jshier** [comment]
This has already been done as part of our work for Alamofire 5. We've removed all public `Result` extensions and left the few we need internally visible to the library.

**Comment by philtre** [comment]
I guess my question would be whether there is a need for the `AFResult` typealias when the code using the two extensions - `flatMap` and `flatMapError` - can be easily changed to use the native non-throwing methods.

Moreover, the `DataResponse` and `DownloadResponse` classes now have `flatMap` and `flatMapError` methods with a different signature than the native `Result` equivalents.

Would it be sensible to add a failure type constraint on those two classes (eg. `DataResponse<Success, Failure: Error>`) and then simply forward the `map` and `flatMap` closures to the object's `result` property?

**Comment by jshier** [comment]
`AFResult` is used heavily in our tests, and is also what we expose in our public APIs that use `Result`.

As for the mapping APIs, which the APIs don't match `Result`'s, I don't think they need to. `Result` was intentionally given a restricted API set by the Swift core team, given the considerations of life in the standard library, and I don't think we need to limit all `Result` using APIs to that case.

As to making the `Response` types doubly generic, that may have some value. Would you be willing to be together a PR making a change and exploring the impact on users? My main concern is that it adds complexity where most users don't need it, so it would be good to see some motivating examples.

@cnoon Any thoughts here?

**Comment by cnoon** [comment]
I think I could go either way with the doubly generic response types here @jshier. I get the motivation, but I agree with your point that this is most likely additional complexity for the benefit of very few. It's also a pretty big breaking change that might be a bit painful for clients to adopt.

What we do in our own internal library is remap any errors coming out of AF into our own error type. That makes the most sense if you're using a mix of your own response serializers and AF provided ones. You only want to transform the errors in one place if you have to.

I like the idea of seeing some examples. I think that could help justify making the change directly in AF rather than having clients map externally.

**Comment by philtre** [comment]
Sorry for the delay. 
I submitted a PR that hopefully addresses some of @jshier & @cnoon 's concerns. Let me know what you think

**Comment by jshier** [comment]
This has been completed!
