### ISSUE TITLE
How to print "HTTP Body" in multipart request

### ISSUE THREAD

**Issue by VivekVithlani** [Alamofire/Alamofire#2874]
Hello,

I want to print "**HTTP Body**" in the multipart request

Right now I am using this code for request and this is working fine, but what should I code for multipart request?

`print("HTTP Body : " + String(decoding: response.request?.httpBody ?? Data(), as: UTF8.self))`

I am also trying with this code but HTTP Body does not print **(blank string print)**
`print("\n\n\nResponse Debugdescription = \(response.debugDescription)\n\n\n")`

I want to print "HTTP Body" in the **multipart request**

## What did you do?

ℹ print("HTTP Body : " + String(decoding: response.request?.httpBody ?? Data(), as: UTF8.self))

## What did you expect to happen?
I want to print HTTP Body like this.
ℹ  HTTP body: foo=bar&baz[]=a&baz[]=1&qux[x]=1&qux[y]=2&qux[z]=3.  

## What happened instead?
Print blank string instead of "HTTP body: foo=bar&baz[]=a&baz[]=1&qux[x]=1&qux[y]=2&qux[z]=3"
ℹ HTTP body:.  

## Alamofire Environment

**Alamofire version:5.0**
**Xcode version:10.2** : 
**Swift version:4.2**
**Platform(s) running Alamofire:iOS**
**macOS version running Xcode:10.14.5**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

Thank you.

**Comment by jshier** [comment]
Please fill out the issue template and provide the requested information and we can help you investigate. We can reopen the issue once that's been done.

**Comment by VivekVithlani** [comment]
> Please fill out the issue template and provide the requested information and we can help you investigate. We can reopen the issue once that's been done.

Please check the updated question with a template. Please check again and solve this question asap.
I think this is a very simple question.

Thank you.

**Comment by jshier** [comment]
Without a code sample for more context I can't be sure, but if your multipart data exceeds the in-memory limit (by default 10,000,000 bytes), then it won't be printed, as it will be streamed from disk rather than attached to the `URLRequest` used for the upload. In that case an `EventMonitor` implementing `request(_ request: UploadRequest, didCreateUploadable uploadable: UploadRequest.Uploadable)` should give you the opportunity to inspect what's being uploaded.

As an aside, make sure you're running the latest Alamofire 5 beta, as there have been enhancements to `*Response`'s `debugDescription` to include both the request and response body.

**Comment by jshier** [comment]
Closing for now, feel free to update if further investigation has yielded anything useful.
