### ISSUE TITLE
DataResponse should be a failure if the http status code is not in range 200-299.

### ISSUE THREAD

**Issue by rickwierenga** [Alamofire/Alamofire#2881]
Eg: When the server returns a response 'Not Found', this response is returned as a success. The status code however, is 404 which is clearly not a success.

**Comment by jshier** [comment]
This is the role of the `validate()` APIs, which allows users to customize their response validation, including status codes. We’ve left this as a customization point both to match `URLSession`’s behavior but also to allow maximum flexibility for developers interacting with APIs that don’t necessarily follow REST best practices. It also easier to implement and use as something you add to your calls instead of something you override or remove.
