### ISSUE TITLE
How to change timeoutIntervalForRequest for Alamofire (5.0.0-beta.6) ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [Alamofire/Alamofire#2894]
> Other issues should be opened on Stack Overflow with the tag `alamofire`.
Yes, I did, I asked there, but no one answered my questions!

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

change the `timeoutIntervalForRequest` for alamofire 5

        let headers: HTTPHeaders
        headers = ["Connection": "keep-alive"]
        
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = 300
        configuration.httpShouldUsePipelining = true
        let sessionManger = Session(configuration: configuration, startRequestsImmediately: true)

        sessionManger.download(modelUrl, to: destenation).downloadProgress { Progress in
                print("Download Progress: \(progress.fractionCompleted)")
        }

## What did you expect to happen?

ℹ It should start downloading the file from the `url`.

## What happened instead?

ℹ The request stops at `sessionManager.download()` line

## Alamofire Environment

**Alamofire version:** Alamofire (5.0.0-beta.6)
**Xcode version:**  10.2.1
**Swift version:** 5
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.6

## Demo Project

ℹ 

    class func downloadModel(modelUrl: String) {
        
        let headers: HTTPHeaders
        headers = ["Connection": "keep-alive"]
        
        let destenation = Utilities.getDestenationForModel(modelUrl: modelUrl) // app support dir
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = 300
        configuration.httpShouldUsePipelining = true
        let sessionManger = Session(configuration: configuration, startRequestsImmediately: true)

        // this one stop the downloading
        sessionManger.download(modelUrl, to: destenation).downloadProgress { Progress in
            print("Download Progress: \(progress.fractionCompleted)")
        }
        // this on is working but with 30 sec timeout interval.
        //AF.download(modelUrl, headers: headers, to: destenation).downloadProgress { progress in
          //  print("Download Progress: \(progress.fractionCompleted)")
        //}
            .response { response in
                switch response.result {
                case .success(let success):
                    if let url = success?.absoluteURL {
                        FTApi.compileNewModel(url: url)
                    }
                    break
                case .failure(let err):
                    print(err)
                    break
                }
        }
    }

# Pod file:

platform :ios, '12.0'

target 'testApp' do
   use_frameworks!
   pod 'Alamofire' # Using Alamofire (5.0.0-beta.6)
   pod 'ObjectMapper' # Using ObjectMapper (3.5.0)
   pod 'AlamofireObjectMapper' # Using AlamofireObjectMapper (6.0.0)
   pod 'MBProgressHUD' # Using MBProgressHUD (1.1.0)
end

**Comment by cnoon** [comment]
Hi @Mohammed-Eliass,

Your session manager is going out-of-scope which means the progress `print` statement will never be printed. You will need to hold on to the session manager as a property somewhere in order to complete the request.

In the future, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by Svoka** [comment]
Actually, I have the same bug. But I receive 
load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled"

I think it's quite common task and should be describe properly in documentation
