### ISSUE TITLE
Alamofire 5 retry in interceptor called twice if http status code is 401, 403 ....

### ISSUE THREAD

**Issue by erkutbas** [Alamofire/Alamofire#2997]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I'm using Alamofire 5 with functions like below.

```swift
init() {
        
        let adapter = ApiAdapter()
        let retrier = ApiRetrier()
        let interceptor = ApiInterceptor(adapter: adapter, retrier: retrier)
        let eventMonitor = ApiEventMonitor()
        
        session = Session(configuration: .ephemeral, interceptor: interceptor, eventMonitors: [eventMonitor])
        
    }
    
    func executeRequest<T: Codable>(request: URLRequestConvertible, completion: @escaping (Result<T, ErrorResponse>) -> Void) {

        session.request(request).validate().responseData { (alamofireResponseData) in
            print("ALAMOFIRE EXECUTED")
            switch alamofireResponseData.result {
            case .failure(let error):
                print("ERROR : \(error)")
                if let data = alamofireResponseData.data {
                    do {
                        let dataDecoded = try JSONDecoder().decode(ErrorResponse.self, from: data)
                        completion(.failure(ErrorResponse(returnMessage: dataDecoded.returnMessage, status: false)))
                    } catch let error {
                        print("error : \(error)")
                        completion(.failure(ErrorResponse(returnMessage: error.localizedDescription, status: false)))
                    }
                } else {
                    completion(.failure(ErrorResponse(returnMessage: error.localizedDescription, status: false)))
                }
            case .success(let data):
                print("SUCCESS")
                do {
                    let dataDecoded = try JSONDecoder().decode(T.self, from: data)
                    completion(.success(dataDecoded))
                } catch let error {
                    print("error : \(error)")
                    completion(.failure(ErrorResponse(returnMessage: error.localizedDescription, status: false)))
                }
            }
            
        }.resume()
        
    }

class ApiRetrier: RequestRetrier {
    
    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        print("\(#function) : request : \(request), retryCount : \(request.retryCount)")
        
        completion(.doNotRetry)
    }
}
```

ℹ I expected retry called once because I've called retry with completion(.doNotRetry). However, it called itself twice.

ℹ However, it called itself twice.

**Alamofire version:** 5. 
**Xcode version:** Version 11.2
**Swift version:** 5
**Platform(s) running Alamofire:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Do you have a URL that triggers the behavior? What is the response that triggers it? Please provide more details.

**Comment by erkutbas** [comment]
> Do you have a URL that triggers the behavior? What is the response that triggers it? Can you provide a demo project? Please provide more details.

Thanks a lot, I found the answer in this link - https://github.com/Alamofire/Alamofire/issues/2562

**Comment by jshier** [comment]
I can replicate this behavior using `httpbin.org`. 

By default, since the 401 response doesn't include any body data, response serialization fails, which triggers retry.

With `validate()` in the mix, I see two retries, both of which state they're due to the 401 response. However, this may be a bug, as it seems like one of them should be the serialization error and the other the 401 error. While I think it makes sense for this case to trigger twice, it's important that the error reported is accurate in both cases, so this requires more investigation.

**Comment by jshier** [comment]
Thinking about it more, I'm pretty sure this is a bug, as a failure in `validation` should only retry once, as we should never see the serialization failure at all.

**Comment by cnoon** [comment]
From the code sample above posted, it shouldn't even retry. It should just hit the retrier which tells the session `.doNotRetry`. Then it should be handed to the serializers which will essentially just no-op and keep the error intact. Then, since there's still an error associated with the request, it should go back to the retrier a second time to see if it should be retried. Again, it will hit the `.doNotRetry` case and the final completion will be called.

Isn't this all the correct behavior? I think what's getting confusing in this thread is calling hitting the retrier a retry. I'd also say that `validate()` can retry as many times as the client wants if they build their retrier to do so.

**Comment by jshier** [comment]
@cnoon Thanks, that explains things a lot better. I guess I was thrown off by the 401 error being passed through the serializer unchanged. It makes sense that, with serializer trigger retry, we can have scenarios where the same error asks for retry more than once.

**Comment by wlisac** [comment]
I encountered this behavior today and I found it surprising.

Is there a way for the `RequestRetrier` to know how many times it has been asked if it wants to retry a request?

In the (naive) example below, there doesn't appear to be a way to only call `repairSessionAsync ` once per request since the `RequestRetrier` is called twice with a `retryCount` of `0` both times.

```swift
func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
    // Retry 401s one time
    if request.retryCount == 0 {
        repairSessionAsync { result in
            switch result {
            case .success:
                completion(.retry)
            case .failure(let error):
                completion(.doNotRetryWithError(error))
            }
        }
    } else {
        completion(.doNotRetry)
    }
}
```
