### ISSUE TITLE
Unsupported URL upon a GET request

### ISSUE THREAD

**Issue by mado-bohsali** [Alamofire/Alamofire#3001]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Invoked a GET request 

## What did you expect to happen?

ℹ AFDataResponse object

## What happened instead?

ℹ failure(Alamofire.AFError.sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1002 "**unsupported URL**" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=ec2-3-85-233-54.compute-1.amazonaws.com/delivery, NSErrorFailingURLKey=ec2-3-85-233-54.compute-1.amazonaws.com/delivery, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <CE6EF9EA-B511-46BA-B051-F74DF7482DDA>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <CE6EF9EA-B511-46BA-B051-F74DF7482DDA>.<1>, NSUnderlyingError=0x600002a7ec40 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}})) 

## Alamofire Environment

**Alamofire version:5.0.0-rc.3
**Xcode version:11.2
**Swift version:5
**Platform(s) running Alamofire:5.0.0-rc.3
**macOS 10.15.2 running Xcode:11.2

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
<img width="544" alt="Screenshot 2019-11-17 10 37 38" src="https://user-images.githubusercontent.com/18421260/69005214-7c2e3900-0927-11ea-88df-039cd05193d2.png">

**Comment by jshier** [comment]
This is a system error, not an Alamofire error. It appears your URL doesn't have a scheme, so that's likely why it's invalid.

Additionally, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com).

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
