### ISSUE TITLE
Deprecation UIWebView

### ISSUE THREAD

**Issue by vcapilladeveloper** [Alamofire/Alamofire#3005]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have uploaded a version of my app on iOS with afnetworking as a dependency. My application does not use UIWebView and apple reports that "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information."

## What did you expect to happen?

An update of the UIWebView+AFNetworking to use WKWebView

## Alamofire Environment

**Alamofire version:3.2.1
**Xcode version:Xcode 11.2
**Swift version:Swift 5
**Platform(s) running Alamofire:iOS
**macOS version running Xcode: 10.15.1 (Catalina)

**Comment by jshier** [comment]
Alamofire doesn’t use `UIWebView`.

**Comment by Alexdelgadodiaz** [comment]
Hello there, I am investigating this because I am going through the same issue and I have followed this trick :

```
cd ~/Library/Developer/Xcode/Archives/<date>/myapp.xcarchive/Products/Applications/myapp.app

nm myapp | grep UIWeb
for framework in Frameworks/*.framework; do
  fname=$(basename $framework .framework)
  echo $fname
  nm $framework/$fname | grep UIWeb
done
```
and Alamofire is one of the libs that appear in the list. How is this possible to be happening if as you say, UIWebView isn't in it? 

https://stackoverflow.com/questions/57722616/itms-90809-deprecated-api-usage-apple-will-stop-accepting-submissions-of-app

**Comment by jshier** [comment]
Feel free to check our repo, we don't use it at all.
