### ISSUE TITLE
Download progress broken when loading gzip compressed content

### ISSUE THREAD

**Issue by Querschlag** [Alamofire/Alamofire#3009]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Downloaded a file with `Content-Encoding`: `gzip`.

## What did you expect to happen?

The progress should not stay at `0.0` and then jump to `1.0` 

## What happened instead?

It did.
I was able to verify this by disabling Gzip compression. After that the progress worked fine.

## Alamofire Environment

**Alamofire version:** `5.0.0-rc.2`
**Xcode version:** `11.0`
**Swift version:** `5.0`
**Platform(s) running Alamofire:** `iOS 13.1.2`
**macOS version running Xcode:** `macOS Catalina 10.15.1`

**Comment by jshier** [comment]
Alamofire relies on the underlying [`URLSessionDownloadTaskDelegate`](https://developer.apple.com/documentation/foundation/urlsessiondownloaddelegate) methods to update progress during the download. This usually relies on the `Content-Length` header being present in the response. Since you have control over the server, it would be interesting to see if the `gzip` version of the download contains the header while the non-`gzip` version does not. Could you check that?

**Comment by Querschlag** [comment]
I tested and `Content-Length` is present in both cases - when `Content-Encoding` is set to `gzip` and also with disabled Gzip compression.

**Comment by jshier** [comment]
Another factor may also be overall size. If the download is small enough, there will be no progress callbacks. How much data are you downloading when gzip is active?

**Comment by Querschlag** [comment]
My test sample is pretty big. `Content-Length`reads `1192308`.

**Comment by Querschlag** [comment]
I dug into this and was able to reproduce this with a plain `NSURLSession` implementation.
The problem is with `func urlSession(URLSession, downloadTask: URLSessionDownloadTask, didWriteData: Int64, totalBytesWritten: Int64, totalBytesExpectedToWrite: Int64)` not returning the correct `totalBytesExpectedToWrite` from the `Content-Length` as the value is always `-1`.

**Comment by jshier** [comment]
Thanks for the investigation. It's unfortunate this is bugged but it good to know for sure.
