### ISSUE TITLE
Alamofire 5 URLError

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#3028]
I'm using _Alamofire 5.0.0-rc.3_.
_In 5.0.0-beta.6_ it was ok.

Example:
Before Alamofire returned the `Error` that i could cast to `URLError`. And then check if it `URLError.Code.notConnectedToInternet` or not.
Now Alamofire returns an `Error` as `NSError`. That looks like "_Error Domain=Alamofire.AFError Code=13 "URLSessionTask failed with error: Not Connected to the internet_.""

Why and how to cast it as URLError?

**Comment by NikKovIos** [comment]
Now Alamofire handle any error and wrap it. Found URLError in:

```
if let afError = error.asAFError {
            switch afError {
            case .sessionTaskFailed(let sessionError):
                if let urlError = sessionError as? URLError {
```

**Comment by danielsaidi** [comment]
This is not a good change, given our architecture. We have a domain layer that does not know anything about AF, where we check for raw error characteristics, much like the disconnect you mention above. The new AF structure means that we can't have this logic in domain, since it must also take AF errors into consideration.

**Comment by maxx-cyber** [comment]
It is ridiculous :(

**Comment by OhadMaor** [comment]
In version 5.6.1 you can actually do it using:
`error.asAFError?.underlyingError`
and of course you can cast it to `NSError` if you need:
`error.asAFError?.underlyingError as? NSError`
