### ISSUE TITLE
Authenticate NTLM works with invalid credentials

### ISSUE THREAD

**Issue by jsuske1985** [Alamofire/Alamofire#3034]
Hello,

I am having an issue with authenticate NTLM credenitals, when I use valid credentials, it works, but when I use invalid credentials it does not fail, it works as the same as it would with valid credentials. This is only the case when I enter valid credentials first. Is there away to clear the credentials or what am I doing wrong here? Here is my code:

```
func loginUser(_ username: String, password: String, completion: @escaping (_ result: Bool) -> Void)
    {
        
        let user = username

        let password = password

        let url = webservice

        let credential = URLCredential(user: user, password: password, persistence: .none)

        let headers = ["Accept": "application/json;odata=verbose", "Content-type": "application/json;odata=verbose"]
        
        Alamofire.request(url, method: .get, headers: headers).authenticate(usingCredential: credential).responseJSON {
                (response) in

                print(response.result)
            
                switch response.result {
                    
                case .success:
                    if let value = response.result.value {

                        completion(true)
                    
                    }else{
                        
                        print("There is error in the server response")
                        
                        completion(false)
                    }
                    
                case .failure (let error):
                    
                    print("The NTLM request error is: ", error.localizedDescription)
                    
                    completion(false)
                    
                }

            }
        
    }
```

**Comment by jshier** [comment]
Fundamentally, you need to investigate whether authentication is actually being performed here, because it's not clear whether that's true or not. NTLM authentication isn't something Alamofire tests specifically, so we rely on the functionality from `URLSession`. Setting the appropriate break point in Alamofire's [handling of authentication challenges](https://github.com/Alamofire/Alamofire/blob/hotfix/Source/SessionDelegate.swift#L260), or checking server or proxy logs, would help you determine whether you're actually authenticating at all.

Second, I don't think Alamofire 4 automatically supports NTLM authentication, as it's one of the methods that calls the `URLSession` delegate method, rather than the task delegate, so there's no way for us to provide the credential. You can get around this by implementing the `sessionDidReceiveChallengeWithCompletion` closure on the `SessionManager`, you just need to be careful to copy in the existing code from the delegate to make sure other challenges are handled normally, and provide your credential. Alamofire 5 should handle all of this on a per-`Request` basis automatically.

Finally, I think StackOverflow is likely your best bet for finding a solution to this issue, so I'm closing it here. If the StackOverflow discussion reveals a larger Alamofire issue, feel free to update this issue with any additional details.
