### ISSUE TITLE
Enhancement - blanket curl representation for every request  in sessionmanager

### ISSUE THREAD

**Issue by 8secz-johndpope** [Alamofire/Alamofire#3135]
I add one line into the codebase 
print(request.cURLRepresentation())

it's not possible to do this dynamically - but it's incredibly useful when I want to hit the api with a request using the terminal.

If there was a flag we could trigger - then this maybe very helpful to others too.

```swift
    @discardableResult
    open func request(_ urlRequest: URLRequestConvertible) -> DataRequest {
        var originalRequest: URLRequest?

        do {
            originalRequest = try urlRequest.asURLRequest()
            let originalTask = DataRequest.Requestable(urlRequest: originalRequest!)

            let task = try originalTask.task(session: session, adapter: adapter, queue: queue)
            let request = DataRequest(session: session, requestTask: .data(originalTask, task))

            delegate[task] = request

            if startRequestsImmediately { request.resume() }
if debugPrintCurl {
 print(request.cURLRepresentation())
}      
            return request
        } catch {
            return request(originalRequest, failedWith: error)
        }
    }


```

**Comment by jshier** [comment]
You can add a `cURLDescription` closure to any request and it will be fired as soon as the description is available. No need to produce it in our request pipeline.

```swift
AF.request(...).cURLDescription { print($0) }.response(...)
```

**Comment by johndpope** [comment]
Neat. This doesn’t appear to be documented anywhere. it also doesn’t allow enmasse. All I’m asking is a Boolean flag. I have dozens of end points and adding this and removing this for AppStore would be a pain. While the code is beautiful/ consider it’s tangled.

**Comment by jshier** [comment]
It's documented in our [Usage documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#curl-command-output). In order to efficiently deal with getting the descriptions from the requests you want, I would suggest unifying your request pipeline so that all of your requests flow through the same creation methods. Not only would that allow you to customize all of your requests the way you want but is generally a better idea so that you know all of your requests are being created the same way. Alternatively, you can use our `EventMonitor` protocol to see when `Request`s are created and immediately print their cURL descriptions then. For example, the `ClosureEventMonitor` that come with Alamofire would let you do it rather easily:

```swift
let monitor = ClosureEventMonitor()
monitor.didCreateRequest = { request in
    request.cURLDescription { print($0) }
}
let session = Session(..., eventMonitors: [monitor])
```

**Comment by 8secz-johndpope** [comment]
that seems more suitable - thanks
