### ISSUE TITLE
Network link conditoer 100% Loss problem

### ISSUE THREAD

**Issue by RoeeNadam** [Alamofire/Alamofire#3139]
Hello I have a problem in Alamofire 5.0.5 iOS,
when I try to check 100% Loss connection to internet.

![Screen Shot 2020-03-31 at 13 16 12](https://user-images.githubusercontent.com/16390768/78015309-eb924b80-7351-11ea-8654-bb812151e576.png)
![Screen Shot 2020-03-31 at 13 16 37](https://user-images.githubusercontent.com/16390768/78015321-edf4a580-7351-11ea-869b-23bf0e385a8e.png)

in isReachable I get "true" instead of "false"

what can be the problem ?

**Comment by jshier** [comment]
Apple's network reachability framework, exposed through our `NetworkReachabilityManager`, is not a foolproof system, so it shouldn't be relied on to properly detect connectivity on a moment to moment basis. This is especially true when running the link conditioner, since that's basically fakes certain network conditions which may or may not impact reachability. Apple's, and ours, recommendation is to perform your requests without a reachability precheck and only check reachability if you want to inform user errors. Use the notification to see when the system comes back online if you need.
