### ISSUE TITLE
Extend cancelAllRequests method

### ISSUE THREAD

**Issue by tfonfara** [Alamofire/Alamofire#3190]
## What did you do?

Updated to latest version 5.2.0

## What did you expect to happen?

I want to be able to cancel *some* (not all) previously started requests.

## What happened instead?

I've noted this newly introduced note: `This instance should **NOT** be used to interact with the underlying URLSessionTasks. Doing so will break internal Alamofire logic that tracks those tasks.`
Previously I used the way that is described here to cancel requests: https://github.com/Alamofire/Alamofire/issues/1703
This doesn't seem to be the way to go any longer. I've noticed `cancelAllRequests` method. So my suggestion would be to either make `activeRequests` public or to introduce a filter option that's used in `cancelAllRequests` method, like this:
```
public func cancelAllRequests(completingOnQueue queue: DispatchQueue = .main, isIncluded: ((Request) -> Bool)? = nil, completion: (() -> Void)? = nil) {
    rootQueue.async {
        var requests = self.activeRequests
        if let isIncluded = isIncluded {
            requests = requests.filter(isIncluded)
        }
        requests.forEach { $0.cancel() }
        queue.async { completion?() }
    }
}
```

## Alamofire Environment

**Alamofire version: 5.2.0**
**Xcode version: 11.4.1**
**Platform(s) running Alamofire: iOS**

**Comment by jshier** [comment]
You're right, an API that operates on the `activeRequests` would be a good idea, in addition to the `cancelAllRequests` API. Rather than any sort of filtering API, just providing a closure which would enumerate the `activeRequests` should be flexible enough for any use on all requests.

You can keep your existing logic, as cancelling tasks directly will work, you just lose out on Alamofire's `manuallyCancelled` error and the proper `isCancelled` state.

**Comment by jshier** [comment]
@tfonfara Take a look at #3200 and let me know what you think.
