### ISSUE TITLE
override sessionDidReceiveChallenge method to bypass server trust issue in Alamofire5

### ISSUE THREAD

**Issue by abhishekkharwar** [Alamofire/Alamofire#3263]
Hi all we were using alamofire 4.9.1 before and recently i have upgraded to Alamofire 5 and with that we are facing bellow error

The certificate for this server is invalid. You might be connecting to a server that is pretending to be “XXX.XXX.XX.X” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?,

In Alamofire 4.9.1, we had resolve same issue by override didReceive challenge method as bellow

```
delegate.sessionDidReceiveChallenge = { session, challenge in
               var disposition: URLSession.AuthChallengeDisposition = .performDefaultHandling
               var credential: URLCredential?

               if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                   disposition = URLSession.AuthChallengeDisposition.useCredential
                   credential = URLCredential(trust: challenge.protectionSpace.serverTrust!)
               } else {
                   if challenge.previousFailureCount > 0 {
                       disposition = .cancelAuthenticationChallenge
                   } else {
                       credential = WebAPIManager.manager.session.configuration.urlCredentialStorage?.defaultCredential(for: challenge.protectionSpace)
                       if credential != nil {
                           disposition = .useCredential
                       }
                   }
               }
               return (disposition, credential)
           }
```

**Comment by jshier** [comment]
This is essentially equivalent to using the `DisabledTrustEvaluator`, but that's a bad idea. Like the code you posted, it accepts any server trust as valid, even those from other domain or unexpected certificates, so I would suggest not using it. Instead, if your production server has an invalid certificate, you should fix the certificate if you can. If you can't do that, you should, instead of accepting all trusts, which is a security issue, pin the server's certificate directly. That way you at can at least be sure you're connecting to the right website with the right certificate.
