### ISSUE TITLE
Any improvements on Request retrier for fetching the response data -- Response data in RequestRetrier #1950

### ISSUE THREAD

**Issue by Laxmanraju** [Alamofire/Alamofire#3296]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire version:**
**Xcode version:**
**Swift version:**
**Platform(s) running Alamofire:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
`RequestRetrier`s can access any `Data` downloaded by a `Request` by accessing the `request` variable passed to the required method. However, I would suggest, if you need to parse that data, to do so in a custom serializer and passing the resulting value along in the error that you need to retry, rather than doing it in the retrier itself.

In the future, please fill out the issue template.
