### ISSUE TITLE
Continually retrying with RequestRetrier makes memory go up with every retry.

### ISSUE THREAD

**Issue by be-bert** [Alamofire/Alamofire#3364]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

When using a `RequestRetrier` to continually retry a failed request, the memory usage continues to go up in the application until a successful request happens.

Here is a Stack Overflow [link](https://stackoverflow.com/questions/64944667/how-to-retry-url-requests-indefinitely-until-success-with-alamofire-5) for a basic setup to recreate.

## What did you expect to happen?

The memory should not continue to grow when the retry handler is executed.

## What happened instead?

The memory footprint increases as retries happen, and seems to clear on success.

## Alamofire Environment

**Alamofire version: 5.4.0**
**Xcode version: 12.2**
**Swift version: 5**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.15.7**

## Demo Project

[RetryAlamofire.zip](https://github.com/Alamofire/Alamofire/files/5578334/RetryAlamofire.zip)

**Comment by jshier** [comment]
Profiling in Instruments this seems like expected behavior, as Alamofire `Request`s accumulate all of the underlying `URLRequest`s, `URLSessionTask`s, and `HTTPURLResponse`s from every retry within a single request. It's deallocated once the `Request` is deallocated. You can control this growth through the proper use of retry timers and limits. That is, you should only retry using a timed falloff (as Alamofire's `RetryPolicy` does) and should only retry for a limited number of attempts. 

Feel free to investigate further and open another issue if you find memory leaks or other bits that Alamofire shouldn't be holding onto during retry, otherwise this appears to be expected behavior.
