### ISSUE TITLE
DownloadRequest with Http caching, 304 not modified

### ISSUE THREAD

**Issue by dabaicaifen** [Alamofire/Alamofire#3405]
## What did you do?
1. Uses `DownloadRequest` for a large file download. 
2. It is working for the first time.
3. The second time, the server gives a 304 response because there's no modification on the file.

## What did you expect to happen?
`DownloadRequest` handles the 304 code properly. 
1.  If with option `.removePreviousFile`,  `DownloadRequest` should do nothing.
2. If without option `.removePreviousFile`, `Alamofire` didn't throw any error.

## What happened instead?

1.  If with option `.removePreviousFile`,  `DownloadRequest` should do nothing.
2. If without option `.removePreviousFile`, `Alamofire` didn't throw the following error:
    ```
     Failed with error: Error Domain=NSCocoaErrorDomain Code=516, "....tmp" couldn't be moved to "..." because an item with the same name already exists.
    ```

## Alamofire Environment

**Alamofire version:** 5.4.1
**Xcode version:** 12.4
**Swift version:** 5
**Platform(s) running Alamofire:** iPhone 12 simulator, iOS 14.4
**macOS version running Xcode:** Catalina 10.15.7

**Comment by jshier** [comment]
I'm not sure I'd expect 304 responses to downloads to work correctly, as there's no way for the underlying `URLSession` to know you've downloaded and moved a particular file. 

But can you describe the behavior you're seeing in more detail? If there's already a file, downloading another file without `.removePreviousFile` is expected to throw an error.

**Comment by VaslD** [comment]
Although the specification doesn't explicitly require this, but a `304` should be generated almost **only** if the client actively checks/asks for it, such as sending a conditional request with `If-Modified-Since` or `If-None-Match`.

Which means unless (A) you already have the cache (downloaded file) somewhere, **and** (B) know the state of it (e.g. last modification, checksum, entity ID, etc.), **and** (C) actively asks the server if you can get a `304`, the server should **not** just hand out `304`s to random download requests. And if you already have A+B+C, Alamofire should tell you no different than it currently does (that your A is good enough).

It seems there is either some custom-tweaked business logic on the problematic server, or the app generating this issue is expecting something a little different than widely used HTTP standards.

**Comment by decazuk** [comment]
@dabaicaifen, You should determine download behavior by yourself, you can check response status code in  
`public typealias DownloadFileDestination = (
        _ temporaryURL: URL,
        _ response: HTTPURLResponse)
        -> (destinationURL: URL, options: DownloadOptions)`
and return proper DownloadOptions.

**Comment by jshier** [comment]
Given the solutions provided here and the lack of a generalizable implementation, we're going to leave this to users to implement outside Alamofire, barring new suggestions. Thanks for everyone's input.
