### ISSUE TITLE
suspend and resume download requests for large files

### ISSUE THREAD

**Issue by balusu-murali** [Alamofire/Alamofire#3434]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

When i cancel a download request (downloading a large file to disk) - this request produces resumeData with the data downloaded so far - but I would like a responseURL with the URL of the file with the partially downloaded data. I plan to use the responseURL serializer at the end to never load the entire data in memory - but if I want to suspend and resume downloads - then this is forcing me to load the data in memory.

## Feature Request

I think we should have a feature with responseURL that points to a file containing the partial data downloaded so far.

## Value to Alamofire

without having this - it is very hard to suspend and resume requests to download large files.

**Comment by jshier** [comment]
Unfortunately the only way to do this would be to parse the cancellation data, which is an internal format that isn't officially specified. Given that fact it doesn't seem like an appropriate feature for Alamofire since it would depend on `URLSession` internals.

I am a bit confused about your loading situation here though. You don' need to manually load the file in order to not read it into memory, that's already possible through the default `.response` method on `DownloadRequest`. It's only the build in serializers that read everything into memory. Creating your own that doesn't do that would be the recommended way forward.

**Comment by balusu-murali** [comment]
regarding response serializer: i'm fine with using the responseURL serializer - so no questions on that.

my main point is about suspending and resuming download without resumeData but using a resumeURL - since resumeData could be large for large files? is there a way I could achieve this now? like write data in chunks to custom files or something?
@jshier please let me know. any suggestions/pointers would help..

**Comment by jshier** [comment]
No, that's not how `resumeData` works. `resumeData` is a serialized representation of the information needed to resume a download, including things like the current `URLRequest`, the byte range downloaded and the original size, and the `URL` to the partial data on disk. It does not include the partially downloaded data.

**Comment by balusu-murali** [comment]
makes sense. thank you!
