### ISSUE TITLE
Client Certificate authentication with PIV card during TLS Auth on iOS

### ISSUE THREAD

**Issue by murali238** [Alamofire/Alamofire#3507]
As of now we are unable to do client certificate authentication with PIV card during TLS handshake.

we have NSURLAuthenticationMethodClientCertificate call back in the session delegate method but it expects SecIdentity(cert+private key)along with the public part of the certificates.

It will be good if support will be extended to PIV smart cards to do TLS mutual Authentication.

**Comment by jshier** [comment]
That sounds like a feature request for Apple, or something to build yourself. I'm not familiar with the CryptoTokenKit framework you'd use to extract certificates from smart cards, but it appears you can get the certificate `Data` from them, which you would then need to turn into a `SecIdentity` value, which may or may not be possible. You would then create a `URLCredential` using `URLCredential(identity:certificates:persistence:)`.

It's unlikely we'd ever build something like this into Alamofire itself due to its niche applicability, complex and risky implementation, and difficulty of reliably testing it. If you can find a way to solve these issues reliably, please let us know and we may be able to reconsider.
