### ISSUE TITLE
Retry method of RequestRetrier called again after doNotRetry

### ISSUE THREAD

**Issue by lionhylra** [Alamofire/Alamofire#3524]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Retry failed request. Just run the sample project.

## What did you expect to happen?

retry method called 5 times and it prints:
Retry Count: 0
Retry Count: 1
Retry Count: 2
Retry Count: 3
Retry Count: 4

## What happened instead?

Retry Count: 0
Retry Count: 1
Retry Count: 2
Retry Count: 3
Retry Count: 4
Retry Count: 4

## Alamofire Environment

**Alamofire Version:** 5.4.4
**Dependency Manager:** SPM
**Xcode Version:** 13.1
**Swift Version:** 5.0
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:** 11.5.2 (20G95)

## Demo Project
[AlamofireRetry.zip](https://github.com/Alamofire/Alamofire/files/7568123/AlamofireRetry.zip)

**Comment by jshier** [comment]
This is expected. Retriers are called when a `Request` first completes in order to trigger retry *before* serializing the response `Data`, and then again *after* serialization to give the retrier one last chance based on the error coming out of the serializer. Of course, in this case the error coming out is the same that went in, the validation error, but we don't do any checking to see if the error has already been "retried". Mainly this is because we don't know whether it's possible for the serialization result to impact the retrier's logic, so we don't assume users mean to only run the retrier before or after. We should make this fact clearer in the documentation so users aren't surprised by the behavior.
