### ISSUE TITLE
Concurrency is not compatible with Mac App Store / AppStoreConnect

### ISSUE THREAD

**Issue by frogg** [Alamofire/Alamofire#3537]
Uploading an app with version 5.5 is impossible (Error Message Attached).
On 5.4.4 it works fine.

I assume this is related to async / await.

Error Message:
```
This bundle is invalid. The executable code in [ICE Buddy.app/Contents/Frameworks/libswift_Concurrency.dylib] contain unsupported content. With error code STATE ERROR.VALIDATION ERROR.90000 for id 45011870-c31a-4c30-93e7-9c7d2014dbe0
```

![image](https://user-images.githubusercontent.com/5204169/148531399-40023507-0307-4dd4-9931-9f2e58c3b680.png)

**Comment by jshier** [comment]
Yep, looks like Apple is still having issues with concurrency back deployment. This is very similar to #3529 and has the same fix: keep using 5.4.4 until Apple fixes it. You'll have to keep using older version of every library that updates to support concurrency.

**Comment by jshier** [comment]
I heard word that the macOS deployment should [now be fixed](https://forums.swift.org/t/app-store-connect-does-not-accept-back-deploy-concurrency-macos-app-that-build-by-xcode-13-2-rc/53913/22). Can anyone confirm?

**Comment by MariusDeReus** [comment]
@jshier, not sure if you mean this: but last week I still had issues when using Alamofire 5.5 and compiling on Xcode 13.2.1. Those builds crashed on macOS 10.14 and before, because the concurrency library cannot be found. 
I am using Cocoapods and have the app deployment target set to macOS 10.13. Apparently there is no way that Cocoapods can see that it needs to take Alamofire without the concurrency extension.

**Comment by jshier** [comment]
@MariusDeReus No, this is a different issue. Your issue is #3529, and the only solution there is to keep using Xcode 13.1 or Alamofire 5.4.4 until either Apple issues a fix or we can separate out the concurrency feature into a subspec for Alamofire. This issue was simply about being able to submit to the App Store. It looks like that's fixed, so I'm closing this issue.
