### ISSUE TITLE
Response Decodable with Generic and Inheritance

### ISSUE THREAD

**Issue by avjiang** [Alamofire/Alamofire#3577]
I am trying to POST a request. My Codable class inherits another class

    public class BaseObject: Codable {
       @objc public dynamic var status: String?
    }

    public class FirstChildObject<T: Codable>: BaseObject {
       public dynamic var data: T?
    }

    public class SecondChildObject<T: Codable>: Codable {
       public dynamic var data: T?
    }
    
    public class GenericObject: Codable {
       public dynamic var string: String?
    }

Issue that i face is with `SecondChildObject` i can map the response from the JSON to my generic data type. But not with `FirstChildObject` that inherits a base class

This is the JSON sent 

    {
	     "status": "success",
	      "data": {
		   "string": "test"
	       }
    }

I am calling this `AF` function

     let dataTask = self.alamofireManager.request(urlRequest,
                                              method: .post,
                                              parameters: JSONObject,
                                              encoder: JSONParameterEncoder.default,
                                              headers: headers).serializingDecodable(FirstChildObject<GenericObject>.self)
                                              
What am I missing here? Please kindly help. Thank you

    Alamofire: 5.5.0
    Xcode: 13.3
    iOS: 15.4

**Comment by jshier** [comment]
This doesn't really have anything to do with Alamofire. `Codable`'s interaction with classes and inheritance is a well known issue in Swift. If I remember correctly I believe the issue is that subclasses don't call their superclass's implementation in the synthesized implementations generate for the subclass. So you'll want to implement `Codable`'s requirements manually and call super. You can find more resources elsewhere online.
