### ISSUE TITLE
BDH - Vulnerable Library open-source library - Ruby i18n/1.8.10

### ISSUE THREAD

**Issue by LalitKY** [Alamofire/Alamofire#3594]
> ℹ During BDH scan we found that in Alamofire we are there is  Vulnerable Library open-source library - Ruby i18n/1.8.10 issue.

## What did you do?

ℹ We run bdh scan over the application. 
In Alamofire below issue arise.
Vulnerable Library open-source library - Ruby i18n/1.8.10.
I checked in https://github.com/Alamofire/AlamofireImage/blob/master/Gemfile.lock that 
i18n (1.10.0)
      concurrent-ruby (~> 1.0)
is being used which is creating the issue.

## What did you expect to happen?

ℹNo Vulnerability should arise while running BDH scan

## What happened instead?

ℹ Vulnerability (CVE-2020-7791 – impacting availability only) arises out of insufficient handling of erroneous language tags white running BDH scan

## Alamofire Environment

**Alamofire Version: 5.5.0**
**Dependency Manager: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.5.0")**
**Xcode Version: 13.2.0**
**Swift Version: 5**
**Platform(s) Running Alamofire: iPad**
**macOS Version Running Xcode: macOS Big Sur 11.6**

**Comment by jshier** [comment]
Our Ruby dependencies are only used for release deployment and are updated for release. Since we just did the 5.6.0 release, everything should be on the latest version. Additionally, since these aren't dependencies of Alamofire itself, this report is invalid.

In the future please follow our security disclosure policy by emailing security@alamofire.org first.
