### ISSUE TITLE
Alamofire 5 never call back after session request (very occasionally and randomly.)

### ISSUE THREAD

**Issue by thatsxiao5** [Alamofire/Alamofire#3602]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Our App was using AFNetworking successfully.  Recently, We want to upgrade it to Alamofire 5. as the same as the issue 3396[https://github.com/Alamofire/Alamofire/issues/3396],  our application isn't doing anything very complicated.
I use Alamofire 5 like this: 
```
  // define a custom RequestInterceptor for retry and adapt urlRequest 
  // executed just once
  session = Session(interceptor: requestInterceptor, serverTrustManager:manager)
  session.request(url, method: method, parameters: parameters, headers:headers).validate().responseJSON(completionHandler: { response in   
            // call back 
        }).cURLDescription(calling: { description in           
           // for logger  
         }).responseString { response in
            // for logger  
         }

```

## What did you expect to happen?

We expect all HTTP requests to result in the completion block being called.

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire Version: 5.4.4
**Xcode Version: 13.1 (13A1030d)
**Swift Version: Swift 5
**Platform(s) Running Alamofire: iOS 15.3.1 on iPhone13 pro
**macOS Version Running Xcode:  11.4
**Project language: mixed ObjC + Swift

**Comment by jshier** [comment]
Please keeps discussion in #3396. As stated in that issue, I've never been able to replicate this, so a project which does would be extremely valuable. Additionally, you should upgrade to Swift 5.6.1 when you get a chance, just so we can all use the same version. Also, while creating a test project you may also want to experiment with our concurrency APIs. The concurrency runtime should guarantee that the wrapping completion handlers are called once and only once, so it may be a good way to verify that things are executing as you expect.

As an aside, I suggest using an `EventMonitor` for logging rather than completion handlers, they allow you to tap into existing handlers rather than performing extra work. And you shouldn't create a `Session` per request, that's very inefficient.
