### ISSUE TITLE
Does Alamofire currently implement a background api?

### ISSUE THREAD

**Issue by wdq123550** [Alamofire/Alamofire#3690]
Does Alamofire currently implement a background api?
thanks

**Comment by CaioSym** [comment]
While Alamofire does make correct usage of DispatchQueue's to ensure the main thread is not blocked and offers a good amount of customisation options in that area it does not support background URLSessions. See:
> Alamofire does not support URLSessions configured for background use. This will lead to a runtime error when the Session is initialized.
From: https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md

**Comment by jshier** [comment]
Alamofire does not currently support background `URLSession`s. Feel free to join the discussion in https://github.com/Alamofire/Alamofire/discussions/3615 and add your requirements. 

I've experimented with adding support for background assertions but due to Alamofire's extension-only API requirement, we'd have to use the oldest and hardest to use versions of these, which makes it hard to test and ship. Wrapping your own background task management around Alamofire shouldn't be difficult, so if you just need a bit extra background processing time, that may be what you want to start with.

Real, proper background `URLSession` support will likely be largest single feature Alamofire has ever actually built. And it will be largely impossible to test in an automated fashion since tests can't actually trigger background behavior. So while it's something I'd like to investigate it may or may not ever happen, especially without greater community involvement.
