### ISSUE TITLE
[!] Error installing Alamofire using cocoapods

### ISSUE THREAD

**Issue by iHSharma** [Alamofire/Alamofire#3706]
While installing Alamofire on brand new project facing this error

pod version is 1.12.0

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/s8/xxyszzbx0nl2dr0xg9n3h_vw0000gn/T/d20230419-9782-4vr35d --template= --single-branch --depth 1 --branch 5.6.4

Cloning into '/var/folders/s8/xxyszzbx0nl2dr0xg9n3h_vw0000gn/T/d20230419-9782-4vr35d'...
warning: Could not find remote branch 5.6.4 to clone.
fatal: Remote branch 5.6.4 not found in upstream origin

**Comment by jshier** [comment]
Not sure what the issue is, but it looks like it's trying to clone a branch, but 5.6.4 is a tag. CocoaPods may look for both, I'm not sure. Either way it seems to be an issue with your CocoaPods environment or something similar. Ensure you're using `pod 'Alamofire'` but otherwise there isn't anything for Alamofire to do here.
