### ISSUE TITLE
Increase Minimum Deployment Target To Be Compatible with Xcode 14.3

### ISSUE THREAD

**Issue by LowAmmo** [Alamofire/Alamofire#3716]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Trying to lint a podspec that has a dependency on Alamofire

## What did you expect to happen?

Linting to succeed

## What happened instead?

Getting an error due to the minimum deployment target being too low

## Alamofire Environment

**Alamofire Version:** 5.6.4
**Dependency Manager:** Cocoapods
**Xcode Version:** 14.3
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 13.3.1

## Demo Project

n/a

## Suggested Improvement

Just need to increase the minimum deployment targets in the podspec. I would suggest:
* iOS - 12.0
* OSX - 11.0
* tvOS - 12.0
* watchos - 5.0

(could go a little lower (at least iOS 11.0)...but these versions are already 4 years old)

**Comment by jshier** [comment]
Alamofire tries to support at least one major version of Xcode back, so at most we'd be able to bump the minimums to those supported by Xcode 13. Additionally, we keep the CocoaPods and the Xcode project deployment targets in sync so all consumers of the framework receive the same values. This is also rather sensitive since it means Carthage (and even CocoaPods) users would see a breaking change if we were to update that deployment target. So really I'd prefer not to touch it, and users needing to ignore warnings would use the tooling to do that. For CocoaPods, you can ignore warnings while linting, or for end consumers, add a `post_install` hook to set the deployment target to what you need (I usually remove it altogether).

In the end I don't think this is something we can change without breaking some number of users (impossible to know how many) so I'm hesitant to make any change here. Make sense?

**Comment by LowAmmo** [comment]
@jshier - I guess I should add...not just linting fails...but the ability to publish to a podspec repo fails.

Setting the minimum deployment target to iOS 12.0 would 100% still support Xcode 13. Just without making this change, no one who has Alamofire as a dependency can publish an update podspec when using the current Xcode version - 14.3.

The Podfile trick absolutely works for in Alamofire is only a dependency of an Application, or if someone is just trying to build something that includes Alamofire. But, _publishing_ the updated podspec becomes impossible. 😦 

Hopefully, that helps clarify what the issue is??  Updating the deployment target really won't keep anyone from using older Xcode versions (unless they're using Xcode 9 or 8??). Also, you can't actually publish to the app store using anything other than Xcode 14, now, anyway.

**Comment by jshier** [comment]
You can allow warnings during lint and pushes using the `--allow-warnings` flag, so no one should be blocked from anything.

**Comment by jshier** [comment]
Ah, yes, that would be a much bigger issue. Looks like bumping to the iOS 11 generation should fix it. I'll do an update.

**Comment by LowAmmo** [comment]
@jshier  - Thanks! Much appreciated!

**Comment by jshier** [comment]
This has been released as 5.7.0, though it may take a while for the CocoaPods update to propagate. Thanks!

**Comment by LowAmmo** [comment]
Thanks for the quick turnaround, @jshier !

![You rock](https://media0.giphy.com/media/7aBE32jCr6lOhtuE9v/giphy.gif?cid=ecf05e47ney0561ue85n6nkpvqe802uak24bu55ka3fxsz3m&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by LowAmmo** [comment]
That's very surprising...I'd be curious are components are having issues?? (I'm guessing it's other components that have Alamofire as a transient dependency and just need to do the same thing: update their deployment targets...)

Running into MANY components out in the wild that aren't being updated very often, and this change by Apple is causing many headaches (at least for my team).

**Comment by jshier** [comment]
Given the number of dependencies Alamofire may be used in, any breaking change has to be carefully measured. Unfortunately this one is too large, as it breaks everything that uses Alamofire as a dependency and matched Alamofire's deployment targets, which is common. Given that your issue is much less common (yours is the first report in the months since 14.3 came out), and can be fixed by a simple `post_install` hook, the tradeoff is clear. Frankly, I've used a `post_install` deployment target for years now, as CocoaPods' default target is 8.0 for pods without one (like executables), which is far too low.

**Comment by LowAmmo** [comment]
Unfortunately, as soon as all those other targets start to update their components...they'll run into the same issue (since the post_isntall hooks don't work for publishing to a spec repo).

But, yeah, I see what you're saying...guess that just means that to make this change you'd have to probably do a major version update to 6.X - which does feel a bit extreme for something that feels so minor.

If nothing else...hopefully it won't be too long until you're able to update Alamofire with these changes... 😦

**Comment by jshier** [comment]
Fortunately, it doesn't seem to be the case that everyone is broken here. I was able to lint and deploy with 14.3 a few times just fine. While we can no longer test on iOS 10 due to a combination of Apple's tools and GitHub Action's available environments, but all my local testing seems to work. Do you have a small example project that's broken? This issue doesn't seem that common.

**Comment by LowAmmo** [comment]
I'll try to put together a sample project to help recreate the error that we are seeing...

**Comment by LowAmmo** [comment]
@jshier  - Got some time to make a sample project, and looks like you are correct. Even though it generates a warning, Xcode 14.3 does allow Alamofire to publish using iOS 10.0 as it's deployment target.

Turns out the issue we are seeing is one of our other dependencies targeting even lower (8.0). But, Cocoapods reports the error in a way that makes it look like all dependencies we have using unsupported deployment targets are the culprit.

So, I apologize for the trouble this caused you, but appreciate the engagement and willingness to help figure this out!

-thanks!
