### ISSUE TITLE
Alamofire 5.5  cache not working. 

### ISSUE THREAD

**Issue by sspogra** [Alamofire/Alamofire#3723]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Not found any compatible solution to do this. Please provide a working solution with code example.

## What did you expect to happen?

I want to save url response in cache and show it when user is offline.

## Alamofire Environment

**Alamofire Version:*5.5*
**Dependency Manager:**
**Xcode Version:**
**Swift Version:*5*
**Platform(s) Running Alamofire:*iOS*
**macOS Version Running Xcode:**

**Comment by jshier** [comment]
Alamofire provides no high level solution for caching outside of what HTTP provides you. So while standard HTTP caching rules should apply, forcing the use of cached data after network failures is not something that will happen automatically. At a lower level you can set the `cachePolicy` on the `URLRequest`s you create and pass to Alamofire (or as part of a `URLRequestConvertible` type you pass in) to one of the values that will use values out of the cache rather than loading, but I don't believe any of the settings will load cache values on error, as the cache doesn't know anything about error. Ultimately this is probably something you'd implement on top of Alamofire so you can control the logic yourself.
