### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by luyun** [Alamofire/Alamofire#3872]
Undefined symbols for architecture arm64:
  "_$ss8DurationV10componentss5Int64V7seconds_AE11attosecondstvg", referenced from:
      _$s9Alamofire16WebSocketRequestC18startAutomaticPing5everyys8DurationV_tF in libAlamofire.a(WebSocketRequest.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jshier** [comment]
With no other details I'll assume you're using an old build product from some other Xcode or Alamofire version, or perhaps have an active architecture issue in your project. Either way I suggest doing a clean build. Since Alamofire doesn't directly offer prebuilt products, there's nothing we can really do to help with your local build issues.
