### ISSUE TITLE
ClosureEventMonitor is not working

### ISSUE THREAD

**Issue by JunkyTang** [Alamofire/Alamofire#3910]
ClosureEventMonitor is not working. When initializing the session with ClosureEventMonitor, the callbacks in ClosureEventMonitor do not respond!

```swift

        let monitor = ClosureEventMonitor()
        monitor.requestDidParseResponse = { req, resp in
            print("requestDidParseResponse")
        }
        
        session = Session(eventMonitors: [monitor])
        
        session!.request("https://xxxxx.com/api/apis/printing/typeface", method: .get, parameters: DataTask.DataParameterType(), encoder: URLEncodedFormParameterEncoder.default, headers: nil, interceptor: nil, requestModifier: nil)
          .responseDecodable(of: DataTask.DataResponseType.self) { resp in
            print(resp.debugDescription)
          }
```

Alamofire Version: 5.10.1
Dependency Manager: CocoaPods 1.15.2
Xcode Version: 16.0
Swift Version: 6.0
Platform(s) Running Alamofire: iOS 18
macOS Version Running Xcode: 15.0.1

**Comment by jshier** [comment]
That's function in the serializer is only called when no serializer is used, due to the fact that closures can't represent the necessary generics. If you check the documentation:

> /// Event called when a `DataRequest` creates a `DataResponse<Data?>` value without calling a `ResponseSerializer`.

If you want to see the parsed generic values you need to write your own `EventMonitor` that implements `func request<Value>(_ request: DataRequest, didParseResponse response: DataResponse<Value, AFError>)`.
