### ISSUE TITLE
Headers missing after deploy

### ISSUE THREAD

**Issue by eikebartels** [Alamofire/Alamofire#405]
Hey, 

when I deploy my app as a release version the customer header will not be set.
In the dev version works like accepted. 
Strange behaviour. Any idea? 

I use iOS 7 and bigger and just drag and drop the Alamofire.swift in my project and create my instance like this 

    lazy var alamofire: Manager = {
        var defaultHeaders = Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders ?? [:]
        defaultHeaders["Accept"] = "application/json"
        defaultHeaders["Content-Type"] = "application/json"
        
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = defaultHeaders
        return Manager(configuration: configuration)
    }()

**Comment by ravelantunes** [comment]
Just for future reference: I was having the same issue, and it seems like Swift optimizer was being the cause. That's why was working on DEBUG, but when doing a release build, it would optimize the code, and for some reason the headers would be present. Disabling swift optimization fixed on RELEASE for me. Objective-c optimization was safe to leave on.
