### ISSUE TITLE
Add mimeType to Upload

### ISSUE THREAD

**Issue by steffimueller** [Alamofire/Alamofire#466]
How can I add mimeType: "image/jpeg" to my upload request?

**Comment by cnoon** [comment]
Please check out #395. I've already posted a bunch of info there and on the linked Stack Overflow question.

---

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by steffimueller** [comment]
http://stackoverflow.com/questions/30017652/add-mimetype-to-upload-using-alamofire
