### ISSUE TITLE
Get the JSON Response as String

### ISSUE THREAD

**Issue by confile** [Alamofire/Alamofire#467]
After my upload I get a JSON response. I do not want to parse it right now so I just need the JSON response as String. Do I have to use ``responseJSON`` or ``responseString`` for that?

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by confile** [comment]
Done http://stackoverflow.com/questions/30012402/get-the-json-response-as-string

**Comment by cnoon** [comment]
Getting a "Page Not Found". If you can get the link fixed, I'd be glad to help.
