### ISSUE TITLE
Header "Alamofire-Swift.h" not found in xcode6.3 iOS 8.3

### ISSUE THREAD

**Issue by raulooo** [Alamofire/Alamofire#468]
In file module.modulemap

framework module Alamofire {
    header "Alamofire-Swift.h"
}

Using Alamofire (1.2.1)
Using Bolts (1.1.5)
Using FBSDKCoreKit (4.1.0)
Using FBSDKLoginKit (4.1.0)
Using FBSDKShareKit (4.1.0)
Using SwiftyJSON (2.2.0)

--

Apple Swift version 1.2 (swiftlang-602.0.49.6 clang-602.0.49)
Target: x86_64-apple-darwin14.3.0

--

XCode Version 6.3.1 (6D1002)

--

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

pod 'Alamofire'
pod "SwiftyJSON", ">= 2.2"

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

**Comment by cnoon** [comment]
Could not reproduce running Xcode 6.3.1 and CocoaPods 0.37.0.

![alamofirepods](https://cloud.githubusercontent.com/assets/169110/7456333/83e2ce82-f238-11e4-9d35-1175dbcefcba.png)

---

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
