### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by kamoljan** [Alamofire/Alamofire#476]
Hi guys

it was working, and suddently I got the following error:

    ld: warning: ignoring file /Users/kamol/Library/Developer/Xcode/DerivedData/ShoppingXXX-dlpuiajnjtnnesfkfvqddrrirgnd/Build/Products/Debug-iphoneos/Alamofire.framework/Alamofire, file was built for armv7 which is not the architecture being linked (arm64): /Users/kamol/Library/Developer/Xcode/DerivedData/ShoppingXXX-dlpuiajnjtnnesfkfvqddrrirgnd/Build/Products/Debug-iphoneos/Alamofire.framework/Alamofire
Undefined symbols for architecture arm64:

I am using CocoaPods:

    pod 'Alamofire', '~> 1.2'

Any bug?

Best regards
Kamol

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by kamoljan** [comment]
@cnoon thank you!
