### ISSUE TITLE
There is a mistake，When some links on request 

### ISSUE THREAD

**Issue by wodetian** [Alamofire/Alamofire#481]
### There is a mistake，When some links on request 

You can try to visit the following link, will be a fatal error

see:http://store.apple.com/cn?afid=p231|camref%3A111lEF&cid=AOS-CN-Aff-PHG
```swift

Alamofire.request(.GET, "http://store.apple.com/cn?afid=p231|camref%3A111lEF&cid=AOS-CN-Aff-PHG", parameters: nil, encoding: ParameterEncoding.JSON).response { (request, response, result, error) -> Void in
            
            println("error ====  \(error)")
            
            println("request \(request)   ----  response \(response)  -----  result \(result)   error \(error) ")
            
            println(response?.MIMEType)
        }
```

Is caused by NSURL is nil, hope to improve

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
