### ISSUE TITLE
How to set the request headers params when upload the data(image,file)?

### ISSUE THREAD

**Issue by amuluo24** [Alamofire/Alamofire#490]
can you tell just for a example ,when i use upload method  ,the response all always tell me "cant find the input stream"?,thx

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
