### ISSUE TITLE
Optional string literal as parameter

### ISSUE THREAD

**Issue by tomvo** [Alamofire/Alamofire#495]
Hey Guys, 

I'm having problems passing in properties that are optional as parameters to an Alamofire POST request. 
I'm new to this so the error might be on my side but why do I get a `Could not find member .POST' when I try to pass in a parameter array that as optional values?

See the three screenshots here:

![image](http://i.imgur.com/bOqVctk.png)

![image](http://i.imgur.com/SzUBwMM.png)

![image](https://cloud.githubusercontent.com/assets/1503385/7784518/9e6c88ee-0168-11e5-9e84-4a102dbc72d9.png)

Any idea on what's going on?

Thanks!

**Comment by cnoon** [comment]
The object type of the `parameters` parameter is `[String: AnyObject]?`. Your `params` dictionary is of type `[String: String?]` which cannot be cast to the expected type. That is the problem. 

Also, you probably shouldn't be passing in a parameter if it doesn't exist. Otherwise you could always nil coalesce the `firstname` value into some default like so.

```swift
let params = {
    "firstname": first.firstname ?? ""
}
``` 

For future issues, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire` instead of creating a support issue in Github. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by tomvo** [comment]
@cnoon Allright, thanks for your response. Makes a lot of sense. Sorry about posting that here, should've read the guidelines. Cheers!
