### ISSUE TITLE
Update API Parameter Abstraction section in README

### ISSUE THREAD

**Issue by joshuatbrown** [Alamofire/Alamofire#497]
The README contains the following code snippet:

```Alamofire.request(Router.Search(query: "foo bar", page: 1)) // ?q=foo+bar&offset=50```

I found that the resulting query is not `?q=foo+bar&offset=50` as the comment indicates, but rather `?q=foo%20bar&offset=50`.

Perhaps a bigger issue is that as I'm trying to work with the [GitHub Search API](https://developer.github.com/v3/search/), I'm unable to include `+` signs in my query, and GitHub doesn't seem to like the encoded version of `+` (`%2B`), nor the encoded version of space (`%20`).

**Comment by tobiasoleary** [comment]
@joshuatbrown I believe Alamofire is handling URI encoding correctly, but it is very strange that GitHub Search API wouldn't handle decoding the URI correctly. 

You could work around this issue with the GitHub  Search API by implementing a custom encoded (see `ParameterEncoding.swift`), that wraps the URL encoded and replaces the encoded characters that the API can't handle with decoded characters (`%2B` -> `+`, `%20` -> ` `).

**Comment by joshuatbrown** [comment]
@tobiasoleary Thanks for the tip on implementing a custom encoding - I'll go that route for now. I appreciate it!

**Comment by joshuatbrown** [comment]
It looks like #167 is where this was changed. But since the `+` sign wasn't included in parameter encoded values before, should it be?

**Comment by joshuatbrown** [comment]
And suddenly, GitHub Search is working with the encoded `+` sign (`%2B`).

**Comment by tobiasoleary** [comment]
@joshuatbrown Glad GitHub Search started working for you. I've looked into your question.

After reading (When to Encode - Section 2.4 - RFC3986)[http://tools.ietf.org/html/rfc3986#section-2.4] I believe it should be encoded, since Alamofire does build the URI up from its component parts.

**Comment by joshuatbrown** [comment]
@tobiasoleary :+1: I think that issue can be put to rest, then. I still think the docs need to be updated, so perhaps I'll do that now.

**Comment by tobiasoleary** [comment]
@joshuatbrown I worry that my initial assessment is flawed. After reading [Reserved Characters - Section 2.2 - RFC3989](http://tools.ietf.org/html/rfc3986#section-2.2).

Since encoded reserved characters are not necessarily semantically identical to unencoded characters.
For example, suppose I want to search GitHub for an extensions (`MyExtension`) of some class (`MyClass`). In some languages convention dictates that you name the file the extension is in with a plus symbol (`MyClass+MyExtension.filtetype`). So I search for `MyClass+MyExtension`. 

Now if the search url is encoded as `?q=MyClass%2BMyExtension` that should indicate I want to search for the string "MyClass+MyExtension", however it the search url is `?q=MyClass+MyExtension` that should indicate I want to search for the strings "MyClass" and "MyExtension". This is according to the [RFC3986](http://tools.ietf.org/html/rfc3986).

Now the reason I believe Alamofire should not change what is currently does is many real-world web applications ignore the semantic differences. 

For example, doing the following searches lead to equivalent results:

* [https://www.google.com/#q=my+wife+is+beautiful](https://www.google.com/#q=my+wife+is+beautiful)
* [https://www.google.com/#q=my%2Bwife%2Bis%2Bbeautiful](https://www.google.com/#q=my%2Bwife%2Bis%2Bbeautiful)

Same with bing:
* (https://www.bing.com/search?q=my+dog+eats+poop)[https://www.bing.com/search?q=my+dog+eats+poop]
* (https://www.bing.com/search?q=my%2Bdog%2Beats%2Bpoop)[https://www.bing.com/search?q=my%2Bdog%2Beats%2Bpoop]

If the API you are integrating with doesn't ignore the semantic differences, then you can implement a custom encoder.

**Comment by cnoon** [comment]
Thank you for your excellent discussion here @joshuatbrown and @tobiasoleary! It is much appreciated and allows others using Alamofire to learn from you. 👍🏻

I've dug through this discussion along with PR #500 and have combined everything into PR #504. If you could take a look I'd appreciate it. I'm going to close this issue out for now. Please direct all info related to this topic to #504 from this point.

Thanks again! 🍻
