### ISSUE TITLE
Alamofire 1.2.2 issue

### ISSUE THREAD

**Issue by edasque** [Alamofire/Alamofire#498]
The following issue appeared when I updated to Alamofire 1.2.2 from 1.2.1. I have switched back and forth and confirmed it only appears in Alamofire 1.2.2.

The code is (obfuscated to protect the innocents):
```swift
        alamofireManager!.request(.GET, HTTPS_API_URL, parameters: search_parameters)
            .responseJSON { (req, res, json, error) in
                if(error != nil) {
                    NSLog("Error: \(error)")
                    NSLog("Error: \(error!.code)")
                  
                    println(req)
                    println(res)
```

and the error output is:
2015-05-27 22:06:47.840 App:[25905:152266] queryAPI at:https://api.obfuscated.org/api ->[o: json, apikey: 12345678, t: search, q: horse]

2015-05-27 22:06:47.848 App[25905:152266] Error: Optional(Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo=0x7c45b040 {NSErrorFailingURLKey=https://api.obfuscated.org/api?apikey=12345678&o=json&q=horse&t=search, NSErrorFailingURLStringKey=https://api.obfuscated.org/api?apikey=12345678&o=json&q=horse&t=search, NSLocalizedDescription=cancelled})

2015-05-27 22:06:47.849 App[25905:152266] Error: -999

<NSMutableURLRequest: 0x7f9373d0> { URL: https://api.obfuscated.org/api?apikey= 12345678&o=json&q=horse&t=search }

nil

Any idea what could be causing it? Not that I am making other request with Alamofire in the app that work without issues but have different characteristics (HTTP & POST, not HTTPS & GET). My hunch is that this this is HTTPS related, possibly? I see the error both in the simulator & on the physical device.

**Comment by mattt** [comment]
That's a failed authentication challenge. Set the `sessionDidReceiveChallenge` property accordingly. See Apple's documentation on [Authentication Challenges and TLS Chain Validation](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/AuthenticationChallenges.html) for more details.

**Comment by edasque** [comment]
Will do. Were changes made in 1.2.2 to pay more attention to auth challenges and that's what I am seeing?

**Comment by cnoon** [comment]
Here's an [example](http://stackoverflow.com/a/30416865/1342462) of how you can dig into the `sessionDidReceiveChallenge` property.

> You should **NOT** use the implementation in that thread directly since it is disabling security checks. However, it should prove useful for debugging purposes.

**Comment by edasque** [comment]
Thank you, I appreciate it.

**Comment by edasque** [comment]
@cnoon , @mattt : sorry to get back a month later, I finally had some time to try to diagnose. Trying to use that code that Christian pointed me to, it seems that the following is true: ```challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust```

I want to make sure I understand this well. Since 1.2.2 Alamofire no longer absorbs the authentication challenges but lets the developer decide how to handle them. In my case, the client is given an opportunity to question the https server certificate and the code provided by Christian ignores the challenge.

Am I right to understand that this is not necessarily a failed authentication but just an opportunity to challenge it? If it is in fact, a failed authentication, I cannot find a reason why that would be (see curl output) and would welcome a bit of help to diagnose what could be wrong in the auth. As advised, I don't want to blow past it but understand more about it so I can help fix the issue wherever it is.

**Comment by edasque** [comment]
@cnoon , @mattt could you please confirm this?

**Comment by cnoon** [comment]
Hi @edasque, I'll give you a quick description of what's happening. Please redirect further issues with this to Stack Overflow. We just don't have enough time to troubleshoot everyone's TLS handshake issues.

With that said, @mattt mentioned that you are seeing a failed authentication challenge because that's exactly what's happening. The server is initiating a TLS handshake, and iOS by default is evaluating the challenge as a failure. This can be for several different reasons, some of which can include an expired certificate, an unsigned certificate or a certificate with a different domain than the `NSURL` that was requested. These are security checks automatically provided by the iOS Security framework to make your life easier.

Since some people need explicit control over these behaviors, we have opened up the ability to override the default Alamofire behavior. That's why I posted the response that I did to show you the basics in how to go about customizing that behavior. What you need to figure out is why the auth challenge is passing through cURL and failing in the iOS evaluation.

Best of luck!

**Comment by edasque** [comment]
@cnoon thank you for your response, it provides me with leads to follow.
