### ISSUE TITLE
Upload files with parameters

### ISSUE THREAD

**Issue by ivangodfather** [Alamofire/Alamofire#499]
Theres a way to uplaod multiple images with data? 
I found this http://stackoverflow.com/questions/26121827/uploading-file-with-parameters-using-alamofire
but seems pretty outdated.

**Comment by cnoon** [comment]
It is outdated, but still stands. We are going to be adding Multipart Form Data support in the Alamofire [1.3.0](https://github.com/Alamofire/Alamofire/milestones) release. Until then, you'll want to follow the info in that thread to get started.

**Comment by ncerezo** [comment]
You may want to check this out in the meantime: https://gist.github.com/ncerezo/b1991f8dfac01cb162c0

**Comment by ivangodfather** [comment]
2 questions, fileUploader.uploadFile(request: request) seems no have a completion handler or similar, what i'm missing? do i need to do anything with that Request? And can i add images in memory like UIImages retrieved from a camera?

**Comment by ncerezo** [comment]
The method returns the Alamofire.Request, which you can chain (if you want) with a completion handler or similar. It's not required though. You can simply make the call and that will upload the file.
As for adding images in memory, I've made a quick change to support it. I've modified the sample also.

Take into account that adding NSData objects instead of files uses twice as much memory.
This method of building the multipart data creates an NSData object where it adds the contents of the request, so if you add a file it will use the memory needed by the file, but if you use a NSData object it will need that data object plus its copy in the request data object.
That is, if you add a file of 500Kb no memory is used until you send the request. It then reads the file and adds it to the NSData object where the request data is built (along with multipart boundaries, etc).
However, if you add a NSData object of 500Kb it uses those plus another 500Kb when it is added to the request data.

**Comment by morizotter** [comment]
@ncerezo
Thanks for your codes! I'm finally be able to upload to S3!
But, first, I couldn't do that. By changing the order of parameters and files, I could do that.

**Comment by ncerezo** [comment]
You're welcome!
I've updated the gist so it puts the parameters first when creating the multipart data.

**Comment by morizotter** [comment]
Thanks again!

**Comment by cnoon** [comment]
Hey everyone, I just put up PR #539 which adds support for `MultipartFormData` uploads. I would love your feedback before merging it in. Cheers.
