### ISSUE TITLE
Add method to set AuthorizationHeader to Request (proposal)

### ISSUE THREAD

**Issue by skywinder** [Alamofire/Alamofire#502]
I would like to propose to implement same functionality as `AFNetworking` methods:

```
- (void)setAuthorizationHeaderFieldWithUsername:(NSString *)username
                                       password:(NSString *)password;

- (void)clearAuthorizationHeader;
```

It's look pretty obvious for me, so I don't know why nobody implement it yet.
If you have any reason to don't do so - let me know. 

Otherwise I'm ready to create PR as soon as you approve  this enhancement.

Related with #27, #32, #99, #111, #119

**Comment by cnoon** [comment]
@skywinder we are going to extend the `request`, `download` and `upload` convenience methods to support custom headers in the 1.3.0 release. We are also going to update the `ParameterEncoding` `encode` method to return an `NSMutableURLRequest`. These two changes should make it MUCH easier to add your own authorization header to a request.

For the time being, I'd like to avoid having special hooks into the `Manager` for appending certain "special" header. Before you know it we'll be supporting a handful of them when this could (and should) be easily handled by the client.

Thoughts?

**Comment by tomj** [comment]
@cnoon [RFC2617](http://tools.ietf.org/html/rfc2617#section-2) states that
>A client MAY preemptively send the
   corresponding Authorization header with requests for resources in
   that space without receipt of another challenge from the server. 

Now it seems that given the `Authorization` headers are part of a standard they're not really a "special" case?  Just a suggestion - I'm no networking guru but on the current project I'm working on the web service won't send a challenge to a failed connection which means I had to get a little hacky to implement and felt like it should belong in Alamofire.

Also note the [prevalent usage](https://github.com/search?l=objective-c&q=setAuthorizationHeaderFieldWithUsername&type=Code&utf8=%E2%9C%93) of `setAuthorizationFieldWithUsername:password:` on AFNetworking projects on the GitHubs.

Either way thanks for your input in this great project.

**Comment by skywinder** [comment]
@cnoon Great news!
I agree, that it's not a good idea to integrate it in `Manager`. That's what about @mattt mention in #113
I think the better place to integrate this functions in `Request` class. What do you think?

And yes, after return an `NSMutableURLRequest` from `encode` (#478) it becomes easier to implement.
I'm open to discuss and ready to help with implementation of this functionality. 
Just let me know! :wink:

**Comment by cnoon** [comment]
Thank you for your feedback @tomj. I agree that `Authorization` headers are a very popular authentication mechanism. We're trying to avoid adding too many APIs around auth and want to encourage users to "think" about and "understand" what it is they are really doing. Note the 20 [issues](https://github.com/search?q=setAuthorizationHeaderFieldWithUsername+language%3AObjective-C+language%3AObjective-C&ref=searchresults&type=Issues&utf8=✓) listed around `setAuthorizationFieldWithUsername:password:`. We want to avoid confusion and make it easy to understand the difference between how a `Request` is constructed and how auth challenges are handled.

The changes I mentioned earlier are a big step in that direction. Adding an `Authorization` header should take place when the `NSURLRequest` is being constructed. Now if you start thinking about how this would work in Alamofire, it gets a bit interesting. In AFNetworking, you have the concept of a `RequestSerializer`. In Alamofire, this does not exist. You need to add the header at the time of creation, which makes things much easier to understand. This may however make things slightly less convenient, but potentially saves people from their own mistakes.

Which leads me to my next point. @skywinder I don't think it would be wise to add a `setAuthorizationFieldWithUsername:password:` on a `Request` because you cannot modify the `Request` once it has been created. It's task has already been sent to the `NSURLSession` to be executed. This is not the case if you set the `startRequestsImmediately` flag to `false` on your `Manager` instance, but the majority of users will most likely use the default value.

This means that you can only attach the Authorization header at the time of construction, which is consistent for all headers and is simple to understand. Now there may be a way to expose a class method on a `Manager` instance to make it easy to generate an `Authorization` header, such as a class method like the following (don't hold me to the method signature):

```swift
public class func authorizationHeaderWithUser(_ user: String, password: String) -> String
```

This would allow users to easily create a base64 encoded String to pass into the `request` function as an `Authorization` header. It's a similar idea to the `defaultHTTPHeaders` static property. I don't think it would be a good idea to add support directly in the convenience `request`, `download` and `upload` functions for a `Authorization` header. We're trying to keep those as light-weight as possible. Now I'm not advocating for this approach, I'm just throwing it out there as food for thought.

**Comment by allaire** [comment]
@cnoon @skywinder What I'm currently doing is manually base64 my username/password (using @skywinder's code from another issue) in my Router (`URLRequestConvertible`) and add it by doing:
`mutableURLRequest.setValue("Basic " + base64String!, forHTTPHeaderField: "Authorization")`.

Is this the preferred way? I need to do this in order to query my staging API (which is protected using HTTP Basic Auth). I would rather not call `authenticate()` on every request.

**Comment by allaire** [comment]
Also @cnoon, I thought that URLRequestConvertible was the way to go to pass individual headers for different requests? This is going to change in a future release?

Thanks!

**Comment by skywinder** [comment]
@allaire My code (https://github.com/Alamofire/Alamofire/issues/32#issuecomment-101336349) it's just a workaround.

As @mattt's mention (https://github.com/Alamofire/Alamofire/issues/113#issuecomment-56207860)
>It's not recommended that you use session configuration headers for something like `Authorization`. Instead, use a type conforming to `URLRequestConvertible` to manage authentication state and routing.

**Comment by cnoon** [comment]
@allaire, your approach is correct. You want to use the `URLRequestConvertible` to attach the header for now. In the 1.3.0 release, you will have a second option that will allow you to pass a `headers` dictionary into the `request`, `download` and `upload` global methods.

**Comment by cnoon** [comment]
@skywinder I'm going to close this issue out. We can revisit this after the 1.3.0 release if necessary. I would like to avoid specific header implementations directly in Alamofire with the exception of the `headers` parameter in those top level functions that we're adding in 1.3.0.
