### ISSUE TITLE
Failure integrating with Alamofire

### ISSUE THREAD

**Issue by jdschmitt** [Alamofire/Alamofire#509]
I am following the steps to add Alamofire to my xcode project (iOS) and it's not working. I get all the way to the last step where I choose it in Embedded Binaries and both versions are there but after I choose it, it shows up as red text in xcode and I can't use the framework.

![screen shot 2015-06-03 at 12 10 55 pm](https://cloud.githubusercontent.com/assets/1347067/7966439/b4d4897c-09e9-11e5-8929-32ba7debd111.png)

I've been copying all the *.swift files into my project to use it but that seems hacky. I'd like to target iOS 7.0 so maybe that's my only option?

XCode v6.3.2
![screen shot 2015-06-03 at 12 13 11 pm](https://cloud.githubusercontent.com/assets/1347067/7966482/f59231da-09e9-11e5-91df-aeb5e526a665.png)

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
