### ISSUE TITLE
When not supplying parameters, Content-Type header is not set

### ISSUE THREAD

**Issue by Dan2552** [Alamofire/Alamofire#515]
When doing a request like: `Alamofire.request(.GET, url, encoding: .JSON)` I would expect the `Content-Type` header to be set to `application/json`

This appears to not be the case because `ParameterEncoding#encode` will return before getting to the code that sets the `Content-Type` because of the check for parameters at the top of the method:
```swift
if parameters == nil {
    return (URLRequest.URLRequest, nil)
}
```

**Comment by jshier** [comment]
I was going to raise this issue as well since I just ran into it with a backend that required the Content-Type header to be set despite not having any body data. Technically I think Alamofire is correct, this header is unnecessary when there is no body data. However, I think poorly engineered back end services are prevalent enough that setting Content-Type all the time as a compatibility measure should be considered. Obviously it's a rather small fix, but I know there's going to be some header changes for 1.3, so I wasn't sure how I should proceed.

**Comment by cnoon** [comment]
Hi gents...thanks for the info here.

In this case, I'd say Alamofire has the correct default behavior. If no data is added to the `HTTPBody` of the `NSURLRequest`, then the `Content-Type` header should not be attached. If you do need to attach the `Content-Type` header, you can do that manually for this particular case.

Adding custom headers will also become much easier in the Alamofire 1.3.0 release. Cheers.
