### ISSUE TITLE
Unable to access singletons in URLRequest

### ISSUE THREAD

**Issue by mabril** [Alamofire/Alamofire#522]
When trying to add custom headers from a singleton, the app don't crash but also it's not continuing it's execution. I'ts very strange beaviour that happens only when accessing the singleton from the URLRequestConvertible of Alamofire.

Here the code:

 var URLRequest: NSURLRequest {
        let URL = NSURL(string: Router.baseURLString.stringByAppendingString(Router.apiPath))!
        let mutableURLRequest = NSMutableURLRequest(URL: URL.URLByAppendingPathComponent(path))
        mutableURLRequest.HTTPMethod = method.rawValue

        let sessionCode = Configuration.sharedInstance.session.code
// If debugging, after this line, it does nothing.
        
        mutableURLRequest.addValue(sessionCode, forHTTPHeaderField: "SessionCode")
        mutableURLRequest.addValue("LogitravelSpain", forHTTPHeaderField: "Application")
        mutableURLRequest.addValue("ES", forHTTPHeaderField: "Language")
        
        if let token = Router.OAuthToken {
            mutableURLRequest.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }
        
        switch self {
        case .PostSession(let parameters):
            return Alamofire.ParameterEncoding.JSON.encode(mutableURLRequest, parameters: parameters).0
        case .GetCatalog(_, let productsPerLOB, let page, let pageSize):
            return Alamofire.ParameterEncoding.URL.encode(mutableURLRequest, parameters: ["productsPerLOB":productsPerLOB,"page":page,"pageSize":pageSize]).0
        default:
            return mutableURLRequest
        }
    }

And here how I have declared the Configuration singleton:
import Foundation

class Configuration {
    
    static let sharedInstance = Configuration()
    
    var apiEndPoint: String = "http://apiq.logitravel.com/mobile"
    
    
    var session: Session = Session()
    
    init() {
        session.obtainSession()
        // TODO: Get Configuration Manager
    }
    

    
}

Anyone has the same problem?

Thanks in advance

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by mabril** [comment]
Just did what you suggested. Hete it is the link, if anyone want's to help.

http://stackoverflow.com/questions/30797242/unable-to-access-singletons-in-urlrequest-with-alamofire

Thanks.
