### ISSUE TITLE
Caching Problems

### ISSUE THREAD

**Issue by sai-prasanna** [Alamofire/Alamofire#526]
I was hosting some JSON files in a simple python httpserver. I doesnt set any caching headers.

I didnt make changes to caching policy.If i made a simple GET request , the request reaches the server first time, from next time the cache is used. Now even if the server is stopped ie unreachable,request succeds without any connection error because the cache is used , Is this intended?

The next problem is that when successful response gets returned from cache, if I call NSURLCache.sharedURLCache().cachedResponseForRequest(request), it returns NIL.

I can load from cache only if I manually store response and data returned by alamofire callback into cache again, eventhough these data were already present.

Is this problem anyway related to how NSURLSession caches data or is this some bug in way alamofire treats cache policies?

**Comment by cnoon** [comment]
Alamofire caching works as expected and leverages all the default behavior of `NSURLSession`, `NSURLSessionConfiguration` and `NSURLCache`. We recently added a large amount of tests around this behavior to prove that it does work as intended. Please check out the [CacheTests](https://github.com/Alamofire/Alamofire/blob/master/Tests/CacheTests.swift) for more information.

In the future, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire` instead of creating a support issue on Github. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
