### ISSUE TITLE
can't use manager request

### ISSUE THREAD

**Issue by sisuc** [Alamofire/Alamofire#535]
hello.

I use this code.
---
        var apiPath : String = "/api/list/"
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.timeoutIntervalForRequest = 60
        let manager = Alamofire.Manager(configuration: configuration)
        manager.session.configuration.HTTPAdditionalHeaders = ["_U" : self._token]
        manager.request(.GET, self._host + self._url + apiPath, parameters: nil)
            .responseSwiftyJSON ({ (request, response, resultJson, error) in
                if (resultJson["Success"]) {
                     //get list success
                } else {
                    println("request : \(request)")
                    println("response : \(response)")
                    println("resultJson : \(resultJson)")
                    println("error : \(error)")
                }

        })
---
And i got some problem 
---
Alamofire version 1.2.1 : No Problem
Alamofire version 1.2.2 & 1.2.3 : 
request : <NSMutableURLRequest: 0x7feb9287fda0> { URL: https://test.com/api/list/ }
response : nil
resultJson : null
error : Optional(Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo=0x7feb92c434f0 {NSErrorFailingURLKey=https://test.com/api/list/, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://test.com/api/list/})
---
response was nil
resultJson was null
Please help me what problem in this code..

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by sisuc** [comment]
oh, sorry,, i see.

please check this question ..

http://stackoverflow.com/questions/30906607/about-alamofire-version-for-use-manager?noredirect=1#comment49855938_30906607

2015-06-18 13:08 GMT+09:00 Christian Noon <notifications@github.com>:
