### ISSUE TITLE
Allow NSURLCredential persistence to be specified

### ISSUE THREAD

**Issue by jessecurry** [Alamofire/Alamofire#537]
There's currently no clear way to reset the current session preventing logout for web services that use basic auth and session storage.

```
    public func authenticate(#user: String, password: String) -> Self {
        let credential = NSURLCredential(user: user, password: password, persistence: .ForSession)

        return authenticate(usingCredential: credential)
    }
```

I'd propose adding a `persistence` parameter to the `authenticate` method or adding a method to the `Manager` to clear the current session.

**Comment by cnoon** [comment]
Hi @jessecurry, thank you for your feedback.

There is a way to reset the credential, but it is pretty hidden. You could get the credential storage and remove the credential like so:

```swift
let manager = Alamofire.Manager.sharedInstance
if let storage = manager.session.configuration.URLCredentialStorage {
    storage.removeCredential(credential: credential, forProtectionSpace: protectionSpace)
}
```

However, since this would be brutal to have to do each time and still utilize the convenience of the `authenticate` method, I think your proposal for exposing the `persistence` parameter is valid. 

I have incorporated your suggestion into cb9e11b9 and set the default value to `.ForSession`. Thus, the change is backwards compatible and still has the same default behavior as before.

Cheers 🍻

**Comment by jessecurry** [comment]
Thanks!

And thanks for the info.

**Comment by jamesallison** [comment]
I think this should be considered for re-opening - I'm using None as the persistence, however the credential still persists. Is this actual Alamofire or NSURLCredential's fault?
``` Swift
let credential = NSURLCredential(user: studentUsername, password: studentPassword, persistence: .None)
Alamofire.request(.GET, "https://api.co.uk/Default.aspx").authenticate(usingCredential: credential)
```
