### ISSUE TITLE
Application Crashes due to malloc error in Alamofire library in Request.swift class.

### ISSUE THREAD

**Issue by renish007** [Alamofire/Alamofire#547]
Greetings,

Thanks for making awesome library in Swift. Right now, I am moving code from Objective C to Swift. I am using Alamofire library for Web service calling. It is working fine but application crashes many time. I am not sure about it's library issues or something else. Please review below console Log with attached screen shot: 

Console Log:
 malloc: *** error for object 0x1700075f0: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug
(lldb) 
![crash_file](https://cloud.githubusercontent.com/assets/4044146/8392031/ac4121a4-1cf8-11e5-8d85-b096f2337b12.png)

![thread](https://cloud.githubusercontent.com/assets/4044146/8392032/ac4549f0-1cf8-11e5-9901-97f0e37ed2af.png)

Please let us know your comments. 

Thank You,
Renish Dadhaniya

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
