### ISSUE TITLE
The operation couldn’t be completed - Mac OS X

### ISSUE THREAD

**Issue by valeIT** [Alamofire/Alamofire#548]
I read [this post](https://github.com/AFNetworking/AFNetworking/issues/2314) and it seems like the error is related...

    NSErrorFailingURLKey=https://www.telize.com/geoip})getlocationOptional(Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be completed. (NSURLErrorDomain error -1001.)" UserInfo=0x600000271ac0 {NSErrorFailingURLStringKey=https://www.telize.com/geoip, NSUnderlyingError=0x600000045fd0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=https://www.telize.com/geoip})

If I do it manually from a browser it works... (No idea if related but it usually happens when I connect to a USA vpn - I'm based in europe.) Any ideas?

PS: I have it running on a background queue every x seconds and when I connect to the vpn it stops calling Alamofire from almost a minute ( internet works from the browser and any other apps). After around 5/10 minutes it works again...

**Comment by valeIT** [comment]
mmm if I use http instead of https it's a lot quicker. Still around 1 minute delay, but way less than the 10 mins I used to have o_o I'm honestly confused...

**Comment by cnoon** [comment]
The `-1001` is a timeout error which is a bit different than the AFN issue you linked. Either way, the issue you are seeing is not directly related to Alamofire with what you have provided. I would encourage you to seek additional support on Stack Overflow.

---

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by valeIT** [comment]
Will do, I'm sorry.
