### ISSUE TITLE
Error: unable to read module map contents

### ISSUE THREAD

**Issue by mozeryansky** [Alamofire/Alamofire#551]
I am having issues with installing Alamofire with cocoapods. This is the error:

error: unable to read module map contents from 'Target Support Files/Pods-Alamofire/Pods-Alamofire.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “Pods-Alamofire.modulemap” couldn’t be opened because there is no such file."

To test this I made a new Xcode project, added a Podfile containing only the content mentioned in the README and did `pod install`, opened the workspace, and performed a build.

**Comment by mozeryansky** [comment]
Turns out it was an xcode problem. Xcode was using another projects project path, even though this was a new project. Closing Xcode and deleting the xcode preferences from ~/Library/Preferences/ fixed the issue.

**Comment by liuxue0905** [comment]
There is no Preferences(dir) in ~/Library, has Preference(file).How can i do~T_T

**Comment by mozeryansky** [comment]
You don't have a Preferences directory? Are you using a Mac?

**Comment by emericspiroux** [comment]
Xcode without a mac ? Are you serious, really ? lol

**Comment by PreetidhankarIOS** [comment]
no......

**Comment by pravinslktechlabs** [comment]
hi

**Comment by pravinslktechlabs** [comment]
I have bugs in project  Workspace open search google but not exact issue Found.
So please Help ..
bellow Erroe.
Error: unable to read module map contents from 'Target Support Files/TTTAttributedLabel/TTTAttributedLabel.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “TTTAttributedLabel.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/slk/Documents/pravinData/SLK039/RxliveRedesign/RxLive Patient APP Redesign Resource(iTechputer)/ashish48-rxpatient-0f9200e812b7/Pods/Target Support Files/TTTAttributedLabel/TTTAttributedLabel.modulemap, NSUnderlyingError=0x7fa757955ca0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by vamshikpadala** [comment]
Dude, Exactly what should be deleted from ~/Library/Preferences ?

**Comment by mozeryansky** [comment]
Run `cd ~/Library/Preferences/` to go to your user preferences.
(~ means your user directory, i.e. /Users/michael/)
Run: `ls -l | grep -i xcode` to list all preference files with xcode in the name. Those are generally the preference files relating to Xcode. From there you can delete all of them or try deleting one at a time until the solution is fixed. This may not work, but it worked for me.
