### ISSUE TITLE
Cancel sometimes doesn't work

### ISSUE THREAD

**Issue by Ufosek** [Alamofire/Alamofire#563]
I have a simple request like:

```
func newRequest() {
    println("CANCEL = \(self.getTime())")
    self.request.cancel()
    
    self.request_ = request(method, url)
    validate(statusCode: [200])
        .validate(contentType: ["application/json"])
        .responseJSON { [unowned self] (_, _, json, error) in
            
            if(error?.code == NSURLErrorCancelled ) {
                println("CANCELED!")
            }
            
            println("DONE LOADING = \(self.getTime())")
            // ...
    }
}
```
As shown above, when new request is invoked, I want previous to be canceled.
And it usually works, but sometimes when previous request is about to end (there is a very short amount of time between logs), it does not.
```
(newRequest) CANCEL = 1436103465.93128
// CANCELED! SHOULD BE HERE
(previousRequest) DONE LOADING = 1436103466.08223
```
To make it work I added a var isCanceled and check whether it is set to true.
I am not sure if it works as it should (it may be too late to cancel) or it is a small bug.

**Comment by cnoon** [comment]
Hi @Ufosek, thank you for reporting your issue.

Without a full code sample, it is difficult to diagnose your issue. Additionally, the code sample you provided is canceling the `self.request` and then creating a new request on `self.request_`. I'm going to assume that that is a typo.

There should always be a slight delay between canceling a request and receiving the callback. The reason is that the request is running on a different queue. The cancellation needs to make it over to the other queue, then call back to the main queue to execute the serialization closure. This is certainly the expected behavior.

As for not receiving the callback, I would assume you have some sort of race condition occurring. Without a full code sample, it would be difficult to diagnose. Regardless, if you could post this question on Stack Overflow, it would receive much more attention. It also let's us focus more on core features and actual Alamofire issues rather than troubleshooting.

Best of luck.

---

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
