### ISSUE TITLE
Alamofire request blocking pushViewController?

### ISSUE THREAD

**Issue by tom-sparo** [Alamofire/Alamofire#565]
On a ViewController, we have in viewDidLoad an Alamofire request to a server with a callback that references self, and also a pushViewController meant to transition to another ViewController.

Unintuitively, the viewDidLoad function finishes and returns, but the pushViewController does not happen until after the Alamofire request finishes and calls the callback.

Is this expected behavior?  Why is this happening?

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
