### ISSUE TITLE
Manager always return error -999

### ISSUE THREAD

**Issue by eimantas** [Alamofire/Alamofire#584]
I create a custom `NSURLSessionConfiguration` with additional http headers. Pass it to `Alamofire.Manager(configuration:)` initialiser and make a request:

```swift
let config = NSURLSessionConfiguration.defaultSessionConfiguration()
let kcService = KeychainService()
if let accessToken = kcService[AccessTokenKey] {
    config.HTTPAdditionalHeaders = ["Authorization": "bearer \(accessToken)"]
}

let sessionManager = Alamofire.Manager(configuration: config)

sessionManager.request(.GET, "https://site/secret", parameters: nil, encoding: .URL)
    .responseJSON(options: NSJSONReadingOptions(0)) { (request, response, responseObject, error) -> Void in
    }
```

The closure always has a `request` and `error` objects, `response` and `responseObject` are always `nil`. Error object contains standard `-999` error.

Help?

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
