### ISSUE TITLE
carthage update error

### ISSUE THREAD

**Issue by MooYoo** [Alamofire/Alamofire#587]
i using cartfile for alamofire, the cartfile show below:

github "Alamofire/Alamofire" "swift-2.0"

when i run carthage update command, it product some complie error below:

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/wangxiaotao/Documents/JRFoundation/Carthage/Checkouts/Alamofire/Source/Upload.swift
	CompileSwift normal x86_64 /Users/wangxiaotao/Documents/JRFoundation/Carthage/Checkouts/Alamofire/Source/ParameterEncoding.swift
	CompileSwift normal x86_64 /Users/wangxiaotao/Documents/JRFoundation/Carthage/Checkouts/Alamofire/Source/Request.swift
	CompileSwift normal x86_64 /Users/wangxiaotao/Documents/JRFoundation/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)

My mac installed Xcode6.3 and Xcode7.0-beta， could you tell me how to fixed this complie error? thanks

**Comment by ikesyo** [comment]
Are you switching the command line tool to beta one? `sudo xcode-select -switch /Applications/Xcode-beta.app`

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
