### ISSUE TITLE
does not support swift2.0

### ISSUE THREAD

**Issue by gtd138** [Alamofire/Alamofire#592]
There are many errors in xcode7.

**Comment by tomwildcat9** [comment]
Same here. Used the swift-2.0 branch like so: 
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

Getting a lot errors. Can be more specific if needed.

**Comment by cnoon** [comment]
I've been using it in multiple projects and everything works properly. Here are a few troubleshooting tips:

* Make sure you have the latest version of Xcode 7 beta 3
* Update CocoaPods to the latest pre-release version
* Clean the project
* Wipe DerivedData
* etc. etc.

---

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
