### ISSUE TITLE
request media url failed

### ISSUE THREAD

**Issue by gtd138** [Alamofire/Alamofire#601]
branch swift2.0, request a media such as http://img4.douban.com/lpic/s3863556.jpg in simulator throw an error! but on ipad did not have this problem. In master banch, it works well!

**Comment by cnoon** [comment]
You're running into [ATS](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/). You can't use the HTTP protocol directly out of the box in iOS 9. Check out this [link](http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/) to resolve your issue.

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
