### ISSUE TITLE
Help - Requesting/Loading Data Before Screen Load using Alamofire

### ISSUE THREAD

**Issue by Kam21** [Alamofire/Alamofire#606]
Hi All,
I am using  Alamofire.request  for my project and just wondering how can i load the data before loading the page.  
I want to use the data to populate the UI.  

The data coming back after the screen loaded and my screen crashes due to not having the data loaded before the screen load.

Note: I am calling a Alamofire.request  on viewDidLoad method.

override func viewDidLoad(){
 
}

Thanks

**Comment by cnoon** [comment]
Hi @Kam21,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Cheers.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
