### ISSUE TITLE
Custom headers doesn't seem to be working.

### ISSUE THREAD

**Issue by SwiftFire** [Alamofire/Alamofire#607]
Trying to use CloudFlare api to get the users information. Need to send headers with the call and it doesn't seem to work with Alamofire.

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do view setup here.
        let manager = Alamofire.Manager.sharedInstance
        // Add API key header to all requests make with this manager (i.e., the whole session)
        manager.session.configuration.HTTPAdditionalHeaders = [
            "X-Auth-Email": "\(passedEmail)",
            "X-Auth-Key": "\(passedApiKey)",
            "Content-Type": "application/json"
        ]
        manager.request(.GET, "https://api.cloudflare.com/client/v4/user")
            .responseJSON { _, _, JSON, _ in
                println(JSON)
        }
    }

Is this a bug or am I doing something wrong?

**Comment by cnoon** [comment]
Hi @SwiftFire,

The behavior works correctly. We have tests confirming this. The issue you are running into has been asked and answered many times before. Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
