### ISSUE TITLE
[Swift 2] POST requests don't get parameters added.

### ISSUE THREAD

**Issue by BasThomas** [Alamofire/Alamofire#623]
Doing a simple request with GET adds my parameters nicely, but doing a POST doesn't.

```swift
let parameters = ["foo": "bar"]

Alamofire.request(.POST, "url", parameters: parameters)
.responseJSON { request, response, json, error in
  print("request: \(request)")
}
```

returns

`request: Optional(<NSMutableURLRequest: 0x7f9864109cb0> { URL: https://api.github.com/repos/BasThomas/junk/issues })`

while

```swift
let parameters = ["foo": "bar"]

Alamofire.request(.GET, "url", parameters: parameters)
.responseJSON { request, response, json, error in
  print("request: \(request)")
}
```

returns

`request: Optional(<NSMutableURLRequest: 0x7f9ef07ef0f0> { URL: https://api.github.com/repos/BasThomas/junk/issues?foo=bar })`

Am I missing something here?

**Comment by cnoon** [comment]
Hi @BasThomas,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by jonauz** [comment]
I'm getting the same issue, and I starting to believe it is an issue within Alamofire core code.
I did found solutions on Stack Overflow, but they are work arounds. I think it's more important to solve it properly.

**Comment by BasThomas** [comment]
You should probably set the encoding to `.JSON`.

**Comment by jonauz** [comment]
Tried, didn't helped.
Tried to test with all mentioned methods that made sense, but no luck. Backend wasn't receiving any parameters using POST method.
Unless I add them straight to the URL part as postfix "...?key=value"
I also used NSURLSession and NSURLRequest in the past, so I know backend part worked. And it works when I test with Postman (i.e. plugin on Chrome).

**Comment by jonauz** [comment]
I think I might be on to an answer for this behaviour.
I noticed that I have specified header Content-Type : "application/json" for POST method, and I think it should be "application/x-www-form-urlencoded" or similar. Or probably just remove it from header and add "..., encoding: .URL, ..." to request.
Haven't tested it properly so can't fully confirm if this truly solves the issue.

**Comment by cnoon** [comment]
@jonauz you need to use the `.URLEncodedInURL` to encode the parameters in the `URL` for a `POST`.

**Comment by MaxymusBoopathy** [comment]
Thank you @cnoon . It worked for me ..I just changed the encoding from .JSON to . URLEncodedInURL it worked like charm

**Comment by ibrar110** [comment]
Somebody help me please,
swift compiler doesn't compile large parameters array.
What should i do?
