### ISSUE TITLE
Downloading with progress -> Cannot invoke 'response' with an argument list of type '((_, _, _, _) -> _)'

### ISSUE THREAD

**Issue by 4np** [Alamofire/Alamofire#629]
Hi,

Carthage just pulled in version ```1.3.0``` (before: 1.2.3) and now XCode is complaining with ```Cannot invoke 'response' with an argument list of type '((_, _, _, _) -> _)'```:

```
        // start download
        let download = Alamofire.download(.GET, url, destination)
            .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
...
            }
            .response { request, response, _, error in
...
        }
```

I checked the documentation if anything changed, but I am doing it [exactly like the documentation states](https://github.com/Alamofire/Alamofire#downloading-a-file-wprogress). Am I doing something wrong?

**Comment by cristeahub** [comment]
My understanding is that these questions should be taken to StackOverflow as that's a better place to ask for support. That being said I had this issue and solved it by being more explicit in my definition and not using `_` in the callback. Try something in the lines of:

```
 Alamofire
      .request(.GET, ..., ...)
      .responseJSON { (request, response, JSON, error) -> Void in
        if let error = error {
          println("Error")
        } else if let json: AnyObject = JSON {
          println("\(JSON)")
        } else {
         println("Something went wrong")
        }
      }
```

**Comment by cnoon** [comment]
Hi @4np, this is the Swift compiler giving you a VERY misleading error. The issue is actually in your `download` declaration. You are missing the `destination` parameter. We brought all the global `Alamofire` methods inline with the `Manager` methods which will cause these issues in certain places.

We also documented this issue in the [release notes](https://github.com/Alamofire/Alamofire/releases/tag/1.3.0) in the upgrade section at the bottom. Additionally, the logic is correct in the [sample code](https://github.com/Alamofire/Alamofire#downloading-a-file-wprogress) in the README.

In the future, when you have issues like this, please take your question to Stack Overflow as @cristeahub mentioned.

Cheers 🍻
