### ISSUE TITLE
Background request not execute

### ISSUE THREAD

**Issue by dromerobarria** [Alamofire/Alamofire#630]
HI, I'm trying to make calls in background like POST,GET to be more precise in the didReceiveRemoteNotification method, because they work as a push notification arrive. My problem is that all the Alamofire.request are never call in Background mode  until I open the app then all works, as i said they are only GET,POST request nothing to download. Is there any way to let the request excute when the app is in Background and not to wit for he user to open the app.

Thanks in advance .

**Comment by cnoon** [comment]
Hi @dromerobarria,

You most likely need to use a background session configuration when setting up your `Manager` instance. Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
