### ISSUE TITLE
Carthage error: "Not a git repository"

### ISSUE THREAD

**Issue by bruceflowers** [Alamofire/Alamofire#634]
I've tried these variations in my Cartfile:

github "Alamofire/Alamofire" "swift-2.0" 
git "https://github.com/Alamofire/Alamofire.git" "swift-2.0"

And I get this error each time when running carthage update:

fatal: Not a git repository (or any of the parent directories): .git

All of my other dependencies can clone and build - any ideas?

**Comment by cnoon** [comment]
Hi @bruceflowers,

It's not an issue with Alamofire but some other issue. Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
