### ISSUE TITLE
'Method' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by Elmundo** [Alamofire/Alamofire#653]
Hi guys,

There is an issue when i try to use 'Method' enum as parameter of an function, gives me error **'Method' is ambiguous for type lookup in this context**. If i use it as argument of  `Alamofire.request()` function there is no problem. What could cause such an error?

>XCode: 6.4v
Cocoapods: 0.38.2v
Swift: 1.2v

```javascript
import UIKit
import Alamofire

class ServerManager: NSObject {

    let ServerPath = "BaseURL"
    
    class var instance:ServerManager {
        struct Singleton {
            static let instance = ServerManager()
        }
        return Singleton.instance
    }

    func request(method: Method, identifier: String, parameters: [String: AnyObject]? = nil) -> Void{
        Alamofire.request(Method.GET, ServerPath, parameters: nil, encoding: ParameterEncoding.URL, headers: nil)
    }
}
```

**Comment by cnoon** [comment]
Hi @Elmundo,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by InderKumarRathore** [comment]
You've to use `Alamofire.Method` to resolve name conflic
