### ISSUE TITLE
Invalid Credential Response

### ISSUE THREAD

**Issue by zgosalvez** [Alamofire/Alamofire#673]
I implemented authorization using credentials, similar to this:

```
let password = "password"

let credential = NSURLCredential(user: user, password: password, persistence: .ForSession)

Alamofire.request(.GET, "https://httpbin.org/basic-auth/\(user)/\(password)")
         .authenticate(usingCredential: credential)
         .response { request, response, _, error in
             println(response)
         }
```

However, I had to include the following to catch invalid credentials. The server replies "Invalid Credentials" if auth was cancelled, but string parameter is `nil` and response status code cannot be determined.

```
...
         .responseString { request, response, string, error in
                println(response) // prints `nil` but I'm expecting an object with statusCode 401
                println(string) // prints `nil` but I'm expecting "Invalid Credentials"
                if let error = error {
                    // Workaround Cancelled error.
                    if -999 == error.code && error.domain == NSURLErrorDomain {
                        title = "Invalid Credentials"
                        message = "Please check your email & password, then try again."
                    }
                }
            }

**Comment by cnoon** [comment]
This is exactly what should happen if the request was cancelled. You are not going to receive an `NSHTTPURLResponse` in the event of a cancellation because the request didn't succeed. You are also never going to receive a valid `string` object if the request didn't succeed because you didn't receive any data from the server.

Additionally, we have test cases verifying this behavior works as expected.
