### ISSUE TITLE
Statuscode 204 raises .Failure

### ISSUE THREAD

**Issue by schickling** [Alamofire/Alamofire#675]
Since the introduction of the `Result` type instead of a `data`, `error` parameter the validation seems to be broken. Everything besides a `200` response is interpreted as a `.Failure`.

Any thoughts about this?

**Comment by kylef** [comment]
@schickling Can you share a bit more code, perhaps an example to reproduce this?

**Comment by schickling** [comment]
Sure but it's pretty straight forward:

```swift
            let request = Alamofire.request(mutableURLRequest)
                .validate()
                .responseJSON { (_, response, result) in
                    switch result {
                    case .Success(let value):
                        sendNext(sink, value)
                        sendCompleted(sink)
                    case .Failure(let data, let error):
                        print(error)
                        sendError(sink, error)
                    }
            }
```

In this case `.Failure` gets called for a response with status 204.

**Comment by kylef** [comment]
@schickling You've used `responseJSON` thus it returns a failure if there is no JSON. You could use `response` if you are not looking for a JSON body.

https://github.com/Alamofire/Alamofire/tree/swift-2.0#response-handling

**Comment by schickling** [comment]
This implementation is some kind of API abstraction I'm using. Previously it worked fine having something like the following:

```swift
                .responseJSON { (_, response, data, error) in
                 // ...
                 if let data = data {
                      sendNext(sink, data)
                 }
```

What's the best way to have the same outcome using the new `Result` way?

**Comment by cnoon** [comment]
Great question @schickling. 

You can no longer use the `responseJSON` response serializer if there is no data returned. That will fail `NSJSONSerialization` which will in turn return a `.Failure` result. As @kylef mentioned, the way to handle this case now is to use the default `response` method that does not leverage a response serializer or return a `Result` type. This was all by design. 

You should not be using a response serializer if you are not expecting response data from the server.

**Comment by schickling** [comment]
Thanks a lot for your quick answers @kylef and @cnoon. I can totally understand why this path was chosen.
