### ISSUE TITLE
Result Type on version 2.0.0-beta.1 is colliding with usage antitypical/Result

### ISSUE THREAD

**Issue by davideme** [Alamofire/Alamofire#695]
Project using https://github.com/antitypical/Result to transform response value of Alamofire cannot be used in the same file.

```Swift
import Alamofire
import Result

Result
```
*Reference to generic type 'Result' requires arguments in <...>*

The problem is the collision between module name and class, even prefixing Result.Result, will no work because it can't find out if it refence the module Result or the class Alamofire.Result.

It will be good to rename Alamofire.Result because it's very specific to response use case, ResponseResult, AFResult or something similar.

**Comment by cnoon** [comment]
We will not be renaming anything in Alamofire due to some collision with another third party library. We cannot let other outside libraries, in which we have no control or influence, govern our naming conventions. That would be a poor policy for our users.

In this case, I would consider continuing to work the problem and think of outside the box solutions. What about the possibility of typealiasing the `Result` from `antitypical` in your project and using that instead? I'm sure there are other options as well.

Best of luck!

**Comment by davideme** [comment]
I agree that you shouldn't rename any component based on any external library possible collision, but using a name as generic as result for Alamofire 2.0, is a bit odd.

The problem with the typealias antitypical is not the best fit in our case, we will search for an alternative solution and trying to keep as much of the semantic in our project as possible.
