### ISSUE TITLE
use Almofire to log in to a website

### ISSUE THREAD

**Issue by mudithsilva** [Alamofire/Alamofire#698]
I'm new to jason.So i'm trying to log in to a website by using user given username and password ( in swift app and pass to website ) by using almorfire,Is it possible to user Almofire to achieve this task ?

**Comment by cnoon** [comment]
Hi @mudithsilva,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
