### ISSUE TITLE
Alamofire for Swift 2 - cannot submit for beta testing

### ISSUE THREAD

**Issue by AndriyGo** [Alamofire/Alamofire#701]
I have followed the instructions on installing the swift2 branch with cocoa pods. The app works well in the simulator, however, when I archive it for submission with Xcode 7 beta 5 I receive an email with an error:

"The bundle contains an invalid implementation of Swift. The app may have been built or signed with non-compliant or pre-release tools"

This issue definitely relates to the framework as without it I am able to submit for beta testing with the same version of Xcode. I have tried turning bit code OFF in build settings for Alamofire but it does not help.

Does anyone know how to fix this?

**Comment by cnoon** [comment]
Hi @AndriyGo,

This may be helpful: https://forums.developer.apple.com/thread/3653.

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by AndriyGo** [comment]
Hi @cnoon!

Thanks for your feedback. I have opened a question on stack overflow (http://stackoverflow.com/questions/32158112/alamofire-swift-2-cannot-submit-for-beta-testing-xcode-7-beta-5). Unfortunately, the link which you sent doesn't help.

While it is not possible to submit apps for release, it is possible to submit them for beta testing with Xcode 7. And without Alamofire I can do it with ease. However, when I add the framework I start getting error messages. Unfortunately, something is not working well with the framework which prevents it from uploading for beta testing. It would be great if someone could look into this.

**Comment by conradwt** [comment]
@AndriyGo Do you have a sample project that reproduces the issue?

**Comment by AndriyGo** [comment]
@conradwt sorry just saw your message. It works fine now after Xcode 7GM and latest update to Alamofire
