### ISSUE TITLE
Custom authentication challenge handling + fallback to default behavior

### ISSUE THREAD

**Issue by dimazen** [Alamofire/Alamofire#704]
I'm faced with issue, when backend sends me both Basic & OAuth in WWW-Authenticate field: 
```
WWW-Authenticate: Basic realm="protected-area"
WWW-Authenticate: OAuth realm="https://my.domain.com"
```

It leads to two possible NSURLProtectionSpace instances in next order: 

- one with authenticationMethod == NSURLAuthenticationMethodOAuth (I'm confused a little bit here, since there is no actual constant for this value, its just the output of the `po` command) 
- with authenticationMethod == NSURLAuthenticationMethodHTTPBasic 

Since I can not handle OAuth I need to reject it. As the result I'll get Basic protection space which is something that I can handle. However, the only way to do so is to set `SessionDelegate.taskDidReceiveChallenge`. Therefore I have to copy & paste code from `TaskDelegate` for all the rest authentication methods handling which is something I don't like. So I'm wondering is there any way to gracefully add that extra "if" directly or indirectly and ability to fallback to the default handling logic? 

Thanks.

p.s. Was thinking about returning a Bool from `taskDidReceiveChallenge` but its a bit weird as for me, what do you think?

**Comment by dimazen** [comment]
If I'll **adjust** code from `TaskDelegate` a little bit to fit my needs here is how it looks like:
```
func URLSession(
    session: NSURLSession,
    task: NSURLSessionTask,
    didReceiveChallenge challenge: NSURLAuthenticationChallenge,
    completionHandler: ((NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Void))
{
    var disposition: NSURLSessionAuthChallengeDisposition = .PerformDefaultHandling
    var credential: NSURLCredential?

    if let taskDidReceiveChallenge = taskDidReceiveChallenge {
        (disposition, credential) = taskDidReceiveChallenge(session, task, challenge)
    } else if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
        let host = challenge.protectionSpace.host

        if let
            serverTrustPolicy = session.serverTrustPolicyManager?.serverTrustPolicyForHost(host),
            serverTrust = challenge.protectionSpace.serverTrust
        {
            if serverTrustPolicy.evaluateServerTrust(serverTrust, isValidForHost: host) {
                disposition = .UseCredential
                credential = NSURLCredential(forTrust: serverTrust)
            } else {
                disposition = .CancelAuthenticationChallenge
            }
        }
    } else {
        if challenge.previousFailureCount > 0 {
            disposition = .CancelAuthenticationChallenge
        } else if challenge.protectionSpace.authenticationMethod != NSURLAuthenticationMethodHTTPBasic {
            disposition = .RejectProtectionSpace
        } else {
            credential = self.credential ?? session.configuration.URLCredentialStorage?.defaultCredentialForProtectionSpace(challenge.protectionSpace)

            if credential != nil {
                disposition = .UseCredential
            }
        }
    }

    completionHandler(disposition, credential)
}
```

**Comment by cnoon** [comment]
While it is certainly possible to return multiple auth challenges, it is not recommended which is pointed out in [RFC 2617 - Section 4.6](http://tools.ietf.org/html/rfc2617#section-4.6). The following threads have more info.

* [Delimiters for WWW-Authenticate for multiple schemes](http://stackoverflow.com/questions/10239970/what-is-the-delimiter-for-www-authenticate-for-multiple-schemes)
* [WWW-Authenticate header - multiple realms](http://stackoverflow.com/questions/3576197/http-authentication-www-authenticate-header-multiple-realms)

Since this is not common case, your only option is to override the `taskDidReceiveChallenge` which you already have. I don't think it's a good idea to add further support to Alamofire for this case since it is not only not recommended, but is also quite rare. Thankfully, you can already override the behavior by overriding the session delegate's task closure. This is exactly why they were opened up in the first place.

It is unfortunate that you need to replicate some of the logic, but that's certainly a better alternative for the community when you consider the 100s of use cases that are not common behavior. We're trying to keep Alamofire simple to use for the common cases, yet flexible enough that power users can customize everything that they need.

Best of luck.

**Comment by dimazen** [comment]
@cnoon thanks for your clarification.
Actually I found that there is no way to reuse certificates evaluation logic, since it is not available due to `internal` access specifier on `serverTrustPolicyManager`. 

However, also I've decided to simplify my approach by sending `Authentication` header in every request (via NSURLSessionConfiguration.HTTPAdditionalHeaders), since this is exactly what system does by using NSURLCredentials ;)
