### ISSUE TITLE
Remove Cache

### ISSUE THREAD

**Issue by telenc** [Alamofire/Alamofire#705]
Hello

When I send a GET request two times i have the same response.
but normally I should not have the same response. I was wondering if it was not because of the cache, and if so how to empty the cache ?

Thank's

**Comment by cnoon** [comment]
Hi @telenc,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
