### ISSUE TITLE
Alamofire doesn't seem to work when including just the Source directory.

### ISSUE THREAD

**Issue by danwalkowski** [Alamofire/Alamofire#708]
I received 46 errors trying to include the Alamofire Source directory directly in my project.

**Comment by cnoon** [comment]
Hi @danwalkowski,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by Rfaessen** [comment]
In Xcode 7 beta 6 i receive an runtime exception:

dyld: Symbol not found: __TMPdVSs12MapGenerator
Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/APPNAME-aoiewmfcyfwtfhfjuskrtwemhqsr/Build/Products/Debug-iphonesimulator/Alamofire.framework/Alamofire
  Expected in: /Users/USER/Library/Developer/CoreSimulator/Devices/AC2BD.../data/Containers/Bundle/Application/2B....509F/APPNAME.app/Frameworks/libswiftCore.dylib
 in /Users/USER/Library/Developer/Xcode/DerivedData/APPNAME-aoie...emhqsr/Build/Products/Debug-iphonesimulator/Alamofire.framework/Alamofire

This occurs on the first call I make with alamofire.
Then I re-read the install instructions, I drag and dropped it in my project, I didn't add it to the Binaries, after doing that, my app doesn't build at all without errors. One thing I'm not succeeding on is setting the build target to 8.3.

Without adding it to the binaries I don't get any syntax errors, nor did I get any runtime errors at beta 5 or earlier.

**Comment by cnoon** [comment]
Both of you need to be on the Alamofire 2.0.0-beta.2 release with Xcode 7 beta 6.
