### ISSUE TITLE
'checkPromisedItemIsReachableAndReturnError' is only available on iOS 8.0 or newer

### ISSUE THREAD

**Issue by PatrickNLT** [Alamofire/Alamofire#720]
62947d6deffc30d3128da580d91084a174fe485d is using `checkPromisedItemIsReachableAndReturnError` in MultipartFormData.swift (https://github.com/Alamofire/Alamofire/blob/62947d6deffc30d3128da580d91084a174fe485d/Source/MultipartFormData.swift#L260).

Unfortunately for us using Alamofire in iOS 7, this doesn't work. A fix would be welcome, thanks!

**Comment by PatrickNLT** [comment]
Same issue with `NSQualityOfService` in Request.swift

**Comment by cristeahub** [comment]
In the swift-2.0 branch, iOS7 is no longer supported. See https://github.com/Alamofire/Alamofire/pull/686 and the comments there.

**Comment by cnoon** [comment]
Thanks @cristeahub.

**Comment by PatrickNLT** [comment]
Thanks for the comments, I missed this.

FWIW, I find it very disappointing that such a reference library dropped support so early for iOS 7. Is there an alternative for Xcode 7 + iOS 7 + Swift?

**Comment by cnoon** [comment]
I'm not sure if there's an alternative. The main reason we've dropped support is that we cannot test it due to the fact that iOS 7 doesn't support frameworks. We'd need to duplicate our entire test suite which is just not reasonable. Therefore, to keep our quality as high as possible with full test coverage, we made the tough decision to drop iOS 7 support.

If you are willing, it would be quite easy to fork Alamofire and make the necessary fixes for iOS 7.

**Comment by cristeahub** [comment]
> If you are willing, it would be quite easy to fork Alamofire and make the necessary fixes for iOS 7.

To add to that, there's a lot of closed prqs on this repo that has made a lot of the changes to support iOS 7 already, so if you're interested @PatrickNLT , I would recommend you to look through them.
