### ISSUE TITLE
Add convenience methods to simplify request parameter construction

### ISSUE THREAD

**Issue by conradwt** [Alamofire/Alamofire#722]
Are there any future plans to add convenience interface for standard classes (i.e. Core Data Supported Types) when using the following API call:

```swift
public func appendBodyPart(#data: NSData, name: String)
```

At this time, I find myself having to do the following:

```swift
var numberType = NSNumber(longLong: 2)
let numberData = NSData(bytes: &numberType, length: sizeof(Int64))

var stringType = "This is a test"
stringType.dataUsingEncoding(NSUTF8StringEncoding)

// or 

let stringData = NSData(bytes: &stringType, length: sizeof(String))

var dateType = NSDate()
let dateData = NSData(bytes: &dateType, length: sizeof(NSDate))

```

I'm using an existing API where I need to pass anywhere from 5 - 9 parameters depending on the API call.  Thus, I was thinking that it could be something similar to the following:

```swift 
public func appendBodyPart(#data: String, name: String)
public func appendBodyPart(#data: NSDate, name: String)
public func appendBodyPart(#data: NSNumber, name: String)
public func appendBodyPart(#data: NSDecimalNumber, name: String)
...
```

**Comment by cnoon** [comment]
Hi @conradwt, thanks for your question and feedback!

At the moment, I think this is something that we should not support. The reason being that there are just too many assumptions that need to be made to write these types of "convenience" methods. 

* How do we know which `NSStringEncoding` to use? 
* How do we know which type of `NSDate` formatter you want to use?

Because of this ambiguity, I think it's best to leave these types of methods out of Alamofire. IMO, they should instead be created as extensions on the `MultipartFormData` class that internally creates the encoded data that you need, then calls the appropriate Alamofire method.

Does that make sense?
