### ISSUE TITLE
At swift2.0, How can I set up the connection timeout value

### ISSUE THREAD

**Issue by 3517277** [Alamofire/Alamofire#730]
i'm sorry to trouble you.but i can find witch the function can setup the connection timeout value.can you help me?

**Comment by cnoon** [comment]
Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
