### ISSUE TITLE
Send raw Json data through alamofire

### ISSUE THREAD

**Issue by tryadelion** [Alamofire/Alamofire#734]
currently reading the documentation it's impossible to send raw json content, already codified in a string, via AlamoFire : 

"{ "a" : "b", "c" : "d", "f" : {"h":"i"},  and the object goes on and on... }"

is there any workaround not present in the docs? 

if not, could this be considered as a required upgrade?

**Comment by cnoon** [comment]
Hi @tryadelion,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by tryadelion** [comment]
as i said, "if not, could this be considered as a required upgrade?" , being unable to create a alamofire instance with a String chain as "params" or as "body" in the Alamofire.request(.POST,etc...) , and having to separately create a Request variable,  transform string into codified NSDATA and applying it to the request's HTMLbody property does not seem the appropiate way of doing it, i had already searched in SO, but thanks (really, i jsut came here when SO's search engien ran out of ideas).

**Comment by cnoon** [comment]
Okay, next time you open an issue, please be a bit more specific. You just answered you own question which is why I pointed you to SO in the first place. Alamofire already supports your use case and is documented accordingly. It does not have your "exact" use case, but certainly walks through creating an `NSURLRequest` and passing that into the `request` method.

If you actually have a feature request (I think you might), then please open the issue as such with a well thought out case. More times then not, those cases actually get implemented in some form. Just please keep in mind that we want to build convenience layers for the common cases, yet remain flexible enough to cover all cases.
