### ISSUE TITLE
Multipart upload along with parameters

### ISSUE THREAD

**Issue by Jayvd** [Alamofire/Alamofire#770]
I have been using this code to upload my user profile picture to the server. but I am wondering how should I post other parameters along with it?

      let parameters = [
            "first_name" : "\(firstName)",
            "last_name" : "\(lastName)",
        ]

How can I include those parameters with the upload picture request?

    Alamofire.upload(.POST,
    URLString: "https://example.com/api/v1/users/profile_pic.json?auth_token=\(auth_token)",
    multipartFormData: { multipartFormData in
        multipartFormData.appendBodyPart(data: imageData, name: "avatar", fileName: "avatar_img.png", mimeType: "image/png")
    },
    encodingCompletion: { encodingResult in
        switch encodingResult {
            case .Success (let upload, _, _):
                upload.responseJSON { request, response, data, error in
                // Do whatever 
                } 
            case .Failure (let encodingError):
        }
    })

**Comment by cnoon** [comment]
Hi @Jayvd,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Thanks!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by cloudjanak** [comment]
This solution is really needed

**Comment by cnoon** [comment]
The solution is already there @cloudjanak. You can use the other `appendBodyPart` methods to accomplish the same thing.
