### ISSUE TITLE
Basic authentication issue with Alamofire 2.0

### ISSUE THREAD

**Issue by tobiasolofssonevry** [Alamofire/Alamofire#775]
This code, using Alamofire 1.3.1 is working:

```
        let alamofireManager = Alamofire.Manager.sharedInstance
        
        alamofireManager.session.configuration.HTTPAdditionalHeaders = ["Authorization": "Basic " + HelpMethods.GenerateBasicAuthenticationString(username, and: password)]
        
        alamofireManager.request(.GET, loginUrlString, encoding: .URL)
            .responseJSON { request, response, responseString, responseError in
                println(request)
                println(response)
                println(responseString)
                println(responseError)
                completionHandler(responseObject: response?.statusCode as Int!, error: responseError)
        }

```

Now i'm converting my project to Swift 2.0 and Alamofire 2.0. However the same code(except for removing the Error parameter) is giving me an 401 error using the same URL, username and password:
```
        let alamofireManager = Alamofire.Manager.sharedInstance
        
        alamofireManager.session.configuration.HTTPAdditionalHeaders = ["Authorization": "Basic " + HelpMethods.GenerateBasicAuthenticationString(username, and: password)]
        
        //Perform request
        alamofireManager.request(.GET, loginUrlString, encoding: .URL)
            .responseJSON { request, response, responseString in
                print(request)
                print(response)
                print(responseString)
                completionHandler(responseObject: response?.statusCode as Int!, error: nil)
        }
```

Am i doing something wrong or is this an issue?

**Comment by tobiasolofssonevry** [comment]
Changed the code to:
```
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = ["Authorization": "Basic " + HelpMethods.GenerateBasicAuthenticationString(username, and: password)]
        
        let manager = Alamofire.Manager(configuration: configuration)
        
        manager.request(.GET, loginUrlString, encoding: .URL)
            .responseJSON { request, response, responseString in
                print(request)
                print(response)
                print(responseString)
                completionHandler(responseObject: response?.statusCode as Int!, error: nil)
        }
```

Now i get a nil response instead of my previous 401 response.

**Comment by AzerTyQsdF** [comment]
You must hold a reference out of scope or use shared instance for manager. If not your request is cancelled very quickly (and your response = nil).
https://github.com/Alamofire/Alamofire/issues/673

**Comment by cnoon** [comment]
Hi @tobiasolofssonevry,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by sauvikatinnofied** [comment]
It seems that for each individual request from Alamofire 2.0, we need to add authentication header. Pleas e have a view on [this answer from Stackoverflow](http://stackoverflow.com/questions/32688546/ios-alamofire-v2-basic-auth-not-working#32689693).
