### ISSUE TITLE
Directly uploading images from assets Library

### ISSUE THREAD

**Issue by tobiasfeistmantl** [Alamofire/Alamofire#805]
I think it would be very convenient if Alamofire supports directly uploading images from the assets library since a lot of people use the UIImagePicker.

Is there any hope that such a feature will be implemented soon?

And if not, what is the best and efficient workaround?

There isn't a lot around on this topic.

**Comment by cnoon** [comment]
I don't think this is something that we'll directly support in Alamofire because 1) it's fairly OS specific and 2) we wouldn't know which upload method you would need to use to send the data to the server. There is some useful information [here](http://stackoverflow.com/questions/12138484/how-to-upload-image-that-was-taken-from-uiimagepickercontroller) and [here](http://stackoverflow.com/a/12121605/1342462) that should help you implement this functionality.
