### ISSUE TITLE
xcode 7.0 and swift2   ıssue 

### ISSUE THREAD

**Issue by idrisyildiz7** [Alamofire/Alamofire#820]
Undefined symbols for architecture armv7:

"Alamofire.Request.(responseJSON (Alamofire.Request) -> (options : C.NSJSONReadingOptions, completionHandler : (ObjectiveC.NSURLRequest?, ObjectiveC.NSHTTPURLResponse?, Alamofire.Result) -> ()) -> Self).(default argument 0)", referenced from:

please help I am using 2.0.2 alamofire.

**Comment by cnoon** [comment]
Hi @idrisyildiz7,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!
