### ISSUE TITLE
Failure in response.statusCode = 204

### ISSUE THREAD

**Issue by tanakorn-digio** [Alamofire/Alamofire#824]
Hi, I use POSTMAN statusCode = 204 but I use this library response.result handle to case .Failure.

# example respond from POSTMAN <h2>
![screen shot 2015-09-30 at 18 23 48](https://cloud.githubusercontent.com/assets/14090510/10191769/37bcccd6-67a1-11e5-9cbd-d8e3d9e3578c.png)

# example respond from library <h2>
![screen shot 2015-09-30 at 18 33 46](https://cloud.githubusercontent.com/assets/14090510/10191837/e932a6e8-67a1-11e5-9405-670a0b3feed5.png)

**Comment by tkrajacic** [comment]
What do you expect when you try to serialize something to JSON that is not JSON?

**Comment by cnoon** [comment]
Any service call that should NOT return data needs to use the `response` serializer at the moment. All the others expect data to exist, otherwise it will return a `.Failure` result. I'll think some more on the idea of having a generic response serializer that supports the concept of `No Data`. Maybe a `responseNoData` serializer?

**Comment by cnoon** [comment]
@tkrajacic please check out #889 if you get a chance. This is our first stab at proper 204 support directly in the response serializers.
