### ISSUE TITLE
Use ErrorType in ValidationResult

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/Alamofire#839]
I'm glad we made the switch to using the generic `ErrorType` for `Result`, but I'm confused why we aren't  using the same generic `ErrorType` in `ValidationResult`. I'd really like to pass my own custom errors into validation.

Is there a reason why we can't/shouldn't be doing this?

**Comment by cnoon** [comment]
That's a great question! The answer is quite complicated so let me split it up.

## Short Version

We don't want users to have to cast response serializer errors from `ErrorType` to `NSError` every time just to allow custom error types for `Validation`.

## Long Version

All Alamofire errors encountered when making a request are stored in a request's `TaskDelegate` instance. That error then propagates to all the responser serializers. Since the majority of errors that can be encountered when making network requests are actually generated by `NSURLSession` rather than Alamofire, it makes sense to have Alamofire also generate NSError objects to maintain consistency. This makes the response serializers much less complicated.

In Alamofire 2.0, we made the unfortunate decision to switch the `TaskDelegate` error to an `ErrorType` rather than an NSError. This forced all users to have to cast the error in the response serializers to an `NSError` even if they didn't implement custom `Validation` closures. Not a great tradeoff considering we have thousands (maybe hundreds of thousands) of people using the response serializers and only hundreds creating custom Validation closures.

There are also many more details in #791 if you'd also like to check that out.

**Comment by AnthonyMDev** [comment]
Got it. That makes perfect sense. Thanks for the quick reply @cnoon. I guess I'll just make my validation errors `NSError`s.
