### ISSUE TITLE
Can't install Alamofire using cocoapods

### ISSUE THREAD

**Issue by felipeflorencio** [Alamofire/Alamofire#842]
Sorry if is in wrong place, but i can't install alamofire using cocoa pods, i still using 1.3.1 version, but when i trie install always come with error :

[!] Unable to satisfy the following requirements:

- `Alamofire (= 1.3.1)` required by `Podfile`

This is my podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
# use_frameworks!

target 'AppName' do
	pod 'Alamofire', '1.3.1'
end
 ```

I Really appreciate any help, again, sorry if is in wrong place

**Comment by kylef** [comment]
@felipeflorencio This is because Alamofire depends on iOS 8.0 (this is required to integrate Swift frameworks). You will either need to find other ways to integrate Alamofire (without CocoaPods), or drop support for iOS 7.

There is a better error message for this in the upcoming version of CocoaPods (0.39).

```shell
$ pod install --no-repo-update --no-integrate
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (= 1.3.1)` required by `Podfile`

Specs satisfying the `Alamofire (= 1.3.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by felipeflorencio** [comment]
Tnk for help, unfortunately i will need insert lib manually so :+1:
