### ISSUE TITLE
Migration to Alamofire 2.0 give me a Multipart Form Data Error

### ISSUE THREAD

**Issue by jdoes** [Alamofire/Alamofire#845]
This code work before migrate to Swift 2.0 and Alamofire 2.0

```swift
manager.upload(requestMethod, NSURL(string: url)!, multipartFormData: { multipartFormData in
    for param in params {
        multipartFormData.appendBodyPart(data: param.1.dataUsingEncoding(NSUTF8StringEncoding)!, name: param.0)
    }

    multipartFormData.appendBodyPart(data: imageData!, name: "file", fileName: "tempImage", mimeType: "image/*") },
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .Success(let upload, _, _):
            upload.responseJSON { _, response, result in
                switch result {
                case .Success(let data):
                    ...
                case .Failure(let encodingError):
                    ...
                }
            }
        case .Failure(let encodingError):
            ...
        }
} )
```
Now the line:

upload.responseJson...
always return fail: 

FAILURE: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://www.myurl/posts, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://www.myurl/posts}

I cant find where is the problem

PD: I have the same problem with Alamofire 3.0

**Comment by cnoon** [comment]
Hi @jdoes,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

**Comment by jdoes** [comment]
Hi cnoon,
Yes, you're right, it was not my intention. But I have opened a question in Stack Overflow two weeks ago without a comment yet.
http://stackoverflow.com/questions/32765558/alamofire-2-0-multipart-form-data-error

As I say, before update everything was working perfectly.

**Comment by cnoon** [comment]
Okay @jdoes. If no one answers or comments on your question, that generally means your question needs to have more detail and be very clear. It also needs to show the steps you've taken to already debug it. Otherwise the community may think you haven't spent the adequate time to debug it. Try to take another pass adding any details you can think of, and I'll take a look.
