### ISSUE TITLE
Need to create new session every time

### ISSUE THREAD

**Issue by gkss** [Alamofire/Alamofire#850]
Hi,

I need to open a new session before every request. But Alamofire manager didn't. 

NSURLSessionConfiguration.defaultSessionConfiguration is enough for me.

Could you help?

**Comment by cnoon** [comment]
Hi @gkss,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!
