### ISSUE TITLE
dyld？why？

### ISSUE THREAD

**Issue by a6475593** [Alamofire/Alamofire#851]
hello，I can get json in my simulator ,but I find a error on my iPhone 6p,

dyld`dyld_fatal_error:
->  0x120051088 <+0>: brk    #0x3

only this message,

**Comment by cnoon** [comment]
Hi @a6475593,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!
