### ISSUE TITLE
Increasing memory usage

### ISSUE THREAD

**Issue by mathiasi** [Alamofire/Alamofire#856]
This is a follow-up to #100 
Whenever I create requests periodically, the memory usage will steadily increase over time. I have created a simple Xcode that shows the behavior: https://www.dropbox.com/s/akropg4xsyswg21/AlamofireTest.zip?dl=0

I have the following code in AppDelegate.swift

    while true {
            Alamofire.request(.GET, "http://127.0.0.1")
            usleep(100000)
    }

And here is the memory-consumption over time (2 min):

![skaermbillede 2015-10-13 kl 11 19 40](https://cloud.githubusercontent.com/assets/2315801/10450719/72566e60-719c-11e5-8278-dd9dca42c0fa.png)

Disclaimer: I'm new to Swift and first time using Alamofire, so it might just be that I'm using it wrong :)

**Comment by kylef** [comment]
There could be a few reasons from your example, why I think you may be seeing this:

- Your example may be inaccurate since you are blocking the main thread which could cause any other tasks to block and stay in memory.
- You are performing a new request every 0.1 seconds, which may be quicker than it takes to handle the responses. If this is the case, new requests will be happening and as time goes on, the amount of requests happening at any time will be more and more.

We can alter your example to no longer block the main thread, and instead dispatch from the main thread after a delay which is a little higher allowing the request to finish. For example:

```swift
class AppDelegate: NSObject, NSApplicationDelegate {
  func applicationDidFinishLaunching(aNotification: NSNotification) {
    performRequest();
  }

  func performRequest() {
    let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC)))
    dispatch_after(delayTime, dispatch_get_main_queue()) { [weak self] in
      print("Performing Request")
      Alamofire.request(.GET, "https://httpbin.org/")
      self?.performRequest()
    }
  }
}
```

With this updated example, you can see the memory usage is constant and not increasing:

![screen shot 2015-10-13 at 16 58 39](https://cloud.githubusercontent.com/assets/44164/10471609/a80b03ec-71cc-11e5-9761-be7b9b1daf1b.png)

**Comment by mathiasi** [comment]
Hi @kylef 

Thank you very much for your example! It got it to work.

I did use another thread in my own application, however I must have been using it wrong (as I said, first time working with Swift so lots of new stuff to me). 
And the frequency of which new requests were sent was just set to a low amount to emphasize the increase in memory consumption :)
