### ISSUE TITLE
Support for HTTP code 204 (No Content)

### ISSUE THREAD

**Issue by rephiscorth** [Alamofire/Alamofire#868]
Following [w3.org](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5) standard on response code **204**, when I do a `DELETE` operation, the server just responds with said code and no body.

[This test case](https://github.com/Alamofire/Alamofire/blob/master/Tests/ResponseSerializationTests.swift#L236) makes sure **Alamofire** raise an error when the body is `nil`. It'd be good to have support for this status code, thanks in advance!!

**Comment by kylef** [comment]
@rephiscorth That specific test case is to ensure that the JSON (or any data) serialiser raises an error when the data is nil since we we're expecting JSON body (or data).

If you're not expecting a body you shouldn't be using the JSON serialiser.

You should instead use the `response` method instead of `responseJSON` when you're not looking for JSON.

```swift
Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
         .response { request, response, data, error in
             print(request)
             print(response)
             print(data)
             print(error)
          }
```

**Comment by cnoon** [comment]
Thanks @kylef.

**Comment by dilizarov** [comment]
I don't see why the framework would fail for anything with a statuscode below 300. Anything 200-299 should work without any qualms. It is the users decision which response serializer works best with their server setup.

**Comment by damienrambout** [comment]
I don't think the JSON serializer should fail in case of a HTTP 204 No-Content status code. I am often working with web APIs that will return a different formatted body depending on whether there's an error.
A specific endpoint could return a HTTP 204 when everything goes well, but might also return a descriptive JSON in case of an error (HTTP >= 400). I'm still going to use `responseJSON()` because I know I'll always get a JSON (or nothing) back. 

(I realize now this is pretty much what @dilizarov said in the previous post :-) )

**Comment by dilizarov** [comment]
Funny enough, that is how it used to work, @damienrambout, but when I had to upgrade to Swift 2, and get the updated version of Alamofire, it broke because they included this new functionality. I still don't know why. Safe to say, I had to fix half my responseJSON callbacks to account for this.

**Comment by cnoon** [comment]
Thanks for your detailed feedback here @dilizarov and @damienrambout!

I understand where you are coming from, but what you are saying @dilizarov is not entirely true. The `responseJSON` serializer has ALWAYS thrown an error when the data returned from the server is empty. How the error is thrown has changed a bit, but even the original version would throw the `No Value` error from `NSJSONSerialization` when trying to deserialize the empty server data. Now we have some additional checks prior to running `NSJSONSerialization`, but the end result is still the same.

With that said, I don't think there's a way to cleanly handle this behavior without creating a custom response serializer. Trying to handle this use case in the common `responseJSON` serializer will just make the complexity too difficult understand for the general user. You need a serializer that first checks for the 204 response code. If it is a 204, return a Success result (probably with a `Void` type). If it is not a 204, run JSON parsing over the server data and extract out the custom error message. This is VERY different behavior than the current `responseJSON` implementation which is why I would encourage you to roll your own solution here.

Another way to do this without creating a custom response serializer would be to use the status code validation logic in conjunction with the `response` serializer. If the error comes back as a validation error, then run the JSON serialization over the server data if it exists and extract the exact error message.

To reiterate, the `responseJSON` serializer is not a solution for anything JSON. It's simply for the VERY common case that you know an API will return JSON in the event that the request is successful.

**Comment by cnoon** [comment]
@dilizarov and @damienrambout, after much internal debate, we've decided it would be best to add better support for the 204 use case. Please check out #889 if you get a chance. This is our first stab at proper 204 support directly in the response serializers.
