### ISSUE TITLE
"Network connection lost" after locking device

### ISSUE THREAD

**Issue by drichardson** [Alamofire/Alamofire#872]
On iOS 9.0.1 using Alamofire 3.0, if I made some requests (which worked), locked the device, and then opened the again immediately the first request would consistently fail. The next time I retried the request it worked.

I have a singleton that caches an Alamofire.Manager. The request would fail with "connection closed" -1005  NSURLErrorNetworkConnectionLost.

After searching for anyone seeing a similar issue, I found [Apple Tech Note TN2277](https://developer.apple.com/library/ios/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION9), which says that the kernel can reclaim sockets out from under apps without them having any idea what happens. Here's the relevant section:

> **Testing Socket Reclaim**
> If you're going to write code that handles a socket's resources being reclaimed by the kernel, you have to figure out how to test it. The exact circumstances under which the system might reclaim a socket's resources are purposely not documented; this gives us the flexibility to improve things in the future. However, on current systems (iOS 4.0 through iOS 4.3), you can get the system to reclaim resources from the sockets in your app by:
>
> 1. putting your app in the background
> 2. ensuring that the app is suspended
> 3. locking the screen
>
> When your app resumes execution it will find that it's sockets have been reclaimed.

My guess is that NSURLSession (which Alamofire.Manager is caching), has one or more sockets it keeps open (possibly to avoid renegotiating TLS handshakes). Then, when the device is locked, the OS reclaims these sockets. The next request on them results in an EBADF errno from the system call, which gets translated into an NSError with localized description "connection closed".

To workaround this, I created a new Alamofire.Manager whenever my AppDelegate's `applicationWillEnterForeground` is called. This completely resolved the issue.

Like I said earlier, this is just my best guess of what is happening under the hood, take it with a grain of salt, but wanted to bring it up at least for discussion to see if there was a more general way of solving the problem.

**Comment by cnoon** [comment]
Thanks for your detailed write up @drichardson. Hopefully this helps someone else fighting a similar issue.

I'm a bit confused though as to whether you're asking a question, or just reporting behavior. The use case you detailed behaves exactly the way I would expect it to. For a default session configuration, the request should fail eventually since you aren't using a background session configuration. If you expect the request to complete successfully even when being backgrounded, then you need to switch over to using a background configuration.

Your proposed solution to the problem doesn't actually solve the connection closed error from occurring, it simply buries it from being reported by deallocating the original URL session and replacing it with a new one. Therefore, I'm not really sure what else to say. IMO, this is behaving exactly as expected.

**Comment by drichardson** [comment]
Yeah sorry, I know it's not exactly a bug report, just describing something that was surprising to me (not being a long time iOS developer).

I know this issues is down in below the socket API, which is below NSURLSession, which is below Alamofire, which is below AlamofireImage and my WebAPI. But when you're using, for example, AlamofireImage and an image doesn't load when the app comes to the foreground, it's a bit strange. AlamofireImage is also caching an Alamofire.Manager in an ImageManager associated with the UIImageView class. The first time you load an image when the app comes to the foreground it fails and you're image doesn't load. I bet there's a lot of this kind of behavior happening.

I wanted to bring it up to see if there was a way to address this in Alamofire that would be transparent to applications and libraries built on Alamofire (like AlamofireImage). Or if not, perhaps some guidance in the documentation about best practices for dealing with this issue.

But if you don't think there's anything to do here, please close it. Not trying to force you guys into anything.

**Comment by cnoon** [comment]
Yeah in this case you'll need to reload your table view cell or reload the `UIImageView`. There's not really anyway around it at the Alamofire or AlamofireImage level. Best of luck!

**Comment by hasanalbukhari** [comment]
@cnoon I use a default configuration. and it returns -1005 connection lost error when app go to background. I may agree that this is an expected behavior. But, the thing is that the server receives the request and completes whatever is required on the server. while I get an error as you can see!
What kind of behavior is that?

**Comment by jshier** [comment]
@hasanalbukhari Please don't bump five year old issues. There is also a well known solution: background task assertions. Take an assertion when your request starts, get a bit more time after your app goes into the background to finish the request. You can read more [here](https://developer.apple.com/forums/thread/85066).
