### ISSUE TITLE
Sending array of dictionaries

### ISSUE THREAD

**Issue by omkar0001** [Alamofire/Alamofire#882]
Not able to send the json of below format in alamofire as post parameter

{"paymenttype":"cod",
 "items": [{"street":"lane1", "city":"mumbai"}, {"street":"lane2", "city":"delhi"}]
}

**Comment by cnoon** [comment]
Hi @omkar0001,

Instead of creating a support issue in Github, please open a question on [Stack Overflow](https://stackoverflow.com) and tag `Alamofire`. The Alamofire community is very helpful and supportive. Stack Overflow is the best place to get your question answered quickly and correctly.

Best of luck!

**Comment by omkar0001** [comment]
I have aldready checked out on stackoverflow 
http://stackoverflow.com/questions/27794918/sending-array-of-dictionaries-with-alamofire. 
http://www.scriptscoop.net/t/482057cd9d3a/ios-sending-array-of-dictionaries-with-alamofire.html.

I didnt get solution so i came here. 
By the way this is one of the lamest responses, i have seen.
You just acted like a support team from fucking Microsoft.

**Comment by cnoon** [comment]
Hi @omkar0001,

I promise you that's the best way to ensure no one ever helps you. Our team works very hard to provide the highest quality libraries we possibly can. Additionally, everyone on our team does this purely on their own time. In order to help us focus on the library and less on support, we direct support questions to Stack Overflow since there are more people there to help answer support types of questions. This allows us to focus on Alamofire, and less on your individual problem of parsing JSON. Comparing our small team's approach to corporate giant of Microsoft is simply an idiotic comparison and is certainly not appreciated.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by omkar0001** [comment]
1) Man..we have figured it out a way. Guess what we are not using yours.
2) We have checked out on stack overflow, we are not able to find out solution. Thats the reason we have asked here.
3) Instead of you writing me a fucking lousy and big fucking big text, you could have answered it.
4) This is the typical problem with you fucking europeans. You guys follow ethics than morals.
5) I donno man for what reason, you are developing whether its your hobby or your jobless. But as  a guy from startup, i expect the people to be proactive. That makes me an asshole to some people. I m fine with it. I live with that.
6) Regarding Microsoft thing you have misunderstood me. Here as you are a small team, i expected very less beureacracy. Guess what you have started acting like a fucking beaureacrat before you guys have become big.

**Comment by IOSDeveloperProgrammer** [comment]
@omkar0001  did you resolved your issue ? I am having same problem now. please tell me if you got that one .

**Comment by RahathCherukuri** [comment]
Its addressed here: https://stackoverflow.com/questions/27026916/sending-json-array-via-alamofire?newreg=cecfc218d5d248638174f1146a10b883

**Comment by bungkhus** [comment]
Hi All, 
This answer solved my problem https://stackoverflow.com/a/40702921/5832339

**Comment by iolegs** [comment]
> https://stackoverflow.com/a/40702921/5832339

Ты ебанутый? )

**Comment by iolegs** [comment]
@bungkhus are you stupid?!

**Comment by adnansiddiq** [comment]
Hi All,
Best answer given here: https://stackoverflow.com/a/27831968
