### ISSUE TITLE
Handling Error w/ JSON

### ISSUE THREAD

**Issue by jamescmartinez** [Alamofire/Alamofire#886]
How can I handle a JSON response when the server returns an error using Alamofire?

Let's say I perform a request that responds with an error:

```swift
Alamofire.request(.GET, "http://httpbin.org/get")
         .validate()
         .responseJSON { response in
         }
```

Response Code: `400`
Body: `{"message": "an error has occurred."}`

Since the request was validated, I expect Alamofire's `response.result` to be an error, `.Failure(let error)`, but I'd like to get the JSON data from the response as well. Unfortunately, Alamofire dictates that whenever the result is a `.Failure`, there will be no `value`.

```swift
    public var value: Value? {
        switch self {
        case .Success(let value):
            return value
        case .Failure:
            return nil
        }
    }
```

Is there a proper way to get this data out of the response without having to parse the raw data manually every time I perform a request to check for this case?

**Comment by cnoon** [comment]
You would need to create your own `response` serializer if you would like this behavior. You could certainly use the `responseJSON` serializer for now, but you'd need to handle the `.Failure` case and parse the server data using `NSJSONSerialization`.

All the default response serializers are written in a manner that when any error occurs, the serializers will not run their serialization logic. This is certainly the most common case which is why they are written in that manner. When deviating from this logic, it's quite easy to create your own custom response serializer tailored to your use case.
