### ISSUE TITLE
status code: 404,but response.result = SUCCESS 

### ISSUE THREAD

**Issue by hengchengfei** [Alamofire/Alamofire#895]
![1](https://cloud.githubusercontent.com/assets/3182964/10756553/cec932d8-7cdf-11e5-870d-983f7677c69a.jpg)

**Comment by cnoon** [comment]
You aren't validating the response status code, so it is possible that a 404 will return you a `.Success` case. All that the `responseData` serializer does is validate that there wasn't an error (which there won't be since you aren't validating the response status code) or that the data exists.

```swift
public static func dataResponseSerializer() -> ResponseSerializer<NSData, NSError> {
    return ResponseSerializer { _, _, data, error in
        guard error == nil else { return .Failure(error!) }

        guard let validData = data where validData.length > 0 else {
            let failureReason = "Data could not be serialized. Input data was nil or zero length."
            let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)
            return .Failure(error)
        }

        return .Success(validData)
    }
}
```

In your case, you are receiving a 404 which isn't throwing an error, and the server is returning data. Therefore, your `responseData` serializer succeeds. If you expect a 404 to always throw an error, you should additionally use the `.validate(statusCode: [200])` method before the `responseData` serializer. More info in the [Validation Section](https://github.com/Alamofire/Alamofire#validation) of the README.

In the future, questions like this are better suited for Stack Overflow with an `alamofire` tag. We use GitHub for bugs and feature requests. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by hengchengfei** [comment]
I really appreciate

**Comment by stevekim0417** [comment]
I am struggling with this issue... Thanks you so much.
