### ISSUE TITLE
Modify Request object after creation

### ISSUE THREAD

**Issue by Neirys** [Alamofire/Alamofire#927]
**Short :** Is there any way to modify the backed `NSURLRequest` (headers, body, or other) of the `Request` object after it has been created ?

**Long :** I have a custom `Manager` with `startRequestsImmediately` set to `false`. If my access token is currently being refreshed, all requests are waiting for refresh to finish, then they are resume.
Of course, I need to modify theirs HTTP headers to update access token before resuming them.

I can't just track directly `NSURLRequest`s then recreating `Request`s object because I need to keep all completion closure previously set for those requests.

Please tell me there's a way, otherwise I'll cry more and more :'(

**Comment by cnoon** [comment]
You cannot modify the `Request`after it has been resumed. With that said, don't cry...there's still a way. 😉

Once the `Request` has been resumed, you need to let it fail, then rebuild it with the new access token and resend it. You also need to make sure to keep the closure around so you can execute it after the second request completes. You also need to make sure you don't call the closure twice.

I've actually built an OAuth2 library for my company ontop of Alamofire that does exactly this. While that library cannot be open sourced, I've detailed the overall solution in this [thread](http://stackoverflow.com/questions/28733256/alamofire-how-to-handle-errors-globally) on StackOverflow. Hopefully that helps get you going.

Best of luck! 🍻

**Comment by Neirys** [comment]
Hi @cnoon, thanks for your quick reply. I actually came across your post on SO yesterday but your solution will be quite hard to implement on my project. We are now not so far from shipping and I'm afraid I can't offer that much refactoring on the core of the app right now (thank to the client for his "last minute requirement" ...). I don't know what solutions are left to me but well, I'll see by tomorrow if I can find out something :(

Anyway, is there a chance we can see request modification feature on future versions of Alamofire ?
I guess the main problem is that `NSURLSessionTask` has on read-only property on `originalRequest` and `currentRequest` and they are `NSURLRequest` so not mutable but well, maybe you guys could find a way :)

**Comment by cnoon** [comment]
First off, there's no quick solution to handling the OAuth2 race conditions. It is a very tricky problem to solve that I've tackled more than once.

With that said, you could add your own extension to an `NSURLSessionTask` if you need to store some additional info on it. There's nothing stopping you from doing this since Alamofire exposes all that logic publicly. As for those two properties being read-only, that not an Alamofire decision, that was Apple's.

If you end up finding a solution that works really well for you and think it might be a good addition to Alamofire, please submit a PR and we'll gladly check it out!
