### ISSUE TITLE
Header Authorization not working

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [Alamofire/Alamofire#928]
Hi I have try all different ways for this I still don't have any luck, I'm using latest version 3.1.2 here is my code 
this is my URL request convertible following the documentation
   
    enum Router: URLRequestConvertible {
    case GetDevices([String: AnyObject])
    case GetDevice(String)
    var method: Alamofire.Method {
        switch self {
        case .GetDevices:
            return .GET
        case .GetDevice:
            return .GET
        }
        
    }
    
    var path: String {
        switch self {
            case .GetDevice(let uuid):
                return "/api/devices/\(uuid)"
        case .GetDevices:
            return "/api/devices"
        }
    }
    
    
    var URLRequest: NSMutableURLRequest {
        let URL = NSURL(string: hostUrl)!
        let mutableURLRequest = NSMutableURLRequest(URL: URL.URLByAppendingPathComponent(path))
        mutableURLRequest.HTTPMethod = method.rawValue
        let toke = "Bearer " + tokenSDK
        mutableURLRequest.setValue(toke, forHTTPHeaderField: "Authorization")
        switch self {
        case .GetDevices(let parameters):
            return Alamofire.ParameterEncoding.JSON.encode(mutableURLRequest, parameters: parameters).0
        default:
            return mutableURLRequest
        }
    }
    }
Then I have my request 

     Session.sharedInstance.ApiManager().request(Router.GetDevices(params)) 
            .responseCollection { (response: Response<[Device], NSError>) in
                debugPrint(response)
                switch response.result{
                case .Success(let data):
                    debugPrint(response.result)
                    fulfill(data)
                case .Failure(let error):
                    debugPrint(response.result)
                    return reject(error)
                }
        }

Here is my Manager 

    class Session {
    static let sharedInstance = Session()
    private var manager : Manager?
    
    func ApiManager()->Manager{
        if let m = self.manager{
            return m
        }else{

            let serverTrustPolicies: [String: ServerTrustPolicy] = [
                        "api-develop.com": .DisableEvaluation
                    ]
            let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
            let tempmanager = Alamofire.Manager(configuration: configuration,serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
            self.manager = tempmanager
            return self.manager!
        }
    }
    }
But I still get error on my response that the token is missing, here is my response
    [Request]: <NSMutableURLRequest: 0x16eded00> { URL: https://api-develop.com/api/devices/b4886e9a-2257-4327-8f2a-82164ee139a0 }
[Response]: <NSHTTPURLResponse: 0x16ed4330> { URL: https://api-develop.com/api/devices/b4886e9a-2257-4327-8f2a-82164ee139a0 } { status code: 401, headers {
    Connection = "keep-alive";
    "Content-Length" = 92;
    "Content-Type" = "application/json";
    Date = "Wed, 18 Nov 2015 21:19:00 GMT";
} }
[Data]: 92 bytes
[Result]: FAILURE: Error Domain=com.alamofire.error Code=-6006 "The operation couldn’t be completed. The authorization token is missing or invalid." UserInfo=0x16d71b40 {NSLocalizedFailureReason=The authorization token is missing or invalid.}

**Comment by cnoon** [comment]
Hi @cesar-oyarzun-m,

I don't see anything obviously wrong. You should use the `debugPrint` functionality on `Request` to attempt to pin down what the issue is through `curl`. Most likely the `Request` isn't being sent correctly. Also, disabling evaluation won't help with the 401. That's only for disabling TLS evaluation.

On a different note, questions like these are best suited for StackOverflow. We use GitHub for bug reports and feature requests. If you could open a question there and post the link to that question back in this issue, that would be appreciated.

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
