### ISSUE TITLE
Making an HTTP request with AF causes a crash when an exception breakpoint is set for a Cocoa app

### ISSUE THREAD

**Issue by dlo** [Alamofire/Alamofire#932]
I have a single exception breakpoint set on an example project. When I do a simple GET request with AF, the app crashes.

See https://github.com/dlo/Alamofire-Crash-Example for example code.

**Comment by jshier** [comment]
The app doesn't crash, you're merely hitting the breakpoint you have set. It's rather common for those of Apple's frameworks that use C++ underneath to use exceptions in ways that Objective-C and Swift don't and so you may hit those exceptions with that breakpoint. That's why I usually run with the exception breakpoint set only for the language I care about. For Swift you can set the Swift error breakpoint, in Xcode 7.1 and higher. 

I'm going to close this issue. Feel free to open another issue if you find a crasher that can be traced to Alamofire's code. 

Also, thanks for the sample project. It made seeing this issue very easy. :+1:

**Comment by dlo** [comment]
Ah, got it. Thanks! That's pretty weird. So I guess Swift-only exception breakpoints in Swift-only projects?

**Comment by jshier** [comment]
Since Swift doesn't use exceptions (though the C++ that underlies much of its implementation might), you'd have to use the Swift error breakpoint like I said. That will break on any thrown error, including those wrapped from Objective-C `NSError`s. Whether that's actually useful to you is up to you to determine.
