### ISSUE TITLE
Supporting HTTP/2 Push

### ISSUE THREAD

**Issue by danielrhodes** [Alamofire/Alamofire#935]
Is it possible to support HTTP/2 push in AlamoFire? About event-stream (SSE)? If no and polling is the best option, does using the same connection to the host over multiple requests happen automatically in AlamoFire or does this need to be configured manually?

**Comment by jshier** [comment]
Alamofire is limited to the HTTP/2 support offered by the underlying iOS system frameworks, specifically `NSURLSession`. Unfortunately, at this time `NSURLSession` offers no exposed support for either `PUSH_PROMISE` or the HTTP/2 stream functionality. Only iOS 9, watchOS 2, tvOS (9), and OS X 10.11 offer any support for HTTP/2, and this functionality is implemented as an invisible layer for existing `NSURLSession` and CFNetworking clients.

As for whether Alamofire will reuse existing connections: as with HTTP/2 support, Alamofire is at the mercy of `NSURLSession`. Fortunately, in this case connections can be reused, at least in the case of HTTP/2 connections, since that is part of the protocol specification. On compatible OSes and connections, HTTP/2 will be used automatically, so you should see connection reuse. However, you should always test to ensure your server is compatible with the HTTP/2 implementation provided by the system frameworks, as no manual control is provided by the frameworks.

As to polling vs. push, if at all possible polling is to be avoided. Unless you need the lower latency of native HTTP/2 push, Alamofire can be combined with Apple's push notification service (APNS) to provide asynchronous support for long running tasks. In fact, APNS was recently converted to HTTP/2 itself, so it's entirely possible they're using some of its abilities in the new implementation. 

For more information about the system networking frameworks and their capabilities, Apple's WWDC sessions are especially helpful. See: (Networking with NSURLSession) [https://developer.apple.com/videos/play/wwdc2015-711/] and (What's New in Notifications) [https://developer.apple.com/videos/play/wwdc2015-720/].

I'm going to close this issue, as there's not a lot we can do here before Apple exposes the required API. If you have more questions regarding hybrid APNS/Alamofire architectures, feel free to as on StackOverflow and tag Alamofire.

**Comment by johndpope** [comment]
related 
https://github.com/nathanborror/swift-http2

**Comment by jshier** [comment]
@johndpope I'm not sure how that's relevant here. Alamofire wraps the underlying `URLSession` APIs, so users of either level of APIs will never see raw HTTP/2 requests, per design. 

@danielrhodes Looks like `URLSession` gained support for HTTP/2 push in Apple's latest OS releases. Support is automatic, so there's nothing to be done by Alamofire or even users of `URLSession` directly to gain support. It essentially acts like a cache preheat, where the pushed response is stored in the associated `URLCache` instance and then used as the response when a request is made for the pushed data.
