### ISSUE TITLE
DER vs .CER vs .CRT etc.

### ISSUE THREAD

**Issue by jacobjennings** [Alamofire/Alamofire#938]
https://support.ssl.com/Knowledgebase/Article/View/19/0/der-vs-crt-vs-cer-vs-pem-certificates-and-how-to-convert-them

From docs: data A DER (Distinguished Encoding Rules) representation of an X.509 certificate.
https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/#//apple_ref/c/func/SecCertificateCreateWithData

From what I gather here: certificatesInBundle in ServerTrustPolicy should also look for .crt and .der files instead of just .cer files. However, .crt and .cer files may be (correctly) encoded binary (DER) or base64-encoded. The Apple docs suggest only binary encoding is valid for SecCertificateCreateWithData. We could validate that each .crt and .cer is binary encoded, or alternatively, convert any ascii-encoded certs to a binary encoded cert before calling SecCertificateCreateWithData.

**Comment by jacobjennings** [comment]
"We could validate that each .crt and .cer is binary encoded" Realized this is already happening, although  it will fail silently

**Comment by cnoon** [comment]
Hi @jacobjennings, thanks for all the info here...nice work. 👍🏼

I think you have a valid point and the `certificatesInBundle` and `publicKeysInBundle` should pick up `cer`, `crt` and `der` file extensions. As for failing silently, I disagree because you can check the number of returned certificates returned by the method. Now it may be a bit difficult to figure out which one was missing, but at least you would know one was.

Would you be willing to put together a PR that updates the behavior here along with a test or two verifying the functionality?

**Comment by cnoon** [comment]
Ping here @jacobjennings...would you be willing to help put this together?

**Comment by jacobjennings** [comment]
@cnoon Sure, I'll put together a PR in the next few days

**Comment by jacobjennings** [comment]
https://github.com/Alamofire/Alamofire/pull/956

**Comment by cnoon** [comment]
I'm going to close this issue out...please redirect all comments to #956.
