### ISSUE TITLE
unable to use Alamofire 1.3.1 to support iOS7?

### ISSUE THREAD

**Issue by AniOSDeveloper** [Alamofire/Alamofire#951]
I got the error below when installing the podfile to the project, as the app should support iOS7, I wrote "pod 'Alamofire', '<=1.3.1'" in the podfile.

[!] Unable to satisfy the following requirements:

- `Alamofire (<= 1.3.1)` required by `Podfile`

Specs satisfying the `Alamofire (<= 1.3.1)` dependency were found, but they required a higher minimum deployment target.

Any sugguestions?

**Comment by kylef** [comment]
Check the [README for version 1.3.1](https://github.com/Alamofire/Alamofire/tree/1.3.1#installation)

> Embedded frameworks require a minimum deployment target of iOS 8 or OS X Mavericks

It's not possible to use CocoaPods or Carthage to integrate Alamofire on iOS 7 since they use frameworks to integrate and thus require iOS 8 onwards.

Check the instructions at https://github.com/Alamofire/Alamofire/tree/1.3.1#source-file

**Comment by AniOSDeveloper** [comment]
ths! :+1:
