### ISSUE TITLE
[ISSUE] Responses are wrong

### ISSUE THREAD

**Issue by sebastienvermeille** [Alamofire/Alamofire#970]
Hello,
Thank you for this great library !
I embedded alamofire into my project but I have something strange with it.

(My api is double checked and works well with other clients so we can assume the problem come from alamofire)

When I call alamofire :

        let request = Alamofire.request(.GET, endpoint + "/rooms/" + String(roomId), encoding: .JSON)
            .responseJSON { result in
                print(result)
                callback(result)
        }

the print display wrong result data. 90% are corrects but "id" are fully wrong for nested objects :

It has this structure : 
{
    id = 7; // Correct !
    lights =     (
         {
            id = 1; // Wrong it should be 33
            on = 1; // Correct
        },
         {
            id = 2 ; // Wrong it should be 7
            on = 1; // Correct
        },
         {
            id = 3 ; // Wrong it should be 3
            on = 0; // Correct
        },
    );
    name = sample;

Do you have an idea where does it come from in alamofire ? I tryed to read the code but I am a beginner so your help is welcome :)

Version used : 3.1.4

Cheers,
Seb

**Comment by cnoon** [comment]
Hi @sebastienvermeille,

We have many tests and thousands of users that are not experiencing this problem. Most likely this is an issue with the way you are forming your response or with your server. In general, these types of questions are best suited for Stack Overflow. We use the GitHub project for bug reports and feature requests.

Best of luck!

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by sebastienvermeille** [comment]
@cnoon  My api return the same result I used wireshark to check my api it send the same things to ios as for angularjs web client.

I really think it's an issue from alamofire. I will try another rest dep for swift and look if it works. So that we can see if it's an alamofire problem or not.

**Comment by ntnmrndn** [comment]
@sebastienvermeille Maybe you could create a sample project which reproduce the issue ?

**Comment by cnoon** [comment]
Agreed @ntnmrndn. 

Alamofire does not actually modify the data coming back from the server in any way @sebastienvermeille. If it is changing, it is not Alamofire that is doing it. The sample code you posted simply makes the request using an `NSURLSession`, and uses `NSJSONSerialization` to parse the response data. There's nothing Alamofire would be doing to modify the data out from under you. 

As @ntnmrndn suggested, if you need further assistance, we need a sample project to go on. Additionally, these types of questions are best suited for Stack Overflow. I can almost guarantee you the issue here is not Alamofire. If you open a question on Stack Overflow and post the link here, we could continue to help you there.
