### ISSUE TITLE
Cannot use the framework When import the framework

### ISSUE THREAD

**Issue by MarcSteven** [Alamofire/Alamofire#975]
Yesterday I imported the library into my project via cocoapods.But it told me there's a error.the error displayed .I changed the setting of target
1,Click the target 
2,enter into the setting of Build  Phases .and then -Enbed Framework...Selected the item "Run script only when installing".The order is over.The error disappeared completely....

**Comment by cnoon** [comment]
Hi @MarcSteven, I'm sorry you were receiving the error. Since there are thousands of people using Alamofire and CocoaPods together without issues, I'm going to assume you were running into an issue with your local setup and possibly your project.

We have fairly detailed instructions in our [README](https://github.com/Alamofire/Alamofire#cocoapods) that should help you iron out your issue. Another useful tip is to make sure your CocoaPods installation is up-to-date and that your Xcode Command Line Tools is set properly. Beyond that, I would encourage you to open a question on Stack Overflow to get further assistance. We use our GitHub project for bug reports and feature requests.

Cheers. 🍻
